### ISSUE TITLE
Allow variable substitution in attributes

### ISSUE THREAD

**Issue by marcokaiser** [pugjs/pug#100]
I am trying to do something like this:

  img(src="#{imgurl}")

but the #{...} placeholders are never replaced if used in attributes. Is there another way to do it? If not, this would be a really helpful additional feature.

Thanks!

**Comment by devoficial** [comment]
Hi when i'm trying to pass src as the image url from database 
like this img(src="#{product.image}") its not getting parsed.
when i inspect the page i saw <img src="#{product.image}">
