### ISSUE TITLE
escape html string

### ISSUE THREAD

**Issue by karellm** [pugjs/pug#1046]
Hi,

I want to escape the following: `the <title> tag is used...` to display it (with the html) inside a p tag for instance.

Does jade provide a simple way to do that? If I do `p the <title> tag is used...` it thinks I'm outputting html.

I'd like to avoid escaping it manually. Thanks!

**Comment by webdiscus** [comment]
9 years later... I have the same situation, I needed to escape HTML tags in a Pug template.

The first way is to add the custom filter to the pug options:

```js
const result = pug.compileClient(str, {
  filters: {
      escape: (text) => text.replace(/</g, '&lt;').replace(/>/g, '&gt;'),
    },
})
```

Or when used the pug-loader:
```js
{
  test: /\.pug$/,
  loader: 'pug-loader',
  options: {
    filters: {
      escape: (text) => text.replace(/</g, '&lt;').replace(/>/g, '&gt;'),
    },
  },
},
```


Then is possible to use the following in pug:

```html
pre: code.language-html
  :escape
    <!-- HTML -->
    <div>
      <p>Text</p>
    </div>

p
  :escape The <strong> element has the closing </strong> tag.

p.
  The #[:escape <html>] element is the root element.<br>
  Inside the #[:escape <html>] element there is a #[:escape <body>] element.
```

## Proposal
Add to Pug embedded small and most useful filters like `:escape` to avoid additional dependencies.

P.S. in the actual/modern alternative [webdiscus/pug-loader](https://github.com/webdiscus/pug-loader#embedfilters) is already implemented embedded filter `:escape`.
