### ISSUE TITLE
Is it possible to iterate template as following?

### ISSUE THREAD

**Issue by skotchio** [pugjs/pug#1082]
I have user.jade template:

```
h1= #{name}
p= #{occupation}
```

And do iterating like the following:

```
users = [{ name: 'Tobi', occupation: 'Ferret' }]

each user in users
   include user
```

But I get the error: #{name} name is not. I know if I change my template to:

```
  h1= #{user.name}
  p= #{user.occupation}
```

All works file but I dan't want to implicity define user in template. Does jade support it?

**Comment by vitamineart** [comment]
> no, what you can do is have `user.jade` look like:
> 
> ```
> mixin user(u)
>   h1= #{u.name}
>   p= #{u.occupation}
> ```
> 
> Then in your view you can have:
> 
> ```
> import user.jade
> users = [{ name: 'Tobi', occupation: 'Ferret' }]
> 
> each user in users
>    +user(user)
> ```

@ForbesLindesay 
Great! And what about object property or array?
Say users have not only name and occupation but also contacts:
```
users = [{ name: 'Tobi', occupation: 'Ferret', contacts: { twitter: 'twitter_url', linkedin: 'linkedin_url' } }]
```

Is it possible to iterate inside the mixin like this:
 mixin user(u)
>   h1= #{u.name}
>   p= #{u.occupation}
      ul
      each contact in #{u.contacts}
            li= contact

**Comment by trasherdk** [comment]
To use `each` you need `contacts` to be Array like. Or do something with `Object.keys`
```js
users = [{ name: 'Tobi', occupation: 'Ferret', contacts: [{ twitter: 'twitter_url', linkedin: 'linkedin_url' }] }]

mixin user(u)
     h1= #{u.name}
     p= #{u.occupation}
     ul
     each contact in #{u.contacts}
         li= contact.twitter
         li= contact.linkedin
```
