### ISSUE TITLE
attribute names always written in lower case

### ISSUE THREAD

**Issue by fschwiet** [pugjs/pug#1085]
A couple times I've ran into bugs where I'll use jade to add attributes to an element, then when I go to read the attribute it is not found.  The problem is that if I use a name that is not lower case, jade makes it lower case, and then when I look for it with the original name it is not found.

  Is there a reason Jade is converting attribute names to lower case?

**Comment by jadaradix** [comment]
Here is a hint for the next person who Googles and comes here. Use dashes for camel case attributes, e.g. <code>data-max-scale</code>. Then when you use the dataset API, you will get back a <code>DOMStringMap</code> with the key <code>maxScale</code>. Very nice.

I had this issue with impress.js. I saw exactly this in the code (<code>root</code> is an element):

    var rootData = root.dataset;
    ...
    maxScale: toNumber( rootData.maxScale, defaults.maxScale )

And so presumed you would write:

    data-maxScale

However, jade gives you <code>data-maxscale</code>, so the key is <code>maxscale</code> which impress.js obviously doesn't recognise. Solution: <code>data-max-scale</code> attribute as above so the dataset API returns <code>maxSet</code> instead. I was about to submit a pull request to impress.js - that would have been embarrassing.

**Comment by TimothyGu** [comment]
@jadaradix said:

> However, jade gives you `data-maxscale`

That's a bug. Can you provide a test case? I can't reproduce this with:

```jade
doctype html
html
  body
    p(data-maxScale="hey")
```

**Comment by jadaradix** [comment]
You're right; I lied (didn't look properly). Chrome is lowercasing the attributes from the source, so by the time you play with the inspector, it has become lowercase.

As proof, here's the jade (notice <code>data-testThing</code> attribute):

    div#slides(data-max-scale="100", data-testThing="x")!= htmlData

The HTML is correct...

    <div id="slides" data-max-scale="100" data-testThing="x">

But the DOM has a lowercase attribute (last one):

<img width="752" alt="screen shot 2015-09-16 at 22 15 05" src="https://cloud.githubusercontent.com/assets/6841082/9918734/74c753e4-5cc0-11e5-9244-239393c60323.png">

Lesson learned: Don't jump to conclusions and don't believe your eyes. Sorry folks; move along now ^

**Comment by TimothyGu** [comment]
Okay, thanks for the explanation ^^

**Comment by fschwiet** [comment]
>>  Chrome is lowercasing the attributes from the source

this
