### ISSUE TITLE
Nest mixin

### ISSUE THREAD

**Issue by bsr203** [pugjs/pug#1103]
I have two mixins like these

```
mixin fm
    form

mixin fi(type)
    input(type=type)
```

But when I nest the call

```
+fm
    +fi('text')
```

it outputs, `<form> </form>`

is there a way to get mixin `fi (input)` also rendered.

Doing so in mixin definition works,

```
mixin fm
    form
    +fi('text')
```

But, I may need to add multiple inputs to the form like

```
+fm
    +fi('text')
    +fi('text')
    +fi('text')
```

is it possible?

**Comment by Kinnardian** [comment]
Do you have a code sample?

**Comment by ZOL-D** [comment]
`
extends ./lnb-layout

mixin menu-li(index, label)
    li.menu-item(class='lnb-' + index) #{label}
        ul.sub-menu-group
            if block
                block

mixin menu-li-a(index, href, label)
    li.sub-menu-item(class='lnb-' + index)
        a(href=href) #{label}

block basic-manage
    ul.menu-group
        +menu-li('class', 'menu')
            +menu-li-a('class', '#', 'sub-menu1')
            +menu-li-a('class', '#', 'sub-menu2')
`

**Comment by StudioSpindle** [comment]
mixin fm
    form
    +fi('text')

**Comment by niftylettuce** [comment]
Adding `block` at the end did the trick for me!
