### ISSUE TITLE
Syntax to support conditional classes

### ISSUE THREAD

**Issue by naltatis** [pugjs/pug#1105]
I recently went through our templates and repeatedly found patterns like this:

``` jade
item = {name: "Hello World", isActive: true, isDisabled: false}
activeClass = item.isActive ? "active" : ""
disabledClass = item.isDisabled ? "disabled" : ""
li(class="#{activeClass} #{disabledClass}")= item.name
```

This is a quite common use case, but the current syntax is overly verbose. It also leaves unneeded white spaces between variables that evaluate to `""`.

I have two possible notations ideas for this:

**class object**

```
li(class={active: item.isActive, disabled: item.isDisabled})= item.name
```

This is a very generic solution similar to the existing array notation, but makes reading quite hard because it introduces another level of nesting. Also parsing a generic object may be quite complex.

This is the way AngularJS handles this http://docs.angularjs.org/api/ng.directive:ngClass#comment-565872594

**pseudo attributes**

```
li(class-active=item.isActive, class-disabled=item.isDisabled)= item.name
```

I personally like this version better. This follows the boolean attribute notation `input(type="text", disabled=item.isDisabled)`. This should be quite easy to implement and very clean to read.

This may cause conflicts if you are trying to create a nonstandard attribute named `class-*`. This could be solved by using another separator like `_`, `~`, `+` or `:` instead of `-`.

What are your opinions on this?

I would like to do the implementation because I think it would make our (and other) templates much cleaner.

**Comment by mahmoudzohdi** [comment]
I know this discussion from long time, but you can simply do that:
`li(class=(condition ? 'some-class' : '' ) )`
the output will be `<li class="some-class"></li>` if `condition` was true
