### ISSUE TITLE
:filter= var

### ISSUE THREAD

**Issue by buschtoens** [pugjs/pug#1171]
AFAIK it's currently impossible to pass variables to filters, as the filters content is directly passed to the appropriate parsers.

I would be very happy, to see support for at least the first and thrid expressions.

``` jade
:markdown
  Hello there, **#{name}**

:markdown
  Hello there, **!{name}**

:markdown= i18n("Hello there, **%s**", name)
```

**Comment by lucascdsilva** [comment]
+1 for runtime filter
