### ISSUE TITLE
option to prevent attribute expansion

### ISSUE THREAD

**Issue by robhicks** [pugjs/pug#1180]
I'm using Express 3.3.5 and Jade 0.35.0 and AngularJS to build various apps. Angular uses various HTML attributes to support functionality. 

Jade expands some of those attributes, creating hard to discover errors in Angular functionality. For example, Jade expands:

```
div(ui-view)
```

into

```
<div ui-view="ui-view"></div>
```

Are there any options that I can add to the Express configuration that will prevent Jade from expanding these attributes?

**Comment by inca** [comment]
+1.

Could someone please spend 15 minutes to update http://jade-lang.com/api/ docs? Please-please-please! Listing all available options (like basedir, doctype, etc) would really be great!

**Comment by ForbesLindesay** [comment]
As always, it would be great to get pull requests: https://github.com/jadejs/jade/tree/master/docs/views

**Comment by inca** [comment]
@ForbesLindesay Yeah, I kinda expected this. But you don't suppose that library users know about API options better than repo maintainers, do you?

**Comment by ForbesLindesay** [comment]
:) true, but it's possible to learn about the options from reading the source, and repo owners don't have unlimited time (I wish I did).

**Comment by TimothyGu** [comment]
@inca `doctype` is already documented.

@ForbesLindesay Do you have any idea what `basedir` is used for? I don't quite understand [the code using the option](https://github.com/jadejs/jade/blob/660ee12cbddfcbb070e736481cafb107ecc41cf1/lib/parser.js#L467-L470).

**Comment by ForbesLindesay** [comment]
If the path starts with `/` it is treated as relative to `basedir` (after removing the initial `/`).  If the path starts with anything else, it is relative to `filename`.  It lets people do things like `extend /layouts/main-layout.jade` rather than `extend ../../../../layouts/main-layout.jade`

**Comment by TimothyGu** [comment]
What if the user wants to use real abspath? Like /var/www/views/layouts/main-layout.jade?

**Comment by ForbesLindesay** [comment]
They can set basedir to `/` but it's generally a bad idea because it makes your code way less portable between machines.

**Comment by geoidesic** [comment]
Says above to pass {doctype: "html"} as options... how / where does one do that?

**Comment by inca** [comment]
Both `jade.compile` and `jade.compileFile` accept optional `options` where you can pass that (AFAIK, `options` and template data are the same object). If you use Express, you can do `app.set('view options', { doctype: 'html' })`.

**Comment by TimothyGu** [comment]
@inca said:
> AFAIK, `options` and template data are the same object

They are only the same object when you are using `render` and friends.

See full API docs: http://jade-lang.com/api/
