### ISSUE TITLE
How can I config the compiled html file with 4-space indent!

### ISSUE THREAD

**Issue by jingyinggong** [pugjs/pug#1200]
Jade template engine is awsome! But I want to config the compiled html with 4 spaces indent! The default indent is 2 spaces, is there a api to config the indent!

**Comment by mcauser** [comment]
It would be nice if you could specify the indent character(s). Once space, two spaces, a tab etc.
In `/lib/compiler.js` this `this.pp = '  ';` could be `this.pp = options.prettyIndent || '  ';`

**Comment by TimothyGu** [comment]
@mcauser it is already possible as the `pretty` option: http://jade-lang.com/api/

> pretty: boolean | string
> Adds whitespace to the resulting html to make it easier for a human to read using `'  '` as indentation. If a string is specified, that will be used as indentation instead (e.g. `'\t'`).
