### ISSUE TITLE
Expand mixin block as attribute

### ISSUE THREAD

**Issue by groner** [pugjs/pug#1265]
I'd like to be able to write a mixin like the following:

``` jade
mixin radio(name, value)
  input(type='radio', name=name, value=value != null ? value : block)
  block
```

The following:

``` jade
+radio('foo') Banana
```

would then generate

``` html
<input name="foo" type="radio" value="Banana">Banana
```

**Comment by spydertad** [comment]
Somewhat related question.  Creating radio buttons in a loop over json. Normal name-value pairs are work as expected. In the loop, setting a radio button to checked by default is fine. Trying to figure out how to not set the checked value for non-selected radio buttons.  

Tried to set attributes with 
    -checked =(!fVar.checked)?'checked':''
but that didn't work.  

Ended up with subordinate mixins where I explicitly set checked.
    case fVar.checked
        when 'true'
             +radioChecked()
        when 'false'
            +radioUnchecked()
Is there a way to do this that is less repetitive?
