### ISSUE TITLE
Includes can't extend blocks

### ISSUE THREAD

**Issue by buschtoens** [pugjs/pug#1267]
Included files that contain block extensions (like `append body`) won't extend the previously declared blocks. Instead of that, they yield in place.

```
//- boilerplate.jade
!!! 5
html
  head
    block boilerplate-head
  body.root
    block boilerplate-body

include navbar

//- navbar.jade
// extends boilerplate
// This somewhere would causes an infinite loop

append boilerplate-body
  nav.navbar Test

append boilerplate-head
  link(rel="stylesheet", href="/nav.css")
```

``` html
<html>
  <head></head>
  <body></body>
</html>
<nav class="navbar">Test</nav>
<link rel="stylesheet" href="/nav.css">
```

The included file appears to get its own context and therefore its own scope of block names. It then can't find the `boilerplate-head` / `boilerplate-body` and assumes that they don't exist and so creates them in place, as if this was a new block definition.

I consider this encapsulation to be unintended and can't really see a possible use case for it (open for suggestions). But what I can tell is, that it took me about 1 hour to really understand what's going on (this is my 4th attempt to correctly file this issue).

What I would expect is, that includees live in the same scope as their includers or at least somewhat bubble up to it, so includer blocks and mixins, etc. are accesible inside the includees. This would allow for a conveinient way of organizing the components of a layout.

Ex: The navbar can resiude in an extra file and will extend all appropriate blocks with stylesheets, scripts, templates, etc.

**Comment by TimothyGu** [comment]
@buschtoens Not sure if you noticed or not, but this is definitely not a problem in include.

```jade
//- layout.jade

#layout-1
  block layout-1
    p Content from layout, inside block #1

#layout-2
  block layout-2
    p Content from layout, inside block #2

append layout-2
  p Content from include, appends block #2
```

returns the exact same thing as the one with `include`.

----

Also, the `append` and `prepend` commands are all [Inheritance commands](http://jade-lang.com/reference/inheritance/) and is therefore not applicable to `include`. I believe `include` does act as a dumb C `#include` (with proper indentation of course).

----

In one of your examples:

```jade
//- boilerplate.jade
!!! 5
html
  head
    block boilerplate-head
  body.root
    block boilerplate-body

include navbar
```

```jade
//- navbar.jade
// extends boilerplate
// This somewhere would causes an infinite loop

append boilerplate-body
  nav.navbar Test

append boilerplate-head
  link(rel="stylesheet", href="/nav.css")
```

----

When used *as-is* the boilerplate would be "preprocessed" to this:

```jade
//- boilerplate.jade
!!! 5
html
  head
    block boilerplate-head
  body.root
    block boilerplate-body

append boilerplate-body
  nav.navbar Test

append boilerplate-head
  link(rel="stylesheet", href="/nav.css")
```

It does not make any sense to append something in the file. So of course append doesn't work.

----

The extends would of course cause an infinite loop as you are making boilerplate include navbar which extends boilerplate.

Assuming you fixed that (and the deprecated `!!!`):

```jade
//- boilerplate.jade
doctype html
html
  head
    block boilerplate-head
  body.root
    block boilerplate-body
```

```jade
//- navbar.jade
extends boilerplate

append boilerplate-body
  nav.navbar Test

append boilerplate-head
  link(rel="stylesheet", href="/nav.css")
```

When you compile the navbar it would show everything correctly.

----

If you would really want boilerplate to be the includer/child, then this would work:

```jade
//- boilerplate.jade
doctype html
html
  head
    include navbar-head
    block boilerplate-head
  body.root
    include navbar-body
    block boilerplate-body
```

```jade
//- navbar-head.jade

link(rel="stylesheet", href="/nav.css")
```

```jade
//- navbar-body.jade

nav.navbar Test
```

----

Unless I'm missing something, I will not reopen this issue.

**Comment by buschtoens** [comment]
Doesn't concern me anymore anyways. I went over to the ember.js camp. But thanks for revisiting this nonetheless. 

If someone else runs into this, they'll at least know what's up. 😊

**Comment by TimothyGu** [comment]
@buschtoens Handlebars, ew

**Comment by buschtoens** [comment]
@TimothyGu haha, I feel you. But I'm using emblem, which is basically jade for handlebars. :)

**Comment by TimothyGu** [comment]
@buschtoens Cool I'll check it out. Thanks! :)

**Comment by ryardley** [comment]
@TimothyGu Not being able to have an include alter code in the layout makes me want to try to move on to different engines. The issue here is that to build an app you need to group like things together so they can be thought of as a unit where in a webpage things that are related often have separate components that need to appear at different spots within the markup. Therefore the idea of getting include files being able to override blocks higher up in the hierarchy is an important one as the buckets can be setup in the layout. I want to be able to group a particular functional component in a single file and have it automatically put the code that component needs in the places that component needs them. The alternative is to split up everything in multiple spots like you have suggested which makes reasoning about what is going on more difficult. Having separate includes means there are multiple places in the codebase that need changing to remove or alter the navbar widget which is a bad thing for software development.

**Comment by TimothyGu** [comment]
If the layout for `comments_widget.jade` is not static then you should consider moving away from includes but rather use mixins for such widgets:

```jade
//- post.jade
doctype

include comments_widget.jade

html
  body
    p Lorem
    +comments_widget({ news: false })
```

```jade
//- comments_widget.jade
include news_widget.jade

mixin comments_widget(options)
  ul.comments
    li Great post!
  if options.news !== false
    +news_widget
```

**Comment by ryardley** [comment]
Ok I see what you mean. So suggested approach is to use nested mixins and specify the configuration through vars and then use logic to conditionally manage dynamic parts. This approach still causes maintenance problems however as a result of all the logic within the mixin when compared to simply yanking out an include line. Removing a dead feature still requires sifting through lots of conditional logic. 

Having includes processed before inheritance is intuitive for folks coming from haml/rails and I think this should be on the roadmap.

**Comment by TimothyGu** [comment]
> Having includes processed before inheritance is intuitive for folks coming from haml/rails and I think this should be on the roadmap.

Technically it is this way, even currently.

Can you make a Git repo (or Gist) of your preferred layout? It might help my understanding to see real code.

**Comment by ryardley** [comment]
Looking at the code it seems like includes (https://github.com/pugjs/pug-linker/blob/master/index.js#L21) is actually occurring after inheritance (https://github.com/pugjs/pug-linker/blob/master/index.js#L17) Perhaps there is a reason for this? 

I will make a repo to show you what I mean.

**Comment by TimothyGu** [comment]
L. 17 is only looking for the `Extends` node, not actually completing the inheritance. After inclusions are applied is the inheritance applied.

I'm actually not sure of the rationale for this at this moment, but I believe it's to prevent some corner cases. @ForbesLindesay, any ideas?

IMO pug-linker is the hairiest code in the entire Pug code base so it's totally normal to not understand it…

**Comment by ryardley** [comment]
Here you go. https://github.com/ryardley/pug-include-block-usecase

**Comment by ForbesLindesay** [comment]
pug-linker is the way it is in order to be as compatible as I can make it with the quirks of the 1.x.x jade versions while also being (hopefully) marginally easier to understand/follow.  Once 2.0.0 is stabilised, I'm hoping we can think about a complete re-write for the linker as part of the 3.0.0 migration with some breaking changes. pug-linker is mainly their to codify the current behaviour.

**Comment by lopugit** [comment]
Has there been any news on this? 

I desperately, desperately, desperately need this functionality, I can't see how this use case wasn't foreseen during production of jade, why wouldn't somebody using some variable scope in an include not want to maybe append some html data to another block in the layout...?

**Comment by lopugit** [comment]
What I meant to comment was has their been any development or solution for this?

Write now I'm working on a way to duplicate my template logic to be able to append some html right below the body, because I just need to create modals while I create other template compiled html, but modals, or bootstrap modals specifically, need to be children of the body

**Comment by mralexgray** [comment]
the fact that this was closed makes me very suspicious that the maintainer doesn't understand why someone might want to USE pug.
