### ISSUE TITLE
Is the compiler async or blocking?

### ISSUE THREAD

**Issue by chetan51** [pugjs/pug#127]
I noticed that the command `jade.render('string of jade', { options: 'here' });` doesn't specify a callback. Does that mean rendering a template with Jade will block the server? How does it work?

**Comment by ebdrup** [comment]
We have a website we've build on pug templates. And what we do is compile all the templates to html files on the filesystem, that we upload to an S3 bucket. Unfortunately the sync blocking IO of pug is making the build/compile of all files take 3 mins, and we are just getting started. 

Our bottleneck is all the compiles, not the renders.

Would you consider accepting a PR that adds support for async IO during compile?
