### ISSUE TITLE
Give an object as a style attribute

### ISSUE THREAD

**Issue by Scimonster** [pugjs/pug#1336]
It would be nice if i could give Jade an object as a `style` attribute value, and Jade would parse that correctly.

For example: `div(style={height:100,color:'blue',border:'1px solid black'}) some text` would then parse to: `<div style="height:100px,color:blue,border:1px solid black">some text</div>`

I could imagine this being useful if someone has a Node-generated object of styles, so it could simply be passed to Jade.

An even cooler extension of this feature would be some of the values being objects. For example: `div(style={margin:{top:5,bottom:20,left:10,right:10}})` => `<div style="margin-top:5px,margin-bottom:20px,margin-left:10px,margin-right:10"></div>`

One last suggestion about this. Have a shorthand value for style objects as `{}`: `div{margin:{top:5,bottom:20,left:10,right:10}}`

Please consider these ideas!

**Comment by jrabbe** [comment]
The case where this would be absolutely invaluable is in templates used for HTML emails. Emails are all about inline styles, and having to specify which styles to supply inline is not only a bother, but incredibly limiting.

**Comment by ForbesLindesay** [comment]
We've supported objects as the style property for quite a long time now.  This issue is over 3 **years** old

**Comment by jrabbe** [comment]
I realized that after I commented, apologies for that. Was trying to track down why an object would be inlined as the toString value, i.e. `[Object object]`, will continue my search.

**Comment by vendethiel** [comment]
It was even called jade then ;-).
