### ISSUE TITLE
Caching of includes/extends/...

### ISSUE THREAD

**Issue by martinheidegger** [pugjs/pug#1371]
I have tried using jade as a language for content additional to a template language. Right now I have 120 pages of html that I want to render with around 50 templates and that takes far too long in jade. I assume its because jade parses all my library.jade files and layout.jade files as well. I think it might be reasonable to cache the extends and include results so the next template doesn't need to process those files again.

**Comment by Tseian** [comment]
load.read = function read(filename, options) {
  return fs.readFileSync(filename, 'utf8');
};
because read file from disk by sync func?

**Comment by ForbesLindesay** [comment]
@Tseian this is a very old issue. If you currently have a problem, please open a fresh issue. It is very unlikely you are experiencing meaningful performance issues caused by pug's synchronous file loading, make sure you actually benchmark where time is spent if you have a problem.
