### ISSUE TITLE
Add option to suppress warnings during compilation

### ISSUE THREAD

**Issue by phated** [pugjs/pug#1395]
There doesn't seem to be a way to suppress warnings during compilation.

Ref: https://github.com/phated/gulp-jade/issues/7

**Comment by bookds** [comment]
please..

**Comment by ForbesLindesay** [comment]
@bookds fix your files, we're not removing the warnings, very soon they will be errors.

**Comment by bookds** [comment]
@ForbesLindesay  I'm integrating the template with handlebar.js includeing {{#each }} tag, that why I can't fix my files from warning. Anyway, thank you for your supporting.

**Comment by ForbesLindesay** [comment]
Just put `| ` before those lines.  You need jade to treat them as plain text.  If you don't mark them as plain text then in 2.0.0 they will stop compiling.

**Comment by bookds** [comment]
Putting " | " is worked. Thank you very much.
