### ISSUE TITLE
Multiline text block.

### ISSUE THREAD

**Issue by raulsebastianmihaila** [pugjs/pug#1404]
Hello. I didn't find in the documentation a way to add multiline text blocks other than using the . after the parent tag and the | on each line. I would like to propose the following syntax:

``` jade
p
    img(src = 'whatever.jpg', alt = '')
    |
        Lots of text here.
        On lots of lines.
        You can add other tags in the parent tag before the pipe character and after.
```

I don't know how to achieve this without using a span tag instead of the pipe character, so I think it would be better like this. Thanks.

**Comment by chrisnicola** [comment]
I know this is an old issue, but I was surprised that pipes don't support multiple lines. The advantage with pipes is you can intersperse more tags without the `#[]` syntax. It isn't a big deal I suppose but is there a reason pipes can't support multiple lines?

The verbatim filter also doesn't seem to work or I can't find docs on where to find it or install it then.

**Comment by TimothyGu** [comment]
@chrisnicola, see https://pugjs.org/language/filters.html. Simply `npm i --save jstransformer-verbatim` or, if you prefer, `yarn add jstransformer-verbatim`.

**Comment by chrisnicola** [comment]
Thanks, I was looking for that in the jstransformer list, but must have passed over it while searching. Sorry for the trouble.
