### ISSUE TITLE
[Feature] Automatically convert camelCase attributes into dashed notation

### ISSUE THREAD

**Issue by peta** [pugjs/pug#1450]
I'd like to see that Jade automatically (or using a flag/option) converts camel-cased attribute names into their dashed equivalents. Writing camel-cased compound words is imo. much more intuitive and fluent and would thus be perfectly in line with the mantra of Jade. What do you think?
### Example

`div(ngBindTemplate="...")` should translate into `<div ng-bind-template="..."></div>`

**Comment by 2metres** [comment]
Any chance of re-opeining this question on the grounds that on the new TVML syntax for Apple's tvOS uses camel cased XML. I'm currently building a node server that would serve up TVML/JS to the AppleTV and I would live to encorporate Jade as a template language over raw XML.

**Comment by ForbesLindesay** [comment]
You'll be able to implement this as a plugin in 2.0.0. In the mean time, if you want camel case output, write camel case jade. If you want hyphenated output, write hyphenated jade.

**Comment by 2metres** [comment]
Just from poking around at the api It appears that I works if you specify:
```res.header('Content-Type', 'application/xml');```
it leaves the case the same, works for me :+1:
