### ISSUE TITLE
Better Pathing

### ISSUE THREAD

**Issue by nijikokun** [pugjs/pug#1467]
Is there a way to do absolute pathing instead of relative pathing?

This complicates a lot of things when you are doing a large project and you are attempting to extend one file, if you nest folders at all you will understand this pain:

```
extends ../../../../../Framework/Layout/complete
```

If there is a better way of doing this then there needs to be better documentation than the one that exists.

**Comment by saviomd** [comment]
Why isn't this documented? This is f****** awesome!

**Comment by TimothyGu** [comment]
@saviomd it was just documented [6 days ago](https://github.com/jadejs/jade/commit/8f918ffff62ba0c77b99bdf8cd11f950da44f1dc) :)

**Comment by saviomd** [comment]
Nice. The doc really is updated (https://github.com/jadejs/jade/blob/master/docs/views/api.jade) but the site isn't (http://jade-lang.com/api/)

**Comment by TimothyGu** [comment]
Yes, we usually update the docs every time we make a new release.
