### ISSUE TITLE
Generating a block of HTML with Jade then Escaping it

### ISSUE THREAD

**Issue by bcomnes** [pugjs/pug#1468]
I'm trying to write an atom feed using jade.  The html inside a content tag needs to be xml escaped but the html isn't completely rendered by the time it gets to the jade template.  Is it possible to somehow escape everything under a certain tag?

``` jade
content(type="html") //Can we escape everything under here?
  div(class="logs") 
    each entry in log.items
      p
        time(datetime=entry.properties.published)
          a(href=entry.properties.url[0])= (new Date(entry.properties.published)).toLocaleTimeString("en-US")
        = entry.properties.content[0].html
```

**Comment by kendrick** [comment]
@ForbesLindesay, thanks a ton for https://github.com/pugjs/pug/issues/1468#issuecomment-38195976. I'm building a pattern library and trying to render a component's rendered markup as its own code snippet, and your `escape()` mixin solved a couple of hours of frustration. 💯

**Comment by TimothyGu** [comment]
@kendrick, unfortunately that mixin relies on Jade/Pug internals, and won't work when Pug 2.0.0 cpmes by. I'll post an updated version of the mixin, but proper support for it will come after 2.0.0.

**Comment by cheshrkat** [comment]
@TimothyGu I actually have the same use case as @kendrick :) Is there an updated version of this mixin? It's a blocker to upgrading from jade to pug :-/

**Comment by TimothyGu** [comment]
Here:

```pug
mixin escape
  - var oldBuf = pug_html;
  - pug_html = '';
  block
  - pug_html = oldBuf + pug.escape(pug_html);
```

**Comment by cheshrkat** [comment]
@TimothyGu thanks! Much appreciated :)

**Comment by shammellee** [comment]
@TimothyGu or @ForbesLindesay is there any documentation on facilities such as the `pug` and `pug_html` objects and how to use them in files being rendered via pug-cli?

**Comment by sarsamurmu** [comment]
@TimothyGu or @ForbesLindsay Are There any Way to Prettify the Code as well? Because I want to use this in one of My HTML Documentation Page.

**Comment by ForbesLindesay** [comment]
@sarsamurmu Prettifying code is out of scope for pug, you can ask questions like this on stackoverflow.com where you may get more helpful responses.
