### ISSUE TITLE
Text with single quote prefix to add trailing space (Slim-style)

### ISSUE THREAD

**Issue by akiva** [pugjs/pug#1526]
So this:

`' this text`

renders as with a single trailing unit of whitespace

It would be great if we could add this feature from [Slim](http://slim-lang.com/) (which is itself inspired from Jade), as some of us (myself included) automatically trim empty space from line-endings.

**Comment by larrybotha** [comment]
Slim has solved this problem - there is no need to hack the problem away with:
- a literal leading / trailing white space (problematic in editors that strip trailing space; intention is not  obvious)
- CSS margins on elements (not a CSS problem - margin != white space; not modular)
- HTML entities (\&nbsp; != white space)

4/6 of [these options](https://github.com/jadejs/jade/issues/905#issuecomment-69221807) are hacks.

With regards to:
```jade
| Here is a
_a_(href='#') link
| and here is
_a(href='#') another one
| .
```
_, although part of the solution, accounts only for space around elements. This doesn't account for trailing space on text nodes. Accounting for trailing / leading spaces on elements, and trailing spaces on text nodes solves this problem entirely.

Perhaps some examples and use cases for Slim's syntax would be more compelling.

## Element with leading space `<`

```slim
| my text node
a< ...
  | my link
```
yields:
```html
my text node <a ...>my link</a>
```

## Element with trailing space `>`

```slim
a> ...
  | my link
| my text node
```
yields:
```html
<a ...>my link</a> my text node
```

## Text node with trailing space `'`

```slim
p
  ' a really really long line of text
  ' that someone would likely want to wrap
  ' to multiple lines.
```
 yields:
```html
<p>a really really long line of text that someone would likely want to wrap to multiple lines.</p>
```

## Example with fully white space supporting syntax

@ForbesLindesay's example can be succinctly written as such:

```slim
' Here is a
a>(href='#') link
' and here is
a(href='#') another one
| .
```

**Comment by shongololo** [comment]
Was this ever resolved? I'm trying to figure out a succinct way to add white spaces.

The documentation says that a pipe with an empty line should add a space, but this doesn't seem to work for me. Further, the `| Here is a #[a(href='#') link] and here is #[a(href='#') another one].`  approach also doesn't seem to work in some cases, so I am at a loss.

**Comment by larrybotha** [comment]
@shongololo you'll have to use the following for white space:

```
| Here is a
= " "
a(href='#') link
| and here is
= " "
a(href='#') another
```

**Comment by gambolputty** [comment]
@larrybotha This does not work for me eather:
```
| Here is a
= " "
strong short
= " "
| link.
```
results to:
`Here is ashortlink.`

**Comment by ForbesLindesay** [comment]
@gambolputty that must be a problem with some kind of post processing you're doing on the pug output. The official pug compiler generates `Here is a <strong>short</strong> link.`
