### ISSUE TITLE
Feat: ability to define templates as partials, which do not need to be compiled as standalone

### ISSUE THREAD

**Issue by kevin-smets** [pugjs/pug#1554]
Often times, I include other templates at compile time, however, they still get compiled into html. Rather than having to config my entire grunt to ignore individual files, would it be a possibility to follow the sass way of doing this?

Sass will not compile underscore prefixed files, e.g. _file.sass. Meaning this file is only ever a partial which is meant to be included, it never gets compiled as a standalone. Maybe this is something jade could use as well? Or another way of indicating a file as a 'partial' and not a 'standalone'.

Right now, there are only two ways to do this, store includes in another folder, and don't compile them, or cherrypick files which should be ignored by the compiler. However, I would feel that being able to indicate this in the file itself would be a worthy addition to the language. I'm interested to see if other would find this useful as well, or maybe not? Either way, feedback much appreciated.

**Comment by BYODKM** [comment]
This is the one of reasons that I can not stop using gulp.
