### ISSUE TITLE
How to pass sessionStorage contents to a Jade variable?

### ISSUE THREAD

**Issue by Jmlevick** [pugjs/pug#1563]
As you might know, there's this **sessionStorage** concept in **HTML5** and I want make use of it for a simple two factor authentication case (on an **ExpressJS** app)... I have this logic/code on my **jade view**:

```
extends ../layout
block content
  - var two_factor = user.two_factor
  - var liveToken = user.liveToken
  - var inputToken = sessionStorage.userToken
  if two_factor == true
    if liveToken != inputToken
      //- Show input for entering user_token
    else
      //- Render Content
  else
    if liveToken == inputToken
      //- Render Content
```

On the server side, every time a user logs in I generate a random 6-digit token code that I send to the user's phone and then what I want to do is (via jade) do the validation as shown here: Basically if a user has two factor auth enabled I want to render only an input field for the user to enter the code and then store that user-entered token into the HTML5 sessionStorage to refresh the page later with the full content visible... Notice I have the **liveToken/inputToken** comparison for both cases of my two_factor condition because if a user doesn't has two factor auth enabled both values ideally would be **undefined**.

The problem I'm having right now is that my **inputToken** variable is returning this error:

> Cannot read property 'userToken' of undefined

I know this is happening because Jade variables are interpreted/executed on the server side and the server doesn't know what **sessionStorage** is (because that's an Object of the client side); But I want to know if it is possible to accomplish what I wanna do here in some way (for example making jade interpret that inputToken variable **on the client** thus have it's value available for the later condition after refreshing the view)...

Any ideas?

**Comment by emerballen** [comment]
After 4 years we can have access to sessionStorage from jade template?
