### ISSUE TITLE
"Unexpected block" warning makes no sense

### ISSUE THREAD

**Issue by pesho** [pugjs/pug#1593]
Assuming the following:

_base.jade_

``` jade
doctype html
html
  head
    title Default title
  body
    block body
      .container
        block content 
```

Most pages in the site will override the `content` block, like this:

_page1.jade_

``` jade
extends base

block content
  h1 Page 1
```

However, a few pages may have special needs, and wish to override the default body structure, by overriding the `body` block:

_page2.jade_

``` jade
extends base

block body
  h1 Page 2
```

Jade >= 1.4.0 however emits the following warning in the latter case:

```
Warning: Unexpected block "content"  on line undefined of base.jade. This block is never used. This warning will be an error in v2.0.0
```

I fail to see the logic in this. The usage is perfectly valid and useful. A warning for this makes no sense Trying to scare me that it will be promoted to an error in v2.0.0 makes even less sense.

**Comment by xReeQz** [comment]
I've got a base layout like that. 
```
doctype html
html
    block variables        
    head
        title= title
        link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
        link(rel='stylesheet', href='/css/app.css')
    body
        header
        section.container
            include ./partials/topNavigation
            block content
```
I use `block variables` to declare some common data which is gonna be shared between blocks. I may or may not use this inside my blocks. I get the warning mentioned above though. Is this the good way to share data like that? If yes, the warning probably has no sense then.

**Comment by ForbesLindesay** [comment]
You should only get the warning for the template that makes the `extend` call, not for the layout template.  Can you check you haven't mis-spelt `variables` in one of your child templates, and if that's the case, provide the pair of templates that produce this warning and we can see if it reproduces?

**Comment by xReeQz** [comment]
Indeed, it was a typo. Sorry for bothering.

**Comment by faddah** [comment]
+1  that this is happening with jade v1.11.0 (installed with npm v4.0.5, node.js v6.9.3 (latest LTS) on a MacOS Sierra v10.12.2.

**Comment by ptaking** [comment]
Still happening.
Example code:
`extends layouts/default

block content
  section.blog-page.spacing
    .container
      .row
        .col-xs-12
          h2.heading-title.nm Blog
          .cat-filter
            .row.oe-row-sm-gap
              .col-xs-9.col-sm-4.col-sm-offset-3.col-md-3.col-md-offset-4.oe-col
                label.select-faker.select-bordered.select-fw
                  select(name="abc")
                    option Tất cả các chuyên mục
                    option(value="1") Giá vàng
                    option(value="2") Cat name 2
                  span
                    i.icon-arrow-down
              .col-xs-3.col-sm-2.col-md-1.oe-col
                button.btn-bordered.btn.btn-md OK
          .blog-list
            .row
              - for (var i = 0; i < 9; i++)
                .col-sm-6
                  article.blog-wrapper
                    .blog-thumb
                      a.thumb.rec-fill.full-cover(href="#", style="background-image: url(" + demoDir + "thumbnail1.jpg)")
                        img.img-semantic(src= demoDir + "thumbnail1.jpg", alt="Blog title")
                    h1.blog-heading.heading-md.under-sep
                      a(href="#") Lorem Ipsum is simply dummy text of the printing
                    .blog-desc
                      p Lorem Ipsum is simply dummy text of the printing and type industry. Lorem Ipsum has been the industry's standard dummy text since the 1500s, when an unknown printer took a galley of type...
                        a.readmore(href="#") Read More
                - if (i%2 == 1)
                  .clearfix.hidden-xs`

**Comment by ForbesLindesay** [comment]
If it's still happening with the latest version of pug, please open a new issue.  However, make sure you:

1. Include all code needed to reproduce the error (e.g. @ptaking you haven't included the template you're extending, so I have no idea whether you've really found a bug)
2. Remove irrelevant code.  I really doubt all those divs with class names are causing this bug.

If you don't do that, I will just close your issue.  I'm going to lock this issue as further comments saying "me too" without proper steps to reproduce are not helpful and drain time that could be spent fixing bugs.
