### ISSUE TITLE
[feature request] class (and id) name prefixing

### ISSUE THREAD

**Issue by d6u** [pugjs/pug#1609]
It's going to be very nice to do something like this:

```
- var prefix = 'somename';
.#{prefix}-class-name
```

**Comment by webdif** [comment]
Any chance to reconsider this?

Time has come for CSS to be modular, with prefix all the way or BEM notations. This requirement is certainly more common now.

I'd love to be able to write something like this :

```jade
- var view = "header"
div##{view}
	nav##{view}-nav
		a##{view}-btn
		a##{view}-logo
```

This would match the current way we write nested CSS with preprocessors:

```styl
#header
	// …
	&-nav
		// …
	&-btn
		// …
	&-logo
		// …
```
