### ISSUE TITLE
Let Jade throw an exception when variables are undefined

### ISSUE THREAD

**Issue by eikawata** [pugjs/pug#1614]
Currently, jade does not warn or throw an exception when variables are not defined.

For example, this

```
title= myVar
```

becomes

```
<title></title>
```

if myVar is not defined.

I think it is very much helpful if we had a way to catch this kind of silly errors in the code. Maybe we could specify a flag to do this?

**Comment by noamtcohen** [comment]
@ekawatani what can do is call a getter in gade: `title= myVar()` then when you call the render function you pass it as a local: 
```javascript
res.render('myTemplate', {myVar:function(){return "my title";}});
```
if `myVar()` is not defined jade will throw an exception.
