### ISSUE TITLE
Feature Request: Multiline Code Blocks

### ISSUE THREAD

**Issue by malkomalko** [pugjs/pug#164]
Much like the new multi-line attributes, I think it would be very nice to have the ability for multi-line code blocks.  I hate going beyond 80 chars per line and sometimes with partial rendering or a condition, things get a little long.

```
!= someAwesomeHelper('param1', 'param2'
                     'params3', 'param4')
```

**Comment by CREEATION** [comment]
:+1:

**Comment by Mikebert4** [comment]
+1

**Comment by wesleycoder** [comment]
:+1:

**Comment by jeromew** [comment]
to avoid further +1 on this : this feature was added in jade 1.11.0
https://github.com/jadejs/jade/commit/87b7f9f037cee3bacf8a423698e017ab91f392be
