### ISSUE TITLE
normal and pretty output both break yaml front matter for jekyll

### ISSUE THREAD

**Issue by afknapping** [pugjs/pug#1656]
i want to generate layout files with yaml front matter for a jekyll page.

testfile.jade:

``` jade
| ---
| layout: default
| ---
.home
  h1.page-heading Posts
```

renders either to:

``` html

---
layout: default
---<div class="home"><h1 class="page-heading">Posts</h1>
```

or this in pretty mode:

``` html
(empty line)

---
layout: default

---
<div class="home">
  <h1 class="page-heading">Posts</h1>
```

both versions break jekylls front matter parsing and thus the whole rendering.
- would you accept a PR where pretty mode does not render an empty first line into the file?
- could you recommend a workaround? i use gulp to generate the files – maybe there is a way to remove the first line of a file on gulp.watch?

any help would be appreciated.

**Comment by TimothyGu** [comment]
With Jade 2.0 you will be able to do:

```jade
.
  ---
  layout: default
  ---

.home
  h1.page-heading Posts
```

which will output

```html
---
layout: default
---
<div class="home"><h1 class="page-heading">Posts</h1></div>
```

in non-pretty mode.
