### ISSUE TITLE
Literate Jade possible?

### ISSUE THREAD

**Issue by sorahn** [pugjs/pug#1665]
Hey guys, just wondering if it would be possible to have some sort of `.litjade` extension that could be parsed like `.litcoffee`.  Since the jade comment default is 3 characters long, maybe there could also be a different character to signify markdown comments?

**Comment by DomVinyard** [comment]
I've never coded anything remotely like this, I imagine there's a good deal of pattern matching? I would find it very useful though, if someone could point me in the right direction I'm sure I could look at piecing something together.

**Comment by TimothyGu** [comment]
@DomVinyard 2-minute implementation:

```js
function literateJadeToJade (lit) {
  return lit.split('\n').map(function (line) {
    return line.indexOf('    ') === 0 ? line.substr(3) : ''
  }).join('\n')
}
```

This is very crude; markdown lines are converted to empty lines to preserve debugging line count.
