### ISSUE TITLE
Error: The end of the string was reached with no closing bracket found.

### ISSUE THREAD

**Issue by ghost** [pugjs/pug#1690]
```
    doctype html
    html
      head
        script.
          function rgbToHex(r, g, b){
            return ("0" + r.toString(16)).slice(-2) + ("0" + g.toString(16)).slice(-2) + ("0" + b.toString(16)).slice(-2);
          }
          console.log(rgbToHex(255, 255, 255));

      body
        h1 Rainbow Text Generator
        input(type="text" id='input'")
        input(type="text" disabled="disabled")
```

**Comment by Kunalk651** [comment]
10|                 label(for="exampleInputPassword1") Password
    11|                 input(type="password" class="form-control" id="exampleInputPassword1" placeholder="Password")
  > 12|                 button(type="submit" class="btn btn-primary") Submit
----------------------------------------------------------------------------^

**Comment by Kunalk651** [comment]
The end of the string reached with no closing bracket ) found.
