### ISSUE TITLE
Pass custom param to include

### ISSUE THREAD

**Issue by artem-malko** [pugjs/pug#1692]
Hi.

Is there any opportunity, to pass custom param to include. 
I've got data: 

``` javascript
    "moduleName": {
        "moduleDataType1": {
            "title": "title1"
        },
        "moduleDataType2": {
            "title": "title2"
        }
    }
```

I've got partial(module) template:

``` jade
    h1
        |#{title}
```

And i've got main template:

``` jade
    html
        body
            include moduleName
```

So, i'd like to pass type of data to include. Is it possible?
I found one issue (https://github.com/visionmedia/jade/issues/798), and it works for me, to use mixins, but is it possible to solve my problem without mixin?
Thank you.

**Comment by jeromew** [comment]
@Congelli501 you can definitely have mixins defined in a file and then use this file as a kind of mixin library. When you include this file inside another pug file, the mixins will be available.

**Comment by Congelli501** [comment]
Ok, my bad. Mixins supersedes includes them!
