### ISSUE TITLE
Named mixins parameters

### ISSUE THREAD

**Issue by zoxon** [pugjs/pug#1695]
Hello.
My projects are quite large mixins with a bunch of options. It is especially difficult to write and read.
For example, one of these mixin.

```
//- Create input:text element with BEM HTML elements
//- @name String
//- @label String
//- @value String
//- @placeholder String
//- @hint String
//- @errors Array
mixin bem-input(name, labeltext, value, placeholder, hint, errors)
```

Always have to watch in what order are the parameters if this parameter does not need to pass it is necessary to put an empty comma or false. It is incredibly inconvenient's terrifying and annoying.

```
+bem-input("input-name", "Input label:", , , , ["error 1", "error 2"])
```

I would like to see in the next version of jade, something like this

```
+bem-input( labeltext="Input label:", name="input-name",  errors=["error 1", "error 2"])
+bem-input( labeltext: "Input label:", name: "input-name",  errors: ["error 1", "error 2"])
```

Briefly:
- The ability to pass values to parameters mixins by name
- Any order of parameters
- Default values for parameters (if not yet)

Perhaps this can be achieved in any other way, if you know how please tell us about it.
Thank you.

**Comment by fmaida** [comment]
Could you possibly consider to re-open this feature request?
Coming from the Python language world, I think it would be very useful being able to write something like:

```pug
mixin greet(first_name, last_name)
    p
        | Hello #{first_name} #{last_name)

+greet(first_name="John", last_name="Doe")
+greet(last_name="Doe", first_name="John")
```

**Comment by zoxon** [comment]
@fmaida you can write your mixins now in this style using attributes
For example [button mixin](https://github.com/zoxon/gulp-front/blob/master/source/modules/button/button.pug)  or [input mixin](https://github.com/zoxon/gulp-front/blob/master/source/modules/input/input.pug). This syntax is much closely to html api.



ps. I'm using [omit](https://www.npmjs.com/package/omit) and [classnames](https://www.npmjs.com/package/classnames) in pug mixins.

**Comment by fmaida** [comment]
Thanks, I'll try that

**Comment by zepp-lee** [comment]
I prefer to pass a single "context" object to my mixins:

    mixin mymixin(c)
        c.title
        c.whatever

    +mymixin({title: 'Some title', whatever: 'Some whatever'})
