### ISSUE TITLE
Add globbing include ?!

### ISSUE THREAD

**Issue by delch** [pugjs/pug#1698]
Hello, can any one add globbing include feature to jade ?

include ./blocks/*_/_.jade

https://github.com/isaacs/node-glob

**Comment by amir-s** [comment]
I think this could be a good feature.

I'm writing a platform that accepts plugins. Each plugin can extend the layout and each plugin can hook some content to another view of another plugin. It couldn't be done normally, but I managed to do it by mixins.
But I need the plugins to register their mixins within the application. They can copy their mixins into a specific folder and in the main layout, I can simply include all the files in that specific folder.

It could also be done if we could dynamically change the include path. Something like:

    // in express for example
    data.incs = ['a/b', 'c/d'];

    // in jade layout
    each inc in incs
        include #{inc}

**Comment by arxpoetica** [comment]
A *very* common use case (and an example of a need for globs) is the inclusion of framework templates, such as Ractive.js html files where the order is NOT important, and sometimes there are a ton of them. Being able to include them all with a single line is a win.
