### ISSUE TITLE
remote script tag not loading resource

### ISSUE THREAD

**Issue by gdibble** [pugjs/pug#1731]
Jade v1.5.0

Neither 
(local relative/abs.) `script(src='/hi.js')` 
or 
(remote loading) `script(src='//code.jquery.com/jquery-1.11.0.min.js')` 
are working.

Here it is in the Chrome 38 Inspection panel: 
![image](https://cloud.githubusercontent.com/assets/906846/5018332/72ecf3f6-6a6a-11e4-8f5b-c5cf4f261f2e.png)

**Network panel never loads the requested JS.** 
**The only way I can get a remotely loaded script file to work is by dynamically appending it using JS.**

**Comment by buddyp450** [comment]
@gdibble how did you resolve while still appending views?

**Comment by gdibble** [comment]
@buddyp450 The easiest way to load a remote script from a view is to use [jQuery.getScript](https://api.jquery.com/jquery.getscript/) ex:

    $.getScript( "ajax/test.js" )
      .done(function( script, textStatus ) {
        console.log( textStatus );
      })
      .fail(function( jqxhr, settings, exception ) {
        $( "div.log" ).text( "Triggered ajaxError handler." );
      });

😄  Does that help, or shall we go into greater detail?

**Comment by buddyp450** [comment]
this helps, tyvm
