### ISSUE TITLE
Pass variable to mixin's block name

### ISSUE THREAD

**Issue by ShadyMind** [pugjs/pug#1739]
**I have a problem with code in mixin:**
To make a table layout I created mixin which are generated from the cell blocks, like here:

``` jade
mixin span(count, size)
  tr
    td
      table([table-attrs])
        tr
          - var i = 0;
          while i < count
            td(width=size)
               block row#{i}
```

But the variables are not passed in the name of the blocks and it would be good to use this approach in future versions of jade or if such an approach exists and I misused it, tell me how it should work.

**Comment by ancmikesmullin** [comment]
I don't actually consider the title of this ticket duplicate. It was the example provided that made it duplicate, but the title is still unresolved.

Anyway, in case someone else comes across this, here's how I solved it.

```
- let ret;
mixin each-if(o, cond)
    - let show = false;
    each v in o
        if cond(v)
            - show = true
    if show
        each v in o
            if cond(v)
                - ret = v
                block

mixin section(label, list)
    +each-if(list, cond1)
        - items = ret
        +each-if(items, cond2)
            h1 #{label}:
```

taking advantage of the single-threaded nature, we are able to create a type of `ret` like a return register in a state machine, where we can pass context between mixin and block invocations.
