### ISSUE TITLE
parse error when using unicode ids/classes

### ISSUE THREAD

**Issue by stephenmathieson** [pugjs/pug#1796]
the string of jade:

```
.☺ hello
#☹ goodbye
```

yields:

```
Jade:1
  > 1| .☺ hello
    2| #☹ goodbye

unexpected token "dot"
```

**Comment by HoffmannP** [comment]
I understand you caution with allowing any characters in id/class-names, it's just that "umlaute" are somthing way more common than ☺ in names. Umlaute (alike other characters with diacritics) are an inherent part of ones language and unicode recognises that by assigning them to the character class letter (either Li, or Lu) while ☺ alike 💩 are assigned the character class symbol, other (So) which seems to be less likely to be a sensible choice for id/class-names.

Thats why I want to ask for theses characters to be first-class-citizens as part of these names - **jade** is about simplifying - to be forced to use quoted attributes is a disadvantage for languages with other alphabets.
