### ISSUE TITLE
Cannot find module 'less'

### ISSUE THREAD

**Issue by rudolfschmidt** [pugjs/pug#1799]
Iam tryin the less filter feature but during the rendering process I always get 

```
Cannot find module 'less'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
```

My code looks like the same code from the testing files

```
style(type="text/css")
  :less(minify=true)
    @pad: 15px;
    body {
      padding: @pad;
    }
```

I use "jade": "^1.8.2", with "express": "^4.10.6",

**Comment by ForbesLindesay** [comment]
You can now alternatively fix this in the latest version of jade by using:

```
npm install jstransformer-less
```

Which will give you the latest version of less as a jade filter.
