### ISSUE TITLE
Default/implicit block when extending layout

### ISSUE THREAD

**Issue by victorandree** [pugjs/pug#1902]
I think it would be nice if any "outside blocks content" of an extending template were put in a "default block" of the parent template/layout (similar to how ERB `yield` works?).

_Edit:_ The below was my first idea – but actually, just reusing `yield` might be better? So a layout will optionally yield to whoever extends it. I'm working on getting this to work in [my fork](http://github.com/vicvicvic/jade) if anyone is interested.

**layout.jade**

``` jade
doctype html
html
  head
    title Layout with Default Block

  body
    block header
      h1 Header

    block
```

**post.jade**

``` jade
extends layout

h1 Content

p.
  Content outside a block in an extending template gets put in the
  "default block" of the extended template

block header
  h1 Overriding explicit block
```

Essentially, this would just be syntactic sugar over explicitly adding a `block content` to the parent/extending template; saving (arguably not) precious indentation. I could not find any explicit issue suggesting or implementing this (or if it can already be achieved, nothing in the docs about it). The above should then produce:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Layout with Default Block</title>
  </head>
  <body>
    <h1>Overriding explicit block</h1>

    <h1>Content</h1>

    <p>
      Content outside a block in an extending template gets put in the
      "default block" of the extended template
    </p>
  </body>
</html>
```

An issue with this is what happens if you have implicit stuff, then an explicit block, then more implicit stuff.

**Comment by TimothyGu** [comment]
This idea is further developed in #2055.
