### ISSUE TITLE
It is not possible to unescape attributes content

### ISSUE THREAD

**Issue by yuchi** [pugjs/pug#198]
There's no way for unescape attributes.
I suggest something like title!='<'

**Comment by gsportelli** [comment]
For the posterity, as documented in the [migration guide to pug 2](https://pugjs.org/api/migration-v2.html), this is now possible:

    - var a = "my main title"
    - var b = "my subtitle"
    label(title!=`${a}<hr>${b}`)

results in

    <label title="my main title<hr>my subtitle"></label>

You need to use both `!=` for the assignment and `` ` `` (backticks) for quoting.

**Comment by actuallymentor** [comment]
Coming back to this thread because of the following issue: I'm trying to add an unescaped string as content, but not as an attribute:

```pug
style.
  #{ css }
```

How do I stop the engine from escaping the `css` variable?
