### ISSUE TITLE
Renaming jade -> pug

### ISSUE THREAD

**Issue by ForbesLindesay** [pugjs/pug#2184]
Unfortunately, [these people](https://www.jadeworld.com/) have a trademark for the word "jade" referring to software, so we've been forced to change our name.  Fortunately, @davidglivar has kindly donated the name "pug" to us.  I've claimed `pug` and `pugjs` everywhere I could think of so hopefully we shouldn't have any problems getting the name.

## Action items

 - [x] create a new logo (@GarthDB)
 - [x] design new branding for the website (@GarthDB)
 - [x] develop new website
 - [x] rename all repositories
 - [x] update every reference to "jade" to refer to "pug" in all repositories
 - [x] add @TimothyGu as an owner of all "pug" related npm repos
 - [x] publish working alpha-release
 - [ ] test and stabalise release
 - [ ] release pug 2.0.0

## Versioning & Deprecation

There will be no 2.0.0 release of jade, instead it will be released as pug 2.0.0.  In the mean time, pug 0.10.x will be used for experimental releases of pug 2.0.0 until it is stabilised.

Existing versions of jade will be left working for at least 6 months.  There may be a `pug@1.0.0` release aimed at being as compatible as possible with `jade@1.x.y`.

The new website will be at www.pugjs.org (which I have registered).  Once that website is built, http://jade-lang.com/ will be updated to redirect to www.pugjs.org

### Why pug?

It's short, memorable and widely available.  Not only that, but pugs are cute!

### Do we really have to change the name?

Yes.  The stress of pursuing this through the courts would be too high.  I would much rather focus my efforts on writing great software, and supporting the people who use pug.

### Couldn't we just change the name to <insert name here>?

Maybe, but I like pug, and it's definitely available.  If your suggestion was along the theme of "make a one letter change to jade", I think it's preferable in the long run to make a clean break and start with a nice fresh brand.

_more questions (and answers) will be added as they are asked_

**Comment by zhuangya** [comment]
sorry to hear that, but pug sounds perfect to me :+1:

**Comment by alubbe** [comment]
Great to finally be able to talk about this!
I think that the new name might actually give us a bit of PR that we can use to talk about the new modularity and get people to write plugins (or pug-ins ;)).
I'm also +1 on restricting publishing rights.

**Comment by rafis** [comment]
Are they have complaints against **jadejs** or **jadejs-lang**?

**Comment by viktorbezdek** [comment]
I can gladly help with website and logo, at least there will be options to pick from. Interested?

**Comment by ForbesLindesay** [comment]
That would be great.  I've opened a new issue for logo design #2189.

@rafis This decision has been made, I am aware of these issues, but we have neither the finances, nor the time to fight this.

**Comment by benedfit** [comment]
@ForbesLindesay are you at all interested in bringing `jade-lint` under the `pugjs` umbrella during this transition? I'm happy go it alone still, but it would make all the renaming it will need too more seemless. Plus I'd love to get more contributors on board in the process :smile:

**Comment by ForbesLindesay** [comment]
Absolutely, I've been meaning to suggest doing that for a while.  Hopefully I've given you the permission you need to be able to transfer ownership of the project to the pugjs org.

**Comment by tellnes** [comment]
@sidorares Maybe changing the name of https://github.com/sidorares/browserify-jade also? Eg. `pugify`

**Comment by sidorares** [comment]
wow, didn't expect that. @tellnes  - yes, probably makes sense.

@ForbesLindesay - what about http://jade-lang.com/ - is it going to move to pug-lang.com ?

**Comment by benedfit** [comment]
I'm going to rename https://github.com/benedfit/stylperjade to `stylinpug` (stylised: Stylin' Pug). Oh the logo possibilities are endless

**Comment by benedfit** [comment]
@ForbesLindesay with regards to versioning, is there any benefit to resetting all the new packages to 1.0.0 rather than maintaining, or incrementing, their existing version numbers?

**Comment by ForbesLindesay** [comment]
No, it probably makes sense to keep with their existing version numbers.

**Comment by TimothyGu** [comment]
I shall start converting all the repo and package names to pug if there are no objections?

**Comment by ForbesLindesay** [comment]
:+1: I've published an initial version of every module already so I need to add you as an owner on all the packages.  Also let's rename jade-load -> pug-loader for consistency with lever, parser etc.

**Comment by benedfit** [comment]
@ForbesLindesay I've given `jade-lint` the wrong team permissions as I can no longer rename it myself :frowning:. Could you fix for me please?

**Comment by ForbesLindesay** [comment]
@benedfit should be fixed now :)

**Comment by benedfit** [comment]
:+1: ta. I'm all done now

**Comment by dlewand691** [comment]
Wow sorry to hear about all this!

What about something like **Jayde** or **Jaide**?

**Comment by jeromew** [comment]
@dlewand691 thanks for the suggestion but I think that "pug" is now the new name of the project.

**Comment by dlewand691** [comment]
Sounds good. 

One more in case you change your mind... a simple letter swap: **Jaed**.

**Comment by Grawl** [comment]
For russian ears it sounds **very very bad** guys. I'm sad to see all these already merged PRs.

**Comment by joepie91** [comment]
Was there anything filed/sent by the company in question regarding their trademark? Or was this preventative?

**Comment by Xtrinity** [comment]
@dlewand691 Jaed looks awesome ;) It's easier to type than Jade too. Oh wells I guess it's going to be pug

**Comment by zhuangya** [comment]
How bad? In which way?

Даниил Пронин <notifications@github.com>于2016年1月4日 周一02:05写道：

> For russian ears it sounds *very very bad* guys. I'm sad to see all these
> already merged PRs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pugjs/jade/issues/2184#issuecomment-168524497>.
>
-- 
sent via Inbox app :)

**Comment by Grawl** [comment]
@Xtrinity @dlewand691 I am appreciate Jaed too :+1: 

@zhuangya sounds like “poo” :hankey:

**Comment by ForbesLindesay** [comment]
Could you simply pronounce it as мопс (which google tells me is the russian word for Pug)?

**Comment by Grawl** [comment]
@ForbesLindesay hmm sounds better. I'll try. “Мопс” is how I think about this language.

**Comment by geckotang** [comment]
Jayde or Jaide :+1:

**Comment by ForbesLindesay** [comment]
I'm locking this because I have zero interest in debating names.  I thought I made that pretty clear in the original issue.

**Comment by ForbesLindesay** [comment]
The agreement I'm being asked to sign for "Jade Software Corporation Limited":

> In consideration of your agreement not to issue trade mark infringement and passing off proceedings against me in relation to my use of JADE, I Forbes Lindesay, hereby undertake as follows:

> 1.	Within six months of the date of these Undertakings, to cease all use, and not use in the future, the sign JADE or any sign similar thereto, and to make no future use of any such sign;

> 2.	To redesign my website(s) to remove any and all references to the sign JADE, both on and off line, without any financial compensation from you whatsoever;

> 3.	To replace the existing website for JADE (http://jade-lang.com/) with a redirect to a new website.  The new website will not contain, and will not contain in the future, any reference to JADE or a sign similar thereto; and
 
> 4.	Not to assist, cause or procure others to do any act which, if done by me, would breach the above Undertakings. 

> For the avoidance of doubt, references to JADE on the website https://www.npmjs.compage are permissible during the period ending six months after the date of these Undertakings.  Upon the expiry of the six month period, all use of JADE and references to JADE, in any context, will have ceased. 

> I may inform persons of my discontinuation of use of the name JADE for legal reasons but without further comment.

> I agree to ensure that the provisions of this agreement are brought to the notice of and shall be binding upon any relevant affiliate, assignee, successor, licensee or any legal entity with which I am or become associated with, and that I shall procure that each such relevant affiliate, assignee, successor, licensee or any legal entity with which I am or become associated with is bound by these provisions.

> This agreement shall be governed and construed in accordance with the laws of England and Wales and the parties submit to the exclusive jurisdiction of the English Courts.

**Comment by jeromew** [comment]
That's a bit harsh and I don't think you can sign it as is ; you cannot accept "Upon the expiry of the six month period, all use of JADE and references to JADE, in any context, will have ceased." as you are not responsible for all contexts (other people's websites ?) + they have been very slow to claim their potential rights on their trademark which, on top of that, is a common name for jewelry.

I can understand that on good faith, and to be kind with them, you would do your best effort to change the name of the project for which you did not choose the name initially, but this "agreement" does not seem to have a fair wording.

**Comment by ForbesLindesay** [comment]
Updated agreement I'm now being asked to sign for "Jade Software Corporation Limited", after some changes were requested.  I have not yet signed anything:

> In consideration of your agreement not to issue trade mark infringement and passing off proceedings against me in relation to my use of JADE, I Forbes Lindesay, hereby undertake as follows:

> 1.	Within six months of the date of these Undertakings, to cease all use, and not use in the future, the sign JADE or any sign similar thereto, and to make no future use of any such sign;

> 2.	To redesign my website(s) to remove any and all references to the sign JADE, both on and off line, without any financial compensation from you whatsoever;

> 3.	To replace the existing website for JADE (http://jade-lang.com/) with a redirect to a new website.  The new website will not contain, and will not contain in the future, any reference to JADE or a sign similar thereto; and
 
> 4.	Not to assist, cause or procure others to do any act which, if done by me, would breach the above Undertakings. 

> For the avoidance of doubt, references to JADE on the website https://www.npmjs.com are permissible during the period ending six months after the date of these Undertakings.  Upon the expiry of the six month period, I will make no further use of the sign "JADE" in any context. 

> I may inform persons of my discontinuation of use of the name JADE but without further comment.
I agree to ensure that the provisions of this agreement are brought to the notice of and shall be binding upon any relevant affiliate, assignee, successor, licensee or any legal entity with which I am or become associated with, and that I shall procure that each such relevant affiliate, assignee, successor, licensee or any legal entity with which I am or become associated with is bound by these provisions.

> This agreement shall be governed and construed in accordance with the laws of England and Wales and the parties submit to the exclusive jurisdiction of the English Courts.

This is looking better, but the sentence:

> I shall procure that each such relevant affiliate, assignee, successor, licensee or any legal entity with which I am or become associated with is bound by these provisions.

Still seems like it's requesting I do something outside of my control.

**Comment by jbnicolai** [comment]
> I may inform persons of my discontinuation of use of the name JADE but without further comment.

Depending on interpretation, this could be very limiting as well. E.g.: does discussing the above agreement, after signing, count as commenting on the process of the discontinuation of the name JADE?

---

On a broader note: why do you feel you have to sign the above? You've already started the process of renaming JADE in good faith. They could extend you the same courtesy. If they want to legally bind you to do so then they can, but they'd have to go to court, and the outcome would still be the same. You have documented proof of already taking best-effort action to change the name on as short a basis as possible.

I realize this is perhaps not the forum for further discussion on this, and it's a personal choice that you are more than free to make. Just hoping you can avoid tying yourself to any vague legal agreement, if at all possible.

**Comment by TimothyGu** [comment]
Rename has been done.
