### ISSUE TITLE
Question - Whitespaces to separate a link between text

### ISSUE THREAD

**Issue by cjoudrey** [pugjs/pug#221]
This may have been asked before or I might just be blind, but what is the best way to obtain the following:

``` html
<p>Some text <a href='#'>test</a> more text.</p>
```

It seems to me the only way is to do the following:

```
p Some text 
  a(href='#') test
  = ' more text.'
```

**Comment by lukasziegler** [comment]
Hi, has someone already worked out a fix or a workaround for this problem? The problem still seems to exist: https://codepen.io/lukasziegler/pen/jwrdqR?#

**Comment by jeromew** [comment]
depending on what you are looking for, you can use

````
p a paragraph #[a(href="https://pugjs.org") with an inline-link] with a space
````

**Comment by lukasziegler** [comment]
That would work. Thanks for the quick reply!
