### ISSUE TITLE
Test Results page

### ISSUE THREAD

**Issue by cesarkohl** [pugjs/pug#2215]
Hi,

The Test Results page is not working properly: https://travis-ci.org/jadejs/jade

Best,
Cesar

**Comment by ForbesLindesay** [comment]
The link is out of date as we are in the process of transitioning to a new name.  Currently they are at https://travis-ci.org/pugjs/jade  Once the move is complete they will be at https://travis-ci.org/pugjs/pug

**Comment by cesarkohl** [comment]
Thanks!
