### ISSUE TITLE
loop for variable ,  Compile does not pass  (pool english)

### ISSUE THREAD

**Issue by gdzgshum** [pugjs/pug#2271]
i use vue.js like angular.js in jade

here is the code:

```
ul.list
      li(v-for="item in items")
        a(v-link="{ path: '/item' }")
          h3 {{item.name}}  --- work
          state-information(item= {{ item.name }})  --- not work
```

error: Unhandled rejection SyntaxError: Unexpected token {

1、  `{{item.name}}`  for vue
2、 `state-information`  is vue components

please help

**Comment by ForbesLindesay** [comment]
```
state-information(item= {{ item.name }}) 
```

should be:

```
state-information(item='{{ item.name }}') 
```

As you want the `{{...}}` to be processed by angular and ignored by jade.
