### ISSUE TITLE
Can external functions hooked up while compiling template ?

### ISSUE THREAD

**Issue by 116mails** [pugjs/pug#2273]
Problem is:  I have a template with some code snippet. now I want code snippet highlighted using thirdparty highlighters which can be achieve if I can call a external function whenever compile see block of code snippet and return html string from function call. 

is it possible with current design ? if not, let me know how to customize it ? 

thanks,
Kumara

**Comment by ForbesLindesay** [comment]
Once #2286 is merged, you can update to pug@2.0.0-alpha2 and then pass a `fitlers` option:

index.pug

```
:highlight(lang='javascript')
  // this is an example code snippet
  console.log(40 + 2);
```

index.js

```
var pug = require('pug');
pug.renderFile('index.pug', {
  filters: {
    highlight: function (src, options) {
      return highlight(src, options.lang);
    }
  }
});
