### ISSUE TITLE
Forward Slash giving error inside an interpolated tag

### ISSUE THREAD

**Issue by bk2dcradle** [pugjs/pug#2274]
The following is not compiling:

```jade
ul
    li #[span Facebook:// #[a(href="#") abc]]
```

with the error

```
The end of the string was reached with no closing bracket found.
```

Do I need to escape any character, or is it a bug?

Essentially, I want this to be the HTML:

```html
<ul>
    <li><span> Facebook:// <a href="#"> abc </a> </span> </li>
</ul>
```

**Comment by Kafiil** [comment]
I think it's a bug, you'll just have to skip it somehow like this :

**Comment by ForbesLindesay** [comment]
Try upgrading to the new alpha release (pug@2.0.0-alpha1, the project has been recently renamed).  Alternatively, you can do the following, as a temporary workaround:

```
ul
    li #[span Facebook:#{'//'} #[a(href="#") abc]]
```
