### ISSUE TITLE
http://www.pug-lang.com/ is down

### ISSUE THREAD

**Issue by valtido** [pugjs/pug#2276]
Need I say more?

Your domain name prob needs renewing.

**Comment by NoNameProvided** [comment]
http://jade-lang.com/ is up. They had to rename jade to pug due to some legal concern, and the migrating is still in progress. Once it done pug-lang.com will be up.

**Comment by allanwhite** [comment]
pug-lang.com shows a site about dogs. Maybe grab the .org?

**Comment by NoNameProvided** [comment]
pug-lang.com shows me the default Namecheap page because the site is not configured yet. The puppies you see are ads.

**Comment by kevinrambaud** [comment]
Any update there ?

**Comment by HandyAndyShortStack** [comment]
Hey I have pug-lang.com.  Sorry about that - I want to give it to this project.  Who do I transfer it to?

**Comment by valtido** [comment]
@HandyAndyShortStack  I think the project owner, @ForbesLindesay

**Comment by HandyAndyShortStack** [comment]
Okay, I reached out to him and I'll try and get that domain moved over as soon as possible.

**Comment by valtido** [comment]
@ForbesLindesay  is unresponsive, I tried to tweet on his twitter, and nothing so far.

https://twitter.com/forbeslindesay?lang=en-gb 

probably something to do with that law suite against jade lang.

**Comment by HandyAndyShortStack** [comment]
I would be fine with transferring the domain to @bloodyowl, @hemanth, @jbnicolai, @rlidwka, @TimothyGu, or @tjconcept.

**Comment by HandyAndyShortStack** [comment]
Domain transfer to @ForbesLindesay is underway.

**Comment by HarrisonB** [comment]
The website is once again returning a Namecheap page holder. Is this a new issue?

**Comment by NoNameProvided** [comment]
It was never working as far as I know.
