### ISSUE TITLE
Interpolation inside braces?

### ISSUE THREAD

**Issue by dustindowell22** [pugjs/pug#2277]
This should work, right?

Below I'm using ExpressionEngine if tags.
```jade
  -e += '{if #{i}_filename}#{i}{/if}'
```

This works fine though.
```jade
  -e += '{if ' + i + '_filename}' + i + '{/if}'
```

**Comment by TimothyGu** [comment]
No. `#{}` construct only works in Jade/Pug text.

If you want to do this as a piece of runnable JavaScript code, either do the second example you gave or use ES2015 template strings (if your JavaScript runtime supports it):

```jade
  -e += `{if ${i}_filename}${i}{/if}`
```
