### ISSUE TITLE
support for amp project?

### ISSUE THREAD

**Issue by zhuangya** [pugjs/pug#2278]
any plan for supporting [amp](https://www.ampproject.org/) ?

thanks

**Comment by alejonext** [comment]
Currently it supports all *ML and XML. Although I have not worked with special characters. like these.

```
<html ⚡>
```

**Comment by zhuangya** [comment]
i mean there are some restrictions for the amp-validated webpage, something like:

```html
<style amp-custom> /** custom style **/</style>
```

if you want to add a new `style` tag

**Comment by alejonext** [comment]
Well
```
style( amp-custom )
```

**Comment by ForbesLindesay** [comment]
As far as I know, there's nothing that prevents you using amp in pug.  I don't currently have any plans to specifically support it, and I'm generally pretty skeptical of amp.  However, if there is something concrete that's hard to write in pug but needed for amp, we could consider it.

**Comment by alejonext** [comment]
A... other library ?? other collection of mixins

**Comment by michrome** [comment]
Example of a valid AMP page using pug:

```pug
doctype html
html(amp)
  head
    script(src='https://cdn.ampproject.org/v0.js', async)
    link(rel='canonical' href='.')
    meta(charset='utf-8')
    meta(name='viewport' content='width=device-width,minimum-scale=1,initial-scale=1')
    style(amp-boilerplate).
      body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
    noscript
      style(amp-boilerplate).
        body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}
  body
    block content
```

**Comment by tycho01** [comment]
Square brackets used in AMP attribute names could be addressed with [pug-plugin-ng](https://github.com/tycho01/pug-plugin-ng).

**Comment by anubhav756** [comment]
In my case this did not work:
`a(on='something...' [class]="something==1?'active':'inactive'")`

But this did:
`a([class]="something==1?'active':'inactive'" on='something...')`

**Comment by droooney** [comment]
@anubhav756, that's because pug thinks that you're trying to access a property (in this case invalid) of the `something` string. You could easily avoid that by inserting an attribute name into `""`:

```pug
a(on='something...' "[class]"="something==1?'active':'inactive'")
```
