### ISSUE TITLE
Comments on same line as a 'block' declaration when extending

### ISSUE THREAD

**Issue by jmsherry** [pugjs/pug#2282]
Hi Guys,
I couldn't see an issue that matches this, but I may have missed it (so just close the ticket if I have) - I'm sure I can't be the first to come across it . Details are here: http://stackoverflow.com/questions/36325907/warning-unexpected-block-content/36325908#36325908

Basically, if (in your layout.jade) you put `block content //- Main content goes here...`and then have another file (say index.jade) extend from it, then it will not register and you'll get a warning of 'Warning: Unexpected block "content"  on line 3 of index.jade. This block is never used.'

Thanks  guys...

**Comment by ForbesLindesay** [comment]
This should now be fixed in the latest release of pug.
