### ISSUE TITLE
How to pass options to jstransformer filters?

### ISSUE THREAD

**Issue by simbo** [pugjs/pug#2288]
as the topic says...

I am using pug 2.0.0-alpha1 and installed `jstransformer-marked` to use a markdown filter.

And now i wonder how to customize marked options...

**Comment by ForbesLindesay** [comment]
Once #2286 is merged, you will be able to use `{filterOptions: {marked: {...myMarkedOptions}}}` as your options.  In the mean time, you can also use:

```js
:marked(option1='value')
```
