### ISSUE TITLE
broken links all over your github page

### ISSUE THREAD

**Issue by ohNegative** [pugjs/pug#2289]
FYI guys:

Full documentation is at (pug-lang.com) <--- this is a broken link that goes to Name Cheap domain registry page

You can test drive Pug online (here) <--- this returns a 404 page

The official (pug tutorial) <---- this returns:

"The www.pug-lang.com page isn’t working

www.pug-lang.com didn’t send any data.
ERR_EMPTY_RESPONSE"

Hopefully these get corrected soon and this project gets some more love. I would hate to think you're losing people because of these links being broken.

Pete

**Comment by maraisr** [comment]
Dunno what's going on with the guys at Jade. But this rename definitely isn't going smooth. Love what they produce, but yeah... Kinda ge tthe impression this is a little bit of a dead project?

**Comment by luxlogica** [comment]
@maraisr the Pug project is far from dead - you can see all the activity going on if you check the stats and graphs here on GitHub. Unfortunately, changing the name of a well-established project is not a small task. Along with the name, you have to change your brand, your logo, your websites, your documentation, everything. And you have to keep on developing your product.

To understand everything that is involved, please have a look at #2184 - and keep supporting Pug!

**Comment by maraisr** [comment]
Most definitely! Love what you guys do! It's a core piece I what we do here at Qantas! Well done already guys!! Massive effort - is there anyway I could help? Quite happy to assist I anything!

**Comment by TimothyGu** [comment]
Fixed in d4b4f78.
