### ISSUE TITLE
Long multi-line attribute expressions break when indented with tabs instead of spaces.

### ISSUE THREAD

**Issue by terrycloth** [pugjs/pug#2290]
I'm working on a web page that contains several "responsive" images (using the `srcset` attribute). The JavaScript expressions which define the `src` and `srcset` img attribute gets to be very long, so I break it up into multiple lines. When the lines are indented with spaces, this works as it should. But when the lines are indented with tabs, I get the error "Duplicate attribute "+" is not allowed."

I've created a [gist](https://gist.github.com/terrycloth/1cfd26105cfa7cea31b061d3c525d1b4) which demonstrates the problem -- there are two code snippets with identical contents, except that one is indented with spaces and one is indented with tabs. The version with tabs breaks.

I've only tested this with the latest stable release of pug ("jade" 1.11.0).

**Comment by terrycloth** [comment]
I just noticed that the tab-indented version also works if the `+` operator appears at the *end* of a line, instead of the beginning of a line. However, I prefer having operators at the beginning of the line, because things at the beginning of the line are easier to notice.

**Comment by ForbesLindesay** [comment]
Can you test this with pug@2.0.0-alpha3 and confirm whether this is still a problem.

**Comment by terrycloth** [comment]
Okay, the issue seems to be fixed already in the latest version of pug.

Thanks!
