### ISSUE TITLE
Mistake in *.pug breaks gulp

### ISSUE THREAD

**Issue by Ferym26** [pugjs/pug#2296]
I'm really looking for a solution (google, github, stackoverflow) for several days, but could not find a working solution.
My task:
```js
gulp.task('pug', function build() {
	gulp.src('frontend/pug/**/*.pug')
		.pipe(plumber())
		.pipe(pug({pretty: true, basedir: __dirname + '/frontend/pug'}))
		.pipe(gulp.dest('app'))
		.pipe(browserSync.stream());
});
```
help me find a solution

**Comment by ForbesLindesay** [comment]
Looks like you should open this issue against gulp-pug but in any case you haven't said what doesn't work, just given us a tiny snippet of code.

**Comment by Ferym26** [comment]
I am sorry if I said it is not clear.
Just when I'm writing in * .pug something like this
```js
.wrapp
    h1 Hello world!
    +++
```
with stupid mistake "+++" my gulp-watch task down and everything has to be restarted

**Comment by TimothyGu** [comment]
Yeah that's a gulp-pug bug.

**Comment by LiTiang** [comment]
SO WHY COLSED ??????

**Comment by ForbesLindesay** [comment]
Locking this as you need to raise bugs in gulp-pug if you want them fixed.  This is the core pug repository.
