### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by maraisr** [pugjs/pug#2297]
Gotta love this guys! Been using Jade for a year or so now! But I don't have syntax highlighting for Pug as Jade is jade still in many eyes. 

Would I need to contact the guys at `vscode` to spin up a language package for Pug, seeing as they already have Jade built in?

Would my quick and easy solution to just grab the jade highlighter, and change the file extension and we good to go?

**Comment by ForbesLindesay** [comment]
Yes, for vscode you'll probably need to ask them.  It should be as simple as adding the same syntax highlighter to `.pug` files as you suggest.

**Comment by Kequc** [comment]
I found out how, in user settings.

    "files.associations": { "*.pug": "jade" }

**Comment by NoNameProvided** [comment]
This can be closed now, as `.pug` files are now properly highlighted.

**Comment by TimothyGu** [comment]
@NoNameProvided, thanks!

**Comment by maraisr** [comment]
Thanks mate! So good! 😎
