### ISSUE TITLE
Does this website still maintain ?? http://jade-lang.com/

### ISSUE THREAD

**Issue by iroy2000** [pugjs/pug#2298]
Since Jade is renaming to pug,  is there any migration path ??

Are the usage will all stay the same ?? 

I think it will be great if there is a short docs in the website to clear confusion ?

And some of the links in pug website were broken, e.g.  http://www.pug-lang.com/tutorial/

**Comment by TimothyGu** [comment]
jade-lang.com probably will be redirected. The code is the same.

**Comment by iroy2000** [comment]
Ok, thanks, test it and work. But just to make sure people need to change extension to `pug` instead of `jade`
