### ISSUE TITLE
Code line break

### ISSUE THREAD

**Issue by THE-Beck** [pugjs/pug#2300]
Is there any better way to write this? Because writing = multiple times is not cool...

```
pre
  code
    = "<div class='element'>"
    = "<h3 class='title'>Title</h3>"
    = "</div>"
```

also how about line breaks in code?

**Comment by ForbesLindesay** [comment]
We don't support multi-line JavaScript expressions at the moment.  It is something we could consider in the future, but don't forget you can also just write:

```
pre
  code
    <div class='element'>
    <h3 class='title'>Title</h3>
    </div>
```

because pug accepts inline html.

**Comment by THE-Beck** [comment]
Oh i see, Thanks!
