### ISSUE TITLE
Migration from jade to pug doesn't work. Missing version 1.1.0

### ISSUE THREAD

**Issue by kulak-at** [pugjs/pug#2301]
After updating from jade to pug as it is recomended templates compliation stopped working. My template:

```
extends ./partials/template.pug

block content
  h1.subject Reset your password
  a.btn(href="#{activationLink}") Reset Password
  p.text I you haven't request your password being reset, please ingnore this email.
```
The pug version does not interpolate `#{activationLink}` to it's string value. I think the main reason behind it might be the fact the last stable version of jade is not available in pug repository - in pug repo is only version 0.0.0, 0.1.0 and alpha version of 2.0.0.

Note: Interpolation outside the blocks works fine, for example all variables inside my partials/template.pug works fine.

**Comment by TimothyGu** [comment]
We removed interpolation support in attributes. You have two options:

1. ES2015 template string

   ```jade
a.btn(href=`${activationLink}`)
```
2. Just use the variable

    ```jade
a.btn(href=activationLink)
```

**Comment by hovosanoyan** [comment]
Is there any option for easy migration. Other breaking changes are easy to fix, but this one is time consuming (2500 lines to replace). Or Is there anything planned to write?
