### ISSUE TITLE
escaping variables, behavior has changed for attributes

### ISSUE THREAD

**Issue by simbo** [pugjs/pug#2302]
When pug was still jade, this used to work:

```
span(class="icon-#{item.icon}")
```

Now with pug 2.0.0-alpha3, i have to do this (which also worked before, but was optionally):

```
span(class="icon-" + item.icon)
```

I have to admit, in this example, the second solution looks cleaner. But in most other, maybe more complex situations, i prefer the first solution.

Is this change on purpose? If yes, why?

**Comment by kimar** [comment]
I also ran into this and basically need to refactor lots of code due to this... Actually I prefer the first versio of the latter one...

**Comment by ForbesLindesay** [comment]
We've intentionally removed support for interpolation in attribute values.  If you are using a recent version of node.js you can just use template strings:

```
span(class=`icon-${item.icon}`)
````

And for legacy environments, string concatenation works well enough:

```
span(class='icon-' + item.icon)
````

Having syntax for this tended to lead to a huge number of people not realising you could use any JavaScript values for attributes so it made more sense to make people learn the language properly.  I've seen lots of people do:

```
a(herf="#{myLink}")
```

and similar, which can be simplified to:

```
a(herf=myLink)
````

This change forces people to write the cleaner code.
We've intentionally removed support for interpolation in attribute values.  If you are using a recent version of node.js you can just use template strings:

```
span(class=`icon-${item.icon}`)
````

And for legacy environments, string concatenation works well enough:

```
span(class='icon-' + item.icon)
````

Having syntax for this tended to lead to a huge number of people not realising you could use any JavaScript values for attributes so it made more sense to make people learn the language properly.  I've seen lots of people do:

```
a(herf="#{myLink}")
```

and similar, which can be simplified to:

```
a(herf=myLink)
````

This change forces people to write the cleaner code.

**Comment by kimar** [comment]
Fair enough, totally agree that using ES6 template strings is the way to go in this particular scenario. However I'm still encountering an issue using `Pug 2.2.0-alpha3`.

I'm using Express 4 and Node.js 5.5.0

This is what I have:

```
div.avatar-div(style=`background-image: url(https://www.gravatar.com/avatar/${locals.account.avatar})`)
```

And I'm getting the following error:

```
   34|                                 div.avatar
   35|                                     center
 > 36|                                         div.avatar-div(style=`background-image: url(https://www.gravatar.com/avatar/${locals.account.avatar})`)
---------------------------------------------------------------------^
   37|                                             img(src=`https://www.gravatar.com/avatar/${locals.account.avatar}`)
   38|                             div.col-md-4.col-account-email
   39|                                 //- p Username:
Syntax Error: Unexpected character '`'
```

From what I understand this should normally work...

**Comment by TimothyGu** [comment]
@kimar This has been fixed in pug-lexer@1.0.1, included in pug@2.0.0-alpha6. Thanks for reporting!

**Comment by kimar** [comment]
@TimothyGu awesome work! Thank you 👍

**Comment by soulcreate** [comment]
> span(class=`icon-${item.icon}`)

May you give any example?
I have `node -v v11.13.0` and nothing render. What is environments I should have to get work it?
