### ISSUE TITLE
pug npm package does not have 1.x releases

### ISSUE THREAD

**Issue by ianmaddox** [pugjs/pug#2303]
Upon trying to install Jade/Pug 1.11.0, I got the following error:

    npm ERR! No compatible version found: pug@^1.11.0
    npm ERR! Valid install targets:
    npm ERR! 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha1, 0.1.0, 0.0.0

**Comment by ForbesLindesay** [comment]
Updating to `pug` requires also updating to the 2.0.0 alpha.  We hope to have a stable 2.0.0 release very soon.

**Comment by jodytate** [comment]
Will pre 2.x versions remain available in the npmjs repository under https://www.npmjs.com/package/jade? If not, are you open to the idea of making pre 2.x versions available under the pug brand?

**Comment by rhbecker** [comment]
I was pondering the same question @jodytate just asked, almost verbatim.

**Comment by TimothyGu** [comment]
@jodytate & @rhbecker, yes.

**Comment by rhbecker** [comment]
@TimothyGu: I can't help but notice that the quantity of your answers is one fewer than the quantity of @jodytate's questions. Am I interpreting correctly that it'll be one or the other, but you're not yet sure which?

**Comment by TimothyGu** [comment]
I meant to answer the first question, since the second questions is contingent upon "no" being the answer to the first :)

But sorry about that confusion. Yes, 1.x will continue to be on npm as jade. 2.x will only be available as pug.

**Comment by rhbecker** [comment]
excellent! thanks!

**Comment by vdh** [comment]
It feels like a needlessly-awkward situation to add a depreciation warning to `jade@1.11.0`, but then not re-publish it as `pug@1.11.0`? We're stuck in this limbo between a depreciated library and an alpha one.

I like installing alphas as much as the next person, but other libraries that I'd like to make PRs towards in order to fix the warning (e.g. webpack/jade-loader), might not be as recklessly-adventurous as I am.

**Comment by TimothyGu** [comment]
@vdh, okay. I'll un-deprecate `jade@1.11.0` in the meantime, if @ForbesLindesay can confirm that doing so is acceptable under the terms he signed.

**Comment by vdh** [comment]
@TimothyGu Is there a reason a `pug@1.11.0` version couldn't be published as a copy of the `jade@1.11.0` release? It's a good idea to promote users to migrate from `jade` to `pug`, but without the 1.11.0 release to swap over to it's a lot harder to update dependencies.

**Comment by jescalan** [comment]
I have to second @vdh here. The transition over to pug means massive breaking changes for libraries that I'm working on, and I'd like to get them out of the way as soon as possible. Speaking of which, is there any even extremely rough timeline on when the `2.x` release is coming up?

**Comment by TimothyGu** [comment]
@jescalan, my expectation is within the next month.

@vdh, no, there is no reason not to. PR welcome.
