### ISSUE TITLE
include:marked why can't be insert code

### ISSUE THREAD

**Issue by awesomes-cn** [pugjs/pug#2304]
I just want to include a markdown file through the route action name
```
include:marked #{route.action}
```
But this doesn't work !!! this just include the `/views/home/#{route.action}` not compile `#{route.action}`

So what should I do ?

**Comment by ForbesLindesay** [comment]
On the roadmap for 3.0.0 (#2030) but unless someone else contributes a patch, I don't expect that to be for quite a long time.

**Comment by ForbesLindesay** [comment]
I'm locking this to avoid yet more fragmentation of discussion around dynamic includes.
