### ISSUE TITLE
No Breaking Changes

### ISSUE THREAD

**Issue by aw** [pugjs/pug#2307]
Hi @pugjs team,

Forgive me if this sounds rude (I know), but is it possible to **NOT** introduce breaking changes? (see #2305)

For example, if you plan to change the way dates are formatted, add a new function for that and leave the old one as-is? or perhaps include a flag argument such as `--breaking` which allows us to choose whether we want to work with the old dates or new dates, and on your end you can simply check for that flag and output the new/old date accordingly?

Breaking changes are a real pain, and I think a bit of diligence would be helpful when modifying code that's used by other people in production. It would help avoid "unintentional breaking changes" aka "bugs".

Thanks.

**Comment by ForbesLindesay** [comment]
The change to how Date is stringified has been planned for a long time, and emitted a warning for most of that time so people have had plenty of time to prepare.  You opt-in to breaking changes by updating to the most recent version.  Adding some other method to opt-in would mean that new users would still end up seeing the old behaviour, so at best we could make it opt-out.  Doing so would add considerable amounts of work & overhead.  If that's what you want, just use the old version.

**Comment by ForbesLindesay** [comment]
As for un-intentional breaking changes, these are indeed bugs.  They will be fixed, but wasting time putting intentional breaking changes behind a flag would not have reduced the likelihood of these bugs occurring.
