### ISSUE TITLE
Require('fs') in jstransformer makes it impossible to use webpack for browser environment.

### ISSUE THREAD

**Issue by azotova** [pugjs/pug#2310]
One of the dependencies, jstransformer, requires `fs` and breaks if `fs.readFile` is not defined. I use pug in the project that is compiled with Webpack for the browser, and since `fs` is not available there, the build gets broken. Is there a workaround to solve this issue? (In the meantime I just commented out the line `var filters = require('pug-filters');` but this is not a good solution.)

**Comment by ForbesLindesay** [comment]
You should not be compiling pug templates on the fly.  You can use the pug-cli to compile your templates to JavaScript using node.js.  This will be about 1000x more performant.  Alternatively, you could build a pug webpack loader to do the compilation on the fly that way.

If you really want to compile templates on the fly (like we do for interactive demos in the documentation) you can either use browserify, or configure webpack to expose an empty `fs` module.

**Comment by azotova** [comment]
Thanks @ForbesLindesay. Unfortunately, I am afraid that those solutions would not work. I use webpack to bundle a few files to be used in the browser environment, and one of those files uses pug `compile` function and hence requires pug. The problem is that an empty `fs` module (the default option in browserify AFAIK) doesn't solve the issue in the same way it does for pug-loader, because jstransformer contains the statement `tr.readFile = Promise.denodeify(fs.readFile);`. The function fs.readFile is not defined in the empty object.
At this point it looks like any code that contains `require('pug')` cannot be bundled with either webpack or browserify. This was not the case with v. 1.11.0.
