### ISSUE TITLE
Variables in string doesn't render anymore. "foo-#{ bar }"

### ISSUE THREAD

**Issue by MathiasPaumgarten** [pugjs/pug#2313]
I converted my jade setup from a working state to a pug setup. And it seems to me that inline variables inside of a string don't render no more. 

```jade
div( class="page-#{ page }" )
```

I want to apologize if it is a planned change and I simply didn't look close enough. Can anybody confirm this is on my end?

**Comment by ForbesLindesay** [comment]
This is intentional, see #2305

**Comment by philip-morning** [comment]
The pug 2.0 way to do this is like so:  `div(class="page-" + page)`

**Comment by MathiasPaumgarten** [comment]
@philip-morning thanks for the update. Even a year later. 👍
