### ISSUE TITLE
Enable github code highlight for .pug files too

### ISSUE THREAD

**Issue by abdulhannanali** [pugjs/pug#2314]
Meanwhile Github is highlighting `.jade` but not `.pug` files. Can anyone who knows the appropriate way propose to github to highlight `.pug` files just like `.jade` files too? That'll be very appreciated. 

Thanks a lot.

**Comment by blakeembrey** [comment]
https://github.com/github/linguist

**Comment by TimothyGu** [comment]
github/linguist#2956
