### ISSUE TITLE
Preserve folder structure after compiling with commandline

### ISSUE THREAD

**Issue by imanghafoori1** [pugjs/pug#2318]
How to complie a folder structure of pug files into the same one into html ?!

a/b1/b11.pug
a/b1/b12.pug
a/d2/d22.pug

into 
a/b1/b11.html
a/b1/b12.html
a/d2/d22.html

I am trying to use npm scripts as a task runner instead of gulp or grunt.

**Comment by ForbesLindesay** [comment]
The CLI lives in a separate repository.  Please open this issue on https://github.com/pugjs/pug-cli
