### ISSUE TITLE
Form in a form

### ISSUE THREAD

**Issue by boetnet** [pugjs/pug#2322]
Hi,

I am encountering a weird issue with pug.
Here is the pug code I am using
``` jade
html
    body
        form(onsubmit="return alert('1')")
            input(type="submit" value="1")
            form(onsubmit="return alert('2')")
                input(type="submit" value="2")
            form(onsubmit="return alert('3')")
                input(type="submit" value="3")
```
This pug code generates a page that I inspect with the DOM explorer (IE and Chrome) and with the "View Source" (IE and Chrome). Note that both inspection are done on the same page at the same time.

Here is the html code I see **in the "View source"**
``` html
<html>
  <body>
    <form onsubmit="return alert('1')">
      <input type="submit" value="1"/>
      <form onsubmit="return alert('2')">
        <input type="submit" value="2"/>
      </form>
      <form onsubmit="return alert('3')">
        <input type="submit" value="3"/>
      </form>
    </form>
  </body>
</html>
```
Here is the html code I see **in the "DOM explorer"**
``` html
<html>
  <body>
    <form onsubmit="return alert('1')">
      <input type="submit" value="1"/>
      <input type="submit" value="2"/>
    </form>
    <form onsubmit="return alert('3')">
      <input type="submit" value="3"/>
    </form>
  </body>
</html>
```

The correct code is the one of the "View Source" but in the browser this page behaves like what is shown in the DOM explorer. e.g. Clicking on input 1 and 2 will display a javascript alert with the value 1.

It is very strange and I don't see what to do to solve this. I am also unsure if it is a bug of pug or of something else.

Thank you for your help.

**Comment by TimothyGu** [comment]
What you are trying to do is not valid HTML. Pug faithfully compiled your code to HTML. The browser is trying to compensate for the error, and this compensation results in the tree you see in dev tools.
