### ISSUE TITLE
Load Assets

### ISSUE THREAD

**Issue by admdh** [pugjs/pug#2325]
It would be great if there was ability to load assets like css and js relatively to jade files. So for example it was possible to do something like this:
```
folder structure:
[src]
     | - [components]
          | - component.pug
          | - component.js
          | - component.css
          | - component.png
     | - index.jade

index.jade:
html
     head
          ...
     body
          include components/component.pug
```
and in component.pug file instead of:
```
link(href="components/component.css" ...)
img(src="components/component.png")
```
use: 
```
link(href="component.css" ...)
img(src="component.png")
```
why could be this useful? 
I think it's really great for component driven development. Of course in build time it will put all files separately and use one include for css and one for js.

**Comment by TimothyGu** [comment]
There is a Webpack loader for Pug, for example, that when combined with other loaders can [do this for you](https://github.com/pugjs/pug-loader#embedded-resources). The feature itself is out of scope for Pug.

**Comment by iamfrntdv** [comment]
is there any way to solve this without webpack?

**Comment by ForbesLindesay** [comment]
Without knowing how you plan to serve up your static assets and where the pug template will be hosted, it's difficult to see how this could be done.  It could probably be built as a plugin though, it's just not simple.
