### ISSUE TITLE
The file extension `.jade` is injected when you run `extends '<my file>'` without an explicit extension.

### ISSUE THREAD

**Issue by maraisr** [pugjs/pug#2328]

**Comment by mccart** [comment]
had to specify explicit extension .pug to get it to work.

**Comment by ForbesLindesay** [comment]
Please ensure you have updated to the latest version of pug and try again.  If the problem persists, you can comment here and I will re-open.

**Comment by mccart** [comment]
$ npm update pug 
does nothing...  error still persists.

adding this to package.json
    "pug": "*",
+   "pug": "https://github.com/pugjs/pug.git"

$ npm update
express_website@1.0.0 /home/mccart/Projects/NodeJSProjects/BasicExpressWebsite
└── pug@2.0.0-alpha6  (git+https://github.com/pugjs/pug.git#610972b2cedad7861ed9a447792112559615b4c3)

Success - no longer have to explicitly specify extension .pug for extends <file>

**Comment by ForbesLindesay** [comment]
npm's update command doesn't update the currently installed packages and I'm not sure `*` includes alpha versions.  Set it to `"pug": "2.0.0-alpha6"` then run `npm install`.
