### ISSUE TITLE
pug v1.11 not published in npm.js

### ISSUE THREAD

**Issue by rkurbatov** [pugjs/pug#2332]
I'd like to use pug in my repo but only version 2.0.0-beta or 0.1.0 available to install. Could you publish version 1.11?

**Comment by wolfgang42** [comment]
In [#2303](https://github.com/pugjs/pug/issues/2303#issuecomment-213143863), @TimothyGu said:
> 1.x will continue to be on npm as jade. 2.x will only be available as pug.

**Comment by trakout** [comment]
I'm using:
`{"pug": "^2.0.0-alpha7"}`

**Comment by TimothyGu** [comment]
@wolfgang42 has it right. I will add a note to the README soon explaining the relations between Jade and Pug.
