### ISSUE TITLE
i'm using jade 'extends' syntax. but it's not working(still find .jade file)

### ISSUE THREAD

**Issue by breaklee** [pugjs/pug#2338]
i've renewed my project to pug.

change : file extention .jade to .pug
change : express view engine to pug

```javascript
app.set("view engine", "pug");
```
and in my index.pug,
using this syntax.

```javascript
extends layout
```

and install new modules "pug"
```bash
npm install pug
```

but, when i start my app, raise an error below
```json
{"errno":-2,"code":"ENOENT","syscall":"open","path":"/path/layout.jade"}
```

what's wrong?

**Comment by WilixLead** [comment]
I have equal problem and found what's was wrong.
In included module pug-loader in NPM latest package we have old code in line 29
`if (node.type === 'Extends' || (!node.filter && /\.jade$/.test(path)))`
In pugjs/pug-load github repo already new version of code. 

Also, another place in this repo lib/index.js line 72
`if (path.basename(filename).indexOf('.') === -1) filename += '.jade'`

And it also already fixed, but from npm I have older version.
I think, contributors should just update NPM package for latest version of code

@breaklee You can just replace next files
https://github.com/pugjs/pug/blob/master/lib/index.js -> node_modules/pug/lib/index.js
https://github.com/pugjs/pug-load/blob/master/index.js -> node_modules/pug-loader/index.js

And get worked engine (and wait updates from package contributors)

**Comment by ForbesLindesay** [comment]
Make sure you're using the latest version of pug `npm install pug@2.0.0-alpha6`.
