### ISSUE TITLE
Maybe rename pug?

### ISSUE THREAD

**Issue by LestaD** [pugjs/pug#2340]
I guess name of package sounds worse
I can give you any name for the package from my reserved list for free:

- zink
- uran
- uranium
- selen
- rhenium
- quot
- qod
- prev
- oos
- palladium
- parens
- waterpool
- ol
- oct
- raised
- ndash
- mts
- marganese
- mandorine
- mandarine
- latin
- kex
- lantan
- iun
- harry
- gudge
- genious
- furer
-ftor
- footer
- extern
- erbium
- dob
- distr
- discard
- dualplex
- char
- astat
- 422
- 403
- 3.14
- voltage

And more at [~lestad](https://www.npmjs.com/~lestad)

**Comment by jamen** [comment]
Jade has practically just migrated everything to Pug, as well as the branding assets being made, and the domain has been bought.

If you don't like the name, considering using aliases in whatever environment:
```javascript
var jade = require('pug');
```
```shell
alias jade="pug";
```
etc.

This is an opinionated issue, so I don't imagine it will get very far...

**Comment by jamen** [comment]
On the side note, it is _against_ npm's policy to reserve package names like that to begin with...  Esspecially with what you are doing in such a large volume.  Someone is easily able to free your packages via npm support anyways.

**Comment by TimothyGu** [comment]
The name has already been decided. Plus as @jamen mentioned what you are doing here is not legal or ethical so please do the community a favor and unpublish the packages. Thanks

**Comment by ForbesLindesay** [comment]
I've submitted a request to npm support to ask them to remove those packages.  @LestaD please don't do this in future, please use your time to do something productive.
