### ISSUE TITLE
Interpolation in attributes not working in Pug 2a6

### ISSUE THREAD

**Issue by bassie1995** [pugjs/pug#2346]
I use interpolation to inject variables into HTML attributes, but with Pug 2.0.0 alpha 6, this doesn't seem to work anymore.

I can still 'print' the value with something like
    p.
      #{user._id}

But in an attribute, like
    form(action='../enable/user/#{user._id}', method='post')
it simply redirects to `<url>/user/#{user._id}`, which obviously results in a 404.

**Comment by bassie1995** [comment]
I saw https://github.com/pugjs/pug/issues/2305#issue-148065470 and tried to use
    action='../enable/user/${user._id}'
but this now redirects to `/enable` instead of `/enable/user`.

**Comment by bassie1995** [comment]
I read it again and saw that I seem to need to use `action='../enable/user/' + user._id'`. This works.

Sorry, late night!

**Comment by TimothyGu** [comment]
If you want to use the former syntax, you need to use the backtick character (the key you use to markup a piece of inline code in Markdown), not single quote.

**Comment by bassie1995** [comment]
Ah, cool! Is there any specific (dis)advantage to that over using the new syntax?

**Comment by TimothyGu** [comment]
The backtick syntax is part of [ES2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), so if you are unfamiliar with the latest version of ECMAScript I recommend checking it out. There isn't really a significant disadvantage other than that V8 isn't very optimizing when it's used.

**Comment by bassie1995** [comment]
Ah, I had forgotten to look at ES2015 changes. Hadn't noticed the backticks in the change issue yet, even.

Thanks!

**Comment by jq-87** [comment]
this is a big problem, i got a large jade codebase and i just upgraded to Pug. 

I have a lot  of code that does things like
`a(href='#{url}')` 
or 
`div(class='section #{class} gutters')` 
search and replace is not an option because there is a vast variety of use cases ..

what do you recommend I do?

**Comment by lukewendling** [comment]
+1 @jq-87 

we use ```script(src='js/app.#{Date.now}.js')``` for cache busting. the previous behavior of string interpolation for such attrs is very helpful. please don't make me go back to grunt! :)

**Comment by ForbesLindesay** [comment]
Just update to the new syntax.  It's the same number of characters.
