### ISSUE TITLE
Escaping of attributes in mixins

### ISSUE THREAD

**Issue by WartClaes** [pugjs/pug#2353]
I have a problem with the following setup where I want to pass an HTML entity with an attribute (or even as a parameter. The result stays the same) :

```jade
mixin foo
    .foo #{attributes['bar']}

+foo(
    bar="&ecirc;"
)
```

**Expected:** 

```html
<div class="foo">ê</div> <!-- resulting in ê -->
```

**Result:**

```html
<div class="foo">&amp;amp;ecirc;</div> <!-- resulting in &amp;ecirc; -->
```

This is because values are escaped, which means that also the ampersand would become a html entity for which he escapes the first ampersand.

One solution would be using the exclamation and the equal sign in my mixin 

```jade
.foo!= attributes['bar']
```

But the result of this is also not the expected one since jade still escapes the ampersand by using `&amp;` their self. This way the ampersand renders as a html entity but the combination is still ignored by HTML.

```html
<div class="foo">&amp;ecirc;</div> <!-- resulting in &ecirc; -->
```
In the end the original entity will not be parsed, is there a way to fix this?

**Comment by TimothyGu** [comment]
The correct way is to use `!=` syntax for unescaped attributes, but mixins are a special case: it also supports regular JavaScript arguments, so you will have to disambiguate using an empty set of parentheses.

Try this:

```jade
mixin foo
    .foo!= attributes['bar']

//- vv disambiguator
+foo()(
    bar!="&ecirc;"
)
```

or this:

```jade
mixin foo
    .foo !{attributes['bar']}

+foo()(
    bar!="&ecirc;"
)
```
