### ISSUE TITLE
Dead link - Test drive, readme.md

### ISSUE THREAD

**Issue by thejohnsmith** [pugjs/pug#2355]
** Duplicate of #2354
## 'Test Drive' Url leads to a 400 page in the Readme file

**Context:** 
> You can test drive Pug online [here](https://naltatis.github.io/pug-syntax-docs).

**File:** `README.md`
**Broken Link:** `href= https://naltatis.github.io/pug-syntax-docs`

- [ ] Update link or remove altogether if page no longer exists

**Comment by TimothyGu** [comment]
Fixed in d4b4f78.
