### ISSUE TITLE
Meteor Package

### ISSUE THREAD

**Issue by KyleKing** [pugjs/pug#2359]
I currently use the [Meteor Jade Package](https://github.com/mquandalle/meteor-jade), which is a version of Jade that supports the Spacebars syntax included with Meteor. Is there a migration guide for any changes in Pug to help Meteor Jade update? Or just to change the name?

-Kyle

**Comment by ForbesLindesay** [comment]
I do not have any involvement in the meteor package.  Please direct your questions to the meteor jade repository.

**Comment by KyleKing** [comment]
Oh no, I'm just asking if there is a changelog to help migrate the meteor package to pug. There hasn't been activity on the meteor package: https://github.com/mquandalle/meteor-jade/issues/198. So far it has been the least productive discussion... 

I want to help see that the Meteor community gets to use the newest version of Pug/Jade

**Comment by ForbesLindesay** [comment]
#2305 is a rough log of breaking changes externally.  Internally the architecture has changed dramatically.  The core components (lexer, parser, code-gen etc.) have all been split out into separate npm packages, which should make it easier if you need to highly customise the output.  I haven't really looked at how meteor jade was working.

**Comment by KyleKing** [comment]
Okay, then I might port Pug directly to Meteor rather than introducing the
breaking changes to Meteor-Jade

On May 6 2016, at 10:12 am, Forbes Lindesay &lt;notifications@github.com&gt;
wrote:  

> [#2305](https://github.com/pugjs/pug/issues/2305) is a rough log of breaking
changes externally. Internally the architecture has changed dramatically. The
core components (lexer, parser, code-gen etc.) have all been split out into
separate npm packages, which should make it easier if you need to highly
customise the output. I haven't really looked at how meteor jade was working.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/pugjs/p
ug/issues/2359#issuecomment-217450962)![](https://github.com/notifications/bea
con/ADm-k3itsV1hZ-sw0QqBD77w0DXqzYGaks5p-0xfgaJpZM4IYBEN.gif)

**Comment by jbernard1** [comment]
@ForbesLindesay Will there ever be a release for a pugjs package on Meteor? I am new to meteor and would like to use pug instead of pure blaze.

**Comment by hems** [comment]
+1 for pug and blaze jazziness! would be super awesome

**Comment by splex7** [comment]
+1 it will be very nice
