### ISSUE TITLE
Filters -- Jade to Pug

### ISSUE THREAD

**Issue by zmanring** [pugjs/pug#2360]
I have ported over my code from Jade to Pug and it seems to missing filters? Does anyone else have any insight on this?

**Comment by jceipek** [comment]
I'm no expert; I just started using Jade in the past few days and discovered yesterday that it was renamed `Pug`.

However, I think that filters now need to be passed in as options via [jstransformers](https://github.com/jstransformers).

To use the filter `:marked` for markdown, this worked for me:
```
require("pug").render(pugString, { filters: [ require('jstransformer-marked') ] })
```

If anyone has more experience with `Pug`, please chime in.

**Comment by zmanring** [comment]
Yeah I was reading about that but I didn't know if that was locked down to just jstransformer filters. I will need to see how to make my own then.

Here is an example of how it currently works in Jade. This is used to render Lorem text locally and on export to use the CMS driven scripting language of your choose. (*.licoffee)
```
      jade.filters.content = (block) ->
        blockArray = block.split('||')
        localBlock = blockArray[0].trim()

        jade.render localBlock, { lorem: lorem }
```

Here it is in use. (*.jade)
```
        :content
          | 1(888) 555-55555 || ${contactus.prettyPhoneNumber}
```

Any thoughts on that?

**Comment by ForbesLindesay** [comment]
You can just do:

```js
require("pug").render(pugString, {
  filters:  {
    content: function (block) {
      return 'some string';
    }
  }
})
```

I think we should maybe support specifying filters using the old way as well as this new way.

**Comment by zmanring** [comment]
Ah perfect, so its in the render function.. I didn't see that. I kept looking in the root for `filters` which is how Jade was :) I will give this a shot, thanks!

**Comment by qm3ster** [comment]
If I am using pug in express, is there a way to set some filters for all calls to res.render?
Preferably in a way that would allow me to add more for specific calls.

**Comment by qm3ster** [comment]
@jceipek @ForbesLindesay In both jstransformer and inline filter declaration, what actually specifies the name of the filter?! Where is ":markdown" defined, vs ":potatoes"?

**Comment by zmanring** [comment]
@ForbesLindesay Where would "PugSring" come from? In Jade you return a block in the callback?

**Comment by TimothyGu** [comment]
@qm3ster, for the most recent documentation see https://github.com/pugjs/pug/blob/master/docs/views/reference/filters.pug. That tells you pretty muh everything you need to know about filters in Pug. We haven't gotten time to convert it to HTML yet but the Pug file is the most we have right now. Hope it helps.

@zmanring, `pugString` is just a placeholder.

**Comment by zmanring** [comment]
Thanks Tim, with some finagling I got it working as intended. Thank you for your help and understanding.

**Comment by zmanring** [comment]
@TimothyGu Is there a way to pass in `local` data into a filter? I know you can pass in options `:filter(option1, option2)` but can I do something like `filter(options!=#{local})`?

**Comment by ForbesLindesay** [comment]
@zmanring  no because filters are handled at compile time.  They cannot depend on runtime information.

**Comment by qm3ster** [comment]
Okay, so it gets it from the name property of the transformer module, or the param name in the manually passed filters object.
Now can someone explain why 
```js
var marked = require('marked');
...
exports.render = function (str, options) {
  return marked(str, options);
};
```
is somehow different from 
```js
...
exports.render = require('marked');
```
(which does not let the filter get registered)

**Comment by TimothyGu** [comment]
@qm3ster, first, you most likely want to use the already-existing jstransformer-marked module. Second, the exported `render` function takes three arguments, not just two, with the last being `locals`; OTOH marked takes three arguments as well, but the last is `callback`. That's why they are not compatible.

**Comment by qm3ster** [comment]
@TimothyGu That's where I took it from, I was studying how to make filters.
Alright, I see the wrapper does change call signature, by blocking the locals object from going into the callback. Thank you for the explanation.

**Comment by Dan503** [comment]
I've upgraded a [Yeogurt](https://github.com/larsonjj/generator-yeogurt) project to using Pug and the filters seem to not work any more.

I've tried both `:marked` and `:markdown` as filters and I keep getting this error:
`````````
unknown filter ":marked"
```````
or
`````````
unknown filter ":markdown"
```````
I'm using Pug through gulp using the gulp-pug npm plugin

I've tried doing this after npm installing `marked` and it didn't work.
```````````
//blah blah gulp code
.pipe(plugins.pug({
    pug: pug,
    filters: [ require('marked')  ],
}))
//blah blah gulp code
``````````
I have no idea how to get the Pug to read the markdown filter :(

Just to test, I tried using a `:coffee-script` filter since it hasn't gone through any changes since it's inception and that didn't work either. Where have all the filters gone???

I'm running Pug version 3.10.6.

**Comment by TimothyGu** [comment]
@Dan503, first, I'm not really sure what version "3.10.6" refers to... Jade's latest is 1.11.0, and Pug's latest is 2.0.0-beta6, and gulp-pug's latest is 3.0.4.

The way filters work in Pug is that, instead of requiring the users to download a bundle of filters the user might not even use, you now have to install individual filters through the [jstransformer](https://www.npmjs.com/browse/keyword/jstransformer) system. In your case, simply `npm i --save jstransformer-marked` should work. For coffee-script, it is `npm i --save jstransformer-coffee-script`.

Check our our [updated documentation](https://pugjs.org/language/filters.html) for more information.

**Comment by Dan503** [comment]
Thank you :)

I'll give that a try as soon as I get the chance.

In the documentation link you posted, it says to use `markdown-it` as the Markdown filter. Is that the recommended one to use now?

Sorry about the version number. I keep forgetting that `npm [module-name] --version` doesn't output the module name version, it outputs the npm version.

**Comment by TimothyGu** [comment]
No, marked is just as supported as markdown-it. marked had some unfixed security issues (since fixed) when I wrote the documentation, but I can probably revert to markdown-it now.

**Comment by ForbesLindesay** [comment]
I think in my personal opinion, markdown-it currently seems better supported/maintained, but you can use whatever markdown compiler you want (as long as it has a `jstransformer-` wrapper).  pug doesn't take any particular stance on the correct one to use.

**Comment by seguri** [comment]
@Dan503 I have the same problem! I've created a filter, then switched for a moment to create a custom version of jquery (git clone, npm install, npm install -g grunt-cli), came back to pug, and now I get `unknown filter`!

**Comment by Dan503** [comment]
@seguri the filters need to be manually downloaded now. They aren't included by default any more.

See filters in the documentation for more info.
https://pugjs.org/language/filters.html

**Comment by seguri** [comment]
@Dan503 I never supposed they were included. I've created a filter, switched to building a custom jquery, and when I was back to my project, my filter was no more recognized. I also moved to a temporary folder, [downloaded the example](https://pugjs.org/language/filters.html#custom-filters), and I get
```
undefined:7
};
 ^

SyntaxError: Unexpected token ;
    at parseObj (~/.nodenv/versions/10.14.2/lib/node_modules/pug-cli/index.js:101:29)
    at Object.<anonymous> (~/.nodenv/versions/10.14.2/lib/node_modules/pug-cli/index.js:81:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
Removing the semicolon leads to `unknown filter "my-own-filter"`.

**Comment by ForbesLindesay** [comment]
If you can submit a full test case demonstrating the issue I'll be happy to investigate further. If so, please open a fresh issue as this one is a very old issue.
