### ISSUE TITLE
Parsing class error

### ISSUE THREAD

**Issue by Tommy-42** [pugjs/pug#2362]
Hello there,
this is the first issue that I open on github, so let me know if anything is wrong ...
I tried to implement bootstrap 4 on one of my school projects and I ended up to have a problem with some class that have changed from bootstrap 3
Like `.form-group` change to `.form-group-*`
so `div.form-group-*`
gives : `unexpected text "*"`

did I done something wrong or it is an unknown issue ?

best regards,
tommy

**Comment by ForbesLindesay** [comment]
You're mis-reading the documentation.  What they mean by the `*` is not that there's a literal `*` in the class name.  They just mean that the same is true for all classes that begin `form-group`.  The actual sentence from the docs is:

> Dropped `.form-group-*` classes for simplicity’s sake. Use `.form-control-*` classes instead now.

You can see the full docs for what class names you should use where in http://v4-alpha.getbootstrap.com/components/forms/

**Comment by Tommy-42** [comment]
oh damn you right, sorry for useless issues !
