### ISSUE TITLE
Allow duplicate block in layout

### ISSUE THREAD

**Issue by sd65** [pugjs/pug#2367]
Hi,

I can't manage to make Pug works correctly for my use case.
I develop a website where a page can be loaded **completely or partially** (content only, for a Ajax changing page).

I think something like this should works : 

```
// page.pug
block content
  p Hello
```

```
// layout.pug
if (ajax)
  block content
else
  html 
    head
      ...
    body
      ...
      block content
```

But it don't work. Maybe because the double "block content".

---

Currently I'm using this ugly workaround : 

```
// page.pug
block content
  block contentAjax
    p Hello
```

```
// layout.pug
if (ajax)
  block contentAjax
else
  html 
    head
      ...
    body
      ...
      block content
```

Do you think this should be fixed too ?

**Comment by ForbesLindesay** [comment]
This is something I'd like to look at for 3.0.0 but it's too much work to get this right to do it for 2.0.0.

**Comment by redwoz** [comment]
Note that I'm having the same issue when moving from jade->pug - this is existing functionality in jade@1.11.0 which has broken somewhere along the line to pug@2.0.0-alpha8

**Comment by TimothyGu** [comment]
Are you sure that this works with `jade@1.11.0`? I don't think it was supposed to.

**Comment by redwoz** [comment]
definitely - also described in #2379 suggesting common use case when performing conditional blocks for partial ajax page loads (which is what i am doing).

issue/jade resolution reproducible below taking the /example from pug@2.0.0-alpha8:

### original

$ node examples/extend.js
**_ok_**

### break code

-- extend-layout.pug:

```
html
  head
    h1 My Site - #{title}
    block scripts
      script(src='/jquery.js')
  body
    if(true)
      block content
    else
      block content
    block foot
      #footer
        p some footer content
```

$ node examples/extend.js
**_fails_**

### fix code (by using jade)

$ npm install jade
$ rename "s/.pug/.jade/" ./examples/*.pug

-- extend.js:

```
var pug = require('jade')
  , path = __dirname + '/extend.jade'
  , str = require('fs').readFileSync(path, 'utf8')
  , fn = pug.compile(str, { filename: path, pretty: true });

var tobi = { name: 'tobi', age: 2 };
var loki = { name: 'loki', age: 1 };
var jane = { name: 'jane', age: 5 };

console.log(fn({
    title: 'pets'
  , pets: [tobi, loki, jane]
}));
```

-- extend.jade:

```
extends extend-layout.jade

block scripts
  script(src='/jquery.js')
  script(src='/pets.js')

block content
  h1= title
  each pet in pets
    include pet.jade
```

$ node examples/extend.js
**_ok_**

any effort getting this working in pugjs and preventing dirty workarounds appreciated.

**Comment by ForbesLindesay** [comment]
If this worked in jade then I think we should attempt to fix this before the final 2.0.0 release.

**Comment by perrin4869** [comment]
The example above seems like an anti-pattern to me. Would it not be better to render different templates for each case?

```js
if (ajax) res.render('ajax', ajax);
else res.render('foo')
```

**Comment by sd65** [comment]
@perrin4869 Firt because will need to repeat the parameters for `res.render` and secondly because you don't want to repeat the content of your pages in "mypage.pug" and "mypage_ajax.pug".

**Comment by Tiliavir** [comment]
Also required for AMP (accelerated mobile pages) and all other scenarios, where you want to dynamically provide the user with another layout of the same content ...

**Comment by garkin** [comment]
Lost 4 hours to find this **not documented** degradation after `pug` migration.
Really a party killer for ajax.

**Comment by TimothyGu** [comment]
@garkin, #2305 is now referenced in the README. And since this is a bug, it won't go into the ticket as those are legitimate changes.

**Comment by daviddiasfront** [comment]
I'm facing the same issue, I try using case and if/else and something that was working before with Jade is no more working with Pug.

```pug
if (pageType == "masonry")
    block content
else if (pageType == "2cols")
    block content
else
 block content
```

In my index.pug, I have the block content with content inside that is no be printing. Have your an idea when that could be fixed?

**Comment by chharvey** [comment]
@sd65 Could you not use a mixin to achieve this? A mixin with zero parameters is basically the same as a block.

    // page.pug
    mixin content()
      p Hello

    // layout.pug
    include page.pug
    if (ajax)
      +content()
    else
      html 
        head
          ...
        body
          ...
          +content()

**Comment by OwnageIsMagic** [comment]
@chharvey 
```javascript
var a;
```
```javascript
var b;
```
\`\`\`javascript
var a;
\`\`\`
\`\`\`javascript
var b;
\`\`\`

**Comment by Scriptura** [comment]
@ForbesLindesay : I confirm that the extended blocks nested under conditions worked under Jade.

**Comment by ForbesLindesay** [comment]
Thank you for your patience on this issue.  The latest release 2.0.0-beta8 should resolve things.  Please try it out and open a new issue if anything is still broken.

**Comment by Mad-Chemist** [comment]
> Thank you for your patience on this issue. The latest release, 2.0.0-beta8, should resolve things. Please try it out and open a new issue if anything is still broken.

To the best of my knowledge I don't think `2.0.0-beta8` or `2.0.3` includes a fix to this issue.  I'm noticing that conditionally modifying blocks ignore the conditional logic and will still always apply all modifications.

**Comment by ForbesLindesay** [comment]
@Mad-Chemist Can you open a fresh issue and fill out the issue template to clearly describe the problem you are currently experiencing. You can refer to this issue if you think it's related, but I'd like to keep each issue about exactly one bug if possible, and I think the exact bug tracked by this issue has been resolved.
