### ISSUE TITLE
New sintax for Pug? problems with Jade mixin

### ISSUE THREAD

**Issue by kengreg** [pugjs/pug#2370]
Hello, I just recently find out that Jade will change to pug so I decided to change my Jade files to pug and start using it.
However, I have find some issues with the mixin sintax which I can not find a solution. The mixin sintax changed? 

for example, in jade I could use this>>

```
mixin practice(figure, alt)
  div
    - each practice2, i in alt
      -var image3 = '<img src="'+figure[i]+'" alt="'+alt[i]+'" />'
        figure!= image3
+practice(['https://domain.com/img/hello-picture.gif','https://domain.com/img/Hello_logo_sm.gif'],['hello', 'hola'])

```

But now when I tried to compile it with pug, it always says that its incorrect. How is the correct way to handled two arguments (or one or more) with the mixin? make them variables? how is it?

Thanks for your help in advance and I really appreciate your work making possible this kind of markup language to write HTML.

**Comment by SergioCrisostomo** [comment]
It might be related to the new syntax for `each` loops now deprecating the `- each` usage. 

There are some known breaking changes in issue `#2305`, you might want to check there.

**Comment by ForbesLindesay** [comment]
You should no-longer prefix `each`, `for`, `if`, `else` etc. with `- ` as they are not true JavaScript.  They are part of the `pug` syntax and are keywords in their own right.
