### ISSUE TITLE
Exclamation mark breaks Pug

### ISSUE THREAD

**Issue by subchild** [pugjs/pug#2376]
```
> 15|     !!! 5
------------^
    16|     html(lang='en-us')

unexpected text "!!! 5"
```

Also affects libs which use it, e.g. https://github.com/FGRibreau/pound which uses this syntax:
`!{renderScript("app")}`

**Comment by ForbesLindesay** [comment]
That was a breaking change from so long ago that we no longer even warn about it.  You should use `doctype html` rather than `!!! 5`
