### ISSUE TITLE
Is there any breaking changes between jade 1.x and pug 2.0? 

### ISSUE THREAD

**Issue by vilitormanen** [pugjs/pug#2377]
Is there any breaking changes between jade 1 -> pug 2? If there is can I see somewhere the list of changes? 

Oh, is there any time table for official release? We really can't include any alpha-versions to our software.

**Comment by freezy** [comment]
There is #2305 which I found after a few frustrating hours of debugging. Huge refactoring due to name change plus these subtle changes was kind of sneaky. Might be a good idea to link this issue in the README or at least in History.md, folks!

**Comment by TimothyGu** [comment]
Yeah, I'll put an explanation in README when I get the chance.

**Comment by TimothyGu** [comment]
Done.
