### ISSUE TITLE
Conditional block wrappers

### ISSUE THREAD

**Issue by subchild** [pugjs/pug#2379]
We're using something like this in Jade (not latest) but Pug doesn't appear to like calls to the same `block` in a single layout. 

Any known workarounds? Thanks.

```
if (!req.headers["x-pjax"])
    doctype html
    html(lang='en-us')
        head
        body
            main
                block content

if (req.headers["x-pjax"])
    main
		block content
```

The above code doesn't display the `content` block in either case.

**Comment by ForbesLindesay** [comment]
Duplicate of #2367
