### ISSUE TITLE
legacy attribute string interpolation support

### ISSUE THREAD

**Issue by jq-87** [pugjs/pug#2383]
I commented on this issue here:
https://github.com/pugjs/pug/issues/2346

I really want to upgrade to Pug but this feature deprecation is a big blocker for me at the moment - I have a very big jade codebase that I would need to update.

Is there any version of Pug that supports the string interpolation in attributes that were allowed in the latest jade version?

Please help!

**Comment by TimothyGu** [comment]
No, if you want to use legacy Jade syntax you have to use Jade. Would it help if we warn against possible instances of the old syntax?

**Comment by jq-87** [comment]
I will continue using the latest Jade then. At least until I can fully update my codebase to use the string template syntax, will Jade still be available as a npm download for a while?

**Comment by TimothyGu** [comment]
`jade` will be available permanently.

**Comment by jq-87** [comment]
cool
