### ISSUE TITLE
bug: support '.jade' file exention

### ISSUE THREAD

**Issue by tomByrer** [pugjs/pug#2388]
[> include only works with .pug file extensions. We should make this support legacy .jade extensions (with a deprecation warning)](https://github.com/pugjs/pug/issues/2305#issue-148065470)

Might be a while before the editors fully catch up with the new file extension.  Right now in Atom I'm forced to keep `*.jade`, so I hope this is still compatible for the 2.0 release.

Might want to add to checklist: 'Notify all hipster code editors about new file extension'.  ;)

**Comment by tomByrer** [comment]
Upgrading to bug, since getting this error:

> message: 'ENOENT: no such file or directory, open \'/src/base.pug\'\n    at //src/colors/colors.jade line 1',

Editing the line to `extends ../base.jade` fixed the issue.

Should only warn for 2.x branch IMHO, if not forever.

**Comment by ForbesLindesay** [comment]
I don't plan to fix this.
