### ISSUE TITLE
block keyword inside filter

### ISSUE THREAD

**Issue by qm3ster** [pugjs/pug#2390]
```pug
mixin md
    div(class!=attributes.class)
        :remarkable
            block

+md.lmao
    # AYY LMAO
```
Produces 
```bash
    10| block article
    11|     +md.lmao
  > 12|         # AYY LMAO
----------------^
    13|     - title="Home"
    14|     section
    15|         :remarkable

" AYY" is not a valid ID.
```
(And `#AYY` fails silently, producing `<div class="lmao"><p>block</p></div>`)

I am guessing this is once again because mixins get compiled for clientside after all filters have been substituted.
It would be good to have a way to write at least static server-side mixins with filters.

:+1: Great job on `.class` notation being included in the mixin attributes btw.

**Comment by ForbesLindesay** [comment]
This is working as intended. You are correct re compile vs. runtime.
