### ISSUE TITLE
unclear warning: Unexpected block undefined

### ISSUE THREAD

**Issue by tomByrer** [pugjs/pug#2391]
Full error report:
`Warning: Unexpected block undefined on line undefined + of undefined. This warning will be an error in v2.0.0`

My file:
```jade
extends ../base.jade

block append body-content
	.colors testing colors
```
& I forgot `block body-content` in base.jade 😊 
Edit; same error if compiling multiple files; extra confusing.

Expected:
File path(s) & line number of error.
Not to become an error in v2.0.0.  Please consider waiting to v2.1.x, or even v3.

cheers :)

**Comment by chuchuhao** [comment]
get the same error message 😢

**Comment by ForbesLindesay** [comment]
Update to the latest pug alpha.  If there's still no line number and you can submit a repro case I'll look into it.

**Comment by anowlcalledjosh** [comment]
@ForbesLindesay I'm having the same problem.

index.pug:

```
extends a
block foo
```

(it doesn't matter what the block is called, it just needs to not exist in a.pug)

a.pug:

```
```

(file can contain any valid Pug, including being empty, as long as it doesn't contain `block foo`)

Compiling gives `Warning: Unexpected block undefined on line undefined + of undefined. This warning will be an error in v2.0.0`.

Output of `pug --version`:

```
pug version: 2.0.0-alpha8
pug-cli version: 1.0.0-alpha6
```

**Comment by ForbesLindesay** [comment]
Thanks for following up.  I was able to reproduce the issue and have submitted a fix.  I'll let @TimothyGu review it and publish a new version.  We might want to call the next version beta1 rather than alpha9 as we're approaching a much more stable release.
