### ISSUE TITLE
Allow multiple filenames

### ISSUE THREAD

**Issue by jwerre** [pugjs/pug#2393]
I have two directories one for layouts and one for included in my project. When I go to compile I can only specify one or the other which results in an error. It would be nice to pass an array of filenames like so:

		var options = {
			filename: [ 'path/to/pug/layouts', '/path/to/pug/includes' ],
			compileDebug: false,
			pretty: false
		}

		var html = pug.compile( template, options);

**Comment by ForbesLindesay** [comment]
1. You want basedir for this, file name should always be the actual location of your file.
2. You can still only have one basedir because it would make your code harder to understand if you add many basedirs.  Just do `include /includes/my-include.pug` and `extends /layouts/my-layout.pug`
