### ISSUE TITLE
Encoding does not encode ' (single quote)

### ISSUE THREAD

**Issue by ckeboss** [pugjs/pug#2397]
The encoding should encode all html special chars ("&<>'), and currently it only does "&<>.

This issue can cause XSS attacks if an escaped jade var is used in say a script tag:
```javascript
script.
    foo('#{bar}')
```
when bar = '); alert('foobared');

I will create a PR soon to address this, just wanted to document in here.

**Comment by ForbesLindesay** [comment]
This is working as intended.  You need to escape a lot more than that to embed user entered text in JavaScript

**Comment by ForbesLindesay** [comment]
To do this you should use something like https://www.npmjs.com/package/js-stringify
