### ISSUE TITLE
How to fix jade1.11 vulnerabilities without going pug?

### ISSUE THREAD

**Issue by DeadCham7** [pugjs/pug#2399]
For our site, security and stability is valued most.

We can't afford to convert jade to pug when pug is still alpha version but at the same time we need to take care of the security holes(https://nodesecurity.io/advisories/39, https://nodesecurity.io/advisories/48 ).

Those two issue seems like its coming from uglify and tranformer. Is there anyway I can fix those vulnerabilities? Maybe is it possible to get fixed version of those   ##dependencies?

Please enlighten me! Thanks in advance.

**Comment by TimothyGu** [comment]
These "security" issues may be severe, if the server actually uses UglifyJS to minify user's untrusted code. For Pug/Jade, unless you are compiling user's code on your server, there is literally no way for UglifyJS to be used on untrusted code. And if you _are_ compiling untrusted code on your server, far worse things can happen, such as

```js
!= fs.readFileSync('/etc/passwd', 'utf8')
```

As a result, jade 1.11 is not insecure, as these advisories seem to say.
