### ISSUE TITLE
Conditional adding of attributes?

### ISSUE THREAD

**Issue by Qard** [pugjs/pug#240]
Basically I'm wondering if there is, or could be, a cleaner way to do this;
- if (checked)
  input.check(type="checkbox", checked="checked")
- else
  input.check(type="checkbox")

**Comment by conmute** [comment]
Just I had this issue, and solution for my case was:

```jade
table#example
    thead
      tr
        each val, index in tableData[0]
          th(data-dt-filter-here=(index == 'email'?'':false))
            !=index
```

This will produce

```html
<!-- ... -->
<th data-dt-filter-here>
   index value
</th>
<!-- ... -->
```

Combiningthis and @bevacqua example yuo can easely adjust to any situation of conditional attributes in jade.

**Comment by isiahmeadows** [comment]
@conmute That helped me on something I'm working on. But for that particular example, I don't see why you couldn't just do this?

```jade
each _, index in tableData[0]
  th(data-dt-filter-here=(index === email))!= index
```

**Comment by conmute** [comment]
@isiahmeadows Nice, thank you!

**Comment by ForbesLindesay** [comment]
Just set the doctype to `'html'` and it will generate the shortened form by default anyway.

**Comment by conmute** [comment]
@ForbesLindesay I didn't tested, but do this work when including a jade tempalte file?

And also i also need to be working without `<!DOCTYPE html>` in file. For example: angular templates.

Can i type `doctype html` in such whay that jade will process it, but will not render it?

**Comment by ForbesLindesay** [comment]
I mean pass in an option `{doctype: 'html'}`.  This is implicitly handled for you providing you have `doctype html` **before** the code with the attribute.

**Comment by conmute** [comment]
@ForbesLindesay Oh... now its documented in [Jade API](http://jade-lang.com/api/). Doctype option is there.

**Comment by cyberkatze** [comment]
@ForbesLindesay Thank you very much for help with doctype! :+1:

**Comment by Bamieh** [comment]
I faced this issue today, and solved it like this:

``` Jade

mixin image-object(imgPath, options)
    - var inv = function(boolean, result) {return boolean?result:boolean;};
    - options = options || {};
    - options.dataSrc = options.dataSrc || false;
    img( data-src=inv(dataSrc, imgPath), src=inv(!dataSrc, imgPath) )

+image-object('#test1', {'dataSrc': true})  //- result: img( data-src='#test1' )
+image-object('#test2')  //- result: img( src='#test2' )
```

**Comment by ghuroo** [comment]
thank you so much @tj :) that helped a lot

**Comment by notHaiLuu** [comment]
> You could also use `||`
> 
> ```js
> a(href=url, data-url=dataUrl || false)
> ```

@tschaub and @bevacqua save my life. It's worked perfectly

**Comment by Pradnyana28** [comment]
Maybe someone comes here are facing issue like me that want to use a condition in class attribute without breaking another class name and you can write it like this

`a(href=route.about_us, class=(router.path == route.about_us ? 'active' : 'inactive'), class='another class')`

And the output would be like this if the condition returns true

`<a href="/about-us" class="active another class">menu<a/>`

I hope it helps.

**Comment by ForbesLindesay** [comment]
You can even do it as a shorthand:

```pug
a.another.class(href=route.about_us, class=(router.path == route.about_us ? 'active' : 'inactive')
```
