### ISSUE TITLE
unclear how to escape within attribute values

### ISSUE THREAD

**Issue by gmarciani** [pugjs/pug#2400]
It is not clear to me how to escape characters within an attribute value.
For example, I would like to compile the following Jade

`div(ng-class="'my-class': condition1 && condition2") `

into the following HTML

`<div ng-class="'my-class': condition1 && condition2"></div>`

but I get

`<div ng-class="'my-class': condition1 &amp;&amp; condition 2"></div>`

Am I missing some language feature, or the language does not provide a direct unescaping yet?

**Comment by TimothyGu** [comment]
We do. See http://jade-lang.com/reference/attributes/#unescaped.

```jade
div(ng-class!="'my-class': condition1 && condition2")
```

gives the desired result.

**Comment by designermanjeet** [comment]
awesome man thanks
