### ISSUE TITLE
Wrong parse variable in element attributes 

### ISSUE THREAD

**Issue by seonetartem** [pugjs/pug#2403]
Release 2.0.0-alpha8
`- my_var = 'Jade'`

h3(class="#{my_var}") is a #{my_var}

=>

`<h3 class="#{my_var}">is a Jade</h3>`

**Comment by ForbesLindesay** [comment]
Attribute interpolation was removed.  Just do `h3(class=my_var) is a #{my_var}`

**Comment by seonetartem** [comment]
if i need concatinate like 
placeholder="{{ '#{path}password.placeholder' | translate }}"?

**Comment by TimothyGu** [comment]
@seonetartem, see #2305 for a list of alternatives.
