### ISSUE TITLE
Extends extending even when in if block

### ISSUE THREAD

**Issue by Cactucs** [pugjs/pug#2404]
When extends is placed in conditional (if), it's extending, even when condition evaluates to false.

``` jade
mixin content
    if bar
        extends ../layouts/default
        block content
            block
    else
        block

+content
        h1 Hello!
```

**Comment by ForbesLindesay** [comment]
It should give you a syntax error when it gets to `extends ../layouts/default` because `extends` is only valid at the top level.  Thank you for reporting this bug.

**Comment by kylekatarnls** [comment]
I see two ways to do that.

Right in the lexer: https://github.com/pugjs/pug/blob/e29d65da9d69fa602003e1e520103b4afb77e135/packages/pug-lexer/index.js#L573

By saying extends must start a line.

Or in the parser:
https://github.com/pugjs/pug/blob/e29d65da9d69fa602003e1e520103b4afb77e135/packages/pug-parser/index.js#L732

By saying the extends can not be in a block.

I would say the first is better as the error is raised earlier.

For any of the option I can propose a pull-request.

**Comment by ForbesLindesay** [comment]
I think the linker is probably the best place to put this.  I.e. We can disable whatever's causing it to still find that extends, and then also throw a syntax error there.  It doesn't really matter too much how early we catch it.

**Comment by kylekatarnls** [comment]
Locally I try this with a unit test and get as expected: `Declaration of template inheritance ("extends") should be the first thing in the file.`

But if the file is not found, the "no such file" error has the precedence. Ideally, the syntax error should come first rather the extended file exists or not.

**Comment by ForbesLindesay** [comment]
This should now be resolved, although the no such file error does still take precedence.  I think that is OK, as you could be using the standard loader with a custom linker, that might support extends being inside an if statement.
