### ISSUE TITLE
Un-deprecate jade until pug 2.0 stable is out.

### ISSUE THREAD

**Issue by paulmillr** [pugjs/pug#2405]
There is no reason to have jade 1.11 deprecated since 2.0 is unstable / unusable stuff right now. Can you un-deprecate it back?

**Comment by DeadCham7** [comment]
I agree. That is why I asked question about fixing vulnerabilities #2399 I appreciate communities hard work but it is just so sad that there 0 documentation whatsoever about migration jade to pug. I am newbie and this is so not newbie friendly..  I got no attention for my question too. :(

**Comment by TimothyGu** [comment]
@paulmillr, I agree as well, but it is not within my power to undeprecate the package (CC @ForbesLindesay).

@DeadCham7, I wrote [some documentation](https://github.com/pugjs/pug/blob/master/README.md#rename-from-jade) on the status of Pug vs Jade. Is there something missing you are looking for?

**Comment by ForbesLindesay** [comment]
The agreement I ultimately made requires deprecating jade, so my hands are tied here.  Jade won't be unpublished though.  I believe we are extremely close to a stable release of pug at this point.

**Comment by paulmillr** [comment]
This is pretty shitty considering you've [broken](https://github.com/pugjs/pug/issues/2305) some old syntax in 2.0.

Meh.

**Comment by shpros** [comment]
The better thing to do would have been to have released pug 2.0 as an exact port of jade 1.11 with the only changes being renames, without any additional syntax changes, bug fixes, or features. Then add the breaking syntax changes, bug fixes, and features in pug 3.0. (3.0 rather than 2.1 or 2.0.1 because Breaking. Feature. Fix. https://twitter.com/_ericelliott/status/667839964378451968 )

**Comment by frob** [comment]
@shpros It would have been better to just release pug as v1 as a direct port of jade v1 with only the command/project name changing. We could have even kept the same everything. Why can't we do this now. It seems like the name change has been a bunch of yak shaving.

**Comment by jeromew** [comment]
well history cannot be changed. The name change was imposed on the project by an external force after the jade 2.0 refactoring was well underway and deviated the project from its original timeline.

The trademark owner could certainly have handled this differently to increase its karma in the open source community but the name change + deprecation is something that cannot be changed now.

Like any big refactoring, the 2.0 conveys risks but will bring rewards with feature that were long standing requests on 1.0.

The jade 1.0 tests are used to ensure that 2.0 is not too far from 1.0 feature wise. Let's hope that there are not too many untested corner cases. The new improved errors will hopefully facilitate the migration of jade templates when something breaks.

@ForbesLindesay and @TimothyGu among others are doing a great job on this release and it is not a simple task considering the popularity of jade !

The only thing I can see to alleviate the renaming problem would be if someone do a simple "jade" => "pug" renaming of the last jade revision and if we publish it under "pug". I don't need it myself and I don't know if @ForbesLindesay would accept that if someone prepared such a fork + it would not solve the problem of external projects (like express) that need to do their own "jade" to "pug" renaming.

**Comment by ForbesLindesay** [comment]
I would be willing to publish a 1.x.x version of pug as @jeromew suggests if someone prepares such a fork.  They will need to find and replace `jade` with `pug` (for all cases) except for where we use a file extension, as that needs to remain `.jade`

**Comment by frob** [comment]
@ForbesLindesay Would this need to be in all the pug repos or only this one?

**Comment by markcollinscope** [comment]
@ForbesLindesay I really appreciate that you are all working hard to fix this. However developers with deadlines who have taken the 'risk' of using Jade/Pug are now being hit by this.

A simple piece of direction would help. Which version of jade/pug should we use to ensure we can still continue working whilst you guys do the valiant job of improving it?

Thanks a lot.

**Comment by ForbesLindesay** [comment]
You should install and use pug.  jade is deprecated.  Pug is already way better than jade has ever been.

**Comment by paulmillr** [comment]
Rrrright. Except that it breaks quite a few jade 1.0 syntaxes!

**Comment by jeromew** [comment]
jade 2.0 was meant to be a major version bump with backwards incompatibilities. These allow for long standing improvements.

pug = jade 2.0

If you really need a non deprecated jade 1.11.0, @ForbesLindesay agreed on my proposal a few posts above. Simply fork https://github.com/pugjs/pug/tree/v1.x.x , make the necessary changes mentioned in https://github.com/pugjs/pug/issues/2405#issuecomment-229907604 and this fork should be able to be published as maybe pug 1.11.0

but do not expect pug 2.0 to have a full language compatibily with pug 1.11.0.

We all hate incompatibilities. As @markcollinscope said, we all are developers with deadlines that fear the impacts of major version bumps. But we also need to sometimes take care of technical debt. The architecture of jade 1.x was starting to be a limiting factor for too many of the opened issues.

Once again, If someone who is blocked by the "deprecated" warning can take care of creating the fork that was mentioned, a iso-language pug could be published.

Regarding the title of issue, "undeprecate jade until pug 2.0 stable is out", this will not happen for legal reasons as @ForbesLindesay has already mentioned.

I am closing this issue.

If someone wishes to prepare a pug 1.11.0 version out of jade 1.11.0, please open a separete PR.
