### ISSUE TITLE
symbols in mixins

### ISSUE THREAD

**Issue by diginfo** [pugjs/pug#2417]
I am unable to print symbols using mixins, without mixins the symbols are printed correctly:

This works:

    label &mu;

This does not:

    mixin label(label)
      -if(label.text)
        -text=label.text; delete label.text
        -if(text=='') label.class='empty';
        label&attributes(label)=text
      -else
        -var attr={}; if(label=='') attr.class='empty';
        label&attributes(attr)=label

    +label('&mu;')

Any suggestions on how to solve this ?

**Comment by TimothyGu** [comment]
You need to make sure the text is not escaped again in the mixin.

```pug
mixin label(label)
  -if(label.text)
    -text=label.text; delete label.text
    -if(text=='') label.class='empty';
    label&attributes(label)!=text
  -else
    -var attr={}; if(label=='') attr.class='empty';
    label&attributes(attr)!=label


+label('&mu;')
```

**Comment by diginfo** [comment]
Thanks, that works if I call the label mixin directly, but not when I call it from another mixin:

	mixin label(label)
	  -if(label.text)
	    -text=label.text; delete label.text
	    -if(text=='') label.class='empty';
	    label&attributes(label)!=text
	  -else
	    -var attr={}; if(label=='') attr.class='empty';
	    label&attributes(attr)!=label
	
	formitem(label,input)
	  +label(label)
	  +input(input)
