### ISSUE TITLE
Complex object is displaying as [object Object] in template

### ISSUE THREAD

**Issue by Madhust** [pugjs/pug#2418]
Hi All,

I am trying to display a complex object in the template as follows. But it shows `[object Object]`.

`$(".someclass")[#{controls.name}](controls.props)`

My data looks like below.
`{`
` controls:{ name:"mButton", props:{ text:"MButton"} }`
`}`

How can i display it as string?

Regards,
Madhu

**Comment by ForbesLindesay** [comment]
You can use the [js-stringify](https://www.npmjs.com/package/js-stringify) module from npm.  Add that module to your locals (`pug.renderFile('filename', {stringify: require('js-stringify')})`).  Then you can use it like:

```js
$(".someclass")[!{stringify(controls.name)}](!{stringify(controls.props)})
```

`js-stringify` produces a string of JavaScript that evaluates to the value you pass to it.  In this way it's very similar to `JSON.stringify`.  Unlike `JSON.stringify` though, it's safe to use without further escaping (and handles newlines a little differently).  Note that you should only use `!{` in combination with a module like `js-stringify` that does escaping for you, for everything else you should stick to `#{`.
