### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by fanyer** [pugjs/pug#2419]
I want to ask if there are any methods to generate a compiled HTML like
`<label class="mdl-accordion__label">
  <i class="material-icons indicator">chevron_right</i>
  Getting started
</label>`

the content of tag outside should align after the content of tag inside .
How to achieve this by using the Jade Style.
Now I can only use reletive postive to simulate the i tag align in the front.

The core problem is that if both two Neighboring tags  have contents and they are Indent to each other ,how to change the alignment of the two contents

**Comment by jeromew** [comment]
jade/pug currently does not offer a way to precisely manage the html output (prettifying, indenting, aligning, ..).
This is considered out of scope for the project and if you need to prettify the html output, you should post-process the generated html (with htmltidy for example)

**Comment by fanyer** [comment]
all right! It feels unawesome...Thank you
