### ISSUE TITLE
Find solution for bemto

### ISSUE THREAD

**Issue by ForbesLindesay** [pugjs/pug#2423]
See discussion in https://github.com/pugjs/pug-lexer/commit/6bbb5150b0fed6028285873b9234173ac425ae5a#commitcomment-17850659

We need to find a good solution for the bemto mixins as they currently make use of setting non-standard class names as the attribute for a mixin (then re-writing them inside the mixin).

Suggested options:

1. We could relax validation on class names to allow the bemto style class names, even though they are not valid in normal html.
2. We could write a plugin to relax the validation on the class names so the current bemto mixins can continue to be used, with a plugin.
3. We could re-write the functionality of the bemto mixins as a full pug plugin, doing the class name re-writing at compile time.

Option 2 seems like a good interim solution to me, while option 3 seems best long term.  My suggestion would be to write the option 2 plugin and name it something like `pug-plugin-bemto-legacy` and write Option 3 and call it `pug-plugin-bemto`.

One big advantage of the full plugin is that we could provide a syntax that really _makes sense_ for bemto, rather than piggybacking on mixins and classes.  The other thing would be that it would result in an absolutely massive performance boost.

My suggestion would be to use the `&` character to denote  a bemto element. and the `^` character to denote a bemto block.  (Someone who actually uses bemto should bikeshed/vote on what characters they actually wan to use, but ideally avoid `#`, `!`, `=` etc. as these mean something special in pug).

### Blocks

```
^.foo bar
^span.foo bar
```

```html
<div class="foo">bar</div>
<span class="foo">bar</span>
```

### Elements

```
^.foo
  &.bar baz
^span.foo
  &span.bar baz
```

```html
<div class="foo">
  <div class="foo__bar">baz</div>
</div>
<span class="foo">
  <span class="foo__bar">baz</span>
</span>
```

### Modifiers

```
^.foo._bar._baz Blah
```

```html
<div class="foo foo_bar foo_baz">Blah</div>
```

Another option would be for the plugin could default all HTML elements to either "elements" or "blocks" by default (which ever one you have more of in a typical bem setup) and then would only need a character to indicate when something was the other one.

**Comment by ForbesLindesay** [comment]
CC @kizu

**Comment by kizu** [comment]
Re: option 3, is there a way, or is it planned (or was it thought of and dismissed) to use a certain pug plugin from the `.pug` file? I.e. without the need to use the JS API. As an example of similar thing, Stylus has a `use()` built-in function that allows developers to apply plugins right from the `.styl` files. This allows us to add any js functionality as a part of a Stylus lib making the lib usage as simple as just importing the needed lib/`.styl`-files.

If such thing would be possible, then the rewriting bemto as a native pug plugin would be perfect.

Regarding the character to denote the bemto block/element, I'll need to think more about it :)

**Comment by ForbesLindesay** [comment]
I don't think a method for adding a plugin from within a pug file has been discussed.  It's an interesting idea though.  I guess the concern would be how to detect it early enough.  If you wanted to be able to enable a plugin from within a file that gets included that's going to be too late for a lot of plugins because by the time we see that file we've already done all the lexing and parsing.

**Comment by ForbesLindesay** [comment]
I didn't realise that these class names actually do work if you escape them in css http://codepen.io/kizu/pen/WxxwdL

Maybe we should just relax the validation to allow class names that start with `--`.

**Comment by kizu** [comment]
Yeah, actually, you can use almost anything as a HTML classes, even emoji, and they could be used in CSS with proper escaping, see https://mathiasbynens.be/notes/css-escapes

**Comment by TimothyGu** [comment]
I don't see a need for strict parsing for `.--` either. It doesn't conflict with any Pug syntax, and doesn't cause any visible inconvenience that I can tell.

HTML [defines](https://html.spec.whatwg.org/multipage/indices.html#attributes-3:classes) `class` as a "set of space-separated tokens," which is in turn [defined](https://html.spec.whatwg.org/multipage/infrastructure.html#set-of-space-separated-tokens) as a "a string containing zero or more words (known as tokens) separated by one or more space characters, where words consist of any string of one or more characters, none of which are space characters." So, there are no limitations for weird Unicode characters in classes in HTML.

I'd vote for removing the check.

**Comment by jeromew** [comment]
Shouldn't we choose the escaped notation in pug ? 
The pug syntax is "selector-oriented" with the dot so I could be easier to tell pug users "write the class name the same way you would in a CSS selector" so `.--` would in fact be `.\--`

I don't measure fully the impact of accepting all valid class names here.

If we keep accepting only a "sane" subset, we need to document somewhere what we believe this reasonable class subset is.

**Comment by ForbesLindesay** [comment]
I agree that we need to document what we do accept.  I want to avoid accepting literally anything because it limits what we can automatically detect after a class name without making it a breaking change.

I would be OK with either making a special case for `--` as being specifically useful for bem, or accepting escapes in the same way as css does.

**Comment by kizu** [comment]
Allowing the escapes would be really awesome, as it would allow things like bemto to add more sugar in that place, even if escaped :D In my opinion both things could be done — allowing `--` and then, maybe later, as it can be a non-trivial issue, adding escapes. But even the `.\--` would be enough for bemto users I guess, as it would be really easy to migrate and won't be that much more code.

**Comment by nfantone** [comment]
Totally on board with @TimothyGu, here. You could even argue that **jade** _used to_ accept classes that **pug** doesn't, so this hurts migration. 

Today I tried to update a project that had classes such as these:

```html
#content
          .row(class='150%')
            .3u(class='12u(mobile)') #  <-- Class names must begin with "-", "_" or a letter.
              section.box
```

which worked just fine with latest **jade**, but didn't even run on **pug**.

**Comment by bigslycat** [comment]
I have not found a suitable solution for me, therefore, I developed the new. I decided that it's best to use a helper. Especially if #2371 will be implement. Please, review this project: https://github.com/bigslycat/pbem

**Comment by iliakan** [comment]
I saw this kind of report somewhere, related to CSS4 first making `--classes` invalid, and them allowing them.

As of now, bemto-style classes are *valid*.

**Comment by dyspop** [comment]
How about this? `.3u(class='12u(mobile)'` 

Trying to work around this in some frameworks with pug.

**Comment by ednilsonamaral** [comment]
And for this?

```
!= "<!--[if lt IE 9]>"
	script(src='assets/js/html5shiv.min.js')
	script(src='assets/js/respond.min.js')
!= "<![endif]-->"
```

I received the following error:

```
    15| 
    16| 		!="<!--[if lt IE 9]>"
  > 17| 			script(src='assets/js/html5shiv.min.js')
--------^
    18| 			script(src='assets/js/respond.min.js')
    19| 		!="<![endif]-->"
    20| 

Buffered code cannot have a block attached to it
```

**Comment by TimothyGu** [comment]
That is exactly how it sounds like. Simply remove the indentation in front of the `script`s and it should be fixed.

```pug
!= "<!--[if lt IE 9]>"
script(src='assets/js/html5shiv.min.js')
script(src='assets/js/respond.min.js')
!= "<![endif]-->"
```

**Comment by khalidhoffman** [comment]
Hi all, I recently wrote a plugin that may be helpful to some of you here. It implements functionality similar to bemto, but imo with much less fuss. I've posted the repo at https://github.com/khalidhoffman/pug-bemify. I would appreciate any feedback as well!
