### ISSUE TITLE
pug loading unlinked stylesheets

### ISSUE THREAD

**Issue by brunoamaral** [pugjs/pug#2427]
I've been going round in circles with this issue and it may be due to my lack of experience with nodejs and pug.

After installing both up to date versions of expressJS and Pug, the resulting html seems to be loading a scaffolding.less stylesheet that I have not referenced in my html.
The site is here: http://coffeeclock.brunoamaral.eu/

The stylesheets I am using are just these two:
`
    <link rel="stylesheet" href="http://coffeeclock.brunoamaral.eu/custom.css" type="text/css">
    <link rel="stylesheet" href="http://coffeeclock.brunoamaral.eu/stylesheets/bootstrap.min.css" type="text/css">
`

The files exist, checked and double checked. The page shows up with a white background because the scafolding.less file is overwriting it.

How can I go about making sure only my stylesheets are loaded ?

**Comment by SergioCrisostomo** [comment]
@brunoamaral can you share the pug generating that page?

**Comment by brunoamaral** [comment]
@SergioCrisostomo sure thing, the whole source is here: https://github.com/brunoamaral/coffeeclock

**Comment by TimothyGu** [comment]
That's not an issue for Pug, since the templating works as expected. But this _might_ work just looking at what you have: try putting custom.css after Bootstrap.
