### ISSUE TITLE
browser link broken

### ISSUE THREAD

**Issue by vontio** [pugjs/pug#2432]
link in the readme
`https://raw.githubusercontent.com/pugjs/pug/1.11.0/pug.js` 404

**Comment by ayroblu** [comment]
This could be https://raw.githubusercontent.com/pugjs/pug/1.11.0/jade.js
Though I'm not sure if there still is a standalone version in pug? That part of the readme would need to be updated

**Comment by TimothyGu** [comment]
This will be fixed in our upcoming new website. There will be a standalone version.
