### ISSUE TITLE
Logic block in tag block behaves differently for mixin

### ISSUE THREAD

**Issue by cpietrzykowski** [pugjs/pug#2438]
li #{key}:
      if typeof val === 'object'
        +mymixin(val)
      else
        #{val}

The mixin is properly output as inner html of the containing tag (in this case `<li>`), but the val is output as an element itself (`<myvalue></myvalue>`). Perhaps I am misunderstanding (being new to jade/pugs I am fully open to being corrected.)

I am using pug 2.0.0-beta3 at this time.

**Comment by TimothyGu** [comment]
Try

```pug
li #{key}:
  if typeof val === 'object'
    +mymixin(val)
  else
    = val
```

Specifically,

```diff
-    #{val}
+    = val
```

**Comment by cpietrzykowski** [comment]
Wow... I must've overlooked that form. I appreciate the response. Navigating jade/pugjs documentation has been fun.

**Comment by ForbesLindesay** [comment]
It equally would have worked if you went with:

```pug
li #{key}:
  if typeof val === 'object'
    +mymixin(val)
  else
    | #{val}
```

The `#{EXPRESSION}` form is for a dynamic tag name if it's at the start of a line, and does basic interpolation only when you've already marked something as plain text.

`= EXPRESSION` is your best bet in most cases though.
