### ISSUE TITLE
span inside paragraph?

### ISSUE THREAD

**Issue by mmmurf** [pugjs/pug#244]
Is it possible to use Jade to do the following:

```
<p>hello there <span>i am happy</span> to meet you</p>
```

What is the recommended approach to obtain that output?

**Comment by yannduran** [comment]
@ForbesLindesay That worked perfectly - thank you!

**Comment by AndrewSouthpaw** [comment]
So useful! Thanks!

**Comment by jmdmao** [comment]
@ForbesLindesay Many, many thanks!!!!

**Comment by BOBCATSON** [comment]
Great to find a solution to my problem, but can you explain _why_ that works?

**Comment by droooney** [comment]
@BOBCATSON, take a look [here](https://pugjs.org/language/interpolation.html#tag-interpolation)

**Comment by BOBCATSON** [comment]
@droooney Thanks, I should have checked the docs better!

**Comment by HolmanGaleanoC** [comment]
> ```
> p hello there #[span i am happy] to meet you
> ```

Thanks
