### ISSUE TITLE
Vague install instructions

### ISSUE THREAD

**Issue by grawlinson** [pugjs/pug#2441]
In README.md, there is an instance of pug-cli being used *before* the command line install instructions are shown. This is a bit frustrating if the end-user has not read the entire README.

Example:

```
To compile a template for use on the client using the command line, do:

$ pug --client --no-debug filename.pug
```
The above code block shows before the below code block.
```
Command Line

After installing the latest version of node, install with:

$ npm install pug-cli -g
and run with

$ pug --help
```

May be easier to move installation instructions of pug-cli to just below the initial installation header.

Example:

### Package
via npm:
`$ npm install pug`

### Command Line

After installing the latest version of node, install with:

`$ npm install pug-cli -g`
and run with
`$ pug --help`

**Comment by ForbesLindesay** [comment]
Thanks for the suggestion.  A pull request would be great.

**Comment by TimothyGu** [comment]
As #2442 is merged, this is fixed.
