### ISSUE TITLE
Jade 1.11.0 and dependency with uglify-js@2.2.5 

### ISSUE THREAD

**Issue by emanuelef** [pugjs/pug#2445]
Hi,
hope the is the right place where to ask.
I'm using jade in an old project, when I run a tool for checking security I get a couple of possible issues.
Both are relative to uglify-js@2.2.5 :
jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5   
[https://nodesecurity.io/advisories/48](https://nodesecurity.io/advisories/48)
[https://nodesecurity.io/advisories/39](https://nodesecurity.io/advisories/39)

I would like to switch to pug but I see it's still in alpha.
What options do I have to consider ?

Thanks in advance

**Comment by ForbesLindesay** [comment]
Pug is now in beta, and is the recommended version for all users.  The only significant item preventing the beta tag being removed is that I haven't had time to get the website and docs sorted for pug.

P.S. Those uglify-js bugs should never have been reported as security vulnerabilities.  It just spreads so much FUD.  Any bug **can** cause a security vulnerability.  Those bug are no more likely than any other to be a security vulnerability.
