### ISSUE TITLE
Whitespace breaks mixins

### ISSUE THREAD

**Issue by ceremcem** [pugjs/pug#2448]
Following mixin does not work: 

```
mixin test(aaa)
    != '<script>'
    block <- there is a whitespace here
    != '</script>'
```

However following mixin works: 

```
mixin test(aaa)
    != '<script>'
    block<- there is no whitespace after `block`
    != '</script>'
```
https://github.com/jamen/gulp-pug/issues/131

**Comment by TimothyGu** [comment]
Pug is a whitespace-sensitive language. I don't really see a purpose in allowing whitespace there, especially since it's not hard to debug this issue.
