### ISSUE TITLE
Pug - Jade

### ISSUE THREAD

**Issue by Metehan** [pugjs/pug#2456]
I was thinking name change just because of developer's choice. But i heard it's because of "Jade" is registered trademark. 

Actually "Jade" and "JadeJs" is not same from law's view. So you can still use JadeJS name without having any legal issue. (If JadeJs not registered). Don't let low-minded trademark trolls change your way. I suggest you get an advice from a lawyer.

**Comment by jfmmm** [comment]
It's the name of a freaking stone... if this can be trademarked I don't know why you think that Pug is safe from lawyers. Should have stood your ground with jade..

**Comment by jfmmm** [comment]
How long before those guys sue your ass..

https://pugonline.org/
