### ISSUE TITLE
No link to tutorial from jade-lang.com

### ISSUE THREAD

**Issue by lukeramsden** [pugjs/pug#2458]

**Comment by aimer1124** [comment]
`Language Reference` can help u.
[Language Reference](http://jade-lang.com/reference/)

**Comment by TimothyGu** [comment]
Are you referring to http://jade-lang.com/tutorial/? It's deprecated and its use isn't encouraged. All information can be found in "Language Reference."

**Comment by lukeramsden** [comment]
Maybe we could make it more clear and change it to Documentation?

**Comment by TimothyGu** [comment]
We are making a new website, and I expect there to be a tutorial in the future.
