### ISSUE TITLE
Using # for xml:id in xml mode

### ISSUE THREAD

**Issue by alexjbest** [pugjs/pug#2460]
Currently using the hash character in xml mode sets the `id` attribute of a tag. However I think the preferred way to set an id type attribute in xml is using the `xml:id` attribute (and this is used by many xml based documents). I think it could be more convenient for people writing xml documents if Pug set the `xml:id` attribute instead when a hash is used.

I tried working out how to do this myself so I could change my local version but I couldn't work it out, so even if nobody else thinks this is a good idea I'd be really happy if someone could point me in the right direction for patching this locally.

Thanks!

**Comment by TimothyGu** [comment]
If you are using the latest version of Pug, you don't need to modify locally. A plugin is much cleaner.

See an example at https://tonicdev.com/timothygu/5790238b7bc70812004f9286
