### ISSUE TITLE
limited error logging in production environment

### ISSUE THREAD

**Issue by shaurabhbharti** [pugjs/pug#2463]
Does jade print less of error trace log in production environment? 

When NODE_ENV is set to 'development', error trace prints filename and line number, along with some code snippet to show where exactly the error is, followed by lot more trace. 
When NODE_ENV is set to 'production', it does not print file name, line number or code snippet. It does print the following trace though.

It may be expected behavior. In that case, is there a way to enable full error stack reporting in production environment, as in development environment?

PS: i need to use NODE_ENV set to 'production'.

**Comment by ForbesLindesay** [comment]
Yes, this is intended behaviour because the code generated by pug in production is way more efficient.  You can force debug mode by passing the option `{compileDebug: true}`.  Otherwise it defaults to `process.env.NODE_ENV !== 'production'`
