### ISSUE TITLE
Attributes requires a "comma-separator" when using with Angular 2 syntax

### ISSUE THREAD

**Issue by madhusudhand** [pugjs/pug#2472]
Pug with Angular 2 syntax of function braces ( ) and square braces [ ]
pug fails with syntax error or it ignores the attribute when they are not separated by comma.

1. Attribute ignored
Pug:
`input(type="text" name="email" [(ngModel)]="email")`
html:
`<input type="text" name="email"/>`

2. Throws syntax error with the use of ( )
`button(type="submit" (click)="login()") Login`

  > 6|   button(type="submit" (click)="login()") Login
-----------------^
    7| 
Syntax Error: Assigning to rvalue

3. When they are comma separated, it works.
Pug:
`input(type="text", name="email", placeholder="email", [(ngModel)]="email")`
``button(type="submit", (click)="login()") Login``
html:
`<input type="text" name="email" placeholder="email" [(ngModel)]="email"/>`
`<button type="submit" (click)="login()">Login</button>`

**Comment by ForbesLindesay** [comment]
This is expected behaviour.  Without the comma it's possible that the attribute starting with `[` or `(` is part of the previous value, because our values are JavaScript expressions.

**Comment by crowmagnumb** [comment]
For me its only the linter that complains with the above error but it compiles just fine. I'm using Atom with linter-pug 2.0.12 and pug 2.0.4. And it only complains about `(` attributes, not `[` ones. Using the example above, I can have

```
input(type="text" name="email" placeholder="email" [(ngModel)]="email")
```
with no commas, but the second one

```
button(type="submit", (click)="login()") Login
```
I need the comma (or quote the whole thing "(click)"="login()") or else my linter fails. BUT again, it compiles fine so I can actually ignore the linter errors if I want.
