### ISSUE TITLE
How to use with Module CSS?

### ISSUE THREAD

**Issue by uinz** [pugjs/pug#2474]
hi, i want use 'module css' in the server side

![image](https://cloud.githubusercontent.com/assets/12208108/17397891/ba7ba9d0-5a6c-11e6-8bc6-2a8259478f67.png)

![image](https://cloud.githubusercontent.com/assets/12208108/17397910/d04deb38-5a6c-11e6-8e9c-af34d011446b.png)

![image](https://cloud.githubusercontent.com/assets/12208108/17397901/c7bcb008-5a6c-11e6-9051-afcd68ec2f76.png)

I got class map but i don't know how to map it to the pug tpl

should use a parse plugin to do this ?

btw, I can't find any doc about `plugin`, where can i find it?

thanks much!

**Comment by uinz** [comment]
i found a solution
but makes me sick

![image](https://cloud.githubusercontent.com/assets/12208108/17400893/0f7d6b52-5a7d-11e6-8c18-32453a69bf19.png)

is there some better way to fix it ?

**Comment by ForbesLindesay** [comment]
Plugins aren't documented yet.  You can use a `preParse` plugin to transform the stream of tokens.  As a rough draft, it should look something like:

```js
const pug = require('pug');
const pugError = require('pug-error');

function cssModules(mapping) {
  return {
    preParse(tokens, options) {
      return tokens.map(tok => {
        if (tok.type === 'class') {
          if (!mapping[tok.val]) {
            throw makeError(
              'INVALID_CLAA_NAME',
              'Class name "' + tok.val + '" not found in css modules mapping',
              {line: tok.line, column: tok.col, filename: options.filename, src: options.src},
            );
          }
          return {type: 'class', line: tok.line, col: tok.col, val: mapping[tok.val]};
        }
        return tok;
      });
    },
  };
}

pug.renderFile('my-file.pug', {plugins: [cssModules(mapping)]});
```

N.B. I haven't tested the above code.

**Comment by LordXaoca** [comment]
Hi, maybe someone can provide tutorial or code example with full flow, how to generate classes map, how to use them into template and how to build prod ready html?

**Comment by niksajanjic** [comment]
Although this solution covers simple examples, it will not work for examples where a class is assigned through JS. For instance:

```js
div(class=[someVariable, { invalid: isInvalid() }])
```

It's not easy to implement logic for every possible example, so it makes sense to take care of this in your code, which means providing mapping inside your pug locals:

```js
div(class=[mapping[someVariable], { mapping[invalid]: isInvalid() }])
```

Or you have to make these classes global and thus immutable.

If there was a lifecycle method where you would have these JS expressions evalutaed into classes, upper code would work. Unfortunatelly, before code generation we still don't have these JS expressions evalutaed and after code generation we have a template function (and parsing that makes very little sense). Even if there was such a lifecycle method, our class could still depend on pug locals variable which means we wouldn know it's class until template execution. It's still usefull in basic examples where classes are assigned as strings.
