### ISSUE TITLE
HELP! Cannot get the right interpretation

### ISSUE THREAD

**Issue by biosunsci** [pugjs/pug#2475]
I am gonna use the new jade, pug, as my view engine, but I went into a problem. I edited a file test.bug for test.
```
//test.pug 
-
	list = ["Mon", "Tue", "Wed",
		"Thu", "Fri", "Sat","Sun"]
each item in list
	li= item
```
just as shown like [jade site demo](http://jade-lang.com/reference/code/) block unbuffered code
but when I run the bash command to get a html version by using command like
`pug test.pug > test.html`

I got the html file in a wrong interpretation likes
test.html
```
<  rendered test.html
i><li>Wed</li><li>Thu</li><li>Fri</li><li>Sat</li><li>Sun</li>
```
My pug version is like this:
![bash](https://cloud.githubusercontent.com/assets/15091103/17425358/edf1bfce-5afe-11e6-80b6-c3a2b59ccdc1.jpg)

There is dev messages in the output, and the expected html code is part missing.
I wonder why i can't get the right results. Did I do something wrong  OR whether there is a bug within the version I used?

**Comment by TimothyGu** [comment]
Simply `pug test.pug` (without the `> test.html` part) would do.
