### ISSUE TITLE
Jade to Pug Migration process

### ISSUE THREAD

**Issue by sapnajindal** [pugjs/pug#2476]
@ForbesLindesay 
My application is currently using jade 1.11.0. I am Planning to migrate from jade to pug. But i see pug 2.0.0 is still in beta. Is there any pug@1.11.0? Or the pug migration will directly be to 2.0.0
When are we planning to have stable pug release?

When is jade getting decommissioned? 
To which version of pug should i migrate from jade 1.11.0?

**Comment by SergioCrisostomo** [comment]
@sapnajindal there are some threads about that:

`https://github.com/pugjs/pug/issues/2453`
`https://github.com/pugjs/pug/issues/2405`

go for  https://github.com/pugjs/pug/releases/tag/2.0.0-beta4, which is the latest as of today

**Comment by TimothyGu** [comment]
We didn't republish jade@1.11.0 as pug@1.11.0, but we will accept a pull request that allows for it. For current usage, pug@2.0.0-beta4 is the latest (and code-wise we are very close to a stable release) so you should use that.
