### ISSUE TITLE
Tag interpolation changes whitespace

### ISSUE THREAD

**Issue by dplepage** [pugjs/pug#2477]
When there's no tag interpolation in a line the end of the line is preserved:
```jade
div
  | blah blah
  | blah
```
```html
<div>
  blah blah
  blah
</div>
```
Which looks like:

> <div>
>   blah blah
>   blah
> </div>
> 

But as soon as you add tag interpolation that line break vanishes:
```jade
div
  | blah #[i] blah
  | blah
```
```html
<div>blah <i></i> blahblah</div>
```
> <div>blah <i></i> blahblah</div>

This makes tag interpolation extremely frustrating to use.

**Comment by TimothyGu** [comment]
This has been [fixed](https://tonicdev.com/timothygu/57a4dc9a44140414004146ef) in Pug 2.0.0-beta4.
