### ISSUE TITLE
Pug/Jade 'case' statement doesnt allow for a ':' within the string

### ISSUE THREAD

**Issue by hawkerboy7** [pugjs/pug#2478]
Hi I noticed the following while creating a case block:

```jade
case testcases
  when "works"
    p This string works
  when "works-1"
    p This string works
  when "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%*()-_=+`~[]{};'\\|<>,./?/*-+"
    p So I tried some characters and this string works as well
  when "doesntwork:"
    p Error: unexpected text "
  when "doesntwork:1"
    p Error: expected "indent", but got "filter"
```
Also the one-lines break
```jade
case testcases
			when "works": p This string works
			when "works-1": p This string works
			when "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%*()-_=+`~[]{};'\\|<>,./?/*-+": p So I tried some characters and this string works as well
			when "doesntwork:": p Unterminated string constant
			when "doesntwork:1": p Error: expected "indent", but got "filter"
```

To me this was unexpected behavior. I should be able to use any string in the `when` but adding a `:` causes a fail. How can I solve this or is it (as I expect) a problem with Pug/Jade.
I am using Jade `1.11.0` but these errors also appear on the website.

**Comment by hawkerboy7** [comment]
Is it related to [":" is not valid as the start or end of an un-quoted attribute.][0]?

[0]: https://github.com/pugjs/pug/issues/2454

**Comment by TimothyGu** [comment]
> Is it related to ":" is not valid as the start or end of an un-quoted attribute.?

No. I can reproduce it in Pug as well.

**Comment by TimothyGu** [comment]
Fixed in pug-lexer@2.0.3. A `npm --depth 99 update pug-lexer` should be able to update that package to the latest version, since I haven't released a new Pug version yet.

**Comment by TimothyGu** [comment]
Hmm seems like there's some npm bug. If the above command doesn't work for you, try `npm uninstall pug-lexer && npm i`. If it does, disregard this message.

**Comment by TimothyGu** [comment]
I've whipped up a new demo: http://pug.timothygu.me/en/language/case.html. It uses the latest version of Pug so you can test your code and see if it's fixed or not.

**Comment by hawkerboy7** [comment]
Nice work man! Seems to be fixed =D
