### ISSUE TITLE
Passing variables through to include-files

### ISSUE THREAD

**Issue by timomue** [pugjs/pug#2480]
**index.pug**

```
extends _layout/base

block content
  include content/news
  include content/gigs
  include content/photos
  include content/videos
  include content/releases
  include content/contact

```
how can I pass variables through to each file of the included files?

I am sending the data that should be passed through via Express.js ...

**app.coffee**

```
app.get '/', (req, res) ->
  res.render 'index', {
    data: data
  }
```

thanks!

**Comment by ForbesLindesay** [comment]
It should already be implicitly available as `data` within your included files.  included files share the same scope as the file they are included into.
