### ISSUE TITLE
Unable to use dynamic classes in Pug template

### ISSUE THREAD

**Issue by Redrield** [pugjs/pug#2481]
I have a site that has an animation that plays over a period of 3 seconds, and I want to only have that play every 20 minutes for each individual user. So I'm handling that with cookies server-side, but when I try to pass a different class to the attribute that needs to be changed (In the event that the cookie exists), the class never gets changed.
To reproduce, make a file similar to the following; http://hastebin.com/nusidanidi.m

And have this on the backend: http://hastebin.com/gokakozala.coffee
And when the page is rendered, just check the source code, to find the class of the body. And see if it changes with the boolean

**Comment by TimothyGu** [comment]
Remove the variable declaraion That will mess up the locals system.
