### ISSUE TITLE
模板从 jade 切换至pug 后 app.locals 无法正常工作

### ISSUE THREAD

**Issue by blue68** [pugjs/pug#2482]
为了跟上pugjs的发展节奏，今天从jade 切换至 pug后， 发现 注入至 app.locals （基于express 4.0）的全局变量，在pug模板， link & script 标签中 直接引用 #{xx.xx} 无法正常显示。

<img width="354" alt="2016-08-10 11 39 42" src="https://cloud.githubusercontent.com/assets/2271067/17541158/391d5b68-5eef-11e6-9ec5-691cca52761e.png">

<img width="512" alt="2016-08-10 11 38 17" src="https://cloud.githubusercontent.com/assets/2271067/17541124/054ac708-5eef-11e6-98eb-f143e81efb59.png">

**Comment by TimothyGu** [comment]
Pug和Jade不互相兼容。#2305 “Removed/Changed syntax”部分有一些升级的建议。

另外，最好用英文提问 :smile: 

---

Pug and Jade are not fully compatible. Please check #2305 for some advice on upgrading.

Also, if possible please file issues in English :smile:

**Comment by blue68** [comment]
@TimothyGu ,  thanks for your reply
