### ISSUE TITLE
pug: command not found

### ISSUE THREAD

**Issue by cybibo** [pugjs/pug#2484]
npm install jade 
but jade:command not found
so install to:
ryan-mac:~ ryan$ npm install pug
pug@2.0.0-beta5 node_modules/pug
├── pug-runtime@2.0.2
├── pug-strip-comments@1.0.1 (pug-error@1.3.1)
├── pug-load@2.0.0 (pug-walk@0.0.3)
├── pug-linker@1.0.0 (pug-error@1.3.1, pug-walk@0.0.3)
├── pug-parser@2.0.1 (pug-error@1.3.1, token-stream@0.0.1)
├── pug-code-gen@1.0.1 (pug-error@1.3.1, js-stringify@1.0.2, pug-attrs@2.0.1, void-elements@2.0.1, doctypes@1.1.0, with@5.1.1, constantinople@3.1.0)
├── pug-lexer@2.0.3 (pug-error@1.3.1, character-parser@2.2.0, is-expression@2.1.0)
└── pug-filters@1.2.3 (pug-error@1.3.1, pug-walk@0.0.3, resolve@1.1.7, clean-css@3.4.19, constantinople@3.1.0, jstransformer@1.0.0, uglify-js@2.7.0)
ryan-mac:~ ryan$ npm install pug-cli -g
/Users/ryan/.node/bin/pug -> /Users/ryan/.node/lib/node_modules/pug-cli/index.js
pug-cli@1.0.0-alpha6 /Users/ryan/.node/lib/node_modules/pug-cli
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
└── pug@2.0.0-beta5 (pug-runtime@2.0.2, pug-strip-comments@1.0.1, pug-load@2.0.0, pug-linker@1.0.0, pug-parser@2.0.1, pug-code-gen@1.0.1, pug-lexer@2.0.3, pug-filters@1.2.3)
ryan-mac:~ ryan$ pug --help
-bash: pug: command not found
why???

**Comment by TimothyGu** [comment]
That's probably because your `$PATH` is set wrongly. Make sure it contains `/Users/ryan/.node/bin`. Either way, it's more of a setup issue than a Pug bug.
