### ISSUE TITLE
Variable doesn't work in attributes

### ISSUE THREAD

**Issue by iburning** [pugjs/pug#2485]
```
- var blog = { id: 1, title: 'test' }
p
  a(href="/blog/#{blog.id}") #{blog.id} #{blog.title}
p
  a(href="/blog/=blog.id") #{blog.id} #{blog.title}
p
  a(href="/blog/" + blog.id) #{blog.id} #{blog.title}
```

```
<p><a href="/blog/#{blog.id}">1 test</a></p>
<p><a href="/blog/=blog.id">1 test</a></p>
<p><a href="/blog/1">1 test</a></p>
```

I test it with beta4 and beta5

**Comment by TimothyGu** [comment]
Check the attributes documentation. The attribute is a JavaScript expression. `#{}` interpolation syntax used to work in Jade, but it was never documented, nor should it work. See #2305 for a list of breaking changes between jade@1.11.0 and pug.

**Comment by iburning** [comment]
OK, i got it. Thanks.
