### ISSUE TITLE
Self closing tag attributes

### ISSUE THREAD

**Issue by kyleholzinger** [pugjs/pug#2489]
In general, pug is pretty good about detecting attributes vs the content of a tag, however it seems like it's a little too strict when it comes to self closing tags. For example, the following will fail saying that `img` is a self closing tag and should not have any contents, when it's "contents" is just its attributes:
```jade
img.avatar ng-if='::someImg' src='{{someImg}}'
```

I have the fix of putting parens around the attributes, since this will force these to be treated as attrs, however it would be a serious problem for me since I am considering switching a rather large codebase to pug from slim, which is fine with this syntax. I realize pug isn't slim, however it seems as if this line should also work fine in pug.

**Comment by TimothyGu** [comment]
I don't really see how _any_ tags would work without parentheses. Parentheses are an essential part, not just for `<img>` but for `<p>`, `<div>`, etc. as well.

**Comment by kyleholzinger** [comment]
Whoops, I think I misunderstood a code snippet I was looking at previously thanks for explaning. Is there any effort to make parens optional? Using regexes you could assume text following the element definition is an attribute if it's in the form `attr-name='something'` using a regexp like `/[\w\-:]+\=\"[\1\-:]+\"/` (of course this regexp is very rough, would need a more complicated one in the future)

**Comment by TimothyGu** [comment]
No, at least there isn't any plans like that in my knowledge. We don't use regexes like that to scan for attributes because of reliability issues, and honestly sometimes I'd rather read imperative code than a long regex :)
