### ISSUE TITLE
Type definitions for typescript

### ISSUE THREAD

**Issue by ubenzer** [pugjs/pug#2490]
Hello,

I am using `jade` in typescript. In `typings` there is a type definition for `jade`:

```sh
typings search jade
Viewing 2 of 2

NAME      SOURCE HOMEPAGE                            DESCRIPTION VERSIONS UPDATED                 
gulp-jade dt     https://github.com/phated/gulp-jade             1        2016-03-16T17:18:10.000Z
jade      dt     https://github.com/jadejs/jade                  1        2016-03-16T15:55:26.000Z
ub@UB-MAC:~/Playground/fil/fil (master)$ 
```

But none for `pug`:
```sh
typings search pug
No results found for search
```

I would be awesome to have them also for `pug`.

**Comment by TimothyGu** [comment]
The "dt" source means that the type definition is from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jade/jade.d.ts).

**Comment by ubenzer** [comment]
Hi @TimothyGu I know that. But a type definition doesn't necessarily have to be hosted in `dt` repo. Some projects maintain typings in separate repository and/or inside of the repository.

May I assume that, there is no plans of releasing a type definition that is maintained by pug team?

**Comment by TimothyGu** [comment]
I wouldn't be extremely opposed to such an idea. Does the typedef have to be in the same repo as Pug proper, or can it be in a separate repo?

**Comment by ubenzer** [comment]
A d.ts file can be included inside of the repo, or distributed separately.

In [this](https://github.com/inversify/inversify-dts) example, it is separate from the project. It contains multiple definitions for some projects. Also a [typings](https://github.com/typings/typings/blob/master/docs/faq.md#should-i-use-the-typings-field-in-packagejson) section can be used in `package.json`. I am not an expert about how to publish a type definition to be honest. :)

**Comment by TimothyGu** [comment]
Alright. If you are willing to whip up a repo with type definitions in them, I'll be happy to transfer it under the umbrella of @pugjs.

**Comment by Extarys** [comment]
Any updates on this?

I would love to use includes and extends from Pug (I used twig for PHP but the JS version isn't enough for me)
