### ISSUE TITLE
Request for Information on Status (not really an issue...)

### ISSUE THREAD

**Issue by markcollinscope** [pugjs/pug#2492]
Hi @TimothyGu & @ForbesLindesay ,

Hope you're good. I just wondered what the status of Pug is compared to the last version of Jade - and if now is a good time to upgrade? I have to look at my UI stuff in the next couple of weeks, so now would be good if it is appropriate.

Many thanks for the great work.

Regards,
Mark.

**Comment by ForbesLindesay** [comment]
We currently recommend upgrading to the latest version of pug, currently 2.0.0-beta5.  We expect to release pug 2.0.0 within the next month ago, but the beta version of pug should already be more reliable/stable/performant than jade.
