### ISSUE TITLE
What are the notable benefits going jade->pug?

### ISSUE THREAD

**Issue by DeadCham7** [pugjs/pug#2493]
I don't know if it's just me cannot find the change log but closest thing I was able to find was history.md.

I know you guys are trying hard to find time for documentations but I believe pug team can benefit more from free testings if you guys list some benefits earned from migrating to new pug.

Thanks for your hard work! Please keep it up!

**Comment by antpaw** [comment]
here are the breaking changes https://github.com/pugjs/pug/issues/2305 and here is why https://github.com/pugjs/pug/issues/2184 the biggest benefit might be long term support and updates in the future. I don't think there are big new features in pug2.0.0, but i might be wrong.

**Comment by TimothyGu** [comment]
There have been a lot of internal changes done, most notably splitting the package into multiple components (which allow for plugins). Performance has also been improved drastically.
