### ISSUE TITLE
Class attribute rendered in different order

### ISSUE THREAD

**Issue by antpaw** [pugjs/pug#2494]
```pug
a.h_action(href="#") //- <a href="#" class="h_action"> in jade
a.h_action(href="#") //- <a class="h_action" href="#"> in pug
```

**Comment by TimothyGu** [comment]
This was intentional. Someone thought putting class in the front would allow Gzip to compress better (#1793). Do you have specific use case that is affected by this change?

**Comment by antpaw** [comment]
Some of my tests failed, because they expected innerHTML, that was all
