### ISSUE TITLE
compile template with mixin throws error

### ISSUE THREAD

**Issue by alexey2baranov** [pugjs/pug#2501]
Hello! I have a mixin and a template with uses this mixin. When I use it on server side by pug.renderFile() everythig is OK. But when i compile them error throwns 

**Mixin.pug:**
```
mixin Mixin
    div this is mixin
```

**Template.pug:**
```
include ./Mixin.pug

div this is template
    +Mixin
```

`execute from source file:`
```
var  output= pug.renderFile(__dirname+"/../public/poligon-pug/tmpl/Template.pug");
console.log(output);
```
**very success output:**
\<div>this is template\<div>this is mixin\</div>\</div>

as I say server side works very fine. Now I'm trying to get client side version of the same templates

**compile:**
> pug --client --no-debug --out public/poligon-pug/js public/poligon-pug/tmpl

**execute from precompiled js:**
`var output = require("../public/poligon-pug/js/Template")();`

**output:**

> var output = require("../public/poligon-pug/js/Template")();
>                                                          ^
> 
> TypeError: require(...) is not a function

**compiled Template.js:**
```
function template(locals) {
    var pug_html = "", pug_mixins = {}, pug_interp;
    pug_mixins["Mixin"] = pug_interp = function () {
        var block = (this && this.block), attributes = (this && this.attributes) || {};
        pug_html = pug_html + "\u003Cdiv\u003Ethis is mixin\u003C\u002Fdiv\u003E";
    };
    pug_html = pug_html + "\u003Cdiv\u003Ethis is template";
    pug_mixins["Mixin"]();
    pug_html = pug_html + "\u003C\u002Fdiv\u003E";
    ;
    return pug_html;
}
```

**Comment by alexey2baranov** [comment]
as i can see from compiled template it is not exported anything. So how can I ask pug to add **module.exports=** ?

**compiled Template.js:**
```
function template(locals) {
    var pug_html = "", pug_mixins = {}, pug_interp;
    pug_mixins["Mixin"] = pug_interp = function () {
        var block = (this && this.block), attributes = (this && this.attributes) || {};
        pug_html = pug_html + "\u003Cdiv\u003Ethis is mixin\u003C\u002Fdiv\u003E";
    };
    pug_html = pug_html + "\u003Cdiv\u003Ethis is template";
    pug_mixins["Mixin"]();
    pug_html = pug_html + "\u003C\u002Fdiv\u003E";
    ;
    return pug_html;
}
```

**Comment by TimothyGu** [comment]
How is `require` mapped to Pug's `compileClient`?

**Comment by alexey2baranov** [comment]
@TimothyGu What is my mistake? How should i compile Pug`s templates into JavaScript to require them later?

When work with Handlebars you can use this command to this task:
> handlebars ./public/poligon-handlebars/tmpl **-c handlebars** -f ./src/templates.js

from Handlebars --help:
> -c, --commonjs       Exports CommonJS style, path to Handlebars module

**Comment by TimothyGu** [comment]
If I understand your use case correctly, appending `;module.exports = template;` to the code returned by `compileClient` should do the trick.

**Comment by alexey2baranov** [comment]
Yes exactly. Can I do this trick with pug-cli?

**Comment by ForbesLindesay** [comment]
there was a discussion a while back around doing something like a `--commonjs` flag, which I think would be a good idea.

**Comment by alexey2baranov** [comment]
@ForbesLindesay I agree. What should i do with this issue? should i close it or leave as is?

**Comment by ForbesLindesay** [comment]
Close it and submit an issue/pull request to https://github.com/pugjs/pug-cli assuming there isn't one already.
