### ISSUE TITLE
Interpolation in attributes doesn't work.

### ISSUE THREAD

**Issue by lschuermann** [pugjs/pug#2502]
Upgrading from jade 1.11.0 to the current pug beta, my webapp broke because I'm using interpolation in attributes like this:

    script(type='text/javascript', src='/foobar/#{scriptpath}')

In the resulting HTML, the script-src attribute will be `"/foobar/#{scriptpath}"` and not `"/foobar/myawesomescript.js"` as in previous versions of jade / pug.
I don't know if this is considered good practice, but I found it quite useful and therefore used it all over my webapp. Is this considered a bug or "broken on purpose"?

**Comment by ForbesLindesay** [comment]
Read through some of the closed issues on attributes.
