### ISSUE TITLE
Idea: a shortened syntax for elements which have only one child

### ISSUE THREAD

**Issue by lazytyper** [pugjs/pug#2505]
This code

``` pug
span.parent
  span.child
    span.grandchild (some text)
span.next
```

could be shortened to

```
span.parent>span.child>span.grandchild (some text)
span.next
```

or, if spaces are supported:

```
span.parent > span.child > span.grandchild (some text)
span.next
```

This shortened syntax makes only sense for elements which have only one child.
If an element has more children, you can't use the '>'-operator:

``` pug
span.parent
  span.child
    span.grandchild (some text)
    span.grandchild (some text)
span.next
```

```
span.parent>span.child
  span.grandchild (some text)
  span.grandchild (some text)
span.next
```

This shortened syntax can reduce some lines and indents if many of those "elements-with-only-one-child" exist.

**Comment by TimothyGu** [comment]
We already support a syntax that satisfies this: https://pugjs.org/language/tags.html#block-expansion

```pug
span.parent: span.child: span.grandchild (some text)
span.next
```
