### ISSUE TITLE
Can't "include" files from paths from variables

### ISSUE THREAD

**Issue by HA3IK** [pugjs/pug#2507]
This thing can include files from paths from variables?

For Example:

**`//- "varFromGulp" is an interactive local variable with path from Gulp`**
`include #{varFromGulp}`

**`//- Log:`**
`Error: ENOENT: no such file or directory, open '[path]\dev\web\pug\#{devDir}.pug' ...`

**Comment by TimothyGu** [comment]
No, you can't do that unfortunately, since includes are static (and therefore don't get access to runtime variables).

I've written a plugin that will allow one to do this, but until then, this isn't and won't be supported in the core.
