### ISSUE TITLE
Feature request: Optional parentheses on self closing/expanded elements

### ISSUE THREAD

**Issue by B7th** [pugjs/pug#2508]
I would find it neat and terse if we could simply write `meta charset="ut8"` instead of `meta(charset="utf8")`, and similarly `form method="POST"` instead of `form(method="POST")`.

Do you think it is something you might add in the future?

**Comment by TimothyGu** [comment]
What should I write, then, if I want `method="POST"` to be part of the body of `form`

**Comment by B7th** [comment]
Sure! If people want to have attribute like content as part of the body of an expanded element, they can have it as the first child with |.

    div bar="baz" buz
      p car="caz" cuz
   div
     | dar="daz" duz
    p

Would yield

    <div bar="baz" buz><p>car="caz" cuz</p></div>
    <div>dar="daz" duz<p></p></div>

**Comment by ForbesLindesay** [comment]
I appreciate the thought here, but I'm confident that making the parenthesis optional in some, but not all, locations will just make pug more confusing.  The inconsistency will be hard for people who don't have a deep understanding of HTML, and the readability is not improved by omitting the parenthesis.
