### ISSUE TITLE
Support interpolation with $ for text to mimic attribute interpolation

### ISSUE THREAD

**Issue by Rush** [pugjs/pug#2518]
The mental overhead of different interpolation methods is starting to be significant:
* `$` for attribute interpolation
* `#` for text interpolation
* `{{ }}`` for Angular.JS interpolation and/or other frameworks

Could Pug support `$` for text interpolation as well? Maybe enabled optionally.

**Comment by Rush** [comment]
Ok so basically all instances of `#` here would need to also support `$`, is that right? -> https://github.com/pugjs/pug-lexer/blob/master/index.js

**Comment by TimothyGu** [comment]
This design is to a degree deliberate. In Pug, there are two sorts of text interpolation: `#{}` which escapes the text, and `!{}` which doesn't. In contrast, in JavaScript there isn't such a distinction, and using either syntax would be, in a sense, "wrong". We want our users to always be aware of implications of the code being written, and making the syntax the same doesn't help. In fact, preventing confusion was one of the reasons why we removed support for `#{}` in attributes.

**Comment by Rush** [comment]
Thanks for the reply. I understand your view even though my opinion is different. I'd rather use `${}` for 99% of the time and `!{}` as the rare exception.

**Comment by ForbesLindesay** [comment]
The problem with that approach is that `${}` in attributes is **unescaped**.  This is often fine, because attributes are escaped by default, but it's enough to justify not re-using syntax that is always escaped (i.e. `#{}`).
