### ISSUE TITLE
Is pug stable enough to use now?

### ISSUE THREAD

**Issue by Jianru-Lin** [pugjs/pug#2526]
Pug is good. But latest release is beta version. Some framework like express depends on jade not pug cause they thought pug is not stable yet. Is it true?

Thanks.

**Comment by BlueChili** [comment]
http://expressjs.com/en/guide/using-template-engines.html

**Comment by thevinci** [comment]
If you want to use precompiled pug in browser, there are still issues.

**Comment by TimothyGu** [comment]
Pug is stable enough to be used.
