### ISSUE TITLE
npm missing some releases of pug?

### ISSUE THREAD

**Issue by chisleu** [pugjs/pug#2527]
`npm show pug` does not list all versions of pug shown. It shows 0.0.0, 0.1.0, and then jumps to 2.0.

Version 1.11.0 is shown as a release on github, but npm does not show it.

This keeps us from simply s/jade/pug/ in our source and file names. The latest pug 2.x breaks our testing because the order of certain tag attributes are reordered between jade 1.11.0 -> pug 2.0.

Do I need to bite the 2.0 beta bullet or should I stick with jade 1.11.0 until pug 1.11.0 is available in npm?

**Comment by ForbesLindesay** [comment]
upgrade to 2.0
