### ISSUE TITLE
Pug function problem!

### ISSUE THREAD

**Issue by jabaz** [pugjs/pug#2530]
Why errors caused by undefined functions does not have a e.code starting with PUG?
When function is undefined in pug, e.code is undefined when catching error, it should start with PUG:.

More details in [here](https://github.com/yan-foto/electron-pug/issues/6)

**Comment by TimothyGu** [comment]
Error codes starting with `PUG` are only used on errors **emitted by Pug** during compilation. In fact, the errors caught in the template itself are not passed through pug-error.
