### ISSUE TITLE
Missing ; at the end of inline CSS style

### ISSUE THREAD

**Issue by meeyuuu** [pugjs/pug#2537]
I'm having a problem creating newsletters using Pug. When the .pug files are compiled to HTML, there's always a missing ";" at the end of each inline CSS. This causes the design to break, especially on HTML newsletters for Microsoft Outlook, because of the syntax error.

Sample:

index.pug
`h1(style="color: red;") Hey!`

Result:

index.html
`<h1 style="color: red">Hey!</h1>`

**Comment by ForbesLindesay** [comment]
This feels like a bug to me.  I think it was done as  a small performance optimisation, but if it breaks rendering in Outlook it's definitely not worth it.  You could fix it with a pull request to https://github.com/pugjs/pug-runtime/blob/master/index.js#L100-L117
