### ISSUE TITLE
Nested while loops do not work as expected

### ISSUE THREAD

**Issue by Dan503** [pugjs/pug#2541]
I have this simple nested while loop pug markup
```````````
- var a = 0;
- var b = 0;
while a < 3
	- console.log('a-outer:',a,'\n');
	while b < 3
		- console.log('a-inner:',a);
		- console.log('b:',b, '\n');
		- b++;
	- a++;
``````````
It produces this output in the console:
````````
a-outer: 0

a-inner: 0
b: 0

a-inner: 0
b: 1

a-inner: 0
b: 2

a-outer: 1

a-outer: 2

a-outer: 0

a-inner: 0
b: 0

a-inner: 0
b: 1

a-inner: 0
b: 2

a-outer: 1

a-outer: 2

a-outer: 0

a-inner: 0
b: 0

a-inner: 0
b: 1

a-inner: 0
b: 2

a-outer: 1

a-outer: 2
````````
It appears that the outer loop doesn't wait for the inner loop to finish before moving on to it's next round, then redoes all it's outer loops for each nested loop again or something. It's weird.

This is the output I would expect that code to produce:
````````````
a-outer: 0

a-inner: 0
b: 0

a-inner: 0
b: 1

a-inner: 0
b: 2

a-outer: 1

a-inner: 1
b: 0

a-inner: 1
b: 1

a-inner: 1
b: 2

a-outer: 2

a-inner: 2
b: 0

a-inner: 2
b: 1

a-inner: 2
b: 2

```````````

**Comment by ForbesLindesay** [comment]
You're not resetting the value of `b` inside the outer loop.  This means that at the end of the first iteration of the outer loop, `b` already has a value of `3` and so it is never triggered again.

The reason it's happening multiple times is not included in this snippet.  I suspect you are rendering your pug template more than once, or this code is in another outer loop.

To fix your example, you could just do:

```pug
- var a = 0;
while a < 3
    - var b = 0;
    - console.log('a-outer:',a,'\n');
    while b < 3
        - console.log('a-inner:',a);
        - console.log('b:',b, '\n');
        - b++;
    - a++;
```

**Comment by Dan503** [comment]
Oh right, I can't believe I missed that. It's so obvious! >_<

The function was getting called multiple times due to it being called once for each page in my site. That's what was throwing me off when looking at the output since it looked like `b` was still being reset but it was actually just the whole function getting called again.
