### ISSUE TITLE
Making a list in Pug from Object.

### ISSUE THREAD

**Issue by ErraticFox** [pugjs/pug#2543]
I don't really know where else to go for a question like this and all I could find was solutions to how to make a list in Pug, but not looping a object to create a list in Pug.

So I have a object I'm looping with: 
```js
                for (var i in players) {
                    playerList += i
                }
```
This successfully grabs all my players names and outputs them as a string. Now I want to turn this into a Pug variable, so I did: `var roomData = pug.renderFile('./views/room.pug', {playerList: playerList})`

Along with my room view being:
```
.row
		.col.s12
				#test
						ul
								#{playerList}
```

This always outputs `<liPlayerName>` when rendered. If put `li` in the pug view and delete it from the loop. Every players name is in one list item. If I do `playerList += 'li ' + i` I get `<li playerName>` rendered. Doing `playerList += 'li\n\t\t'+ 'br\n\t\t' + i` still get everything in the `li` tag. How can I do this?

Another one I've tried `playerList += 'li <br>' + i` which outputs `<ul><li <br="">name</li>name</ul>`

**Comment by SergioCrisostomo** [comment]
Can you give a example of the object you have and the HTML you want to create?

You could use `li= playerList`.

If each `i` in the `for in` loop is suposed to render to a `li` element you could do that loop in Pug passing `{playerList: Object.keys(players}` to Pug the `renderFile` method.

**Comment by ErraticFox** [comment]
I'm not quite sure I understand you... Here's the example

```js
var players = {
	"foo": {
		'something': true
	},
	"bar": {
		'something': true
	}
}
```

and I was wanting to render out

```html 
<ul>
  <li>foo</li>
  <li>bar</li>
<ul>
```

**Comment by SergioCrisostomo** [comment]
@ErraticFox : just saw your question on Stackoverflow. [Answered there](http://stackoverflow.com/a/39520643/2256325), I think it can be followed up there.

**Comment by ErraticFox** [comment]
Thanks!
