### ISSUE TITLE
show pug - answer: how to pug w/ filters, ex: mardown: working!

### ISSUE THREAD

**Issue by archer-90** [pugjs/pug#2544]
I had to figure out how to pug and use filters. I have it working, here is the code in case it helps someone, here you go:

- http://gitlab.com/archer90/archer90/tree/master/archer90

(ps: I had to use gitlab as some password issue w/ github. Also, is there a user community of pug on some forum? I can help w/ that  as I plan to do a lot w/ pug and post lots of examples and meet ups - I have done this before)

**Comment by ForbesLindesay** [comment]
The most useful thing in the short term would probably be for you to contribute to our documentation (https://pugjs.org).

The code for the docs is at https://github.com/pugjs/pug-www

The docs themselves are at https://github.com/pugjs/pug-en
