### ISSUE TITLE
runtime.js not existing.

### ISSUE THREAD

**Issue by bagbag** [pugjs/pug#2547]
Hello,

i just wanted to pug on client side and looked at [https://pugjs.org/api/reference.html](url).

There it says 

> Be sure to send the Pug runtime (node_modules/pug/runtime.js) to the client in addition to the template that you just compiled.

But i can't find that runtime.js.

**Comment by cekvenich** [comment]
I do not think runtime.js is needed or means anything, just a typo.

Here is a working example:
http://github.com/cekvenich/exWebCompSass/tree/master/nlib

**Comment by TimothyGu** [comment]
We haven't yet updated that set of instructions to Pug. Thanks for pointing this out.

**Comment by bagbag** [comment]
@cekvenich 
Either I am dumb or that example doesn't show me, how to use pug on client side (in browser).

**Comment by cekvenich** [comment]
I want to help but sometimes I am short. 
Browser only runs HTML and CSS (and .js) - that is it. For example if you Sass, you must 'transpile' for CSS. If you Pug, you must 'transpile' for html. 
The confusing way that there are many ways  transpile. Ex: PrePros. 
My email is vin (at) eml.cc if you want to screen share so I can show you.

**Comment by TimothyGu** [comment]
@cekvenich, please don't spread things that you don't completely understand (and this issue tracker isn't a job ad).

@bagbag, there are two kinds of "how to use pug on client side".

1. **Rendering** Pug templates that are precompiled
2. **Compiling** Pug templates in the browser

Which one do you need?

**Comment by bagbag** [comment]
My goal is to dynamically create HTML in browser, without the need of a server dealing with pug.

Precompiling wouldn't be a problem for me.

**Comment by cekvenich** [comment]
@TimothyGu this issue tracker isn't a job ad

Why do you say that, Because I tried to help?

**Comment by ForbesLindesay** [comment]
@TimothyGu: I'm not sure what you mean re job ad.  I think @cekvenich was just trying to help.

@bagbag The docs still haven't really been written for this.  The best way to do this is to precompile templates on the server.  You can do this using the pug cli:

```
npm install pug-cli -g
pug --client --name myTemplateFunction my-pug-file.pug
```

This will produce a JavaScript file called `my-pug-file.js` which defines a template function called `myTemplateFunction`.  You can then use it like:

```js
container.innerHtml = myTemplateFunction({someVariables: 'with values'});
```

Alternatively you can use `pug. compileClient('some pug string', {name: 'myTemplateFunction'})` and `pug.compileFileClient('my-pug-file.pug', {name: 'myTemplateFunction'})` from a node.js script.

There are also plugins for gulp/grunt/webpack/etc. if those are more your style.

**Comment by bagbag** [comment]
Yeah, @cekvenich just tried to help me over teamviewer - no more, no less.

@ForbesLindesay Is that a intended way of using Pug or does this may end in some problems I have to hack in order to make it work again?

**Comment by matteofigus** [comment]
Thanks for your answer @ForbesLindesay - still I can't figure out what the answer for the first original question is.

With jade, I used to precompile jade templates to js, and then render them in the browser by first ensuring the runtime was there bundling it from require('jade/runtime.js') to my JS libraries.

From your answer I don't understand if
1) Pug pre-compiled templates (.js) don't need the runtime anymore? In fact require('pug/runtime.js') is not there despite the docs (so the docs need to be fixed)
2) The runtime is actually still needed, but the pug bundling doesn't (yet) include the runtime.js files so this needs to be fixed (or perhaps there is another way to get the runtime.js available via npm - perhaps via another pug-* module?)

Thank you

**Comment by ForbesLindesay** [comment]
The runtime should not be needed by default.

We probably should add an option for `--external-runtime`, after which you would need to add `const pug = require('pug-runtime');` before your template functions.

By default, we just inline the helper functions though.

**Comment by matteofigus** [comment]
Thanks for your answer 👍

**Comment by sunq0001** [comment]
is this problem solved? what is the best way to solve this runtime.js issue?

**Comment by PranayPant** [comment]
STILL have not fixed it. C'mon peeps save us some time looking and searching on the internet for non-existing issues... :P
![image](https://user-images.githubusercontent.com/3720731/35874956-85d61b6a-0b33-11e8-939e-64b4e6e8ae68.png)
