### ISSUE TITLE
Intent and blank line

### ISSUE THREAD

**Issue by AminulBD** [pugjs/pug#2549]
Hello,

Today I'm experimenting with PugJS. Amazing tool.

I'm having few problems and documentation can't solve my problem.
- Line indention.
- Blank line.

I compiling something from here https://pugjs.org/language/extends.html and I'm getting this output:
```
<!DOCTYPE html><html><head><title>Default title</title></head><body><p>this is content</p></body></html>
```

But ,  I want 
```
<!DOCTYPE html>
<html>
  <head>
    <title>Default title</title>
  </head>
<body>
  
  <div>
    <p>Div inside body</p>
  </div>

  <p>this is content</p>

</body>
</html>
```

line indent is considered by using `pretty: '  '` but how can i solve the blank line issue?

Thanks!

**Comment by ForbesLindesay** [comment]
We don't support specifying details of pretty printed output.  You can manually use things like `= '\n'` to add whitespace, but in general we recommend leaving it in the default non-pretty mode.  The behaviour is much more consistent/reliable without indents.

**Comment by AminulBD** [comment]
Yes, I know its very nice for production. Sometimes we need to give edit facilities for client compiled version of the app. But, you know all clients do not have heavy knowledge to edit the .pug files or not readable code.

But, if there is an option I will better to provide human readable for clients.
