### ISSUE TITLE
Why can’t I include a js file for pug to use? (not as plain text)

### ISSUE THREAD

**Issue by danielbayley** [pugjs/pug#2550]
This way I could write in CoffeeScript then simply compile to `helpers.js` and then just `include helpers.js` and use those functions from there…

**Comment by cekvenich** [comment]
You can import or include as .pug (w/ filters). Do you have example?

**Comment by danielbayley** [comment]
~~~ js
// plain-vanilla.js
// This file could have easily been transpiled from CoffeeScript.
function pugs (what) {
  return `Pugs are ${what}.`
}
~~~
~~~ pug
//- cute.pug
include helpers.js

div= pugs('cute')
//- Pugs are cute.
~~~

**Comment by cekvenich** [comment]
I think you can import it. 

You can also do blocks, but just import it.

**Comment by TimothyGu** [comment]
See https://github.com/pugjs/pug/pull/1397#issuecomment-33372328

**Comment by hilleer** [comment]
I am not sure if you have got it working yet, but figured I would give my possible solution. 

Have you tryed something like this?: 

```
script
        include path/path/path/random.js
```

**Comment by danielbayley** [comment]
@hilleer That would include the js in a `<script>` tag, whereas I wanted to just include the javascript for pug itself to use (helper functions etc…) as if they were written in the file itself like `- function whatever () {` except not written in the file, but a separate file and included **as code** (not to be rendered). I noticed that you can pass stuff to pug, using `-O` on the command line for example, but I think this way should be possible too…

**Comment by hilleer** [comment]
Ahhh, I see - I apparently completely misunderstood you. Sorry about that

**Comment by devmckeon** [comment]
```
//- helper.js.pug
-
  var helper = (str) => str.toLowerCase().replace(/[^\w]/,'_');
```

```
//- template.pug
include helper.js.pug
- var itemName = 'Admin Page';
a(href=helper(itemName))= itemName
```

Just add another step to your build process that prepends a "-" to the start of the js file, and adds an indentation string to every line. 
(e.g.: fs.writeFileSync('helper.js.pug', ('-\n'+fs.readFileSync(helper.js).split(\n).map(l=>'\t'+l).join('\n'));  )

**Comment by markcollinscope** [comment]
Just an observation here: I have also wanted to include a .js file 'as if' it had the '-' at the top and is indented appropriately.  Here I mean the .js file is included within a Pug file and acts as if the contents of the JS file were defined with the Pug file.

However - as far as I understand it - if you put the '-' at the top of the JS file, it will not be usable as a pure JS (as well as in the pug file).

It struck me that a simple solution to this would be to use either a JS comment or string as the mechanism to indicate to pug that a whole load of javascript is coming. I.e. 'pug-include-js' (or whatever is chosen) would act in the same way as the '-' does at present.

e.g. test.js:
'pug-include-js'
<tab>    some javascript...
<tab>    some javascript...
<tab>    some javascript...

then in the pug file, just:

include test.js

in this way the JS file is still legal JS, but Pug would know to treat it as if it were simply 'in pug file' javascript.

**Comment by kizu** [comment]
+1 here, as Pug now allows includes **only** with extension, it should be possible to have `include lib.js` and apply everything included this way as a js block without causing any filename conflicts.

**Comment by kizu** [comment]
I think we need something like `include:js lib.js` here, as otherwise we would have a conflict with the current literal include. But that's surely the feature that I need rather often.

_(deleted prev. comment as there I didn't realise that including just `.js` would include as text now and changing this would be breaking)_

**Comment by pborunda** [comment]
This seems to work for file format
[example.zip](https://github.com/pugjs/pug/files/814946/example.zip)

`//-
	/* pug_include_js compatibility header
-
	/**/ 


	// For js/pug compatibility, all lines below must start with TAB
	a_global_flag = false`

**Comment by aleclarson** [comment]
@kizu I think your idea of a `:js` filter is the perfect solution! 👍

**Comment by ForbesLindesay** [comment]
duplicate #2772

**Comment by danass** [comment]
> ```js
> // plain-vanilla.js
> // This file could have easily been transpiled from CoffeeScript.
> function pugs (what) {
>   return `Pugs are ${what}.`
> }
> ```
> 
> ```
> //- cute.pug
> include plain-vanilla.js
> 
> div= pugs('cute')
> //- <div>Pugs are cute.</div>
> ```

is that real?
i just get pugs is not a function
(im using express render in nodejs with pug)

**Comment by hilleer** [comment]
@danass yes.

If used like you describe, you should also be able to use it like:

`res.render('template-file', { pugs });`

or

`res.locals.cats = pugs`
