### ISSUE TITLE
option to add or remove inline tags

### ISSUE THREAD

**Issue by AminulBD** [pugjs/pug#2551]
Hello,

I was wondering if there is an option to control inline tags.

I mean user can add or remove inline element tags.

Thanks!

**Comment by cekvenich** [comment]
Can  you explain plz.

**Comment by TimothyGu** [comment]
Not currently. We might consider adding such an option in the future.

**Comment by AminulBD** [comment]
@cekvenich I'm talking about [this](https://github.com/pugjs/pug-parser/blob/master/lib/inline-tags.js#L3).

Some times we need add or remove tags.

Anyway,  I'm closing this issue because of this issue is nothing serious at this moment.
