### ISSUE TITLE
Access CLI Options variables

### ISSUE THREAD

**Issue by lukeramsden** [pugjs/pug#2553]
So the problem I'm having is that in index.pug  I can write `title= doctype` and in index.html it says the title is "html", but if I write `title= title`, it doesn't work. I don't see anywhere in the docs for pug or pug-cli on how to access variables in the pug code. Why does doctype work but not title? I don't see the difference.
index.pug
```pug
html(lang="en")
  head
    title= title
```
options.json
```json
{
	"doctype": "html",
	"title": "Page Title"
}
```
cli command
`pug -O options.json dev -P -w -o public`

**Comment by lukeramsden** [comment]
Ok... So I didn't change anything but it works now. Might be a bug.

**Comment by lukeramsden** [comment]
So the reason for it not working is that even on an index.pug render when I use -w on the CLI, it doesn't reload changes to options.json. Fix cli or just update docs to say to rerun the command when you update options?

**Comment by TimothyGu** [comment]
See pugjs/pug-cli#4

**Comment by lukeramsden** [comment]
@TimothyGu Yeah I saw that, but I misread it. I just thought it meant that it didn't rebuild the project, I didn't realize it meant that the watch command didn't read the options file on every build (which it should)
