### ISSUE TITLE
Cant set disabled attribute on input

### ISSUE THREAD

**Issue by xtra-rene** [pugjs/pug#2554]
```
if (action == "new") {var disabledOnUpdate=""; };
if (action == "show") { var disabledOnUpdate="disabled"; };
...
input.form-control(type="text", name="username", value=objectdata.username, #{disabledOnUpdate})
```

I need an output like `<input type="text" name="username" value="user1" disabled>`
The interpolation doesnt work in this case.
I also tried:
`input.form-control(type="text", name="username", value=objectdata.username, "" + disabledOnUpdate)`

**Comment by ForbesLindesay** [comment]
interpolation doesn't work in attributes, but pug supports `true`/`false` for boolean attributes like this:

```pug
input.form-control(
  type="text"
  name="username"
  value=objectdata.username
  disabled=action === 'show'
)
```

Will produce:

```html
<!-- if action === 'show' -->
<input type="text" name="username" value="user1" disabled>
<!-- if action !== 'show' -->
<input type="text" name="username" value="user1">
```

**Comment by ForbesLindesay** [comment]
See https://pugjs.org/language/attributes.html#boolean-attributes for future reference.

**Comment by xtra-rene** [comment]
Thanks! This works great.
