### ISSUE TITLE
Pass string with all attributes to tag

### ISSUE THREAD

**Issue by JGAntunes** [pugjs/pug#2560]
Hi there, sorry for opening an issue with something that might come out as a stupid question but I've been looking everywhere and still haven't found a way to deal with this.

Is there any way to pass a whole string as the attributes of a certain tag? Something like:
```javascript
const htmlAttributes = 'lang="en" amp'

// pug file
html(htmlAttributes)

// expected output
<html lang="en" amp>
```

**Comment by zoxon** [comment]
Try use attributes

```jade
- var htmlAttributes = {"lang":"en", "amp": true}
html&attributes(htmlAttributes)
```

**Comment by JGAntunes** [comment]
Thanks @zoxon but unfortunately I don't have control over the `htmlAttributes` var, it's something I receive as it is (a string). I wanted to avoid having to "parse" this to create an object but it looks like there's no other way.

**Comment by TimothyGu** [comment]
You could try hacking around it using [unescaped attributes](https://pugjs.org/language/attributes.html#unescaped-attributes):

```pug
- const htmlAttributes = 'lang="en" amp'
html(some-non-attributes!=`" ${htmlAttributes} other-non-attribute="`)
```

Indeed this isn't ideal, but that's the best thing I can think of right now.
