### ISSUE TITLE
Syntax highlighter into pug templates

### ISSUE THREAD

**Issue by edusl** [pugjs/pug#2561]
Hi, I'm trying to integrate a syntax highlighter system (for a styleguide), I tried with [prismjs.com](prismjs.com) and [highlightjs.org](highlightjs.org), but I can't get it to work properly.

somebody know a simple option to display highlight code?

Thanks!

**Comment by ForbesLindesay** [comment]
Run:

```
npm install jstransformer-highlight
```

(or `yarn add jstransformer-highlight`)

then in your template:

```pug
link(rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.7.0/styles/default.min.css")
pre
  code.hljs
    :highlight(lang="javascript")
      function foo() {
        alert('This is JavaScript');
      }
```
