### ISSUE TITLE
rendering is very slow when running on AWS lambda

### ISSUE THREAD

**Issue by nguyeda** [pugjs/pug#2562]
Hi Guys,

I'm running a very small app using pug, it works perfectly fine when I run it locally using express, but when I deploy it to an AWS lambda it becomes very very slow (like 15 seconds rendering slow).

The problem seems to be happening when I start to include other pug templates in my main template:

```
extends ./fragments/layout

block content
  header
    include ./fragments/navbar

  section
    include ./fragments/home
    include ./fragments/features
    include ./fragments/skills
    include ./fragments/testimonials
    include ./fragments/experience
    include ./fragments/education
    include ./fragments/contact

  footer
```

the "extends" part does not seems to have any impact on rendering time, but as soon as I add the first "include" statement, it becomes very slow. 

Any idea?

**Comment by TimothyGu** [comment]
Is the problem just for the first include, or all includes? just for Lambda or on your desktop as well? You might try to increase the memory of the Lambda function, which will allocate more computing resources (IIRC include I/O).

**Comment by nguyeda** [comment]
@TimothyGu, it seems that my templates were a bit too complex so it indeed required a bit more processing power. The maximum memory used by the function is 75MB, which is why I initially configured it with only 128MB of RAM. Increasing to 1024MB did the trick: now the first invocation takes about 1.8s, which is still a bit slow but acceptable for my purpose. 

Thanks for your help :-)

**Comment by TimothyGu** [comment]
Yep. The trick is that increasing memory will actually increase all other resources as well (like CPU and network):

> **Q: How are compute resources assigned to an AWS Lambda function?**
>
> In the AWS Lambda resource model, you choose the amount of memory you want for your function, and are allocated proportional CPU power and other resources. For example, choosing 256MB of memory allocates approximately twice as much CPU power to your Lambda function as requesting 128MB of memory and half as much CPU power as choosing 512MB of memory. You can set your memory in 64MB increments from 128MB to 1.5GB.
>
> _(https://aws.amazon.com/lambda/faqs/)_

**Comment by ForbesLindesay** [comment]
N.B. if deploying to a service like AWS lambda, you should pre-compile your templates to a function (like you would do if you were rendering them client side).  Otherwise you will be compiling your template every time AWS spins up a new process.  This probably happens pretty frequently.

I suspect if you do this you will find that it runs an order of magnitude faster, even with the lower memory options.

**Comment by dkimot** [comment]
How would you save that compiled function so it could be reused after Lambda is "shut down"?

**Comment by ForbesLindesay** [comment]
Use `compileFileClient` and save the resulting string to a file.  You should do this *before* deploying to AWS.
