### ISSUE TITLE
One link in README.md doesn't work

### ISSUE THREAD

**Issue by zeakhold** [pugjs/pug#2563]
In README.md line 142,the Chinese version of document(Readme_zh-cn.md) doesn't exit:
  - [Pug - 模板引擎](https://github.com/pugjs/pug/blob/master/Readme_zh-cn.md)

**Comment by LionNatsu** [comment]
I think, if you need to read the  Chinese version of documentaion, the repo [pugjs/pug-zh-cn](https://github.com/pugjs/pug-zh-cn) which is work-in-progress might help you, there is `Readme_zh-cn.md`, though it is veeeery out-of-date. Anyway, if you can take a look into my pull request https://github.com/pugjs/pug-zh-cn/pull/1 and review the translation (there is a link to my preview website). Any comments or suggestion are welcome.  :)

**Comment by zeakhold** [comment]
I understand,thanks.
