### ISSUE TITLE
browser standalone form missing

### ISSUE THREAD

**Issue by agauniyal** [pugjs/pug#2565]
https://raw.githubusercontent.com/pugjs/pug/1.11.0/pug.js

gives **404: Not Found**

**Comment by ForbesLindesay** [comment]
We should serve this from pugjs.org instead and update the docs to use that.

**Comment by TimothyGu** [comment]
The newest version is available at https://pugjs.org/js/pug.js. Where did you find the link to that file?

**Comment by agauniyal** [comment]
@TimothyGu - https://github.com/pugjs/pug/blob/master/README.md#browser-support

**Comment by agauniyal** [comment]
https://github.com/pugjs/pug/pull/2570

**Comment by TimothyGu** [comment]
Fixed by #2570.
