### ISSUE TITLE
Mixin with iteration

### ISSUE THREAD

**Issue by Luiggiggi** [pugjs/pug#2571]
i'm new to pug and js but i'm learning.
so i've this mixin:
```
- var n = 0;
mixin paginator(number, root)
  while n < number
    img.slide-pagination(src=root+'-pag'+ n +'.png')
  n = n++;
```
to make a list of items with the same 'root' and progressive 'n' but i can't figure a way to do it.
please help me!

**Comment by Luiggiggi** [comment]
solved with this:
```
- var n = 0;
mixin paginator(number, root)
  while n <= number
      img.slide-pagination(src=''+root+'-pag'+ n++ +'.png')
```
hope it helps 😄

**Comment by jeromew** [comment]
your first example did not work because the javascript calculation (`n = n + 1`) is not inside the while loop and not in javascript mode

Also, you may want to initialize `n` inside the mixin since it is a variable that is local to the mixin.

For example you can try
```
mixin paginator(number, root)
  - var n = 0;
  while n < number
    img.slide-pagination(src=root+'-pag'+ n +'.png')
    - n = n + 1;
```
