### ISSUE TITLE
Pug doesn't seem to allow for hash syntax of ng2 ViewChild

### ISSUE THREAD

**Issue by jrgleason** [pugjs/pug#2572]
First of all pug is great so far for ngTemplates but I found one issue. The following HTML is required for injecting dom elements via `@ViewChild`

```
<div #main>
    <h1>Test Html</h1>
</div>
```

Try to convert this over to pug like this...

```
.app( #main )
    h1 My Angular App
```

But it doesn't seem to work. 

```
Unhandled Promise rejection: Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) (" #main\u003E\u003Ch1\u003EMy Angular App\u003C\u002Fh1\u003E\u003C\u002Fdiv\u003E";;return pug_html;}[ERROR ->]"): AppComponent@0:221
Invalid ICU message. Missing '}'. (" #main\u003E\u003Ch1\u003EMy Angular App\u003C\u002Fh1\u003E\u003C\u002Fdiv\u003E";;return pug_html;}[ERROR ->]"): AppComponent@0:221 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) (" #main\u003E\u003Ch1\u003EMy Angular App\u003C\u002Fh1\u003E\u003C\u002Fdiv\u003E";;return pug_html;}[ERROR ->]"): AppComponent@0:221
Invalid ICU message. Missing '}'. (" #main\u003E\u003Ch1\u003EMy Angular App\u003C\u002Fh1\u003E\u003C\u002Fdiv\u003E";;return pug_html;}[ERROR ->]"): AppComponent@0:221
```

**Comment by jrgleason** [comment]
I also tried `(#main='')` which also does not seem to work. The error was because I was using pug-loader and not pug-html-loader

**Comment by TimothyGu** [comment]
Okay, I assume this is not a bug on our side.

**Comment by chrisnicola** [comment]
@TimothyGu actually this is an issue here which is that something like:

```
div(#reference)
```

Compiles to:

```
<div #reference="#reference"></div>
```

Which does cause an error with Angular 2. Is there a reason why Pug repeats the attribute name?

For now `#reference=""` does work, but it is a bit less than ideal.

**Comment by TimothyGu** [comment]
@chrisnicola, see https://pugjs.org/language/attributes.html#boolean-attributes. You have to specify the doctype either as an option, or using the `doctype` keyword, in order to get the shortened syntax.

**Comment by chrisnicola** [comment]
@TimothyGu is that going to add the doctype to the top of all my templates? These are Angular 2 templates they generally don't start with a doctype declaration.

**Comment by chrisnicola** [comment]
Ah I see it can be passed globally as an option. Setting it in my webpack loader options does the trick. 🍻
