### ISSUE TITLE
"Jade" is a registered trademark ? What a bull shit !

### ISSUE THREAD

**Issue by hellolake** [pugjs/pug#2574]
Jade is not a commercial project, right? Why they do not allow you to use the name "jade" ? Is that means we can not speak or write "America" and "USA" because they are belongs to America ? Holly my lady gaga, BTW, I do not like the name 'pug', totally lost vision...orz

**Comment by TimothyGu** [comment]
Trademark laws have nothing to do with commercial/not commercial. Indeed, you are not allowed to call your product "America" when there is already a company that exists with that name in that specific field.

Either way the rename has been decided. The fact that you "do not like" Pug is no ground for renaming yet again.

**Comment by atilkan** [comment]
What jade means? **"Jade is an ornamental rock, mostly known for its green varieties, which feature prominently in ancient Asian art."**  
I wonder what you gonna do when they register **pug**.  
Wait... https://trademarks.justia.com/search?q=pug
Already 6 company registered it. I don't know how this trademark thing work. Not like i thought i guess. Be ready they will call you any time.
Why i am not happy with the name? it is a modified dog name. It can't live without the help of human. It also pronounce bad. 
20 company registered the name Jade. You could just subname it like them. Like jade.io/jade. 
You can't change the name after this point i know. But your story is kinda suspicious. I think you just wanted to change it or gave up quickly. Both reasons are not acceptable.

**Comment by hellolake** [comment]
@atilkan 

It's just a friendly joke, hey. But, I still doubt that is a public relation problem, u already knew that 'Jade' have been registered by many company, why you cant be one of them? 

As I know you can register a same name but with a different business purpose, like someone may be 'Jade Pet Store', some are 'Jade Software Co.', and you can be 'Jade Script xxx', a same short name but design a different trademark, u can find a lawyer... Dont need to afraid those pig.

I like 'Jade' coz it looks pure, but 'Pug'... something complex..orz

This's a friendly joke too, good day today.
