### ISSUE TITLE
feature question: how to use global vars

### ISSUE THREAD

**Issue by abenf-76** [pugjs/pug#2577]
Hi,
I want to use a global var which can be used in all .pug files. is this possible?
E.g. I want to use "name" as #{name} in main.pug and header.pug, too.

**Comment by ForbesLindesay** [comment]
Pass it to each call to `pug.render`.  If you're using express you can set `app.locals.name = "name";`

You can easily do something like:

```js
function render(str, locals) {
  locals = locals || {};
  locals.name = 'name';
  return pug.render(str, locals);
}
```

There is no need ro pug to support this as a built in concept.

**Comment by abenf-76** [comment]
Thank you very much.
