### ISSUE TITLE
Hex based characters in string (Emoji's)

### ISSUE THREAD

**Issue by bolencki13** [pugjs/pug#2578]
I am trying to display emojis on a page inline using hex based strings and the `&` symbol. Whether the hex string is passed as a viable, or if it is hard coded in, the `&` symbol will automatically have `amp` appended to it. Resulting in `&#x1F62B;` becoming `&amp;#x1F62B;`.

**Comment by TimothyGu** [comment]
Can you copy-paste the specific piece of code?

**Comment by bolencki13** [comment]
**File (test.pug):**
`doctype html
html
        head
                meta(charset="UTF-8")
                meta(http-equiv="X-UA-Compatible",content="IE=edge,chrome=1")
                meta(name="viewport",content="width=device-width, initial-scale=1.0, maximum-scale=1.0")
                title="Test"
        body
                p="&#x1F62B"` 

**Output (test.pug):**
`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"><title>Test</title></head><body><p>&amp;#x1F62B</p></body></html>`

(Formatting has been removed due to GitHub)

**Comment by TimothyGu** [comment]
You can use [`p!= string`](https://pugjs.org/language/code.html#unescaped-buffered-code) to make Pug not escape the ampersand. For GitHub formatting, you can use [code blocks](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

**Comment by ForbesLindesay** [comment]
You could also have used:

```pug
p &#x1F62B;
```

If you know the value up front.

**Comment by zamkevich** [comment]
Hi. Still one week i do not understand whats happens.
Pug work right, like this:
```
<div class="description-question">
    <h2 data-name="some short header">some header</h2>
    <p class="description-question--remark">some text — <a class="link---btn" href="#"><span>some link text</span></a>, some text</p>
…
```

But after install any packages in project, pug do some like this: 
```
<div class="description-question">
    <h2 data-name="some short header">some header</h2>
    <p class="description-question--remark">some text — &lt;a class=&quot;link---btn&quot; href=&quot;#&quot;&gt;&lt;span&gt;some link text&lt;/span&gt;&lt;/a&gt;, some text</p>
…
```

**init code**
```
gulp.task('pug', function() {
  gulp.src(paths.templates)
    .pipe(plumber({errorHandler: onError}))
    .pipe(pug({pretty: true}))
    .pipe(gulp.dest(paths.app))
    .pipe(reload({stream: true}));
});
```
**mixin**
```
mixin description-question(arr)
    .description-question
        - if(arr.header > '0')
                h2(data-name= arr.name)= arr.header
                p.description-question--remark= arr.remark
        …
```
########################

**get mixin**
```
include description-question
    +description-question({
        header: 'header',
        name: 'short header',
        remark: 'some text — <a class="link---btn" href="#"><span>some link text</span></a>, some text'
        …
 })
```

What i do wrong?
