### ISSUE TITLE
Interpolation not supported for .class

### ISSUE THREAD

**Issue by curvedmark** [pugjs/pug#258]
```
- var foo = 'bar';
    p.#{foo}
```

The above code generates `<p>.bar</p>` which should be `<p class="bar"></p>` instead.

I know this works:

```
- var foo = 'bar';
    p(class=foo)
```

But the first version seems to be more succinct.

**Comment by MrFusion42** [comment]
The world needs this

**Comment by davincif** [comment]
@tj, this is not the same thing!
This `foo.bar.baz(class=another)` will add 'another' to foo, that is, foo would have classes "bar baz another".
And this `foo.bar.baz#another` would add 'bazanother', that is, foo would have classes "bar bazanother". Which is exactly what I wish I would have for my project right now =/

**Comment by ForbesLindesay** [comment]
attribute values are full javascript expressions, so you can just do `foo.bar(class=`baz${another}`)
