### ISSUE TITLE
Force line breaking

### ISSUE THREAD

**Issue by matduarte** [pugjs/pug#2580]
Hey,
I would to know is there any way to force line breaking without using "\n". 
I have next code : 
```jade  
footer
   .soc
      a(target='_blank', href='https://dribbble.com/***')
        span.ion.ion-social-dribbble
      a(target='_blank', href='https://twitter.com/***')
        span.ion.ion-social-twitter
      a(target='_blank', href='https://github.com/***')
        span.ion.ion-social-github
      a(target='_blank', href='https://instagram.com/***')
        span.ion.ion-social-instagram-outline
      a(href='/releasenotes.html')
        span.ion.ion-code
  .copy &copy; 2016 ***. All rights reserved.
```

after rendering I have this : 
```html
<footer>
        <div class="soc"><a target="_blank" href="https://dribbble.com/***"><span class="ion ion-social-dribbble"></span></a><a target="_blank" href="https://twitter.com/***"><span class="ion ion-social-twitter"></span></a><a target="_blank" href="https://github.com/***"><span class="ion ion-social-github"></span></a><a target="_blank" href="https://instagram.com/***"><span class="ion ion-social-instagram-outline"></span></a><a href="/releasenotes.html"><span class="ion ion-code"></span></a></div>
        <div class="copy">&copy; 2016 ***. All rights reserved.</div>
</footer>
```
what I would to see is this : 
```html
<footer>
  <div class="soc">
    <a target="_blank" href="https://dribbble.com/***"><span class="ion ion-social-dribbble"></span></a>
    <a target="_blank" href="https://twitter.com/***"><span class="ion ion-social-twitter"></span></a>
    <a target="_blank" href="https://github.com/***"><span class="ion ion-social-github"></span></a>
    <a target="_blank" href="https://www.instagram.com/***"><span class="ion ion-social-instagram-outline"></span></a>
    <a href="/releasenotes.html"><span class="ion ion-code"></span></a>
  </div>
  <div class="copy">© 2016 ***. All rights reserved.</div>
</footer>
```
The problem is that non indented code kill all css style for unknown reason.
What I would to see is this : 

<img width="1146" alt="screen shot 2016-10-15 at 18 37 44" src="https://cloud.githubusercontent.com/assets/16789874/19411746/7acc315a-9307-11e6-9b52-350700115f91.png">

And what I see with Jade rendering is : 

<img width="1145" alt="screen shot 2016-10-15 at 18 43 33" src="https://cloud.githubusercontent.com/assets/16789874/19411745/7483991e-9307-11e6-8451-a192d49004e5.png">

Is there any correct way to force line breaking ?
Thanks.

**Comment by TimothyGu** [comment]
You could try something like this:

```pug
footer
   .soc.
      #[a(target='_blank', href='https://dribbble.com/***'): span.ion.ion-social-dribbble]
      #[a(target='_blank', href='https://twitter.com/***'): span.ion.ion-social-twitter]
      #[a(target='_blank', href='https://github.com/***'): span.ion.ion-social-github]
      #[a(target='_blank', href='https://instagram.com/***'): span.ion.ion-social-instagram-outline]
      #[a(href='/releasenotes.html'): span.ion.ion-code]
   .copy &copy; 2016 ***. All rights reserved.
```

Beyond that, no, there isn't a way to force addition of whitespace.

**Comment by devmckeon** [comment]
Could this be a template option? {renderInlines: 'block' || 'none' || 'all' || 'pug'}
**block**: html block elements are always on own line, while inline elements are inlined in html code
**none**: all html elements are indented as children and on own line
**all**: everything is inlined (newlines preserved in pug block text/code), this is similar to minification
**pug**: like none, except that elements inlined in pug ( li: a: span: text) are inlined in html output (This could be the default)

**Comment by matduarte** [comment]
Thank you @TimothyGu it's worked fine for me
