### ISSUE TITLE
Support template strings in ES6

### ISSUE THREAD

**Issue by devmckeon** [pugjs/pug#2581]
Currently it seems the parser removes blank lines in every context. This is problematic for code blocks because now in ES6 with the addition of template strings, removal of blank lines unconditionally in code blocks can greatly affect template strings.

I suggest that the parser recognize blocks (both code and text) so as to avoid causing issues with template strings in both unbuffered/buffered code (executed when compiling/rendering template), AND code output from the template (for example code to be executed on the client),

```
doctype html
  html
    -
      var hello = `
      <pre>
         It's time to say...

              HELLO!!!
      </pre>
      `;
    .hello-world
    script.
      var world= `
      <pre>
         To the brave new world of:

              ES6
      </pre>
      `;
      document.querySelector('.hello-world').innerHTML = hello + world;
```

**Comment by ForbesLindesay** [comment]
I'm not able to reproduce this.  Do you think you could submit a pull request to add a test case.

**Comment by devmckeon** [comment]
Strange, neither am I any longer. I wonder if I had a different version in dev or perhaps it was an issue in my logger. I'll try to reproduce what I was seeing, but I'm going to chalk this one up as user error for now. I'll open another issue if I can provide a test case for it. My apologies.
