### ISSUE TITLE
link tag not self-closing

### ISSUE THREAD

**Issue by nathanbakhuijzen** [pugjs/pug#2582]
Hi, i have trouble with the `link` tag in pug.

I'm making an application using Express and Pug. According to the pug [documentation](https://pugjs.org/language/tags.html), `link` should be a self closing tag.

This is my layout.pug:
![pug_link_tag_not_self_closing](https://cloud.githubusercontent.com/assets/10281985/19450199/caffc270-94a8-11e6-8cf0-8db8cc54c9fd.png)

And this is the generated html:
![pug_link_tag_not_self_closing2](https://cloud.githubusercontent.com/assets/10281985/19450206/d27ef1d8-94a8-11e6-95a8-2bc07a383aa2.png)

Am i doing something wrong or is this a bug?

**Comment by nathanbakhuijzen** [comment]
Nevermind, i inspected the wrong html. This inspector hides the `/` from users. When i looked at the source the `<link foo="bar" />` actually had a closing tag.

**Comment by TimothyGu** [comment]
I know you've solved this problem already, but in HTML5 the two variants are **completely equivalent.** As a result of that I'd encourage _not_ using the `/` suffix just because it's more code to maintain.
