### ISSUE TITLE
Inserting HTML

### ISSUE THREAD

**Issue by brettywhite** [pugjs/pug#2583]
Hello,

I am attempting to insert an HTML block (rows of a table, specifically) into a pug template as part of an email, since I cant use JS or JQuery in an email itself. 

I am making the html rows like this and passing this into the Pug template as a variable called table:

```javascript
function createEmailHTML(list,total){

  var tabledata = JSON.parse(list);

  var html =" ";

  for (i = 0; i < tabledata.length; i++) {
    html += ' <tr><td style="font-family: sans-serif; font-size: 14px; vertical-align: top; border-bottom: 1px solid #eee; padding: 5px;" valign="top">'+tabledata[i].Description+'</td><td class="receipt-figure" style="font-family: sans-serif; font-size: 14px; vertical-align: top; border-bottom: 1px solid #eee; padding: 5px; text-align: right;" valign="top" align="right">'+tabledata[i].Total+'</td></tr> ';
  }
  return html;
} 
```
The render: 

```javascript
          var table = createEmailHTML(lineItems,total);
          res.render('templates/estimateemail', {
            estimates:estimates,
            user: req.user,
            client:client,
            table:table
          });
```
I pass the variable into the template where it should go in the table like so:

<img width="856" alt="screen shot 2016-10-17 at 17 46 43" src="https://cloud.githubusercontent.com/assets/3911458/19457059/8d9b2c46-9492-11e6-8168-6e63cb5db218.png">

but it is duplicating the table created once compiled like this (and adding in those <>>'s):

<img width="520" alt="screen shot 2016-10-17 at 17 46 31" src="https://cloud.githubusercontent.com/assets/3911458/19457085/a72f81d4-9492-11e6-8894-47e568fc4cd1.png">

However, when I escape the text like this: 

<img width="872" alt="screen shot 2016-10-17 at 17 46 51" src="https://cloud.githubusercontent.com/assets/3911458/19457125/d1af671c-9492-11e6-9a00-7eba5c37808f.png">

It shows up as only 2 rows (as it should) and in proper HTML. Not extra <>>'s and duplicated rows:

<img width="568" alt="screen shot 2016-10-17 at 17 47 00" src="https://cloud.githubusercontent.com/assets/3911458/19457144/f5b5bc92-9492-11e6-948d-6bb6561bb0a0.png">

If anyone can see if I am doing something wrong or if it is just not compiling right, it would be appreciated. According to the package.json file, I am on version: "pug": "^2.0.0-beta6",

Thanks

**Comment by brettywhite** [comment]
Turns out I needed to use:

`p!= table`

in the template to have it display correctly.

Not sure if this is in the docs or not.

**Comment by ForbesLindesay** [comment]
https://pugjs.org/language/code.html or https://pugjs.org/language/interpolation.html would have helped you with this.
