### ISSUE TITLE
Idea: Syntax for inline styles

### ISSUE THREAD

**Issue by icholy** [pugjs/pug#2584]
It would be cool if there was a cleaner way to write inline styles.

``` jade
a(href="#" style="background-color: red; line-height: 2em") link
```

``` jade
a(href="#")
    background-color: red
    line-height: 2em
```

**Comment by ForbesLindesay** [comment]
We already support `a(href="#" style={'background-color': 'red', 'line-height': '2em'}) link` and the string representation, we do not need/want a third way of representing inline styles.  Also, the syntax you propose would conflict with existing pug syntax.

**Comment by TimothyGu** [comment]
If you prefer writing it in multiple lines, try

```pug
a(href="#" style={
  'background-color': 'red',
  'line-height': '2em'
}) link
```

**Comment by ccckblaze** [comment]
why not doing this, just like jquery
a(href="#" style={backgroundColor: red; lineHeight: 2em}) link
a capital helps alot!
