### ISSUE TITLE
Tritium not decoding angular JS attributes values {{}}

### ISSUE THREAD

**Issue by sumeetsonawane11** [pugjs/pug#2587]
Hi ,

I am working in one of my project and i face one issue. The site is developed in Angular JS.
The issue is , I have one anchor tag in html as as <a class="image" href="%7B%7Bitem.url%7D%7D>'
I want to decode the href attribute of the above element to {{item.url}} through **Tritium** language.
How can I do that with Tritium language ?
Any help would be appreciated.

**Comment by ForbesLindesay** [comment]
Not enough info here to debug this.
