### ISSUE TITLE
include inside if else

### ISSUE THREAD

**Issue by wallneradam** [pugjs/pug#2588]
I think my other reported issue #2586 is related to this.

When you include something in an "if else", the include file is included in both "if" and "else". Which can be a problem if you use prepend or append blocks or some variables. It worked good in Jade. I think includes and extends should be processed after ifs.

**Comment by ForbesLindesay** [comment]
Pleas provide a complete example, along with what it output before, and what it outputs now.

**Comment by andreamangano** [comment]
I have the same issue. I would like include a file according to the environment but both statements are evaluated.

That's an example:

``` javascript      
if isDevelopment
    include ../assets/icons-sprite.svg
else
    include ../public/icons/icons-sprite.svg
```

**Comment by ForbesLindesay** [comment]
Include is processed at compile time, this has always been the case. There have been no recent regressions in that space.
