### ISSUE TITLE
Project missing standard CHANGELOG.md

### ISSUE THREAD

**Issue by elektronik2k5** [pugjs/pug#2589]
First of all thank you for everyone involbed and dedicated to this project! :)

I believe many people would benefit from having a standard, simple `CHANGELOG.md` file, such as this one: https://github.com/jtangelder/sass-loader/blob/master/CHANGELOG.md
![image](https://cloud.githubusercontent.com/assets/1078554/19532139/0f43fa8c-9643-11e6-8b48-a232fc4688e1.png)

Thank you!

**Comment by TimothyGu** [comment]
Instead of a CHANGELOG.md, we have had a History.md file that has a pretty simple format.
