### ISSUE TITLE
How to check whether a variable is undefined?

### ISSUE THREAD

**Issue by DerEnderKeks** [pugjs/pug#2598]
I'm trying to check whether a variable is undefined.
I tried that in different ways:

```
if typeof foo === "undefined"
    - var foo = ''
```
```
if !foo
    - var foo = ''
```
```
- if (!foo)
    - var foo = ''
```

It always sets the variable to `''` even if a value was set before.

---
Pug version: 2.0.0-beta6

**Comment by TimothyGu** [comment]
Try removing the `var`, which will erase the local:

```pug
if foo === undefined
    - foo = ''
```

![image](https://cloud.githubusercontent.com/assets/1538624/19816347/bc7e15b6-9cfb-11e6-860a-5f5dcd131a4e.png)

**Comment by DerEnderKeks** [comment]
That works. Thanks!
