### ISSUE TITLE
Something strange with "Attribute Interpolation" and "ES2015 template strings"

### ISSUE THREAD

**Issue by lerfi** [pugjs/pug#2599]
I am working on some APIs in my Node.js project and I get an error when I  try to create a new link (tag `<a href="link">`) in template (using "Attribute Interpolation" and "ES2015 template strings").
Code example:
```pug
- var id = '1234567'
a(href=`/some/api/item/delete/${id}`) // Error
```
- Error: The end of the string was reached with no closing bracket found.

so i start experimenting:
```pug
a(href=`/some/api/item/delete/anytext/${id}`) // Good
a(href=`/some/api/item/deleteanytext/${id}`) // Good
a(href=`/some/api/item/anytextdelete/${id}`) // Good
a(href=`/anytext/delete/${id}`) // Error
a(href=`delete`) // Also good
a(href=`delete/`) // Error
```
only `delete/` produce error.

> Try on "pug": "^2.0.0-beta6" and online converter http://html2jade.org/

**Comment by TimothyGu** [comment]
Heh that's odd. Using the provided code on our [website](https://pugjs.org/language/attributes.html)

```pug
- var id = '1234567'
a(href=`/some/api/item/delete/anytext/${id}`)
a(href=`/some/api/item/deleteanytext/${id}`)
a(href=`/some/api/item/anytextdelete/${id}`)
a(href=`/anytext/delete/${id}`)
a(href=`delete`)
a(href=`delete/`)
```

works just fine. Can you paste the entire stack trace?

**Comment by lerfi** [comment]
Thanks.
The problem was in online converter (http://html2jade.org/) and my current IDE.
