### ISSUE TITLE
Please do not deprecate pug.filters

### ISSUE THREAD

**Issue by ICodeMyOwnLife** [pugjs/pug#2600]
The document says that pug.filters has been deprecated in favor of the filters option.
When using pug with express I don't directly call pug.render or pug.compile methods, so setting pug.filters is the only choice I have when needing custom filters. Please do not deprecate it.

**Comment by TimothyGu** [comment]
If you put the filters in `app.locals.filters` or `res.locals.filters`, they will have exactly the same effect as putting them in `pug.filters` -- but cleaner. Please check if that works.

**Comment by ICodeMyOwnLife** [comment]
I've tested and it worked perfectly. Thank you very much. I think this issue should be closed now.
