### ISSUE TITLE
Input tags not always adding type attribute

### ISSUE THREAD

**Issue by DaClan008** [pugjs/pug#2601]
Hi, recently I came to love pug (or jade at first) and had no issues at all.  Today however something strange is happening.  I'm not sure if others have the same problem.

I have (shortened code)

```pug
        fieldset#fs-name.larger
            input.fill-option(type='text')
        fieldset#fs-pword.larger
            input.fill-option(type='password', name='password1', id='pword')
        fieldset#fs-surname.larger
            input(type='text') 
        //- etc
```
please note that this is just some extracts and shortened version of my code.  I did compile it though and got the following output from these sections

```html
        <fieldset class="larger" id="fs-name">
                          <input class="fill-option">
        <fieldset class="larger" id="fs-pword">
                          <input class="fill-option" type="password" name="password1" id="pword">
        <fieldset class="larger" id="fs-surname">
                          <input>
```

Is there a reason why the input field does not include type when type is text?

I am using gulp-pug v3.1.0 on a windows 10 machine (not sure if this makes any difference)

Surely if password works (ps.  email also works perfectly) text should also work?  Am I missing something here?

**Comment by ForbesLindesay** [comment]
What are you using to look at the output?  The output you've shown does not look like it was copied from your text editor since it's missing closing tags.  If you can show the actual input and incorrect output I'll re-open this.

**Comment by DaClan008** [comment]
I looked in my html output file that has been build by running gulp-pug.

A mentioned above, I did not include the entire file as I believe it to be irrelevant to the issue.  Content after the input is correct and content before the issue is correctly parsed.

Here is the output of the first input("text") that has a problem
##pug
```pug
        fieldset#fs-name.larger
            input.fill-option(type='text')  
             //- , name='name', id='name', required, formnovalidate )
            label.email(for='name')
            span(data-text='Name') Name
```

The commented out section should also be included in the input as attributes, but I removed it to see if any of those attributes caused the problem
The rest of the details follow exactly the same pattern.  And as mentioned before it is only the input fields that has a type of text that has the issue.  [password, email, date] all works fine (even the not so widely used 'tel' type is working perfectly.

##html
```html
        <fieldset class="larger" id="fs-name">
                <input class="fill-option">
                <label class="email" for="name"><span data-text="Name">Name</span></label>
         </fieldset>
```

ps.  I am not sure if this is going to make a difference, but the "module" (subscription-module) where these fields are used in is an external file and is included by means of a mixin.

The file start with:
```pug
    mixin addSub(.... options)

            //- first use of option variables
            .scroll-container
                if compName && compName !== ''
                    h1= compName
                if title && title !== ''
                    h3= title
                form(action='', data-at=dataAt, data-dot=dataDot, data-adres=data, data-info= dataInfo, onsubmit='subscribeSubmit(this)',  method='post',  enctype='text/plain')
                      fieldset#fs-name.larger
                          input.fill-option(type='text')  
                          //- , name='name', id='name', required, formnovalidate )
                          label.email(for='name')
                               span(data-text='Name') Name
                      fieldset //- ... the same pattern

                      //-  the final set of options is used:
                      fieldset#fs-email-body.larger
                            if bodyDescription && bodyDescription !== ''
                                    textarea.fill-option(name='body', id='email-body')
                                    label.email-body(for='email-body')
                                            span(data-text=bodyDescription)= bodyDescription
```

If that is not enough... I have simplified things and commented out all everything.  I now only have this in my subscription module pug file

```pug
mixin addSub(button, title, emailDescription, bodyDescription, submit, compName)
    form
        input(type='text')
    //- .subscription [and everything else is commented out]

    //-  I call it from my main page like this
    block cta
         span.down-pointer(onclick='coc.bannerActionClick(false)')
         include ../_modules/subscribe
         +addSub("Subscribe", "Subscribe", "Email", "Add a Comment (optional)", "subscribe", '...')

    //- my base file only have a place for
   block cta

```
it generated

```html
               <form>
                  <input>
                </form>
```
Hope this helps!

**Comment by ForbesLindesay** [comment]
See if you can produce as small an example input as possible, then run pug so the output ends up in a file, then copy that entire file verbatim.  e.g. 

Input:

```pug
mixin addSub(button, title, emailDescription, bodyDescription, submit, compName)
  form
    input(type='text')
+addSub()
```

Output:

```html
<form><input type="text" /></form>
```

To figure out the minimum input, delete lines and, after each deletion, see if the problem persists.  Make sure you are also copying the raw HTML text.  If you copy from the Elements tab of Chrome Dev Tools (for example) you can get different results.  e.g. the browser may not display the `type="text"` since it's the default so it doesn't make any difference.

**Comment by DaClan008** [comment]
Yes I look at the raw html file that was output to my tmp folder.  i.e. it was not a copy from Crome Dev Tools or any other dev tools.

I have created 2 new pug files in my project.  These are the entire files:
```pug
//-main
html
<!--[if lt IE 9]>
<html class='lt-ie9 no-js' lang='en'>
<![endif]-->
<!--[if gte IE 9]><!-->
<html class='no-js' lang='en'>
<!--<![endif]-->

include ../_modules/subTest.pug
+addSub2()


</html>

//- subTest file
mixin addSub2()
    form
        input(type='text')

```
Here is the HTML output
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN" "http://www.w3.org/TR/xhtml-basic/xhtml-basic11.dtd">
<html></html><!--[if lt IE 9]>
<html class='lt-ie9 no-js' lang='en'>
<![endif]-->
<!--[if gte IE 9]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<form>
  <input>
</form></html>
```

Sorry for the late reply.  I am building a new project (in new folder), trying to replicate the issue.  I note all my steps that I am doing.  Once that is done and the problem remains I will let you know how to get the same environment that I am building on.

Thanks for your feedback this far!

ps.  just to clarify the above code is a complete copy and paste of the 3 files.  I have also commented out all other "pages"/pug files.  I.e. all my html files (except the one above) have absolutely nothing in it.  Pug therefore only has (according to me) the above code to run through.  I have looked at all the output html files and can confirm that they are totally empty.

**Comment by DaClan008** [comment]
OK.  I have found a way to reproduce this.

I use  a yeoman generator.  The generator is slightly old and needs updating (I was thinking of doing this at some point, but this generator offer me a way to quickly get going at the moment, and it could reproduce my problem).  The generator is => yeogurt (v 1.5.3)

It still run jade.  so I basically do the following installing the generator
1.  yo yeogurt --skip-install  (will not run npm install)
2.  open package.json{
         - replace gulp-jade with gulp-pug.  
         - replace jade with pug
         - replace all versions of dependency files with *  (i.e. not depending on any specific version)
3.  run npm install
4.  while npm install is running open up gulpfile, gulp/copy, gulp/jade, gulp/watch.  and replace all references to jade with pug
5.  rename gulp/jade.js to gulp/pug.js
6.  Wait for install to complete and run gulp serve

My index.pug file now looks like this (complete copy):
```pug
extends _layouts/base

block content
  .container
    .yeogurt-info
      form
        input(type="text")
```
and the output is:
```html
<!DOCTYPE html><!--[if lt IE 9]>
<html class='lt-ie9 no-js' lang='en'>
<![endif]-->
<!--[if gte IE 9]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>test</title>
  <meta name="description" content="A new Yeogurt application">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="./styles/main.css">
</head>
<body><!--[if lt IE 9]>
<p class='browsehappy'>You are using an <strong>outdated</strong> browser. Please <a href='http://browsehappy.com/'>upgrade your browser</a> to improve your experience.</p>
<![endif]-->
  <div class="container">
    <div class="yeogurt-info">
      <form>
        <input>
      </form>
    </div>
  </div>
  <script src="./scripts/main.js"></script>
</body></html>
```

I am not sure if I am doing something wrong here, but as I understand it if one type is working (i.e. passwords), then text should also be working from a pug perspective?  If you test on your end you'll see that other types work, it is just text that is not working correctly.

Thank you!!

**Comment by DaClan008** [comment]
Any feedback?

**Comment by jeromew** [comment]
what version of pug are you using. According to your steps, you are installing "pug": "*", which installs pug 0.1.0. You need to use pug@2.0.0-alpha6

**Comment by jeromew** [comment]
It seems your project uses `gulp-htmlmin` which in turn uses `html-minifier` which has a `removeRedundantAttributes` option. Can you confirm you problem comes from this and close this ticket accordingly ?

I think nobody came back to you before because we nobody sees how pug could remove tamper with attributes in this way.

**Comment by DaClan008** [comment]
The pug@2.0.0-alpha6 was not the issue... but thanks for the help on this one too!!

The issue was the html-minifier - you are correct.  Thank you very much Jeromew it is back working perfectly!!

ps.  on a side note-> "upgrading to 2.0.0-alpha" I found all my includes were not working because they did not have .pug extension at the end.  I don't mind adding them now, however it was a nice feature in the previous ("*" - released) version that pug assumes your files are .pug files.  I am sure there are a reason why this feature is not there anymore and it is not a major issue.  

Thanks for all you guys' help it is really appreciated and love this package!!
