### ISSUE TITLE
Dynamic/Runtime Markdown/Filter?

### ISSUE THREAD

**Issue by polarathene** [pugjs/pug#2603]
Apologies if this has been discussed a bit, browsing through similar issues and the filter docs it seems I can only add MarkDown with a filter that takes static strings, no template variables or data provided during the render?(I'm using gulp-pug).

My specific data is a property from an array of objects to be built with a loop in pug. I'm fine with either a md string or filepath, but as neither is an option how should it be approached? Should I parse the JSON in the gulp task and replace the field with markdown converted into an html string for pug to use?

I'm not sure what is blocking filters from being dynamic and able to use data at runtime for server side rendering but is there any plans in future to extend the feature to allow this? Besides this, pug has been fantastic to use, thanks! :)

**Comment by ForbesLindesay** [comment]
Filters are compile time because this is a huge perf win when filters are used for static content (e.g. if you want coffee-script in an inline `script` tag.  The other reason is that they're not really needed if you just have a string at runtime.  You can either convert your strings to HTML in advance, or just pass a `markdown` function in as one of your locals then do:

```pug
div!= markdown(myRuntimeVariable)
```

**Comment by polarathene** [comment]
@ForbesLindesay was there any reference to passing functions in as locals to achieve functionality like this in the docs? If there isn't might be nice to point that out on the filter docs next to the warning about compile time.

If there is no problem allowing dynamic/runtime use of filters beyond perf concerns, shouldn't it be possible with an option flag to avoid the issue I'm having(I've noticed quite a few others had it too) and effectively treat it like your given solution(just without the need for a user to pass it in as a local function), with the variety of jsTransformer plugins for filters it seems silly to restrict their usage to compile time only when there isn't a real reason preventing it. 

For my use case of pug I don't need any perf wins, just the nice templating language and features, using existing filters would have been really nice. It's just a little confusing to be told we should precompile dynamically sourced data(locals) into html or via alternatives to filters outside of pug while having neat transform functions in pug only for static data embedded into the template(might as well precompile that and copy/paste?).

**Comment by pbattisson** [comment]
@polarathene did you get this working? Agreed an example would be useful - I have a dynamic string which markdown-it doesn't want to render.

**Comment by polarathene** [comment]
@pbattisson I switched to Marko which has similar syntax to pug(as well as regular html like syntax as well), it allowed me to create a js helper that parsed the markdown string into escaped html. It was very easy, I don't think pug would allow it?
