### ISSUE TITLE
Request to create a new stable release.

### ISSUE THREAD

**Issue by Abhinay077** [pugjs/pug#2610]
With jade we are facing node security issues. I request you to release a stable Pug so that we can migrate from jade to pug.

**Comment by asgoth** [comment]
Development needs to be stable first, no? :)

We are all waiting (patiently) for a new stable release, but give them some time. Lots of issues still open, so don't expect it soon(?).

**Comment by cheshrkat** [comment]
Is there a timeline/rough expectation of when pug 2.0 will be released? ie. are we talking weeks or months?

**Comment by YasharF** [comment]
Yes, would you be able to release 2.0.0 perhaps as is, and address minor bugs and other issues in 2.0.1 or later?  From my understanding, a problem is that there is currently no "stable" release of pug/jade free of dependencies with security vulnerabilities.  There are two areas that I have ran into issues with the current release condition of pug:
1. Security practices and policies in many organizations require using security patched and supported versions that also don't depend on dependencies that are vulnerable. pug 2.0.0-rc.x meets this requirement, but ... see 2 below
2. Policies for some teams and organizations that maintain very stable code require that only stable releases of dependencies are used.  An example in the open source community is ExpressJS.  ExpressJS-generator by default is still deploying jade, one of the reasons that has come up is that pug still doesn't have a stable release (https://github.com/expressjs/generator/pull/183).

Is there a checklist of deal breaking blockers that are blocking 2.0.0-rc4 to be repacked as 2.0.0?

**Comment by YasharF** [comment]
@ForbesLindesay thank you for the great work!  We know you are really busy, but any chance we can have a version 2.0 (non-rc) published soon.  Perhaps with some known bugs that are going to be fixed in version 2.0.x releases?  Since Jade is out, and pug is the replacement, we are looking forward with just an initial official release of pug.  Anything that the community can help you with to get 2.0 out?

**Comment by YasharF** [comment]
This issue can now be resolved as 2.x has been officially released.
