### ISSUE TITLE
How to create working .pug/.jade file in GitHub Repo?

### ISSUE THREAD

**Issue by noahrezentes** [pugjs/pug#2611]
Hey, maybe this is simple, but I've been trying to find an answer too long.

**Comment by ForbesLindesay** [comment]
What does "working" mean to you?  What are you actually trying to achieve.

**Comment by noahrezentes** [comment]
Just trying to use it in place of HTML on my GH Pages site.

**Comment by saviomd** [comment]
you will need to compile to html and push it
gh-pages only "autoprocess" jekyll
