### ISSUE TITLE
includes does not eval vars

### ISSUE THREAD

**Issue by cekvenich** [pugjs/pug#2622]
Here is example:

```pug
- var CON = '../../con_m/post/two/'
p #{CON + 'story2.html'}
//include #{CON + 'story2.html'}
```

Line 2 works as var.
But if I uncomment line 3 (include) it says:
   Error: ENOENT: no such file or directory, open 'post/two/#{CON + 'story2.html'
It does not eval the var on include. 

I need to specify the directory of the file via a var - for source vs dist.
I may be using it wrong. Else, the include does not eval vars.

**Comment by cekvenich** [comment]
Any update on this?

**Comment by puppetmaster3** [comment]
Just a ping.

(also if you ever list projects using pug, here is mine: https://github.com/struts3/what-demos )

**Comment by ForbesLindesay** [comment]
We don't support "Dynamic Include".  There are lots of issues people have opened about this.  It's really complex to implement and not actually nearly as useful as people think it would be.

**Comment by adamvleggett** [comment]
People open issues about this because they want it. Since they want it, it is useful. Therefore, you should consider implementing it.

**Comment by ForbesLindesay** [comment]
Please try to think about how that comment looks. Maintaining pug is not my "job", I'm a volunteer. I'm fairly confident that the most urgent requirement is documentation, not dynamic includes. Doing dynamic includes properly could easily be a couple of weeks of full time work. You don't appear to have volunteered to help in any way, you just seem to be attempting to make me feel bad about not building it for you. As a volunteer, I generally spend more time on things I enjoy, and dealing with demands from entitled people is not my idea of fun, so they significantly harm the project's progress.

**Comment by nparian** [comment]
@ForbesLindesay Thank you for all your contributions thus far.  I agree this would be a nice to have.  If possible could you please leave the request open as a "Nice to Have Feature" for future contributors?

**Comment by ForbesLindesay** [comment]
This is already being tracked in multiple places. e.g. #2030
