### ISSUE TITLE
Does Vue.js directives work with Pug.js?

### ISSUE THREAD

**Issue by felipecaldas** [pugjs/pug#2623]
Hi guys,

I just created a simple expression application and trying to use the Vue.js directives to create two-way binding and others and using Pug.js as well. This is my Pug:

```
extends layout.pug

block content
  div(class='content')
    h1(id='title') {{ message }}
    form(class="pure-form pure-form-stacked")
      fieldset
          legend A Stacked Form
          label(for="email") Email
            input(id="email",type="email", placeholder="Email")
          label(for="password") Password
            input(id="password", type="password", placeholder="Password")
          label(for="state") State
            select(id="state")
                option AL
                option CA
                option IL
          input(type='text', "v-model"="message")
          input(type="button", class="pure-button pure-button-primary", value="Sign in",  "v-on:click"='submitClick')
  script.
    var app = new Vue({
      el:'#title',
      data: {
        message : 'A Vue Message'
      },
      methods: {
        submitClick: function() {
          console.log('click');
        }
      }
      });

```

The  {{ message }} line is working but the onClick event and the v-model is not... am I doing something wrong or it doesn't work?
Thanks !

**Comment by TimothyGu** [comment]
Can you check the generated HTML? If there's anything wrong it would be in the HTML.

**Comment by felipecaldas** [comment]
Dang, that was fast. Thank you

This is the HTML:


```
<!DOCTYPE html>
<html>

<head>
    <title>Express</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/stylesheets/style.css">
    <link rel="stylesheet" href="https://yui-s.yahooapis.com/pure/0.6.0/pure-min.css">
    <link rel="stylesheet" href="https://yui-s.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
    <script src="https://unpkg.com/vue@2.1.3/dist/vue.js"></script>
</head>

<body>
    <div class="content">
        <h1 id="title">{{ message }}</h1>
        <form class="pure-form pure-form-stacked">
            <fieldset>
                <legend>A Stacked Form</legend>
                <label for="email">Email
                    <input id="email" type="email" placeholder="Email">
                </label>
                <label for="password">Password
                    <input id="password" type="password" placeholder="Password">
                </label>
                <label for="state">State
                    <select id="state">
                        <option>AL</option>
                        <option>CA</option>
                        <option>IL</option>
                    </select>
                </label>
                <input type="text" v-model="message">
                <input class="pure-button pure-button-primary" type="button" value="Sign in" v-on:click="submitClick">
            </fieldset>
        </form>
    </div>
    <script>
        var app = new Vue({
            el: '#title',
            data: {
                message: 'A Vue Message'
            },
            methods: {
                submitClick: function() {
                    console.log('click');
                }
            }
        });
    </script>
</body>

</html>
```

**Comment by TimothyGu** [comment]
I'm not too familiar with Vue, but does the HTML itself work?

**Comment by felipecaldas** [comment]
The HTML is rendering ok. I am wondering if this has to do with when the Pug.js templating takes action and when VueJs bindings take action? Like one is happenning before the other so the DOM is not getting updated? I don't know.

I used VueJs without any templating package and it worked just fine. but it would be awesome if it could work with Pug too coz Pug is great =]

**Comment by TimothyGu** [comment]
If the generated HTML work, then unfortunately I don't think we can help you. Pug templating generates an HTML; it doesn't do anything other than that like DOM.

**Comment by felipecaldas** [comment]
Hi Timothy. I got this working. Indeed, I made a mistake. The view "el" element was poiting to the wrong wrapping Div and thats why Vue couldnt find my directives.

Thank you so much for your time

**Comment by ankush981** [comment]
This discussion helped me quell my fears as well! :+1:

**Comment by foolishchow** [comment]
Is there any config that can make  `pug.comfile` do not add default attribute value?

the problem i've met is 
```pug 
a.index-category(v-press)
```
after compile ,pug give this
```html
<a class="index-category" v-press="v-press"></a>
```
but correct would be
```html
<a class="index-category" v-press></a>
```

**Comment by droooney** [comment]
@foolishchow, you're looking for the `doctype` option ([reference](https://pugjs.org/api/reference.html)). Just use `html` doctype in this case.

**Comment by MonoStas** [comment]
@foolishchow, maybe you are looking for `a.index-category(v-press='')`

**Comment by luckyjavid** [comment]
If the doctype is html, Pug knows not to mirror the attribute, and instead uses the terse style (understood by all browsers).
doctype html

input(type='checkbox' checked)
