### ISSUE TITLE
Class attributes with string object

### ISSUE THREAD

**Issue by mattidupre** [pugjs/pug#2624]
I noticed that Pug does a nifty job interpreting the class attribute when the type is not a string primitive:

```div( class=['val1', 'val2'] )```
 ```
<div class="val1 val2"></div>
```

```div( class={ key1: 'val1', key2: 'val2' } )```
```
<div class="key1 key2"></div>
```

However, I noticed the following:

```div( class=(new String('val')) )```
```
<div class="0 1 2"></div>
```

Any chance we could add a type check for string objects?

My use case is that I'm attaching methods to the string object to simplify BEM syntax. This way, I can do something similar to the following:

```div(class=block('foo')) : div(class=block('foo').element('bar'))```
```
<div class="foo">
   <div class="foo__bar"></div>
</div>
```

(For now, I'm just returning an array with a single element and attaching my methods to that. It works, but it's dirty.)

**Comment by ForbesLindesay** [comment]
I'm afraid there's no good way to fix this without breaking other, much more common use cases.  We actually support three different types for classes:

1. strings
2. Arrays of strings
3. objects that map strings onto true or false

Your `String` objects are being mis-interpreted as objects mapping class names onto `true` or `false`.
