### ISSUE TITLE
sharp in html attribute makes template parse error

### ISSUE THREAD

**Issue by vadimzham** [pugjs/pug#2626]
Try to convert next html to pug:
```<div class="filter_open" #filterEl></div>```

Most oblivious way should be next:
```.filter_open(#filterEl)```
But this makes template parse error.

Working example below: 
```.filter_open(#filterEl='')```
But this code is not oblivious and not short.

**Comment by ForbesLindesay** [comment]
Pass the `{doctype: 'html'}` option to default to the short form for boolean attributes.  Also make sure you're using the latest version of pug.

**Comment by vadimzham** [comment]
Here are too much solutions that using templates that practically only parts of html(sure, without doctype). Angular using it(just for example).

I think, adding possibility to configure pug templates out of pug templates(adding config file in the root of the project polder, like tsconfig/postcssconfig) will be best solution in this  case. You will keep default settings untouched but it will be possible to customize it for all templates.

I see the next solution: be possible to define custom config file in the first row in the pug file.

**Comment by ForbesLindesay** [comment]
Configuration is out of scope for pug core.  The gulp, grunt etc. plugins all support some way of passing config options like the doctype.
