### ISSUE TITLE
Support for ES6 template strings as variable interpolation

### ISSUE THREAD

**Issue by 19majkel94** [pugjs/pug#2633]
As we now have ES6 template strings in Attribute Interpolation , it's really annoying to switch between `#{variable}` and `${variable}` syntax.
Is it possible to use ES6 template strings syntax in tags body? Like:
```pug
h1 Hello, ${name}!
```
Instead of:
```pug
h1 Hello, #{name}!
```
I tried weird combination like:
```pug
h1 `Hello, ${name}!`
```
But it's not working at all 😞

**Comment by MistaTwist** [comment]
You can use a variable is the way you want, then put that in the tag:

`- var text = `Hello, ${name}`;
h1=text`

Is that what you were hoping to do? Hope I've understood your issue correctly!

**Comment by MistaTwist** [comment]
Hi again,

You can also make a one-liner from the above:

`` h1=`Hello, ${name}` ``

**Comment by 19majkel94** [comment]
The `=` was the missing part in my failed experiments. Thanks!
