### ISSUE TITLE
How to pass a variable into a function?

### ISSUE THREAD

**Issue by abenf-76** [pugjs/pug#2636]
Hi,
I want to output 
`<meta name="date" content="2016-12-10T00:00:00+02:00">`
where the string behind 'content' should be given with a variable
I tried this but failed:
`meta(name='date', content=#{myvar})`
`meta(name='date', content='#{myvar}')`
I am pretty much sure there is a very easy solution on this but my JS experience might be little.

**Comment by jbsulli** [comment]
Should be able to do:
```
meta(name='date', content=myvar)
```
[Attributes are just regular JavaScript.](https://pugjs.org/language/attributes.html)

**Comment by abenf-76** [comment]
Thanks a lot! That's really easy!
