### ISSUE TITLE
Commenting with multiline attributes

### ISSUE THREAD

**Issue by skyrpex** [pugjs/pug#2637]
I'm not sure if this is intented, but this example gives an error when compiling to HTML:

```pug
//- input(
    class="form-control",
    type="text",
)
```

The last line (`)`) is not successfully commented. This should be commented too, even the parenthesis not being indented, don't you think?

Edit: another reason for it to work is that this example actually works well (seems inconsistent behavior to me):

```pug
div(
    class="test"
)
    p Test
```

Regards!

**Comment by ForbesLindesay** [comment]
I think it's better for us to be consistent and only comment out things that are indented within the comment.  I would simply write:

```pug
//- 
  input(
    class="form-control",
    type="text",
  )
```
