### ISSUE TITLE
Problem with switch doctype

### ISSUE THREAD

**Issue by woneob** [pugjs/pug#2638]
I have to select a `doctype` on each page. However, if more than one `doctype` exists, 
self-close `/>` follows the doctype that was last declared.

layout:
```js
block variables

switch doctype
  when 'strict'
    doctype strict
  when 'transitional'
    doctype transitional
  default
    doctype html
```

page:
``` js
extends /layout
block variables
  - var doctype = 'strict';
```

result:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <meta charset="utf-8"> 
```

The `doctype` is in **strict** mode but `<meta charset="utf-8">` does not have self-close `/>`.

**Comment by ForbesLindesay** [comment]
doctypes are processed at compile time, so we cannot handle switching in this way.  If you need to do it, you should use the `{doctype: '...'}` option, which should override the `doctype` statement in your template.
