### ISSUE TITLE
Problem of rendering input value with express

### ISSUE THREAD

**Issue by Els-y** [pugjs/pug#2640]
Hi, I encounter some problems when I use pug as my express's view engine. However, the problem doesn't happen with jade.

as follows

when using pug,
index.pug 
```jade
input(type='hidden', value='#{token}')
```

server.js
```javascript
res.render('index', {token: 'testToken'});
```
I expect that the index.pug will be rendered to
```html
<input type="hidden" value="testToken">
```

but, I just get the result like
```html
<input type="hidden" value="#{token}">
```

---

However, when I use jade, the result is the same as I expected.
```html
<input type="hidden" value="testToken">
```

Is there a problem with my method of use?

**Comment by jeromew** [comment]
Attribute values do not accept interpolation anymore in pugjs. cf https://pugjs.org/api/migration-v2.html

you have to use

    input(type='hidden', value=token)
