### ISSUE TITLE
Space at the end of the comment

### ISSUE THREAD

**Issue by Scriptura** [pugjs/pug#2641]
Good morning,

For a long time I had noticed that it was missing a space at the end of a comment. This is still the case to date:
`<!-- test-->`
It seems to me that we should logically get this:
`<!-- test -->`
While waiting for a possible correction, I correct the output of Pug under Gulp doing this:
`.pipe( replace( /(-->)/g, ' $1' ) )`

**Comment by ForbesLindesay** [comment]
We don't attempt to generate machine readable comments.  I would prefer not to change the exact output of comments.  If you really do need this, you can always add a trailing whitespace.
