### ISSUE TITLE
Compilation of extended blocks in a condition

### ISSUE THREAD

**Issue by Scriptura** [pugjs/pug#2645]
Hello,

Since I switched from Jade to Pug I noticed that the extended blocks no longer work properly if they are inserted in a condition:

```
// PatternLayouts.pug

block var
  - name = 'Titre'
  - contentlarge = false

main(itemprop='mainContentOfPage')
  if contentlarge
    block content
      p [Default Content 1]
  else
    .section
      .wrap
        h1(itemprop='headline name').emphasized= name
        block content
          p [Default Content 2]
```

```
// index.html.pug

extends PatternLayouts

block  #var
  - contentlarge = true

block content
  [A content for index.html...]
```

If the `block content` is invoked via another file it will be displayed only for the first condition, by for the "else", in this case (if `contentlarge = true`) we will only have the default alternative display (`[Default Content 2]` ) instead of `[A content for index.html...]`.

PS: I do not know if my message is very clear: I wrote it in French and passed on in an automatic translation ...

**Comment by Tiliavir** [comment]
might duplicate https://github.com/pugjs/pug/issues/2367

**Comment by Scriptura** [comment]
Right, thank you. So I see that it is real bug ...
