### ISSUE TITLE
"#{ anything }" is unknown in pug template

### ISSUE THREAD

**Issue by fengxinming** [pugjs/pug#2646]
For example:
a(href='#{contextPath}/test.html')  => <a href=''#{contextPath}/test.html"></a>

Why isn't it different with Jade template? I tried changing extension of Jade file, but those marks not worked in Pug template

The version of NodeJs is v6.9.1

**Comment by Tiliavir** [comment]
from https://github.com/pugjs/pug/issues/2305 section "Removed/Changed syntax":
>[old:]
> a(href="#{link}")
>a(href='before#{link}after')	a(href=link)
> [new:]
>a(href=`before${link}after`) (on Node.js/io.js ≥ 1.0.0)
>a(href='before' + link + 'after') (everywhere)	We removed support for interpolation in attributes since it was unnecessarily complex in implementation and tended to delay users learning that they can just use any JavaScript value in place of attributes

**Comment by fengxinming** [comment]
@Tiliavir I really hope you restore interpolation to be used because it's really easy to be learned, you need to provide a option for letting us who set up interpolation function. If not, we rarely can't migrate jade to pug2, you know we have more thousand of jade files in our project.

**Comment by Tiliavir** [comment]
I'm not part of this project, i was just citing another issue.

**Comment by jeromew** [comment]
@fengxinming regarding the 

````
a(href=`before${link}after`)
````

notation, you need to have the backticks to have the ES6 template mechanism.

I don't think attribute interpolation will be provided in pug2 (even via an option). It is going to be painful for some codebases that rely heavily and we are sorry about that. We think the choice was made for good reasons.

**Comment by ForbesLindesay** [comment]
It would be great if we could write a "pug-migration" tool that could use the `pug-lexer` to search for attribute values, and then convert them to either plain values (in the case of `href="#{value}"`) and ES6 template literals (in the case of `href="#{value}/something.html"`)

**Comment by fengxinming** [comment]
@jeromew 真的非常感谢您
