### ISSUE TITLE
Tag interpolation inside filter text?

### ISSUE THREAD

**Issue by jbsulli** [pugjs/pug#2647]
I am having tag interpolation being parsed inside filter text? Is this supposed to be happening?

For example, the following pug:

```pug
:test
    | test #[span this].
```

results in the test filter receiving `| test .` and the rendered output being the same (if the filter is just a pass through function. Ex: `function testFilter(value){ return value; }`).

Would this be a bug?

**Comment by jbsulli** [comment]
Normal interpolation is handled the way I would expect:

```pug
:test
    | test #{test}.
```

The filter received `| test #{test}.`.

And this is with pug@2.0.0-beta6.

**Comment by ForbesLindesay** [comment]
Yes, I think this is a bug.  `#[...]` style interpolation should probably just be ignored inside filters.

**Comment by jbsulli** [comment]
Just submitted a pull request for a fix ([https://github.com/pugjs/pug-lexer/pull/75](https://github.com/pugjs/pug-lexer/pull/75)). I'm a little new to contributing so let me know if there is anything else you want done.

Thanks for all your hard work on Pug! I love it.

**Comment by jeromew** [comment]
I happen to hit a similar issue on both jade & pug and I realize I have a big misunderstanding about filters.

My previous mental model was:

**Comment by ForbesLindesay** [comment]
I agree, we should just consider this a breaking change.

Currently I can't think of any cases where we'd want to enable one but not the other.

**Comment by jeromew** [comment]
should be fixed in pug@2.0.0-beta11
