### ISSUE TITLE
No Try Catch Statement Support

### ISSUE THREAD

**Issue by jlissner** [pugjs/pug#2649]
More of a feature request than a bug, but it would be really nice if we could write something like
```
try
    .content= item.child.content
catch
    .content Looks like This content doesn't exist
```

instead of

```
if item && item.child && item.child.content
    .content= item.child.content
else
    .content Looks like This content doesn't exist
```

-Thanks

**Comment by jbsulli** [comment]
I've done my share of those if statements...

**Comment by austindebruyn** [comment]
I made a plugin for this here https://github.com/austindebruyn/pug-plugin-try-catch. I could contribute this back if try/catch becomes part of the language. There's a much cleaner implementation that could be written into the code generator.

**Comment by ForbesLindesay** [comment]
I don't think this is something we should add to the language just yet, although I'll be interested to see if the plugin gets wide adoption (which might change my mind).

The plugin looks mostly great, the only thing I would do differently, is in the `parse` part of the plugin, you should be able to generate three unbuffered code blocks (`try {`, `} catch (ex) {` and `}`) then just parse the tryBlock and catchBlock without actually needing to use code-gen from within your plugin.

**Comment by austindebruyn** [comment]
@ForbesLindesay That approach didn't work for me because the val of each unbuffered code block is validated through acorn (so `"try {"` doesn't fly). And if unbuffered code blocks could be assembled in that way, then this would be possible in pug:
```
- try
  h1= bad.var
- catch
  h1 busted
```

I think feature would need code-gen support to really work.

**Comment by ForbesLindesay** [comment]
Unless it's changed recently, unbuffered code blocks are not validated though acorn (only buffered ones are). And that code should work fine.

**Comment by jlissner** [comment]
- try {
  h1= bad.var
- ;} catch {
  h1 busted
- }

acorn throws an Unexpected Token error for me.

**Comment by TimothyGu** [comment]
@jlissner, that is because you need a `(err)` after `catch`.

```js
- try {
  h1= bad.var
- } catch (err) {
  h1 busted
- }
```

works just fine.

**Comment by austindebruyn** [comment]
Thanks @TimothyGu @ForbesLindesay , I updated my plugin to build those code blocks and not use codeGen.

**Comment by ForbesLindesay** [comment]
@austindebruyn you should remove the `return pug_html;` as that bit happens automatically.  Another slight issue with this, that's probably not as easy to fix, is that it's not currently all or nothing, i.e.

```pug
try
  ul
    li One
    - badFunction();
    li Two
    li Three
catch
```

Would, I think, output `<ul><li>One</li></ul>` when what you'd want it to output is the empty string.

**Comment by austindebruyn** [comment]
@ForbesLindesay The `return pug_html;` is that solves that problem - the built code looks like

`try { pug_html += function (pug_html) {` <- scopes pug_html to the tryBlock's code, so that if it breaks halfway through,nothing is appended to top-level pug_html. the function needs to return at the end to actually append anything

**Comment by ForbesLindesay** [comment]
Ah, I didn't read it carefully enough.  That's a very neatly written solution :)

**Comment by truongthai2409** [comment]
I was able to run it
.header-profile
                    - try {
                        if (Data.persion)
                            img(src=`${Data.persion}`, alt="Name").dropdown-sellect 
                        else
                            img( src=`${Data}`, alt="", srcset="").dropdown-sellect
                    - ;} catch { 
                        img(src="../../images/bg01.jpg", alt="")
                    - }

**Comment by EstevezCarlos** [comment]
In 2025 you can use `or` to prevent bad variables from breaking whole template:
```js
h1=title||'cannot read "title"'
```
Tested on Bun server.

**Comment by EstevezCarlos** [comment]
Ternary operator can serve similar role. Tested April 2025 with Bun as a server -  bun@1.2.5, pug@3.0.3:
```
- content = item?.child?.content ? item.child.content : "Looks like This content doesn't exist"
.content=content
```
