### ISSUE TITLE
Display <br> in html

### ISSUE THREAD

**Issue by khorns** [pugjs/pug#2651]
I have a problem with this `<br>` that I am pulling off from my database as a string.

```
- var text = 'first Line <br> second Line';
p #{text} 
```
I want to display this string in separate lines. The result should be: 

> first Line
> second Line

However, it renders:

`first Line <br> second Line`

Which method can _pug_ handle this problem?

**Comment by katsura-da** [comment]
I think this is what you are looking for:
https://pugjs.org/language/interpolation.html#string-interpolation-unescaped

So basically:
```jade
p !{text}
```

**Comment by jeromew** [comment]
@katsura-da's answer is correct.

do not use this on user submitted data since you will it can lead to many problems : user hijacking the layout, xss issues, ..

**Comment by khorns** [comment]
Fantastic. The exact solution I am looking for.
