### ISSUE TITLE
pro code code block special handling like Markdown

### ISSUE THREAD

**Issue by liuhuancom** [pugjs/pug#2652]
I would like to use pug to write dynamic documents
Markdown no dynamic interaction html tags also appear cumbersome
The pug is what I want but it does not markdown so well in handling formatting code

**Comment by Kingwl** [comment]
+1

**Comment by ForbesLindesay** [comment]
I think filters might do what you need.  You can use custom filters to process blocks of text within pug documents in whatever way you want to.  See: https://pugjs.org/language/filters.html

**Comment by liuhuancom** [comment]
Thank you very much
