### ISSUE TITLE
Minimize the browser pugjs size?

### ISSUE THREAD

**Issue by LeonDWong** [pugjs/pug#2653]
[Pugjs in browser](https://pugjs.org/js/pug.js) is nearly 500K.Anyway to minimize it?Thx.

**Comment by aMarCruz** [comment]
@LeonDWong , I think including the compiler in browsers is not a good idea.
Some tips:
- Use the Pug plugin for your blunder ([pugjs-brunch](https://github.com/aMarCruz/pugjs-brunch), [rollup-plugin-pug](https://github.com/aMarCruz/rollup-plugin-pug), [gulp-pug](https://github.com/pugjs/gulp-pug), etc) to avoid loading the pug compiler at runtime.
- If you know the values used by your template at compile-time, use static compilation if your plugin allows it.

**Comment by LeonDWong** [comment]
@aMarCruz It's a good idea to render pug template in server end or compile it to html by tools(like brunch, gulp, etc).But if i get a piece of pug template from server and data is in browser, i have to render them via browser end compiler.So i still try to find the way to minimize [Pugjs in browser](https://pugjs.org/js/pug.js).

**Comment by ForbesLindesay** [comment]
You can compile the template to JavaScript on the server side using pug.compileFileClient or the --client flag on the CLI.  This still lets you add the data on the client, but means you won't need the full pug compiler.

**Comment by LeonDWong** [comment]
@ForbesLindesay Thx.It's sort of tricky, but i still wonder is it impossible to minimize the size of  [Pugjs in browser](https://pugjs.org/js/pug.js)?

**Comment by ForbesLindesay** [comment]
No, it can't really be reduced in size, since it is a full compiler.  This is what allows pug to be a powerful templating language.  Even if we could reduce the file size, the compilation process is far too slow to run on every client's browser.  We also make no effort to make that code work in anything other than the latest version of google chrome.

If you need a templating language that is simple enough to build in the browser, I suggest somethign like: https://mustache.github.io/

**Comment by getflourish** [comment]
I’m still wondering: I’ve been using a v0.27 from 2012 to compile templates in browser and the jade.js back then was 42 kb and is so fast, that I can constantly re-render templates with updated options/data. It’s super simple and requires no build tools (e.g. can be used on CodePen). Is there really no way to get a similar small & fast in-browser compiler with pug.js? The 500k version works, but it’s obviously a lot slower :(

**Comment by getflourish** [comment]
I love using jade/pug in the browser for interactive demos and it makes it a great candidate for component based design tools. `jade.js` used to be 41k minified and was blazing fast to compile templates in the browser. I’m curious: why is the file size of `pug.js` 10x bigger and thus also slower?

**Comment by ForbesLindesay** [comment]
It was always slow.  We have optimised for the pre-compiled use case as that is the only way to get reasonable performance.  The trade off is that compiling on the fly is now slower.
