### ISSUE TITLE
Can I use browser?

### ISSUE THREAD

**Issue by uk-taniyama** [pugjs/pug#2655]
I cannot found pug at cdn.
So I want to build by browserify.
BUT some error occurred.

As a result of various experiments, it was solved by applying a patch to the file under "pug".
See my git for details.
https://github.com/uk-taniyama/pug-for-browser

**Comment by strugee** [comment]
I'm unclear on what you want the project to do. This is not a supported way for running Pug in the browser.

See https://pugjs.org/api/reference.html#pugcompilefileclientpath-options

**Comment by kylecordes** [comment]
The ability to execute in the browser would be a fantastic feature for Pug. One use case I would use often: a development-time compile-run cycle which executes entirely in a browser (no server side process needed), plus a production-build process that does it all in advance instead.

**Comment by ForbesLindesay** [comment]
I recommend using a build process in development.  You can use whichever build tool you want:

 - gulp
 - browserify
 - webpack
 - etc.

**Comment by jameslaydigital** [comment]
I can think of several excellent examples of why you would want to do this. First, you don't actually **HAVE** access to the server environment b/c you use a PaaS like firebase, and all your source code is static html files.  Another reason is that you're trying to use a templating engine at work but your boss doesn't want you installing more software on the server.  Perhaps your server is an IBM500 that doesn't support node, npm, or a language which has implemented pug.  I could keep going, but the point is that there are many reasons you may want to do this on the client.  My personal reason is that PHP's pug implementation is taking 3-4 seconds to render a very small pug template and I'm pretty sure it would be faster to just do it on the client.

**Comment by strugee** [comment]
@jameslaydigital did you read the link I posted above? Pug has had the ability to compile for browser usage for a long time - just not in the way OP was asking about.

**Comment by ForbesLindesay** [comment]
@jameslaydigital All the suggestions I posted could be used on the developer's machine if need be, before sending the code to a PaaS like firebase, or copying it onto corporate servers.
