### ISSUE TITLE
Unable to Extend Pug template from different directory

### ISSUE THREAD

**Issue by wsfuller** [pugjs/pug#2663]
Trying to understand how to extend templates in different directories instead of having everything flat have tried a bunch of solutions but getting errors and crawling previous SO questions isn't solving my problem.  

**Directory Structure**

    /application
      app.js
      /routes
        index.js
      /views
        index.pug
        /templates
          layout.pug
      /public
        /images
        /stylesheets
        ...

**App.js**

    var express = require('express');
    var bodyParser = require('body-parser');
    var app = express();

    var path = require('path');

    // parse incoming requests
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));

    // serve static files from /public
    app.use(express.static(__dirname + '/public'));

    // view engine setup
    app.set('view engine', 'pug');
    app.set('views', path.join(__dirname, 'views'));
    app.locals.basedir = app.get('views');

    // include routes
    var routes = require('./routes/index');
    app.use('/', routes);
    ...

**routes/index.js**

    var express = require('express');
    var router = express.Router();

    ...

    // GET /
    router.get('/', function(req, res, next) {
      return res.render('index', { title: 'Home' });
    });

    ...

    module.exports = router;

**views/templates/layout.pug**

    doctype html(lang='en')
    head
      meta(charset='utf-8')
    ...

**views/index.pug**

    extends templates/layout //error
    extends /templates/layout //error
    extends ./templates/layout //error
    extends /views/templates/layout //error
    
    h1 index page

Not sure what's different here but it seems like Express is ignoring anything prefixed to layout. `Error: forms\views\layout.pug`

Not sure why the `template` reference is being ignored. If I move the `layout.pug` into the `/views` directory it will be referenced and work perfectly.

**Comment by jbsulli** [comment]
Hm, I was able to get your code to work without an issue. The following worked for me:

**directory**
```
app.js
/views
   index.pug
   /templates
      layout.pug
```

**app.js**
```javascript
var express = require('express');
var app = express();

var path = require('path');

app.set('view engine', 'pug');
app.set('views', path.join(__dirname, 'views'));

app.get('/', function(req, res, next){
    return res.render('index', { title: 'Home' });
});

app.listen(80, function(){
    console.log('Listening on port 80');
});
```

**layout.pug**
```pug
doctype html
html(lang="en")
    head
        meta(charset='utf-8')
    body
        block content
```

**index.pug**
```pug
extends templates/layout

block content
    h1 hello world!
```

Can you confirm that this simple example works for you?

**Side note:** [`In Pug v1, if no file extension is given, .pug is automatically appended to the path, but in Pug v2 this is behavior is deprecated.`](https://pugjs.org/language/inheritance.html)

**Comment by wsfuller** [comment]
Ok, so looks like I found the problem, hopefully. Looks like the way the view engine was setup is incorrect.

* Was `app.set('views', __dirname + '/views');`
* Your code `app.set('views', path.join(__dirname, 'views'));`

I moved the routes into another directory and render the views from there. Also did a version sanity check on Express and Pug versions. `"pug": "^2.0.0-beta2"` & `"pug": "^2.0.0-beta6"` as well as `"express": "^4.13.4"` & `"express": "^4.14.0"` just to see if there was any discrepancies.

Setting up the view engine is the only difference I've found to provide any continuity in the errors I was seeing. 

As far as your side note, is the .pug appending taking effect after the beta versions? Running 2.0.0-beta6 the file extension is working as expected. 

Thanks for your help

**Comment by jbsulli** [comment]
Sweet! Glad you got it working.

Yeah, looks like pug is still appending the file extension for now. Just wanted to mention it in case you found an edge case where it does not.

You're welcome!

**Comment by wsfuller** [comment]
Appreciate the look out, was digging thought the Pug 2 migration docs. Heck of a tool, so going to implement all the new standards. Really enjoying the interpolation syntax cleans up things a lot.

**Comment by jbsulli** [comment]
Yeah, I really like the interpolation syntax as well. Gets pretty messy to do simple links, bold, span, etc. in paragraphs otherwise.

Good luck!

**Comment by wsfuller** [comment]
Thanks :) Going to close this out since it's solved
