### ISSUE TITLE
Changing the default tag from div to something else

### ISSUE THREAD

**Issue by gushogg-blake** [pugjs/pug#2665]
I have a bunch of templates that make heavy use of `<span>` and no divs, and it would be nice to be able to set the default tag to avoid typing `span` everywhere.

```jade
.foo
    .bar

# would render to: <span class="foo"><span class="bar"></span></span>
```

What do you think to adding a `defaultTag` option to API methods, defaulting to `div`?  Obviously it would change the meaning of any `include`d code as well, but for cases where you control the whole codebase I can't see it being an issue.

**Comment by gushogg-blake** [comment]
Actually I think this might be more useful if it could be set on a per-file basis by a directive within the template.

Also this particular use-case can be implemented fairly cleanly with CSS (`div { display: inline; }`)...

**Comment by ForbesLindesay** [comment]
No, consistency is more important than the perception of convenience here.  Defaulting to any tag already adds significant risk of making code harder to read, making it not always the same tag would make things 10x worse.
