### ISSUE TITLE
What is the npm package `gulp-pug2`

### ISSUE THREAD

**Issue by rekomat** [pugjs/pug#2667]
I spent quite some time today solving a problem passing JSON data to Pug templates until I found out I was using a strange npm package. `gulp-pug2`instead of `gulp-pug`. Exchanging the packages solved all my issues. 

`gulp-pug2` isn't an "official" package, right?!

**Comment by ForbesLindesay** [comment]
gulp-pug2 is not official.  The official package is gulp-pug and you can open issues for any problems you were experiencing at https://github.com/pugjs/gulp-pug/issues  You can also submit pull requests if there are improvements in gulp-pug2 that should be in gulp-pug.  Feel free to ping me if you have problems finding someone to review your pull requests.
