### ISSUE TITLE
Plain text pipe ("|") syntax does not support blank lines

### ISSUE THREAD

**Issue by joliss** [pugjs/pug#2672]
I was surprised to find out that you cannot use the pipe syntax (`|`) for blank lines. The following code:

```
pre
  | foo
  | 
  | bar
```

yields an error:

```
test.pug:3:3
    1| pre
    2|   | foo
  > 3|   |
---------^
    4|   | bar
    5| 

unexpected text "|
  |"
```

I'm guessing the lexer or parser could be adjusted to allow for this?

**Comment by ForbesLindesay** [comment]
Yes, this looks like a bug.  An extra test & pull request to the lexer would be much appreciated.

**Comment by TimothyGu** [comment]
Current, you need a space after the `|` to make it recognize the line as text. The [code in lexer](https://github.com/pugjs/pug-lexer/blob/035c891823b2193121421dc3db660810deac6b3e/index.js#L539-L540) specifically excludes `|` without a space after it. The offending regex was first added in #1587.

**Comment by ForbesLindesay** [comment]
I think we should only require the space if there is at least one character of text.

**Comment by TimothyGu** [comment]
@ForbesLindesay, currently it's just the opposite: you don't need a space before text for it to work, but you _do_ need a space after `|` if there is no text for it to work.

```pug
//- works
| a
|a
|_

//- doesn't work
|
```

**Comment by ForbesLindesay** [comment]
Oops, I'm pretty sure that's the opposite of what I intended it to be.

**Comment by kylekatarnls** [comment]
Hi, is someone assigned to this task? I probably could propose a pull request and unit tests.

**Comment by ForbesLindesay** [comment]
@kylekatarnls. Obody is working on it (as far as I'm aware) if you'd like to submit a pull request, that would be awesome.

**Comment by kylekatarnls** [comment]
This is my humble proposal; #79 One more regex  but it seems to me the more simple way.

**Comment by ForbesLindesay** [comment]
I'm about to release @kylekatarnls's fix for this.

**Comment by kylekatarnls** [comment]
Glad to see that. I can no longer wait for a stable release of Pug and if I can help some more, please let me know!
