### ISSUE TITLE
Support for Polyglot (X)HTML

### ISSUE THREAD

**Issue by Skrupellos** [pugjs/pug#2673]
Please support [Polyglot](https://en.wikipedia.org/wiki/Polyglot_markup) [HTML](https://dev.w3.org/html5/html-polyglot/html-polyglot.html).

This basically means: Use XML output for elements, even though `<!DOCTYPE html>` is outputted. I can think of three possibilities to do so:
1. Something like `doctype polyglot`.
2. A `xml` render option for the API, which creates XML output even though `doctype html` was found (more flexible than 1).
3. Specify doctype and tag-rending with the `doctype` keyword (e.g. `doctype xml html`) or a separate keyword (e.g. `doctype html` and `render xml`).
This would be even more flexible.

## An example
Input (pug):
```pug
doctype polyglot

html(xmlns='http://www.w3.org/1999/xhtml' lang='' xml:lang='')
  head
    meta(name='viewport' content='width=device-width, initial-scale=1.0')/
    title test

  body
```

Output (HTML):
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>test</title>
  </head>

  <body>
  </body>
</html>
```

**Comment by ForbesLindesay** [comment]
I don't see any reason for perusing this.  All modern web pages should be authored using HTML, not some abandoned w3c spec from 2004.

**Comment by lmmarsano** [comment]
Don't know how serious the comment was, but the XML syntax of HTML is _not_ abandoned.
- [Appears in the current spec](https://html.spec.whatwg.org/multipage/xhtml.html#the-xhtml-syntax)
- [Is strongly supported](https://caniuse.com/#feat=xhtml)

Some reasons to support it:
- code reuse: allows bringing XML APIs and technologies to bear
  - XPath, XQuery, XSLT, etc, become available; developers suddenly have more tools in their toolbox to tackle unexpected problems
- some stagnant institutions using content management systems that only serve XHTML
  - employees with little choice in the matter have to work around their institution's limitations
  - pug could bring them relief in these repetitive struggles
- HTML compatibility
