### ISSUE TITLE
watch mode cannot render new .pug files in the directory once the command started.

### ISSUE THREAD

**Issue by DevChache** [pugjs/pug#2674]
I'm using pug cli tools in vs code's internal bash.
Usually when I use `pug -w -P jade/ -o .`, I leave the terminal behind and continue my works on pug templates. It works fine when I save changes to the .pug files created before using "pug -w" command, but fails to recognize files I created after the command.

**Comment by ForbesLindesay** [comment]
Thanks for reporting this, could you please open this issue on https://github.com/pugjs/pug-cli instead.
