### ISSUE TITLE
unable to install pug using npm

### ISSUE THREAD

**Issue by gdams** [pugjs/pug#2683]
I am unable to install pug using the npm release:
https://github.com/pugjs/pug/archive/pug@2.0.0-beta7.tar.gz

It would appear that npm doesn't like the `@` in the tag. This is also an issue with running pug in citgm as this is how citgm downloads the modules.

To recreate:
`npm install https://github.com/pugjs/pug/archive/pug@2.0.0-beta7.tar.gz`

**Comment by ForbesLindesay** [comment]
You need to install it from npm, not GitHub:

    npm install pug@2.0.0-beta7

**Comment by gdams** [comment]
This is going to be an issue if you wish to remain in the module lookup of citgm though, citgm is designed to pull the latest tag from github

**Comment by ForbesLindesay** [comment]
This is being discussed separately in #2684.  citgm has the only legitimate use case for installing from GitHub, since they want to run the tests, not actually install the package.
