### ISSUE TITLE
ES6 fat arrow in latest published version

### ISSUE THREAD

**Issue by davidminor** [pugjs/pug#2688]
There's an ES6 'fat arrow' function in the latest published version - any chance you can change this to a regular function to make it easier to use pug in codebases stuck on older versions of node?

(in pug-linker - just realized this isn't a separate repo now)

**Comment by ForbesLindesay** [comment]
Yes, do you feel like submitting a pull request?

P.S. You are using a dangerously out of date version of npm if it does not support arrow functions.  This puts users of any of the systems you run a serious risk. Upgrading to at least version 4 should be your top priority.

**Comment by davidminor** [comment]
Sure - made a pull request: #2691

RE node version - yes, ironically pug is part of our effort to remove another dependency that's holding us back.

**Comment by ForbesLindesay** [comment]
As it happens, we needed this change anyway to support the in browser version of pug we use in the documentation.
