### ISSUE TITLE
Dealing with classes in custom components

### ISSUE THREAD

**Issue by kostacoffee** [pugjs/pug#2689]
Considering the spec for [custom components and their naming](https://www.w3.org/TR/custom-elements/#prod-potentialcustomelementname) has been out for a few months, there is an issue that needs to be addressed:

A custom component can contain full stops `.` in its tag name. How should pug deal with this?

**Comment by ForbesLindesay** [comment]
I have no plans for pug to handle `.` in tag names at this time.
