### ISSUE TITLE
Errors after installing pug.

### ISSUE THREAD

**Issue by wmsrite** [pugjs/pug#2690]
I installed pug, uninstalled Jade, renamed the extensions and set the view engine in app.js to pug. Now, when I got to localhost:3000 i get these errors throws:
```
Error: No default engine was specified and no extension was provided.
   at new View (/Users/wmsrite/Dev/kayla/node_modules/express/lib/view.js:62:11)
   at EventEmitter.render (/Users/wmsrite/Dev/kayla/node_modules/express/lib/application.js:569:12)
   at ServerResponse.render (/Users/wmsrite/Dev/kayla/node_modules/express/lib/response.js:961:7)
   at /Users/wmsrite/Dev/kayla/app.js:53:7
   at Layer.handle_error (/Users/wmsrite/Dev/kayla/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/Users/wmsrite/Dev/kayla/node_modules/express/lib/router/index.js:310:13)
   at /Users/wmsrite/Dev/kayla/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/wmsrite/Dev/kayla/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/wmsrite/Dev/kayla/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/Users/wmsrite/Dev/kayla/node_modules/express/lib/router/layer.js:73:5)
```

**Comment by ForbesLindesay** [comment]
You need to do:

```js
app.set('view engine', 'pug');
```

You would have previously needed to do:

```js
app.set('view engine', 'jade');
```

This sets the default file extension for your templates.

**Comment by wmsrite** [comment]
Yeah, I've done thAT IN APP.JS

**Comment by wmsrite** [comment]
sorry bout the caps

**Comment by wmsrite** [comment]
here's index.pug:
`html
  head
    title= title
  body
    h1= message
  `

and index.js

`var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index.pug', { title: 'Express' });
});

module.exports = router;
`
and app.js(part of it):
`var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', "pug");

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', routes);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers
`

**Comment by ForbesLindesay** [comment]
The stack trace seems to indicate the problem is at: `/Users/wmsrite/Dev/kayla/app.js:53` but you don't look to have included the `res.render` call on that line in this snippet.

P.S. Which version of pug have you installed.  Make sure you install the latest version:

```
npm install pug@2.0.0-beta9 --save
```

**Comment by wmsrite** [comment]
after i install the latest beta pug, will npm install upgrade my dependencies in package.json or do i have to do it manually?

**Comment by ForbesLindesay** [comment]
If you use the command above, it updates package.json.  You shouldn't be installing pug globally as that won't work.
