### ISSUE TITLE
Uncaught syntax error. unexpected token

### ISSUE THREAD

**Issue by bastet77** [pugjs/pug#2694]
Why does the following pug script not work. In the browser developer tools I get the console message >Uncaught syntax error. unexpected token <

test.js just has a bunch of comments. 

Package has 
"pug":"2.0.0-beta9",
"pug-loader":"<=1.0.2"

Any help would be greatly appreciated.

Ed

 ```pug
doctype html
html
   head        
        script(src='/javascripts/test.js')
    body
        p hello
```

**Comment by ForbesLindesay** [comment]
There's not enough info here to reproduce.  Please provide:

1. a stack trace
2. all the code needed to reproduce the error (you could publish this as a GitHub repo or inline in this issue).

Please format code blocks using [GitHub Flavoured Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) when posting GitHub issues.

**Comment by bastet77** [comment]
How do I do a stack trace in pug? Sorry to ask but I have looked at the documentation and I can't see any mention of a trace.

**Comment by ForbesLindesay** [comment]
How did you get the error message?  How are you rendering pug?  I'm not asking for a pug stack trace, I'm asking for the JavaScript stack trace.
