### ISSUE TITLE
Class modifiers for mixins

### ISSUE THREAD

**Issue by sposhe** [pugjs/pug#2699]
This is a feature request.

It would be great if mixins could have class modifiers that would pass through to the contents of the mixin—in the same way mixins can receive block content.

For instance, when building a menu, this—

```
mixin li(href, title)
  li(class= classes)
    a(href= href) #{title}

nav
  ul
    +li('/', 'Home').large
    +li('/about', 'About').large.active
    +li('/contact', 'Contact')
```
—would compile to—
```
<nav>
  <ul>
    <li class="large">
      <a href="/">Home</a>
    </li>
    <li class="large active">
      <a href="/about">About</a>
    </li>
    <li>
      <a href="/contact">Contact</a>
    </li>
  </ul>
</nav>
```
I'm sure there's a more semantic way to add this functionality, but it would be great to not have to continually add class parameters to mixins and include big strings.

**Comment by ForbesLindesay** [comment]
You can't easily restrict it to just classes, but the following will produce exactly the output you're asking for:

```pug
mixin li(href, title)
  li&attributes(attributes)
    a(href= href) #{title}

nav
  ul
    +li('/', 'Home').large
    +li('/about', 'About').large.active
    +li('/contact', 'Contact')
```

**Comment by sposhe** [comment]
:100: You're the best!
