### ISSUE TITLE
escaping accented chars

### ISSUE THREAD

**Issue by pdepmcp** [pugjs/pug#2704]
I'm not sure if it's a bug or I'm missing something, as I'm quite new to pug.

I have a mixin that takes a parameter, which may containt special characters, in particular I use accented letters. 
The mixin is like this:

```pug
mixin collapsable(questiontitle,blockid,accordionparent)
    .paneltitle.panel
        a.collapsed(href= hashedid, data-toggle="collapse" data-parent= accordionparent)
            p= questiontitle
                block
```
And I call like this:
```pug
+collapsable("Chi può guidare il veicolo?","q1","questionbox")
   | some text inside...
```

My problem is this:
if I pass in "questiontitle" a "ò" it prints "ò", and this leads me to an encoding nightmare. 
If i pass in the escaped char ( "&ograve; or "&#242;"), pug escapes the "&" and the resulting string is "broken"
Is it possible somewhere to tell pug to escape ALL known entities? 
What is the alternate way to print the title forcing a complete non escape of chars so that I can pass in the escaped char? I tried some combinations of #{questiontitle}, "#{questiontitle}", but I was not able to guess how to do it. 

thanks

**Comment by ForbesLindesay** [comment]
Pug is correct not to escape the `ò` character.  What you need to do is ensure that your output is utf8 encoded.  If your web-server is not configured to send the correct header to indicate that the content is in utf8, you can override it by adding the following as the **first** item inside the `head` block of your template:

```pug
meta(charset='utf-8')
```

e.g. https://github.com/esdiscuss/esdiscuss.org/blob/3b117ab9aff91f2b7e28dd2fc32c5bf4276cbded/views/layout.pug#L4
