### ISSUE TITLE
Conditional statement with variable value?

### ISSUE THREAD

**Issue by xstortionist** [pugjs/pug#2716]
Any clues as to what I'm doing wrong here.

```
mixin btn(url, text, type)
	- var btnType = type;

	if btnType = button
		button(type="button")&attributes(attributes)= text
	else
		a(href=url)&attributes(attributes)= text

+btn('#', 'This Is Button', 'button').btn.btn-primary
```

That should output button but instead it outputs A href tag.

`<a class="btn btn-primary" href="#">This Is Button</a>`

**Comment by TimothyGu** [comment]
```pug
if btnType === 'button'
```

is probably what you want.

**Comment by ForbesLindesay** [comment]
Yes, single `=` means "assignment".  You need either `===` (strict equality) or `==` (sloppy equality).  This is a JavaScript thing, rather than a specifically pug issue.

**Comment by xstortionist** [comment]
Thank you both. that worked.

**Comment by ogrotten** [comment]
`if val === 'content'` should be on the Conditionals documentation. The examples only use booleans and therefore only looks like it'll work with booleans.

**Comment by ForbesLindesay** [comment]
@ogrotten could you send a pull request to improve the documentation?

https://github.com/pugjs/pug-en/blob/master/src/language/conditionals.md

**Comment by ogrotten** [comment]
I just started with pug y'day and had several questions that weren't in the docs. So I'll write for a bit. I didn't realize that https://pugjs.org/language/ was accessible here.

**Comment by ogrotten** [comment]
@ForbesLindesay submitted!

**Comment by ForbesLindesay** [comment]
Thanks for the pr @ogrotten, awesome work :)
