### ISSUE TITLE
TypeError in plugin 'gulp-jade-php'

### ISSUE THREAD

**Issue by badoubadou** [pugjs/pug#2722]
Message:
    code.replace is not a function

Since I changed my computer, I can't run my gulp project. gulp-jade-php crash and don't give much information about why. 
I already uninstall and re-install gulp-jade-php, but same error again. 
Any help ?

**Comment by ForbesLindesay** [comment]
We do not maintain that package.  You should post questions on https://github.com/oroce/gulp-jade-php
