### ISSUE TITLE
Lorem generator

### ISSUE THREAD

**Issue by Inst4nt-Fisherm4n** [pugjs/pug#2723]
Does PugJs has lorem generator? For example like in the Emmet:
`lorem3` transrorm to _Rutrum tellus pellentesque._
or
`lorem5` transform to _Lacus, sed viverra tellus in!_
I think it's nice tip. Especially if may be set random lorem words:
`lorem{rand(3)}`

**Comment by ForbesLindesay** [comment]
Probably, but stackoverflow.com would be a better place for this question.
