### ISSUE TITLE
Using "@" in a class name won't compile.

### ISSUE THREAD

**Issue by jonathanrbowman** [pugjs/pug#2724]
I'm trying to use inuitcss as a layout framework, and they do class names with an "@" symbol in them to indicate media query breakpoints. This breaks pug on compile, though.

**Comment by ForbesLindesay** [comment]
If your class names contain special, symbols, you can't use the class name shorthand, you can write it out long hand though:

```pug
div(class="some@class@name")
```

**Comment by SimonPadbury** [comment]
Hi,

Maybe you'd be interested in a new pug/sass/coffeescript framework I've been working on. 

https://github.com/SimonPadbury/Codebase

It's needing some snagging before I properly launch it, but the grid is ready to go.

**Comment by jonathanrbowman** [comment]
Oh, thanks so much for responding and I can't believe I didn't think to try it that way - much appreciated!
