### ISSUE TITLE
whitespace char after/before piping 

### ISSUE THREAD

**Issue by zsitro** [pugjs/pug#2727]
```
p Link goes
  a(href="#") here
  | then whitespace missing before `then`.

//yields:
<p>Link goes <a href="#">here</a>then whitespace missing before `then`.</p>
```

What is the suggested solution besides adding `&nbsp;then`?

I wrote here (not on SO) because I suggest it's an issue with the compiler since I expect the whitespace after the pipe.

**Comment by jwgoh** [comment]
You could add an [empty pipe](https://pugjs.org/language/plain-text.html#recommended-solutions)
