### ISSUE TITLE
#{} / !{} does not convert in string literal.

### ISSUE THREAD

**Issue by ebi-hama** [pugjs/pug#2729]
I try to change from jade to pug.
But pug cannot convert #{}/!{} in string literal.

- var version = '1.1'
script(src='/path/to/script-#{version}')

I want => <script src="/path/to/script-1.1"></script>
I got => <script src="/path/to/script-#{version}"></script>

**Comment by TimothyGu** [comment]
See https://pugjs.org/api/migration-v2.html#attribute-interpolation
