### ISSUE TITLE
Migration from jade to pug

### ISSUE THREAD

**Issue by Pittan** [pugjs/pug#2730]
Hello.
I have a project that is fully written in jade.
I'm trying to migrate this project to pug.

Here is a jade/pug source. 
`div.hogeclass(ng-controller="hogeController as hogeCtrl")`

When I use jade for compile, the result becomes
`<div class="hogeclass" ng-controller="hogeController as hogeCtrl"></div>`
and pug,
`<div ng-controller="hogeController as hogeCtrl" class="hogeclass"></div>`

I want to make this migration without making any diffs in result.
Is there a way to do this? 🐶 🐕

**Comment by qm3ster** [comment]
You can use a html post-processor to sort attribute order. The project never made any guarantees about the order of attributes, and continuously moves in the direction of externalizing the pretty-printing of output.

**Comment by ForbesLindesay** [comment]
No, we don't offer any way to avoid this change.

**Comment by Pittan** [comment]
Well... that's okay :) Thanks for your response ✨
