### ISSUE TITLE
Html entity compile error (unexpected token)

### ISSUE THREAD

**Issue by adi518** [pugjs/pug#2731]
`button#player-next(class="btn btn--player" title='next')&#187;&nbsp;next`

Compile error: `unexpected text "{'&#1"`

This just won't work anymore. I had a slightly earlier version of `pug`, but moved my project to a new repo and now I'm using `2.0.0-beta11` where it simply won't compile. Looking at the docs, I couldn't find a clear solution, sorry if I missed it somehow.

**Comment by ForbesLindesay** [comment]
You must add a space before the content of the button.  e.g.

```js
button#player-next(class="btn btn--player" title='next') &#187;&nbsp;next
```
