### ISSUE TITLE
Extend & include automatically append .pug

### ISSUE THREAD

**Issue by qm3ster** [pugjs/pug#2734]
In the [Docs](https://pugjs.org/language/includes.html) for these two features, it is said this is depreciated.
However, in `2.0.0-beta11` it still works without console warnings.
As mentioned in https://github.com/pugjs/pug/issues/2305#issuecomment-211321404, this means we can not use files without extension.

Personally, I would like this feature to remain, cleaner syntax in multiple places + properly named files that get editor icons are a clear winner over extensions in multiple files and unidentified text files. In fact, that strategy worked so good that moving from jade required only renaming files without touching the contents. So, I vote the documentation be updated accordingly.

**Comment by ForbesLindesay** [comment]
The suggestion isn't that you should remove the `.pug` extension from your file names.  The suggestion is that you should **add** `.pug` to the end of your `include` and `extends` statements.

It is true that this is not actually deprecated though.  You could submit a pull request to remove the statement from our documentation in https://github.com/pugjs/pug-en

**Comment by qm3ster** [comment]
Done: https://github.com/pugjs/pug-en/pull/13 Not sure if I am supposed to close it since it isn't merged yet. Please advise for future reference.

And yeah, that's what I wanted to avoid:
I would much rather keep getting away with not putting the extension in the statements inside file-text than have someone bring to life their perverse desire to include extensionless files.
