### ISSUE TITLE
[pug-parser]: incorrect unexpected token error

### ISSUE THREAD

**Issue by petebacondarwin** [pugjs/pug#2735]
The following piece of pug causes an error in the parser. (It is parsed fine using jade 1.11.0)

```
td(style="vertical-align: top")<a id="some-id"></a>Some content
```

The error message is:

> Unexpected token `text-html` expected `text`, `interpolated-code`, `code`, `:`, `slash`, `newline` or `eos`

Putting a whitespace before the anchor element stops the error but I believe that this is a bug in the parser. Why should `text-html` not be allowed at this point?

**Comment by ForbesLindesay** [comment]
You just have to add a space before the anchor tag.  This is expected as it is plain text after a tag.  I guess the error message could at least be improved though.

**Comment by petebacondarwin** [comment]
Hi @ForbesLindesay - thanks for commenting on this issue.

Yes I understand that I can add a whitespace to make it work. I mentioned this in the original issue.

But I believe that this is a regression from the Jade parser for which this is accepted. I have a large corpus of Jade files that I do not have control over, which use this syntax. So I cannot just go and change all such occurrences.

**Comment by ForbesLindesay** [comment]
This was an intentional breaking change.  Old versions of jade allowed you to omit the space in certain arbitrary circumstances.  This has produced a warning for a long time now, even in jade.  We just recently made the warning into an error.

**Comment by petebacondarwin** [comment]
OK. Thanks.
