### ISSUE TITLE
include:filter ability not widely documented.

### ISSUE THREAD

**Issue by qm3ster** [pugjs/pug#2737]
```pug
include:markdown-it test.md
```
As you can see, this is not highlighted (at the time of posting) above, it is not represented on the [Filters](https://pugjs.org/language/filters.html) doc page or in README.md. The only place it can be found except tests is the [Includes](https://pugjs.org/language/includes.html) doc page.

**Comment by ForbesLindesay** [comment]
Perhaps you could send a pull request to https://github.com/pugjs/pug-en to add a comment about them on the fitlers page, linking to the includes page.

**Comment by qm3ster** [comment]
Done. https://github.com/pugjs/pug-en/pull/12
Looks a little bare, but I understand duplicating the example isn't great either.
Question: who is in charge of the writing style of the docs? In the paragraphs adjacent to the one I added, there was `one can` used vs `you can` and both active and passive voice, so I was not sure how I should write myself.
