### ISSUE TITLE
pug is ugly

### ISSUE THREAD

**Issue by lindwaltz** [pugjs/pug#2738]
I like beautiful things. Pug is a word associated with ugliness, as in 'pug-ugly' etc. I love jade. For this past six months I've cringed every time I had to visit the pugjs website. I still name all files as '.jade' instead of '.pug', because it's too ugly.

Please rename pug - for me this is so important that I cannot use pug, which is sad, because I really love jade ;(

**Comment by lindwaltz** [comment]
this is too much to ask I guess, I don't want to start a flame war... closing...

**Comment by ForbesLindesay** [comment]
Please do not post in our issue tracker in future.
