### ISSUE TITLE
Printing a list of items inside filter()

### ISSUE THREAD

**Issue by caneta** [pugjs/pug#2740]
To print a list of even items using a JavaScript for loop is straightforward:
```
- var numbers = [1, 2, 3, 4, 5];
- for(var i = 0; i<numbers.length; i++)
  - if(numbers[i]%2===0)
      div Number #{numbers[i]}
```
But is there a way to do that with `filter()` or other JavaScript higher-order function?
I mean, something like the following:
```
- [1, 2, 3, 4, 5].filter((x) => x%2===0 ? 'div Number ' + x : '');

```
Thank you

**Comment by TimothyGu** [comment]
Unfortunately, no, you can't at this moment.

You might be interested in Pug's native [iteration](https://pugjs.org/language/iteration.html#each) and [conditional](https://pugjs.org/language/conditionals.html) syntax, which allows you to write something like this:

```pug
- var numbers = [1, 2, 3, 4, 5];
each number in numbers
  if number % 2 === 0
    div Number #{number}
```

**Comment by caneta** [comment]
Ok, thank you @TimothyGu!
