### ISSUE TITLE
Rendering is very slow for large SVG element

### ISSUE THREAD

**Issue by matejkramny** [pugjs/pug#2741]
Minimal example:

```pug
doctype
html(lang="en" ng-app="semaphore"): body
	svg(width="80" height="80" viewbox="0 0 250 250")
		title Ansible-Semaphore on GitHub
		path(d="M0 0h250v250")
		path.octo-arm(d="M127.4 110c-14.6-9.2-9.4-19.5-9.4-19.5 3-7 1.5-11 1.5-11-1-6.2 3-2 3-2 4 4.7 2 11 2 11-2.2 10.4 5 14.8 9 16.2" fill="currentColor")
		path.octo-body(d="M113.2 114.3s3.6 1.6 4.7.6l15-13.7c3-2.4 6-3 8.2-2.7-8-11.2-14-25 3-41 4.7-4.4 10.6-6.4 16.2-6.4.6-1.6 3.6-7.3 11.8-10.7 0 0 4.5 2.7 6.8 16.5 4.3 2.7 8.3 6 12 9.8 3.3 3.5 6.7 8 8.6 12.3 14 3 16.8 8 16.8 8-3.4 8-9.4 11-11.4 11 0 5.8-2.3 11-7.5 15.5-16.4 16-30 9-40 .2 0 3-1 7-5.2 11l-13.3 11c-1 1 .5 5.3.8 5z" fill="currentColor")
```

Rendering with `pug index.pug` hangs at 100% cpu.

Removing `path.octo-body` element fixes this issue.

**Comment by ForbesLindesay** [comment]
I'm unable to reproduce this.  What version of pug are you using?  Are you sure it is pug that hangs at 100% CPU and not something else causing this?

**Comment by matejkramny** [comment]
Hmm it definitely is the pug process.

Using:

```
➜  ~ pug --version
pug version: 2.0.0-beta10
pug-cli version: 1.0.0-alpha6
```

OSX: 10.12
node: v7.5.0 via homebrew

Installed `pug-cli` with `npm install -g pug-cli`

Tested using `pug` programmatically (in REPL) and it works.

**Comment by matejkramny** [comment]
I'll open an issue in [pug-cli](https://github.com/pugjs/pug-cli).

@ForbesLindesay should this issue be closed?

**Comment by ForbesLindesay** [comment]
Yes
