### ISSUE TITLE
Conditional block overrides

### ISSUE THREAD

**Issue by strugee** [pugjs/pug#2742]
Say I have a `layout.pug`: 

```pug
block test
	p Test content defined in layout.pug
```

and a `page.pug`:

```pug
extends ./layout.pug

if false
	block test
		p Test content defined in page.pug
```

Compiling `page.pug` results in an error being thrown ("Only named blocks and mixins can appear at the top level of an extending template").

Obviously this is a perfectly legitimate behavior, but it _feels_ like something that should be supported. I've already defined a default for the block, and I want to override it if a particular condition is true. Thoughts?

**Comment by kylekatarnls** [comment]
As you can see here (https://github.com/pugjs/pug/blob/master/packages/pug-linker/index.js#L106), blocks are replaced during compile-time. So wrap it with a condition would need to move it at runtime.

IMHO, it's not a good idea. Blocks after extends should remains at the top level domain. So they cannot be in any other tag, conditions or else.

Else, you can do something like this:
**layout.pug**
```
mixin defaultTestBlock()
	p Test content defined in layout.pug

block test
	+defaultTestBlock()
```
**page.pug**
```
extends ./layout.pug

block test
	if condition
		p Test content defined in page.pug
	else
		+defaultTestBlock()
```

**Comment by ForbesLindesay** [comment]
The error message here explains exactly what is wrong with your code.

**Comment by strugee** [comment]
@ForbesLindesay yes, if you'd read the last paragraph of the original report you'd know that I read the error and this was a feature request, not a bug report. That being said the reasoning given makes sense, thanks @kylekatarnls. 👍
