### ISSUE TITLE
How to insert expression of handlebars in meta tag?

### ISSUE THREAD

**Issue by livemirsi** [pugjs/pug#2744]
Hello guys. Help me with that:
`meta(name="keywords", content="{{keywords}}")`
output:
`<meta name="keywords" content="">`
But i need: 
`<meta name="keywords" content="{{keywords}}">`
How i can do it?)

Thank you for attention.

**Comment by ForbesLindesay** [comment]
This already works exactly like that at the moment.

**Comment by vickrant** [comment]
but how to write facebook open graph tags
<meta property=”og:locale” content=”en_UK” />
