### ISSUE TITLE
Twig like content transformation?

### ISSUE THREAD

**Issue by blendsdk** [pugjs/pug#2746]
Hi,
Is it possible to do content transformaions like the one existing in Twig (js)? For example:

`#=order_amount | euro#`  transforms to:  €250,-   (`order_amount` being 250.0)
or
`#=myString | UPPERCASE#`  transforms the value of `myString` to uppercase.

Thank you.

**Comment by jeromew** [comment]
As long as you pass a javascript transformation function in locals, you could do something like

    span my amount is #{money(order_amount, 'EUR')}

Here, you would have 

    locals = { money: whatever function } 

but jade does not come pre-bundled with this kind of transforms. You would have to look for instance
