### ISSUE TITLE
Using Pug + CriticalJS ?

### ISSUE THREAD

**Issue by valeriosillari** [pugjs/pug#2748]
Not sure if I am out of topic, but I have new to Pug and I have a question ...

I have a small web application set with Express + Pug

Everything looks fine, but now I want to add a plugin for improve page speed:
Critical (https://github.com/addyosmani/critical)

Basically this plugin "parses" the html + css of a page, change the css file (creating a new css file) and add INLINE in the markup some new code for css trick.

The documentation of the plugin it is very simple. but they always talking about plain HMTL files/page, NOT about markup files created by express or with languages as Pug.

So my question is:

How can try to use Critical with Pug ?
I mean: I need to take a page created in pug, parse the "final" html and css, using critical to set new inline code and then inject again into pug file.

Anyone have already face/solve this problem?

or am I going on a very complete way?

Please if anyone has tips let me know

**Comment by ForbesLindesay** [comment]
You would need to run this tooling on the output of pug.  You can manually render pug templates to a string using `pug.renderFile`.  Beyond that, I cannot offer any support here, but you may find someone on stackoverflow.com who can help you.
