### ISSUE TITLE
Pug XMLHttpRequest

### ISSUE THREAD

**Issue by matteomanfredi** [pugjs/pug#2750]
I am trying to to a GET request to an object in a Pug file:

    -
      var xhr = new XMLHttpRequest();
      xhr.open('GET', "//ipinfo.io/json", true);
      xhr.send();
      xhr.addEventListener("readystatechange", processRequest, false);

      function processRequest(e) {
        if (xhr.readyState == 4 && xhr.status == 200) {
          var response = JSON.parse(xhr.responseText);
          alert(response.ip)
        }
      }

While trying to compile it gives an error at line 253 of the index.js runtime module. 

    TypeError: [...]:1
      > 1| -
        2|   var xhr = new XMLHttpRequest();
        3|   xhr.open('GET', "//ipinfo.io/json", true);
        4|   xhr.send();

    XMLHttpRequest is not a constructor
        at eval (eval at wrap (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:16:11)
        at template (eval at wrap (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:410:319)
        at renderFile (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/pug-cli/index.js:285:40)
        at /Applications/CodeKit.app/Contents/Resources/engines/node_modules/pug-cli/index.js:149:5
        at Array.forEach (native)
        at Object.<anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/pug-cli/index.js:148:9)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)

The fact is that Pug it's supposed to be able to interpret JavaScript as I have already tested multiple times, why doesn't it support XMLHttpRequest()? Is there something wrong in my code?

**Comment by KSXGitHub** [comment]
I think Pug supports JavaScript but doesn't support the APIs (Web APIs, Node.js APIs).

In order to use these APIs, I must implement [Pug API](https://pugjs.org/api/reference.html#pugcompilesource-options) (Node.js) myself and pass functions to Pug via `locals` object  (e.g. `require`, `XMLHttpRequest`)

**Comment by matteomanfredi** [comment]
Oh, I see. I don't think what I need to do it's worth the effort, I will manage it differently! Would be cool to be able to use them, though!

**Comment by KSXGitHub** [comment]
@matteomanfredi How are you using pug? via `pug-cli`?

**Comment by matteomanfredi** [comment]
Using CodeKit ([https://codekitapp.com](https://codekitapp.com)), but it's basically `pug-cli`. It is used just as a preprocessor for me, nothing running on the actual web server. Static files are actually faster and simpler to serve, if it is possible.

On StackOverflow [(http://stackoverflow.com/questions/42566942/pug-xmlhttprequest)](http://stackoverflow.com/questions/42566942/pug-xmlhttprequest) a guy told me the reason that `XMLHttpRequest` wasn't supported was due to speed of execution that could be impacted, but not everyone uses it as a real-time backend.

**Comment by KSXGitHub** [comment]
I don't know much about CodeKit, but I think it's an IDE. I personally use IDE only for learning, I never rely on IDE in my serious projects for sake of customizability.

**Comment by matteomanfredi** [comment]
It's not an IDE, it's a GUI, but nothing changes running from the CLI.

**Comment by ForbesLindesay** [comment]
The cli runs in node.js, so you won't be able to access browser APIs. Even if you use the node http libraries, it won't work because they are asynchronous and pug templates are synchronous. If you need to run asynchronous code in your templates, you have to use them-pug as this is a specialised, advanced use case that we do not support as part of the core pug project.

**Comment by KSXGitHub** [comment]
@matteomanfredi I don't even rely on any GUI. Although I use them frequently (GUI text editor, Git GUI, ...), I always make sure that I can still compile my project with just command-line.
