### ISSUE TITLE
Syntax Error, when using class as an argument for a mixin

### ISSUE THREAD

**Issue by michaelpumo** [pugjs/pug#2753]
If I write the following `mixin`, Pug will error:

`mixin sprite(class='')`

But if I write:

`mixin sprite(className='')`

...it works.

I guess this is because `class` is a reserved word? Not sure if this is expected behaviour or not. 

React behaves in a similar way, so not sure if it's a bug or just a minor misunderstanding. 

Thanks.

**Comment by briman0094** [comment]
Pug files get compiled into JS snippets during runtime, so `class` can't be used as an identifier (as you said, it's a reserved word in ES2015).

**Comment by ForbesLindesay** [comment]
This is because the arguments to mixins are JavaScript variables.  As @briman0094 pointed out, this means `class` cannot be used as an identifier.

Pug automatically handles it for you when used as an attribute, but it cannot do so easily if you use it as a variable.
