### ISSUE TITLE
Maximum call stack size exceeded errors

### ISSUE THREAD

**Issue by Manish-Giri** [pugjs/pug#2754]
Some of the pages in the Language Reference docs have this error while rendering the corresponding HTML - 

![screenshot 2017-03-04 06 22 21](https://cloud.githubusercontent.com/assets/11348778/23578363/f4ce8620-00a2-11e7-95e5-4963af1d51b2.png)

Some of the pages where I'm seeing this are - 
https://pugjs.org/language/mixins.html
https://pugjs.org/language/iteration.html

**Comment by KSXGitHub** [comment]
Also:

![image](https://cloud.githubusercontent.com/assets/11488886/23587427/19f207b0-01de-11e7-8e97-2737807b27a1.png)

https://pugjs.org/language/filters.html#nested-filters

**Comment by matteomanfredi** [comment]
It wasn't like that a couple of days back, I opened the Iterations page to check some syntax and it was working!

**Comment by rhdsmnd** [comment]
Same for the "Mixins" page.

![image](https://cloud.githubusercontent.com/assets/5566652/23685561/a64a9912-0359-11e7-8a65-bfc12862e89b.png)

**Comment by zmw85** [comment]
see the same thing here, I also run into same problem in my code. Can anyone please response to this and fix it please.

**Comment by ForbesLindesay** [comment]
Thank you for reporting this.  I'm quite busy at work at the moment, but I do hope to get to improving the documentation website soon (probably ~1 month).  If someone wants to submit a pull request in the mean time, that would be very helpful.

**Comment by rhdsmnd** [comment]
Seems to be fixed
