### ISSUE TITLE
Space between text elements

### ISSUE THREAD

**Issue by kylekatarnls** [pugjs/pug#2755]
Hi, I tested the following:
```pug
block a
  | a
  | a
```
And I get `a a` but with `apend`:
```pug
block a
  | a
append a
  | a
```
I get `aa`. is it the expected behaviour because I do not find this consistent.

Thanks,

**Comment by ForbesLindesay** [comment]
This is the expected behaviour.  Specifically, pug adds a single whitespace between consecutive piped text lines.  Using `block` and then `append` creates two separate sections of pug code, and so this rule does not apply.
