### ISSUE TITLE
Simple bug in nested <a> tags

### ISSUE THREAD

**Issue by piotryordanov** [pugjs/pug#2760]
Make a simple test with this sample code:

```
each chapter, index in chapters
      a.post
         a.second
```

The result makes no sense at all! 
I'm on beta11.

**Comment by ForbesLindesay** [comment]
You cannot nest a tags, this is a browser restriction, not a pug one.  The pug output is correct, but but the browser guesses at what you meant given the restriction that it cannot nest a tags

**Comment by piotryordanov** [comment]
Oh! I was never aware of this being a restriction!
I'll sleep less ignorant tonight. Thank you :)
