### ISSUE TITLE
No support for custom elements v1

### ISSUE THREAD

**Issue by kristianmandrup** [pugjs/pug#2762]
Trying to use a `hello-world#ce-static` in a *custom elements v1* hello world app.
The element is ignored and never rendered. Please provide some way to make this work.
Thanks.

```
doctype html
html
	head
		link(rel='stylesheet' href='./furtive.css')
	body
		div#root!= ssr
		div#ce
		script(src!= lib)
		script(src='ce.js')
		hello-world#ce-static
```

Looking into the parser, but not sure... how is `type` determined from `peek()`

```js
TokenStream.prototype.peek = function () {
  if (this._tokens.length === 0) {
    throw new Error('Cannot read past the end of a stream');
  }
  return this._tokens[0];
};


  peek: function() {
    return this.tokens.peek();
  },

  parseExpr: function(){
    switch (this.peek().type) {
      case 'tag':
        return this.parseTag();


  parseTag: function(){
    var tok = this.advance();
    var tag = {
      type: 'Tag',
      name: tok.val,

  // ...

// this.tokens = new TokenStream(tokens);

  advance: function(){
    return this.tokens.advance();
  },

```

[token-stream](https://github.com/pugjs/token-stream) Not sure when it is determined that the tag name ends? any non-alpha character?

**Comment by kristianmandrup** [comment]
Ah, now I see. The problem is in `pug-lexer`:

```js
  /**
   * Tag.
   */

  tag: function() {
    var captures;

    if (captures = /^(\w(?:[-:\w]*\w)?)/.exec(this.input)) {
      var tok, name = captures[1], len = captures[0].length;
```

The captures should be allow `\w` and `-` after the first char

`/^(\w(?:[-:\w]*\w)?)/` => 

It should use [validate-element-name](https://github.com/sindresorhus/validate-element-name) instead :)

**Comment by kristianmandrup** [comment]
Would be nice if the tag rules were better documented! Cheers :)

**Comment by ForbesLindesay** [comment]
Custom elements seem to work fine.  The only extra restriction we add is that we don't let tag names end in `-`.  I don't think this is very limiting.
