### ISSUE TITLE
Comments should be allowed as first statements

### ISSUE THREAD

**Issue by antechrestos** [pugjs/pug#2763]
Restrictions such as `Declaration of template inheritance ("extends") should be the first thing in the file.` prevent users from putting a comment in the file header, such as a license header .Could it be possible to add this functionality (if it is possible)? May be from a contribution?

**Comment by jeffwilcox** [comment]
We're still on pug-2 beta 4, and are successfully using pug app-side comments `//-` in the headers for license statements.

**Comment by antechrestos** [comment]
@jeffwilcox Thank you so much; My templates missed the hyphen sign.
