### ISSUE TITLE
Render markdown instead of html

### ISSUE THREAD

**Issue by dpolyakov** [pugjs/pug#2765]
Hello.

I want to use pug for render markdown  instead of html. Is any variant how can i do that?

**Comment by biaomingzhong** [comment]
Just use [filters ](https://pugjs.org/language/filters.html)like` :markdown-it`

**Comment by dpolyakov** [comment]
@biaomingzhong, `:markdown-it` will help me to render markdown to html result document.

But i want create markdown document with pug.

**Comment by johnathankent** [comment]
@dpolyakov 
Leave the filter off, and use includes as plain text. They will render the content as is, and you can leverage Pug's compiler logic: https://pugjs.org/language/includes.html#including-plain-text. This might work for basic markdown compilation.

```
//- index.pug
include header.md

if (someLogic)
  include body.md
else
  include alternateBody.md

include footer.md
```

[For more complex logic or template rendering, I recommend you use a Markdown parser instead](https://css-tricks.com/choosing-right-markdown-parser), as your templates could get confusing when tackling [whitespace](https://pugjs.org/language/plain-text.html#whitespace-control) in smaller functions like iterating over lists or whatnot.

**Comment by ForbesLindesay** [comment]
We don't have anything builtin for this.  I guess you could use a custom code-gen stage like react-pug and then-pug do.
