### ISSUE TITLE
Rendering pug strings in a variable

### ISSUE THREAD

**Issue by webdevian** [pugjs/pug#2766]
I'm trying to pass strings to pug that may contain inline tags (links, code, em etc) and I would like to write them in pug syntax. 

I know that I can unescape plain HTML, is there a way to unescape pug? Or would I have to write a filter to render the pug?

None of these syntax attempts work: 
```pug
- var introduction = "Just clone the project from #[a(href='https://github.com', target='_blank') GitHub] to get started"

p= introduction
p!= introduction 
p.
  #{introduction}
  !{introduction}
p
  != introduction
```

**Comment by webdevian** [comment]
Having done a bit more reading (#1579), and experimenting with filters it seems it's not possible.

**Comment by ForbesLindesay** [comment]
You would have to manually call `pug.render` on your string.  N.B. The performance will not be good.

**Comment by webdevian** [comment]
Ok, that makes sense. Performance is not a problem as it's a gulp build task that generates static html once
