### ISSUE TITLE
Require/Import modules in code blocks

### ISSUE THREAD

**Issue by qm3ster** [pugjs/pug#2772]
Not sure if this belongs in pug-loader more so than here, since without doing further resolution logic the application would be fairly limited, no different from just including a `.pug` file with one `- ` block.
I also understand that this code runs on render and not build, and so would get shipped to client.
However for static rendering it would be much more convenient than having to pass modules through the locals attribute.

**Comment by ForbesLindesay** [comment]
Duplicate #2604
