### ISSUE TITLE
layout's nested blocks cannot be replaced sometimes

### ISSUE THREAD

**Issue by cspotcode** [pugjs/pug#2774]
Nested blocks cannot be replaced when their parent block has already been replaced by a layout.  In my example, base.pug's `content` block is totally wiped out but replaced by a new `content` block in layout.pug.  However, when page.pug tries to put markup in the `content` block, it is ignored.

## base.pug
```pug
block body
    block content
```

## layout.pug
```pug
extends ./base.pug
block body
  script(src="jquery.js")
  block content
    // blank page
```

## page.pug
```pug
extends ./layout.pug
block content
  h1 Main page content!
```

## Expected page.html
```html
<script src="jquery.js"></script>
<h1>Main page content!</h1>
```

## Actual page.html
```html
<script src="jquery.js"></script>
<!-- blank page-->
```

```bash
# Dependencies:
    "pug": "^2.0.0-beta11",
    "pug-cli": "^1.0.0-alpha6"
# Command:
node_modules/.bin/pug -P page.pug
```

When layout.pug's `content` block is renamed to `content2`, and page.pug replaces `content2` instead of `content`, it works.  This suggests that the `content` block introduced by layout.pug is not properly shadowing the `content` block declared in base.pug.

**Comment by cspotcode** [comment]
I think I've isolated the problem to this line:
https://github.com/pugjs/pug/blob/master/packages/pug-linker/index.js#L80

It should not be inside a conditional; it should always be executed.

In my reproduction, the problem is that layout.pug's `block content` has a parent, the `block content` from base.pug.  This causes the line of code I linked to not execute.  This means that when page.pug's `block content` replaces its parent blocks' nodes, the "content" block from layout.pug is not touched.  Therefore, when the final template renders, we don't see the correct contents for the "content" block.

**Comment by ForbesLindesay** [comment]
Thanks for the bug report.  Would you be able to submit a failing test case?  You can see https://github.com/pugjs/pug/tree/master/packages/pug/test/duplicate-block for an example that you can copy.

Comment here if you are going to work on adding the failing test case, that way nobody else will duplicate your effort.

**Comment by cspotcode** [comment]
No problem, I'll make the failing test case.

**Comment by cspotcode** [comment]
I wrote a PR with a failing test case and a bugfix.
