### ISSUE TITLE
How to close compiled outputs when integrated with expresses

### ISSUE THREAD

**Issue by ucev** [pugjs/pug#2775]
![Uploading 屏幕快照 2017-04-16 20.19.13.png…]()
I have tried `process.env.NODE_ENV` or `app.locals`, but it didn't work.Can anyone help?

**Comment by ForbesLindesay** [comment]
It doesn't seem to have uploaded the screenshot, so it's difficult to know what you are asking for help with here.  If you want the output to be cached, you can run with NODE_ENV=production.  e.g.

```
NODE_ENV=production node server.js
```

Setting environment variables has to be done differently if you are on windows.
