### ISSUE TITLE
Why still in beta - when will be in stable

### ISSUE THREAD

**Issue by mohanen** [pugjs/pug#2776]
I know its been asked by others many times 

But really its been posted like it should have been made to stable in 2016 itself, but its been many days and still no word about a stable release .

The org i am  working under wont allow me to use beta versions in projects , so it would be good to know when there will be a official stable release else i have no other way than sticking with the same old html and ejs

**Comment by grawlinson** [comment]
@mohanen Does your organisation consider release candidates as stable releases? The first release candidate of 2.0.0 was released ~1 hour ago.
