### ISSUE TITLE
Conditionals Issues

### ISSUE THREAD

**Issue by paulcamo** [pugjs/pug#2782]
Hi, Im trying to add this conditional

in my utilities.pug I have this
//- -------------- Buttons ---------------- -//
//- --------------------------------------- -//
`mixin basicLink(text, url, newclass, newTab)`
    `a.generic__link(
                    class!=attributes.class
                    href=url
                    target=newTab
                    newclass={active: text === current}
                    ) #{text}`

in my main-header.pug I made this
//- -------------- Header ---------------- -//
//- -------------------------------------- -//
`- var pages = [{name: 'Home', url: 'index.html', current: 'Home'}, {name: 'Internal', url: 'internal.html', current: 'Internal'}]`

   ` ul.main__header__nav
        each page in pages
            li.main__header__nav__item
                +basicLink(page.name, page.url, page.current)`

I'm trying to make work the newclass adding the 'active' class when the page is selected, but the result is: 

`<li class="main__header__nav__item"><a class="generic__link" href="index.html" newclass="{"active":false}">Home</a></li>`

Any idea?

**Comment by Turqueso** [comment]
try this
Mixin
```
mixin basicLink(text, url, current)
  a.generic__link( class!=attributes.class href=url target=newTab class=text === current ? 'active' : '' ) #
```
Itineration
```
ul.main__header__nav
   each page in pages
     li.main__header__nav__item
       +basicLink(page.name, page.url, page.current)
```

**Comment by paulcamo** [comment]
Does not working.

In the main-header.pug I have the code like this:

`- var pages = [{name: 'Home', url: 'index.html', current: 'Home'}, {name: 'Internal', url: 'internal.html', current: 'Internal'}]`


`header.main__header`
    `h1.main__header__title This is a sample template`

    `ul.main__header__nav
        each page in pages
            li.main__header__nav__item
                +basicLink(page.name, page.url, page.current)`

But it returns in all the pages like active...and I really need that the true active page only show the class, not all of them.

**Comment by Turqueso** [comment]
I would need to know more about your structure. But I do something like this, you can adapt it to your needs:

Structure
```
pug/
  - index.pug
  - page.pug
  partials/
    - layout.pug
```

inside layout.pug
```
- var pages = [{name: 'Home', url: 'index.html'}, {name: 'Internal', url: 'internal.html'}]

block menu
  ul
    each page in pages
      li
      if current === page.name
        a(href=page.url class="active")= page.name
      else
        a(href=page.url)= page.name
```

inside index and page
```
extend partials/layout.pug
block menu
  - var current = 'Page' //- or Home
```
