### ISSUE TITLE
Dealing with special tag names (e.g. including periods)

### ISSUE THREAD

**Issue by jdoubleu** [pugjs/pug#2783]
I'm currently porting some html to pug.

I'm including custom XML schemas:
```pug
html(xmlns:another="...")
```

Following the W3C's recommendation for XML it is allowed to use periods in tag names (see here: https://www.w3.org/TR/REC-xml/#NT-NameChar ). However a dot is treated as a class "introducer".

How can I manipulate pug to convert `another:some.tag/`  to `<another:some.tag />` instead of `<another:some class="tag">`?

Or isn't it possible? Will there be such a feature, like escaping tag names?

**Comment by ForbesLindesay** [comment]
You can wrap it in the interpolation syntax for a dynamic tag `#{'some.tag.name'}`

**Comment by ForbesLindesay** [comment]
```pug
#{'@context'}
```

produces

```html
<@context></@context>
```

The problem you're having is that `xml2json` doesn't interpret that as valid xml (because it isn't) you will need to find out if there is any valid xml string that produces your desired JSON, then you can figure out how to generate that XML in pug.
