### ISSUE TITLE
Ability to give detail in template errors

### ISSUE THREAD

**Issue by cheshrkat** [pugjs/pug#2784]
Not sure if this is part of the intent for #2155 or not, so thought I'd raise this separately.

What I would like to do is throw well-formatted and informative errors from templates and template partials.

Example use case: `page.pug` calls a mixin stored in `_widget.pug`: `+widget({ 'size': 'massive' })`

In `_widget.pug` I have a sizes array `['small', 'medium', 'large']` and do a quick check that the passed `size` value is supported. In this case I find it's not, so I want to throw an error.

`throw new Error("Invalid size: " + options.size + ". Expected one of: " + sizes)`

...now that does work, ie. it brings everything to a crashing halt. But it errors out in `_widget.pug` and the trace doesn't mention `page.pug`. Similarly I can provide a quieter console log/warning/error but again it can only say the option was wrong; and not where the option is being used (ie. the bit my users need to go find and fix).

So what I'd really like to do is log a warning message *including info like the originating filename*, ie.

`console.error("Error in " + PUG.CALLER + " Invalid size: " + options.size + ". Expected one of: " + sizes)`

Where PUG.CALLER is some naive pseudocode for the name or details of the template that called the partial (or a trace back up X levels of successful rendering, or whatever). I can imaging all kinds of environment info might be useful (URL, browser, etc) but that's the specific one I hit today :)

For full disclosure this project is actually still on Jade (upgrade is currently blocked, whole other story), but I'm pretty sure this hasn't changed in pug either. My apologies if it has.

**Comment by ForbesLindesay** [comment]
Once we add proper source map support we should be able to do a full stack trace. I think this will take another year or so (unless the pug open collective gets sufficient funding for me to spend a lot more time working on it)
