### ISSUE TITLE
Support for Statamic double curly braces / mustaches / brackets

### ISSUE THREAD

**Issue by rockethouse** [pugjs/pug#2785]
Not sure if this has been covered already or not, or if my question makes any sense as I am very new to pug/jade, but i'll have a go at asking and hope I don't make a fool of myself...

So i'm using Pug with Statamic (a flat-file CMS) and they have their own templating language which uses double brackets ie `{{ stuff }}`.

> see: https://docs.statamic.com/antlers

What i'm finding really annoying is that whenever I want to use a Statamic tag on a new line, I need to put a `|` at the start... making the super nice pug code start to look messy and dirty... 

Example:

```.hero-entry
| {{ collection from="news" }}
.entry {{ title }}
| {{ /collection }}

And also, because of this I can't indent the middle line either, which makes it hard to read.

Is there anyway around this? or a way for Pug to interpret anything wrapped around `{{` and `}}` as plain text?

Thanks!

**Comment by ForbesLindesay** [comment]
No, pug has nothing to help support this.

**Comment by intositeme** [comment]
Is there a workaround for this? I too need {{}} inside attributes without the " " wrapping around for React
