### ISSUE TITLE
Do not work string interpolation in filter

### ISSUE THREAD

**Issue by naoina** [pugjs/pug#2786]
When I use jstransformer-coffee-script as a filter, string interpolation does not work. The following file is example.

```pug
- var hoge = 'foo';
script
  :coffee-script
    a = '!{hoge}'
```

I expected output is:

```html
<script>(function() {
  var a;

  a = 'foo';

}).call(this);
</script>
```

But the actual output is following:

```html
<script>(function() {
  var a;

  a = '!{hoge}';

}).call(this);
</script>
```

How do I use string interpolation in filter?

**Comment by ForbesLindesay** [comment]
You cannot use interpolation inside filters because filters are processed at compile time. You can manually call the render functions using the jstransformer npm module. This will let you pass in your own string.

**Comment by naoina** [comment]
I understand. Thanks.
