### ISSUE TITLE
How to use pug with react instead of jsx?

### ISSUE THREAD

**Issue by salmazov** [pugjs/pug#2796]
I like to write Facebook React.JS apps. But I like pugjs too. How to make them friends?

**Comment by bluewings** [comment]
I felt a similar need, so I created a loader for the web pack.

[pug-as-jsx-loader](https://www.npmjs.com/package/pug-as-jsx-loader)

I have been using this loader in recent months and I feel that productivity has improved a lot.

And you can see how the 'pug-as-jsx-loader' works from the link below.

https://bluewings.github.io/pug-as-jsx-loader/

**Comment by jeromew** [comment]
@bluewings interesting approach.

There was a `react-jade` module for jade but it has not yet been ported. The idea was that jade was directly replacing jsx. cf https://github.com/pugjs/react-jade

`pug-code-gen` has to be modified in the same way jade was modified back then to generate react calls. Nevertheless, there is an ongoing project where `pug-code-gen` will directly generate AST, which will probably make it easier. cf https://github.com/pugjs/pug/issues/2708

**Comment by ForbesLindesay** [comment]
The officially supported way of doing this is now https://github.com/pugjs/babel-plugin-transform-react-pug but it does not have documentation yet, and it only supports inline pug templates, i.e.

```js
function MyComponent() {
  return pug`div some content`;
}
```

produces:

```js
function MyComponent() {
  return <div>some content</div>;
}
```

In the future, I'd like to also provide an option for compiling whole pug files to react/jsx components.  I also obviously want to document the existing solution.

**Comment by michaelalhilly** [comment]
Hi @ForbesLindesay. I'm trying to stick with Pug but as I spend more time working on SPAs it has been somewhat tedious to use Pug across various frameworks. It may be more flexible to use the following:

https://github.com/bluewings/pug-as-jsx-loader

I believe this would allow us to precompile Pug templates into JSX, which can then be precompiled by the SPA specific loader. This way we are not limited to a React specific solution.

It's becoming a real pain to setup different build processes for each.

**Comment by ForbesLindesay** [comment]
https://github.com/pugjs/babel-plugin-transform-react-pug is not actually react specific, it compiles pug into jsx, then you can transpile that jsx to react or whatever.

**Comment by michaelalhilly** [comment]
@ForbesLindesay Sorry for the confusion. I was wrong about both modules. 

The [pug-as-jsx-loader](https://github.com/bluewings/pug-as-jsx-loader) is in fact React-specific.

Your Babel plugin looks great. I'll wait for the import feature as well. I prefer to keep my Pug templates in separate files.

Thanks!

**Comment by ForbesLindesay** [comment]
Not sure what you mean about waiting for the import feature.  The babel plugin I've written is "done" excecpt for documentation.

**Comment by michaelalhilly** [comment]
I'm referring to your comment above:

"In the future, I'd like to also provide an option for compiling whole pug files...".

Were you referring to compiling files with the import/require statement?

**Comment by ForbesLindesay** [comment]
I mean doing something like:

```js
import pug from 'react-pug';

const Foo = pug.compileFile('foo.pug');

// assuming jsx support:
render(<Foo />);
```

The `react-pug` module here wouldn't be included at runtime, but would allow you to run the code server side without any transform.

**Comment by michaelalhilly** [comment]
Yes. That's what I was look for. For now I found a way to separate Pug files with VueJS.

**Comment by jefer94** [comment]
Why no a plugin for babel that transform pug in jsx? it's much better, also react is so popular in current, is a opportunity

```js
import React from 'react'

const Example = () =>
  .bg-red.red
    p
      It's not look better?

export default Example
```

**Comment by Superpencil** [comment]
Hi I don't know how any of this works but I love React and am used to HAML and am super annoyed pug isn't easy to use here, seems like a match made in heaven.

```
import React from 'react'
import pug from 'pug'

const Example = () => pug`
    .bg-red.red
      p
        At least something like this?
`

export default Example
```

**Comment by ezhlobo** [comment]
For people who came from google and other ways, there is a way to achieve that by using babel plugin: [pugjs/babel-plugin-transform-react-pug](https://github.com/pugjs/babel-plugin-transform-react-pug). 

For example, @Superpencil, the following code will work:

```jsx
import React from 'react'
import SomeComponent from './SomeComponent'

const Example = () => pug`
  .bg-red.red
    p
      At least something like this?
    SomeComponent(prop='true')
      ohai
`

export default Example
```

Take a look at more examples in the plugin's repository ;).

**Comment by bluewings** [comment]
@Superpencil 
You must prefix the text node with a ```|```, and check the REPL in the link below.
(pug-as-jsx-loader is a loader for webpack that converts pug to jsx.)
https://bluewings.github.io/pug-as-jsx-loader/
![2018-12-10 10 12 34](https://user-images.githubusercontent.com/1563202/49705770-24417980-fc64-11e8-9f6e-a224cb6b8006.png)

**Comment by Superpencil** [comment]
Am now happily using https://github.com/pugjs/babel-plugin-transform-react-pug!

**Comment by thathsara404** [comment]
Hi,
what should be the file extension when I'm using  banel-plugin-transform-react-pug

**Comment by ezhlobo** [comment]
@thathsara404 all we need to make it work is to be sure that Babel processes your files with pug in react. When you setup your building with webpack or with any other tool, you usually configure Babel to process `.js` or `.jsx` files, thus any of those should be good in your case.

Another answer is try the extension you got used to ;).

**Comment by thathsara404** [comment]
I think I'm dealing with wrong library. I want to render my pug template (main.pug) with react imports.
I have the following post rout and I'm rendering my template there as follows.

router.post('/',function (req, res) {
res.render("main", {name: "test"});
})

I think pug-as-jsx-loader is the matching library for my purpose but unfortunately my project build tool is parcel. So is there any library to do that with parcel ??
