### ISSUE TITLE
Mixed tabs/spaces

### ISSUE THREAD

**Issue by tianshuo** [pugjs/pug#280]
Some editors(DW) automatically formats new lines using tabs, and this means I have to manually grep out tabs, or else there is an error of mixed spaces and tabs. Couldn't we give a default value so that tab=4 spaces?

**Comment by guaka** [comment]
Jumping into a jade project now. Not being allowed to mix tabs and space is a major headache.

**Comment by TimothyGu** [comment]
@guaka how many spaces is supposed to be a tab? 2? 3? 4? 6? 8?

**Comment by guaka** [comment]
First thought was "just do it like Python" but it seems Python 3 doesn't allow mixing tabs and spaces anymore either https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

**Comment by jbnicolai** [comment]
@quaka while I respect and am sorry for the inconvenience you experience, I'm strongly in favor of keeping the current policy as is, and am not going to reopen the issue.

**Comment by BrandonBoone** [comment]
Perhaps a better error message would suffice as a compromise. It took a little digging to figure out that mixed tabs/spaces from my IDE was causing my jade files to fail. A simple, "Mixed indentation" error message would go a long way (not assuming it would be simple to detect such a state).

**Comment by TimothyGu** [comment]
@BrandonBoone, the message I'm getting looks quite clear:

```
    1| p
    2| 	| bkah
  > 3|     | asfd

Invalid indentation, you can use tabs or spaces but not both
```

**Comment by BrandonBoone** [comment]
@TimothyGu, (－‸ლ) - just noticed this myself. Not sure how I missed this. Sorry for the spam, and yes, it is quite clear.

**Comment by guaka** [comment]
What if it's optional? `--tabs=4` and inside a `.jade`, something with `tabs=4` as the first line?

**Comment by TimothyGu** [comment]
@guaka, I don't really understand your question. What is this `--tabs=4` option for?
