### ISSUE TITLE
Include with parameters

### ISSUE THREAD

**Issue by crephix** [pugjs/pug#2802]
Assuming I am using two navigation bars (one dark themed for the homepage and one light themed) -
 except one class they are identical. Right now I am using one include to load my navigation bar for all my pages like this:

```
block content
	include ../common/navigation
	main
```

I would like to pass a paremeter whether I want to include the light or dark themed navigation. Is that possible? If it isn't what would be the best way to achieve my desired result?

**Comment by wsjscss** [comment]
Use `mixin`

[Pug Mixins](https://pugjs.org/language/mixins.html)
