### ISSUE TITLE
Add support for ES6 import

### ISSUE THREAD

**Issue by noonien** [pugjs/pug#2804]
Hello!

I'm using rollup with [rollup-plugin-pug](https://github.com/aMarCruz/rollup-plugin-pug) to compile my pug templates to JS, however, the following pug template:

```pug
- import foo from 'foo';
p= foo('bar')
```

Errors out with:
```Error: 'import' and 'export' may only appear at the top level (2:0)```

I believe this is because the pug compiler adds some code before the import statement.

**Comment by ForbesLindesay** [comment]
You cannot have import statements in pug. I don't think this is something we're likely to be able to fix any time soon.

**Comment by anlexN** [comment]
can you add es6+ import/export feature? @ForbesLindesay
