### ISSUE TITLE
Why does having "class" and other attributes within parenthesis often return an error?

### ISSUE THREAD

**Issue by typistX** [pugjs/pug#2806]
This is more a question than a bug. If I do:

```
button(type="button" class="btn btn-default btn-sm" data-toggle="modal"
data-target=".create-new-brand")
```

Pug will fail and complain about something with "string". Please note that from what I've seen, this happends regardless of the order of the HTML attributes, so:

```
button( class="btn btn-default btn-sm" type="button" data-toggle="modal"
data-target=".create-new-brand")
```

Yields the same error.

I often find myself having to divide into multiple parenthesis, like so (3 different ones in this example):

```
button(type="button")(class="btn btn-default btn-sm")(data-toggle="modal"
data-target=".create-new-brand")
```

And so:

```
div(class="modal fade create-new-brand")(tabindex="-1" role="dialog")
```

Is this the expected behavior?

**Comment by ForbesLindesay** [comment]
What is the entire error message you are getting for the first example?

**Comment by typistX** [comment]
> What is the entire error message you are getting for the first example?

Hi Forbes, thanks for answering so fast. the error ***was*** `invalid syntax (<string>, line 1)`, but I think I found out why: attributes *must* be separated by commas, something I wasn't aware of. I guess this can be closed.

**Comment by ForbesLindesay** [comment]
You do not need commas between attributes. The example you posted works fine in the current version of pug. You might be using an ancient version (from at least 3 years ago, when we required commas). Can you post the stack trace as well?

**Comment by typistX** [comment]
Sorry, I'm using pypugjs and just realized this is pugsjs's repo. Probably need to post it there.

**Comment by typistX** [comment]
[This is the traceback](https://pastebin.com/1DJiN2tZ) if you're still curious.
