### ISSUE TITLE
filter to receive arguments from pug.renderFIle() // to optionally not filter

### ISSUE THREAD

**Issue by puppetmaster3** [pugjs/pug#2818]
I pug.renderFIle() this

```
script
  :babel
```
What I want to do is transpile if ie11, else don't transpile, use the script as is for other browsers. (based on express port, so www.domain is not ie, and ie.domain is ie)

How to do that? 
A) I don't see how to 'skip' a filter in options.filters. I should be able to tell it what filters to use right there, for example, if I don't list babel, it won't.
B) If I write a a custom filter, options.filters = {
  'optional-babel': function (text, options) ........
then how do I pass in a flag from pug.renderFile() that ie = true. options.ie= true? 

I guess option A is better.
This way for example I could chose at pug.renderFile() time which filters instance/implementation I want to use.

**Comment by ForbesLindesay** [comment]
This isn't anything that pug has built in support for.  I'm afraid I'm not able to offer a detailed suggestion, other than to say that filters happen at compile time, so they can't really change based on the current browser.  What you could do is something like:

```pug
script
  if isRecentBrowser
    include ./script.js
  else
    include:babel ./script.js
```

If you have further questions on this, stackoverflow.com may have people with more time to help you.

**Comment by puppetmaster3** [comment]
I don't think you understood the question. I don't need to detect what the browser is.

What I need is to be able to pass in options to pug.foo() and have my filter affect it.
