### ISSUE TITLE
Deferred include (give names to includes or support variables in path)

### ISSUE THREAD

**Issue by dresende** [pugjs/pug#282]
I have an application with several templates, that have a base template. I then include each template (that corresponds to a view of the application). As Jade doesn't seem to support (I couldn't find), it would be great to have an include with a name like

```
include #content
```

or be able to use variables in the path like

```
include 'apps/#{app}/view'
```

Is this possible? Right now, I use a special string like "" and literally .replace() that with the sub template.

**Comment by acidjazz** [comment]
lets get this in for the next jade! https://github.com/jadejs/jade/issues/1990

**Comment by acidjazz** [comment]
Dynamic includes would be so awesome, I've run into issues twice this week on projects where they would solve them immediately
