### ISSUE TITLE
Value of Input field working weird.

### ISSUE THREAD

**Issue by ziyanma** [pugjs/pug#2826]
I tried several way to work around this.

Both
input(value={urn})
input(value="#{urn}")
Doesn't work. The first one fields the input field like this: {"urn" : "myurn"}, Which is definitely what I want. 

Right now I use input (value = "" + urn), but can some one fix it?

**Comment by ForbesLindesay** [comment]
You have not given us enough information here to reproduce/understand your problem.  Please provide:

1. the pug template you are rendering
2. the data you are passing into the pug template
3. the html you expected to receive as output
4. the html you actually receive as output

Please also use the formatting buttons (e.g. the `<>` button formats text as code).
