### ISSUE TITLE
Empty function with :coffee(minify=true)

### ISSUE THREAD

**Issue by kylekatarnls** [pugjs/pug#2829]
**Pug Version:** 2.0.0-rc2

Hi, another question about the actual unit tests:

## Input Pug

https://github.com/pugjs/pug/blob/97941ca599dca34fd82a0c6a0d4298c5c4e7f1e1/packages/pug/test/cases/filters.coffeescript.pug

## Expected

```js
(function(){var math;math={square:function(value){return value*value}}}).call(this);
```

## Actual

```js
(function(){}).call(this);
```
Line 7:
https://github.com/pugjs/pug/blob/97941ca599dca34fd82a0c6a0d4298c5c4e7f1e1/packages/pug/test/cases/filters.coffeescript.html#L7

## Additional Comments

I do not see what the minify option trigger. I do not find this option neither in coffeescript or jstransformer-coffee-script.

I understand non-global code could be removed by an agressive minifier but when I run coffee then uglify-js, I get the complete code above.

So my question is: is this empty bare function really expected?

Thanks,

**Comment by ForbesLindesay** [comment]
The relevant code is: https://github.com/pugjs/pug/blob/master/packages/pug-filters/lib/run-filter.js#L23-L36  The option is also passed to coffee-script though, which may do some of it's own minification.  A fairly primitive minifier could remove all of this as dead code, I don't know why it is being removed in our repo, but not when you attempt to run it manually.
