### ISSUE TITLE
How to use :markdown-it plugins

### ISSUE THREAD

**Issue by dlewand691** [pugjs/pug#2831]
Trying to use the markdown-it-sup plugin but pug is refusing to render. I have a numbers that I'd like to apply the `<sup>` tag to.

## Input Pug

```pug
:markdown-it:markdown-it-sup
    ^1^

```

## Expected HTML

```html
<sup>1</sup>
```

**Comment by ForbesLindesay** [comment]
```pug
:markdown-it(plugins=['markdown-it-sup'])
  ^1^
```

Should work.

**Comment by dlewand691** [comment]
Have another issue trying to use the HTML functionality in :markdown-it. It doesn't seem to be rendering correctly. The syntax I'm using is:

```
:markdown-it(html typographer plugins=['markdown-it-sup'])
    #### h4 Headline here
    <h5 class="text-blue-light">h5 blue headline</h5>
    + [Linked list item](#)
```
The output is plain text after the </h5> but it should be within a <ul>. There's no errors given but the rendering breaks. Is there a JSTransformer plugin needed?

**Comment by ForbesLindesay** [comment]
@dlewand691 that's probably an issue with markdown-it rather than with pug.
