### ISSUE TITLE
JS issues with PUG

### ISSUE THREAD

**Issue by sachinavinaw** [pugjs/pug#2832]
Hi.

I am facing a problem.
I am using pug. I have used number of page events using jquery.
When i run the application, mostly it fails to load js in one go. When I refresh the tab, it loads the js.
I tried both ways:
-Adding js in head
-Adding js in footer
Problem is still persisting. can anyone help?

**Comment by ForbesLindesay** [comment]
This question would be better on stackoverflow.com
