### ISSUE TITLE
Pug parser: additional node props

### ISSUE THREAD

**Issue by droooney** [pugjs/pug#2834]
I'm currently writing a tool for transforming very simple pug into some kind of javascript implementation of the ast.

It would be very nice if the nodes, produced by pug-parser, had lines and columns (maybe positions as well) in the output ast. For me it would be great if at least tag and attribute nodes had those.

**Comment by ForbesLindesay** [comment]
There is already some information.  If you can improve the line/column information in the AST, we would welcome a pull request.

**Comment by droooney** [comment]
When I have some time, I'll be glad to :)

**Comment by droooney** [comment]
I've noticed that attributeBlocks is not an array of attribute block nodes, but rather just their values. Should I make it an array of nodes with their locations, create a new tag node property with an array of nodes or just leave it as it is?

**Comment by ForbesLindesay** [comment]
Making them into true "blocks" would be fine with me.

**Comment by droooney** [comment]
Not sure I get it. Making

```json
{
  "attributeBlocks": ["attributes"]
}
```

into

```json
{
  "attributeBlocks": [
    {
      "type": "AttributeBlock",
      "val": "attributes",
      "line": 1,
      "column": 8
    }
  ]
}
```

would be fine if I change `pug-code-gen` as well?

**Comment by droooney** [comment]
I decided not to add "column" property to Block nodes because they are rather abstract.
