### ISSUE TITLE
Webpack 2 "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by lhviet** [pugjs/pug#2837]
**Pug Version:** 2.0.0-rc.2

**Node Vesrion:** v8.1.2

**Webpack Vesrion:** 2.4.1

I tried to import **pug** into my project which is using angular-cli, however, I met the issues below.
Please inform me if there is any solution for this.
Thanks in advance.

## Input JavaScript Values
WARNING in ./~/pug-filters/lib/run-filter.js
14:11-103 Critical dependency: the request of a dependency is an expression

WARNING in ./~/pug-filters/~/uglify-js/tools/node.js
24:11-32 Critical dependency: the request of a dependency is an expression

WARNING in ./~/pug-filters/~/source-map/lib/source-map/source-map-generator.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/pug-filters/~/source-map/lib/source-map/source-map-consumer.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/pug-filters/~/source-map/lib/source-map/source-node.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by ForbesLindesay** [comment]
You need to compile your templates server side, using something like the pug-loader.

**Comment by lhviet** [comment]
@ForbesLindesay There is nothing to say with server side.
The thing I want is client side like the page: http://html2jade.org/

**Comment by ForbesLindesay** [comment]
We don't support webpack for doing things like that.

**Comment by szkrd** [comment]
@lhviet thought about smg similar, probably you can just include `https://pugjs.org/js/pug.js` in your page, but just like the readme says, the js is indeed huge.
