### ISSUE TITLE
Pug wont install

### ISSUE THREAD

**Issue by kajetan-mazur** [pugjs/pug#2839]
pug version 2.0.0 rc2
node version 6.11.0

making : npm install pug --save and got some error 

![image](https://user-images.githubusercontent.com/22578157/28077592-77d6be64-6662-11e7-9870-fad4388247e7.png)

fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/acorn
Dose anyone got the same error?

**Comment by ForbesLindesay** [comment]
That's not an error, it's just still in progress.  In any case, this would be an npm bug, not a pug bug.
