### ISSUE TITLE
Getting Rendered HTML file as object

### ISSUE THREAD

**Issue by mmoman1993** [pugjs/pug#2840]
I made a template file in PUG and I am trying to render it to HTML and then get the result object and render it into PDF file using another module. 
The issue is that I am not able to retrieve the rendered HTML **object** resulting from PUG in order to **pass** it to the PDF module.

**Comment by ForbesLindesay** [comment]
Pug renders to a string by default. You could use an HTML parser to parse that html. e.g. https://www.npmjs.com/package/htmlparser2
