### ISSUE TITLE
Variable with value of `NaN` has inputs set to `value="null"` instead of `value=""`

### ISSUE THREAD

**Issue by niftylettuce** [pugjs/pug#2841]
If there's a `NaN` variable, then we should render an empty string.

The problem was not so apparent at first, I had an input...

```html
<input type="number" name="subscription_limit" />
```

And it got rendered with a variable:

```html
<input type="number" name="subscription_limit" value=product.subscription_limit />
```

However this value of `product.subscription_limit = NaN`, therefore it outputs as...

```html
<input type="number" name="subscription_limit" value="null" />
```

And since the browser renders this as a number input, the text "null" was not visible, so it wasn't so apparent at first what the issue was.

**Comment by niftylettuce** [comment]
Updated to read `NaN` in title.

**Comment by ForbesLindesay** [comment]
Please fill out the issue template, and be sure to use the actual HTML source code, and not the values from chrome's element inspector.
