### ISSUE TITLE
how to use a javascript module in pug js templates

### ISSUE THREAD

**Issue by ahmadbadpey** [pugjs/pug#2844]
To make random strings in pug template I want to use [random-string][1] javascript module. 

First I install it via npm like this : 

    npm install random-string

Then in pug template I used this : 

    .site
       .title
           - var string = randomString({length: 20});
           | #{string}

But while compiling files I got this error : 

    randomString is not a function

How Can I use third party javascript functions in pug js temaplte? 

  [1]: https://www.npmjs.com/package/random-string

**Comment by droooney** [comment]
Use [globals option](https://pugjs.org/api/reference.html#options)

**Comment by ForbesLindesay** [comment]
Just pass in `{randomString: require('random-string')}` when you render the template.
