### ISSUE TITLE
Standalone is broken

### ISSUE THREAD

**Issue by JourdanClark** [pugjs/pug#2845]
**Pug Version:** I am using the standalone version from [here](https://pugjs.org/js/pug.js), downloaded yesterday.

**Node Vesrion:** This is meant to run on the client.

## Input JavaScript Values

```js
var pug = require('pug');
getTemplateAsString("views/index.pug", function(data){
    var html = pug.compileClient(data, {"filename": "index.pug", "basedir": "views", "doctype": "html", "debug": true});
    console.log(html);
});

function getTemplateAsString(path, callback){
    jQuery.get(path, function(data){
        callback(data);
    });
}
```

## Input Pug
```pug
extends layouts/main.pug
block header
    h1 hello world
block content
    p this is content
block footer
    h3 lakdjfl kajsdl
```

## Expected HTML
```html
<h1>hello world</h1>
<p>this is content</p>
<h3>lakdjfl kajsdl</h3>
```

## Actual HTML
```html

```

## Additional Comments

It seems like the standalone version still requires fs in order to work. I would like to use pug to develop apps with cordova so I would be packaging the js file with it. The reason for my "getTemplateAsString" function was because I was running into an issue where <variable>.readFileSync isn't a method. If i pass it a string of the file's contents, it works just fine.... unless the pug file extends something and then it uses whatever is breaking it if you try to use compileFile/renderFile or compileFileClient. <edit> The same thing happens with compile/render. It works with a string, unless it is extending something. </edit>

=======ERROR=======
Uncaught TypeError: o.readFileSync is not a function _[o = e("fs") ------ If I try to require('fs'), I get MODULE NOT FOUND. require = function e(t, n, r)]_
    at index.pug line 1 _[extends layouts/main.pug]_
    at index.pug line 1 _[extends layouts/main.pug]_
    at Function.r.read (http://192.168.2.21:3000/lib/pug.js:11932:22)
    at Object.read (http://192.168.2.21:3000/lib/pug.js:20788:49)
    at http://192.168.2.21:3000/lib/pug.js:11894:85
    at r (http://192.168.2.21:3000/lib/pug.js:12901:28)
    at http://192.168.2.21:3000/lib/pug.js:12888:29
    at Array.reduce (<anonymous>)
    at o (http://192.168.2.21:3000/lib/pug.js:12887:26)
    at r (http://192.168.2.21:3000/lib/pug.js:12907:31)
    at r (http://192.168.2.21:3000/lib/pug.js:11888:65)
    at Function.r.string (http://192.168.2.21:3000/lib/pug.js:11920:20)

**Comment by JourdanClark** [comment]
Sorry this is completely off topic, but I just noticed the template for creating these threads has a typeo. "Node Vesrion" 
I tried creating a new thread and it was also there.

**Comment by ForbesLindesay** [comment]
You should use something like webpack with pug-loader.  You should not have your cordova app compile pug templates on the fly.  This would be **EXTREMELY** slow, like 10s of seconds added to start up time slow.  The standalone pug build is intended exclusively for the pug documentation, it does not support extends or include because they can't be made to work in a browser. This is also why you were forced to work around the lack of readFileSync.
