### ISSUE TITLE
pug/jade limit

### ISSUE THREAD

**Issue by alieslamifard** [pugjs/pug#2846]
hi
is there any limit on .jade file for compile?
i have over than 50 .jade file and jade do not compile my new file anymore. 
i just delete some of .jade file and it works fine after that.
thanks

**Comment by jonathanarbely** [comment]
Do you get any error messages in the console?

**Comment by ForbesLindesay** [comment]
This limit is not caused by pug, it could be caused by whatever tooling you're using to access pug, but the raw API has no such limit.
