### ISSUE TITLE
Unable to debug syntax errors 

### ISSUE THREAD

**Issue by lopugit** [pugjs/pug#2850]
**Pug Version:** 2.0.0

**Node Vesrion:** 6

## Input JavaScript Values

```js
res.render('pages/home');
```

## Input Pug

```pug
Include /snippets/head
Include /snippets/banner
Include /snippets/productSection
Include /snippets/footer
```

## Additional Comments

So I've been working with pug for about half a year, and I've gotten seriously into it now. But I've run into a problem with debugging and rendering via res.render('template')

If I happen to do something wrong such as forget a comma in a json object or use sqrt() instead of Math.sqrt(), I get acorn.js errors via my browser, which tell me an expected token error, or rvalue assign error. And the line number. But the line number doesn't exactly help because conditional statements in the template may make the code be 3000 lines long or 1500, depending on what products there are, and other variables. And the fact that the root layout file simply includes other files, so the only way I can track these line numbers down is by manually going through the code to see what would render, and count the damn line numbers of each file and add them up.

Is there a better way??

I like the way pug gives you a 5 or 6 line code preview with a long line of ====== signs under the line with the error when you get an undefined or cannot read property error. Is there something like this for syntax and acorn compilation errors?

Ty ty

**Comment by ForbesLindesay** [comment]
There is no good way of pinning down syntax errors like missing a comma in a js object, at least not without a lot of work on our part that I suspect won't be done any time soon.

You should get correct errors output in development for reference errors though. e.g. sqrt instead of `Math.sqrt`.

**Comment by lopugit** [comment]
I've encountered it in a lot of build languages or whatever it's called. There should be a buffer/log kept of correct syntax up until the point of failure, seems like an easy solution.

I will leave the compilation logic to you though.

Thank you so much for jade. 

Appending to blocks from inside includes would be spectacular though, you must have a busy life. I appreciate all the work you've put into jade. 

Take care :)
