### ISSUE TITLE
Pug Sharing Data from JS file to PUG file which has been included in another PUG

### ISSUE THREAD

**Issue by amirzandi** [pugjs/pug#2851]
I am currently creating a website that in most parts I should display such numbers and counters to users. 
These numbers are generally gathered from a database such row count, customer count etc. 
I have created several partials and include them in other PUGs that users need to see the counters.

Queries are executing in a JS file and the results must be passed to these partials. I am not quite sure wether it is possible with PUG engine or not.
If so, please help me in this matter.

Thank you very much.

**Comment by ForbesLindesay** [comment]
Please ask this kind of question on stackoverflow.com
