### ISSUE TITLE
Empty line at the beggining og the file

### ISSUE THREAD

**Issue by birdy90** [pugjs/pug#2854]
**Pug Version:** 2.0.0-beta9

**Node Vesrion:** 6.9.4 (windows)

## Input Pug

```pug
| <?php header('Content-Type: text/xml; charset=utf-8', true);
| require_once($_SERVER['DOCUMENT_ROOT'].'/admin/core/init.php');
| $root = $_SERVER['DOCUMENT_ROOT'];
| require_once($root.'/config/site/router.php'); ?>
```

I have this template rendered and get plain text (php code, actually). But I'm getting an empty line before the text (5 lines instead of 4). But if I change my template to this: 

```pug
<?php header('Content-Type: text/xml; charset=utf-8', true);
| require_once($_SERVER['DOCUMENT_ROOT'].'/admin/core/init.php');
| $root = $_SERVER['DOCUMENT_ROOT'];
| require_once($root.'/config/site/router.php'); ?>
```

I don't get empty line, so my text goes from the very beginning of file (4 lines).

Some strange thing: if I clear this file and write only `div` here, I'll get `<div></div>` on the second line and first line is empty. Is my file is corrupted in some way or there's something I should know but I'm missing?

**Comment by ForbesLindesay** [comment]
Make sure you have pretty mode disabled, if that doesn't work, comment and I can re-open.

**Comment by birdy90** [comment]
Yes, you're right. I have `pretty: true` option. When I turn it off, I get a solid block of text, that is not quite suitable for debugging. But I don't undertand why I'm getting an empty line at the very beginning where there is no empty line in a template. And other files are built well. Every other file starts with:
```
extends ../layouts/main
```
and `../layouts/main` starts with:
```
| <?php require_once($_SERVER['DOCUMENT_ROOT'].'/admin/core/init.php'); ?>
```
And the last paragraph of my original question is still not clear for me

**Comment by ForbesLindesay** [comment]
Pretty mode is not recommended, it is never safe to use pretty mode if your output is whitespace sensitive.

**Comment by birdy90** [comment]
Thanks for your answer! My usecase is to use pretty mode in development, but RSS files built while pretty mode is on are corrupted because of this empty line. So I have to switch mode to debug RSS and then sending them to pruduction (it may be confusing - I don't use pug for RSS, actually, but my backend uses it all over, so I have to build with pug pipe)
