### ISSUE TITLE
ad adsense code

### ISSUE THREAD

**Issue by utan** [pugjs/pug#2855]
Hi, forgive me if this was already anwsered before.. 

How do you insert adsense code in PUG files?

any example?

**Comment by Tiliavir** [comment]
```
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Homepage Leaderboard -->
<ins class="adsbygoogle"
style="display:inline-block;width:728px;height:90px"
data-ad-client="ca-pub-1234567890123456"
data-ad-slot="1234567890"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

gets

**Comment by utan** [comment]
Thank you, i will try ur code. Asap.

**Comment by chovy** [comment]
adsense changed their code snppet recently. My app keeps crashing when I try to add it.

`script(data-ad-client='ca-pub-9632070867896053', async='', src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js')`
