### ISSUE TITLE
can't use pug with webpack2  

### ISSUE THREAD

**Issue by constantank** [pugjs/pug#2856]
when i compile ,this came up,
Module not found: Error: Can't resolve 'fs' in 'C:\Users\lk\Desktop\wb\node_modules\pug-load',

do you know what's wrong? help me thank you .

**Comment by constantank** [comment]
this is my js file.
const pug = require('pug');
console.log(pug)

**Comment by ForbesLindesay** [comment]
If you want to use pug with webpack, you need to use https://github.com/pugjs/pug-loader

Using pug dynamically in client side code like you were attempting will be extremely slow (although it can be made to work by configuring webpack to provide empty mocks of node core modules).
