### ISSUE TITLE
(Ubuntu 16.04, LinuxMint 18.2, Windows 10) pug-cli: command not found

### ISSUE THREAD

**Issue by Appy-Daze** [pugjs/pug#2857]
**Pug Version:** your version number here
2.0.0-rc.3

**Node Vesrion:** your version number here
v4.2.6

## Input JavaScript Values

```js
pug.renderFile('input.pug', {
  whatIsIt: 'language',
});
```

## Input Pug

```pug
h1 I Love Pug
p It's a great #{whatIsIt}
```

## Expected HTML

```html
<h1>I Love Pug</h1>
<p>It's a great language</p>
```

## Actual HTML

```html
<h1>I Love Pug</h1>
<p>It's a great language</p>
```

## Additional Comments
To reproduce (confirmed on Win10, Ubuntu 16.04, LinuxMint 18.2):
  1) install node.js
  2) install pug-cli globally
  3) try to run pug-cli
  4) embrace the disappointment, pet it, watch a Ukrainian Dash Cam video while sighing loudly

I installed as root with "npm install pug-cli --global" (Install order: nodejs/npm->nodemon->pug->pug-cli all but pug-cli went as expected)

This is a GLOBAL install...... So ENV shouldn't really matter as long as "pug" - installed the same way - is found (/usr/local/bin/pug - which is a link to /usr/local/lib/node_modules/pug-cli/index.js).

The folder "/usr/local/lib/node_modules/pug-cli" is there after the install, but there is no file or sym link named "pug-cli" on the system. Which is, of course, why it is not found.

I tried this yesterday, on Windows 10. Same problem. I concluded that the pug-cli install process is broken, hence this report.

Thanks for peaking my interest, btw. I never looked at Jade, then yesterday, spotted an article on pug, got excited, then spent an afternoon verifying that I wasn't making a newbie mistake. But I'm interested enough to not just write it off as wasted time.

**Comment by ForbesLindesay** [comment]
The binary name is `pug`, not `pug-cli`. `pug-cli` is the name of the package.  See pugjs/pug-cli#66
