### ISSUE TITLE
Passing variables from Node results in 'undefined'

### ISSUE THREAD

**Issue by AaronGillBraun** [pugjs/pug#2859]
I have read through multiple questions and issues regarding passing variables from your express app to pug, but none of them seemed to help fix my error. I want to pass a global settings variable from a config file, through express and finally to pug.

_routes.js_
`res.render('index', { FORM_SELECTOR: config.FORM_SELECTOR });`

_index.pug_
```input(type="file" name=`${FORM_SELECTOR}` multiple)```

The variable is fine, because it is used elsewhere in the script without error. But when compiled, the html shows:

_index.html_
`<input type="file" name="undefined" multiple="multiple"/>`

**Comment by ForbesLindesay** [comment]
This should work fine. I suggest you attempt to narrow it down to a small test case that fails.
