### ISSUE TITLE
Dynamic src in script

### ISSUE THREAD

**Issue by jechenique** [pugjs/pug#2871]
**Pug Version:** pug@2.0.0-rc.4

**Node Version:** 8.4.0

## Input JavaScript Values

```js
    res.render('private_layout', {user: req.user, include: ['/private.bundle.js']});
```

## Input Pug

```pug
        each file in include
            script(src='#{file}')
```

## Expected HTML

```html
<script (src='/private.bundle.js''></script>
```

## Actual HTML

```html
<script (src='#{file}'></script>
```

## Additional Comments

Hi there,
I need to set the script src dynamically, but when using the interpolation directly into the src it doesn't works.
The only way to have it working is setting a client side javascript variable and then use that variable into the src.
Can you please let me know whether is this a bug or not?

Regards

**Comment by silentrob** [comment]
Im also seeing this in `Node v6.9.1` Same version of Pug

**Comment by ekfuhrmann** [comment]
Does `script(src= file)` not work?

**Comment by jechenique** [comment]
> Does script(src= file) not work?
Yes it does. Since every answer I found on the internet was with interpolation, I thought it should be done that way. If it is supposed to work that way then is ok.

> each file in include
    script(src=`#{file}`)
With back ticks it doesn't works, the output is
`<script src="#{file}"></script>`

Since it works with the first option I'll leave it that way.
Thank you very much!

**Comment by ekfuhrmann** [comment]
Sorry about that! Back ticks do work, however we were using the wrong token. You should use a `$` for attribute interpolation.

```pug
each file in include
    script(src=`${file}`)
```

Also you're most likely looking at the old API. See [here](https://pugjs.org/api/migration-v2.html) for Pug2 changes which shows both methods I shared with you.

**Comment by jechenique** [comment]
> You should use a $ for attribute interpolation.
Thank you Eric, this way works.

Regards

**Comment by ForbesLindesay** [comment]
No No No, these are plain JavaScript values. Backticks work because they are the ES6 feature, template literals.  If you only have a single value being interpolated, you don't need them:

```pug
each file in include
    script(src=file)
```

The whole point of removing `#{}` support was to help people learn that these values are plain JavaScript, please don't replae `#{}` magic with `${}` magic.

**Comment by jiveshsoftsolution** [comment]
> Sorry about that! Back ticks do work, however we were using the wrong token. You should use a `$` for attribute interpolation.
> 
> ```
> each file in include
>     script(src=`${file}`)
> ```
> 
> Also you're most likely looking at the old API. See [here](https://pugjs.org/api/migration-v2.html) for Pug2 changes which shows both methods I shared with you.

Thanks, this solution worked for me.
