### ISSUE TITLE
cannot use regexp in pug

### ISSUE THREAD

**Issue by willin** [pugjs/pug#2874]
**Pug Version:** 2.0

**Node Version:** 6.10

## Input Pug

```pug
span= '你好'.match(new RegExp("\[^\x00-\xff\]","g")) || []).length
```

## Expected HTML

```html
<span>2</span>
```

## Actual HTML

Error:

error message: expected token ',', got 'RegExp'

## Additional Comments

also tried:

```js
.match(/[^\x00-\xff]/g)
.match(/\[^\x00-\xff\]/g)
.match(new RegExp("[^\x00-\xff]","g")
```

all cannot work

**Comment by droooney** [comment]
Probably, you forgot to insert a `(` in front of the whole JavaScript block.

```pug
span= ('你好'.match(new RegExp("\[^\x00-\xff\]","g")) || []).length
```

seems to be working quite well.

**Comment by ForbesLindesay** [comment]
Yes, the syntax error is correct.  The issue is the `)` before `.length` has no matching `(`.
