### ISSUE TITLE
Feature: allow to configure pug to close void html elements in html5 mode.

### ISSUE THREAD

**Issue by famer** [pugjs/pug#2875]
**Pug Version:** 1.11.0

**Node Version:** 6.11.3

## Input JavaScript Values

```js
pug.renderFile('input.pug', {
  closeVoid: true,
});
```

## Input Pug

```pug
doctype html
img(src="foo.png")
```

## Expected HTML

```html
<!DOCTYPE html>
<img src="foo.png" />
```

## Actual HTML

```html
<!DOCTYPE html>
<img src="foo.png">
```

## Additional Comments
According to [HTML 5 syntax: Start tags p.6](https://www.w3.org/TR/html5/syntax.html#start-tags) single "/" (U+002F) character is allowed as part of the [void elements](https://www.w3.org/TR/html5/syntax.html#void-elements).  
Allow [void elements](https://www.w3.org/TR/html5/syntax.html#void-elements) to have slash character at the end via [options configuration](https://pugjs.org/api/reference.html#options).  
Some engines such as [Thymeleaf 2.x](http://www.thymeleaf.org/) forces void object to have trimming slash even for html5 templates as part xml-like validation. It would be nice to be able to configure pug optionally close void elements.

**Comment by droooney** [comment]
You can use `html5` doctype instead of `html`:

```pug
doctype html5
img(src="foo.png")
```

will be transpiled to

```html
<!DOCTYPE html5>
<img src="foo.png"/>
```

Also, you can explicitly define a self-closing tag by simply putting a `/` at the end of the tag:

```pug
doctype html
img(src="foo.png")/
```

will be transpiled to

```html
<!DOCTYPE html>
<img src="foo.png"/>
```

**Comment by famer** [comment]
Thank you.

**Comment by dippas** [comment]
@droooney AFAIK and from [w3c list](https://www.w3.org/QA/2002/04/valid-dtd-list.html) `doctype html5` it is not standard, can you tell the differences between `doctype html` & `doctype html5` ?

**Comment by silveoj** [comment]
Nothing about `doctype5` on https://pugjs.org/language/doctype.html

I don't get slash like in documentation if
- skip doctype in options and pug file
- with ```doctype html``` in pug

```'<img src="foo.png">'``` // output with default doctype in pug

I get slash
- with `doctype: 'random_symbols'`
- with ```doctype html5``` in pug

```'<img src="foo.png" />'```
