### ISSUE TITLE
Cannot compile all pug's files on project in one script command, please help!

### ISSUE THREAD

**Issue by Sterpa** [pugjs/pug#2881]
**Pug Version:** 2.0.0-rc.4

**Node Version:** v8.6.0

## Additional Comments

I cannot compile all pug's files in one script command, please help!
I use VSCode
In package.json I set `"scripts": {"pug": "pug components/{**/**,**}/*.pug --no-debug --client --name-after-file --extension=pug.js"}` to compile all pug's file in "components" dir,
and run it as - `$ npm run pug`

And every time i got an error:

> > components_1808_2130@1.0.0 pug C:\Users\mikha\Downloads\components_1808_2130
> > pug components/{**/**,**}/*.pug --no-debug --client --name-after-file --extension=pug.js
> 
> fs.js:948
>   binding.lstat(pathModule._makeLong(path));
>           ^
> Error: ENOENT: no such file or directory, lstat 'C:\Users\mikha\Downloads\components_1808_2130\components\{**\**,**}\*.pug'
>     at Object.fs.lstatSync (fs.js:948:11)
>     at renderFile (C:\Users\mikha\Downloads\components_1808_2130\node_modules\pug-cli\index.js:246:17)
>     at C:\Users\mikha\Downloads\components_1808_2130\node_modules\pug-cli\index.js:149:5
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (C:\Users\mikha\Downloads\components_1808_2130\node_modules\pug-cli\index.js
> :148:9)

If i do not use "*" simvol in command - all works fine, if i try to use `*.pug` - i got en error...
What i do wrong!? help please

**Comment by Manmanrai** [comment]
Try this!
`pug *.pug *.html --pretty -w`
