### ISSUE TITLE
Passing mixins as arguments (mixins composition)

### ISSUE THREAD

**Issue by jakub-swierk** [pugjs/pug#2882]
**Pug Version:** 2.0.0-rc.4

**Node Version:** v8.5.0

## Input Pug

```pug
mixin list(data, formatter)
  ul
    for entry in data
      +formatter(entry)
  
mixin question_formatter(data)
  li=`${data}?`
  
+list(['a','b','c'], question_formatter)
```

## Expected HTML

```html
<ul>
  <li>a?</li>
  <li>b?</li>
  <li>c?</li>
</ul>
```

## Actual error

```js
pug_mixins.formatter is not a function
```

## Additional Comments

Can be mixins be passed as arguments to other mixin or they are defined in global namespace? 
It's there some workaround except defining `formatter` just before list mixin use?

**Comment by kylekatarnls** [comment]
Mixin can not be passed like this. And it also seems to me like a very confusing pattern you should not use.

Moreover, mixins are loaded on demand, this means question_formatter is not available in the `pug_mixins` var until you call it one. I think I can find a work-around for this.

**Comment by kylekatarnls** [comment]
See this:
```js
mixin list(data, formatter)
  ul
    for entry in data
      - pug_mixins[formatter](entry)
  
mixin question_formatter(data)
  li=`${data}?`

+question_formatter()
= Object.keys(pug_mixins)
+list(['a','b','c'], 'question_formatter')
```

It works, the only problem is you have to call `+question_formatter()` to enable the mixin.

**Comment by kylekatarnls** [comment]
Another trick, if you call a mixin with a dynamic name, you get all mixins available:

```js
mixin list(data, formatter)
  ul
    for entry in data
      - pug_mixins[formatter](entry)
  
mixin question_formatter(data)
  li=`${data}?`

+#{'list'}(['a','b','c'], 'question_formatter')
```

**Comment by jeromew** [comment]
or more simply

````pug
mixin list(data, formatter)
  ul
    for entry in data
      +#{formatter}(entry)
  
mixin question_formatter(data)
  li=`${data}?`
  
+list(['a','b','c'], 'question_formatter')
````
this way you do not have to rely on the "pug_mixins" variable which is an internal variable.

As @kylekatarnls said, all mixins are compiled but are only kept in the final rendering function is they are used. As soon as there is one dynamicMixin call somewhere, pugjs cannot know if a mixin will be used or not so all mixins are kept. cf https://github.com/pugjs/pug/blob/master/packages/pug-code-gen/index.js#L111 for more details.

**Comment by jakub-swierk** [comment]
@kylekatarnls and @jeromew thank you. I didn't know about `+#{formatter}(entry)`.

> And it also seems to me like a very confusing pattern you should not use.

In my project i have to display about ~50 tables where cells have different content (buttons, texts, anchors, graphs). And best i can figure ot is to create `table` mixin with custom row formatter.

Example:
```pug
// helpers/table.pug

mixin table(data, labels, empty)
    if data.length == 0
        .alert.alert-primary.m-3(role='alert')=empty
    else
        table.table.table-rwd.mb-0
            thead
                tr
                    for label in labels
                        th=label
            tbody
                for row in data
                    tr
                        +tr(row)

// sensors/index.pug

append content
    mixin tr(sensor)
        td: a(href=`/sensor/${sensor.id}`)=sensor.id
        td: a(href=`/bts/${sensor.bts}`)=sensor.bts
        td: a(href=`/building/${sensor.building.id}`)=sensor.building.name
        td: svg(...)
              //- svg with sensor.building.temperature data as graph

    +table(sensors, ['ID', 'BTS', 'Building', 'Temperature'], 'No matching sensors found.')

```
Is there other way to do it or maybe i should just write every table from scratch?
