### ISSUE TITLE
NodeJS code fails to launch after bundling with webpack default config

### ISSUE THREAD

**Issue by rsadyhov** [pugjs/pug#2889]
Pug Version: ^2.0.0-rc.4

Node Version: 7.8.0

Webpack Version: 3.5.6

Inside bundled output I'm getting this:

```js
.map(function(file){
    return /*require.resolve*/(!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
});
```

As result, NodeJS fails to launch. This is because of UglifyJS and I found pretty similar issue here https://github.com/webpack/webpack/issues/4786

Please advise.

**Comment by apokryfos** [comment]
After some digging I've narrowed down that code as being the product of the UglifyJS code segment found in https://github.com/mishoo/UglifyJS2/blob/master/tools/node.js#L4:

```
var FILES = UglifyJS.FILES = [
    "../lib/utils.js",
    "../lib/ast.js",
    "../lib/parse.js",
    "../lib/transform.js",
    "../lib/scope.js",
    "../lib/output.js",
    "../lib/compress.js",
    "../lib/sourcemap.js",
    "../lib/mozilla-ast.js",
    "../lib/propmangle.js",
    "../lib/minify.js",
    "./exports.js",
].map(function(file){
    return require.resolve(file);
});
```

I am however a bit puzzled. Uglify is referenced as a dev dependency so there shouldn't be any production code trying to use it because chances are production installs won't have downloaded dev dependencies.

I've also [asked a question on StackOverflow](https://stackoverflow.com/questions/47452820/getting-error-cannot-find-module-at-webpackmissingmodule)

**Comment by iShawnWang** [comment]
I saw the solution on the SO, but still can't accept the answer, why the configuration is so complex and confused, hoping there is a standardization in the 2019

**Comment by ForbesLindesay** [comment]
This is an issue with UglifyJS. UglifyJS does not support being bundled with Webpack. Please take that up with them as there's nothing I can do about it. I'm sorry, I know this sucks.

**Comment by guybedford** [comment]
Perhaps switching to TerserJS (the new replacement for UglifyJS2) would help avoid this problem?

**Comment by ForbesLindesay** [comment]
We're using UglifyJS for a lot more than just minifying. I think we will ultimately move to babel, but supporting bundling the entire pug compiler with webpack is not currently a priority.

**Comment by ondrejrohon** [comment]
There should be a warning in readme that you can't bundle pug with express. I used pug for years, but now for the first time in webpack project. This issue is very frustrating.

**Comment by ondrejrohon** [comment]
and this issue should be imho open

**Comment by wood1986** [comment]
Hey @ForbesLindesay I have 2 questions

1. If you are going to move away from UglifyJS, will it be a major/minor release?
2. Have you thought about terser?

**Comment by bastidest** [comment]
Possible solution for those who don't want to use [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) and actually want to bundle thirdparty dependencies with dynamic imports. I made a tiny Webpack plugin for that: ([context-map-webpack-plugin](https://github.com/bastidest/context-map-webpack-plugin))

It works for me with the following configuration:
```js
    new ContextMapPlugin('node_modules/uglify-js/tools', [
      '../lib/utils.js',
      '../lib/ast.js',
      '../lib/parse.js',
      '../lib/transform.js',
      '../lib/scope.js',
      '../lib/output.js',
      '../lib/compress.js',
      '../lib/sourcemap.js',
      '../lib/mozilla-ast.js',
      '../lib/propmangle.js',
      './exports.js',
    ]),
    new ContextMapPlugin('node_modules/pug-filters/lib', [
      // I don't use any js-transforms
    ]),
```

**Comment by DanielOrtel** [comment]
not to be annoying, but this is still a problem, 3 years after the OP. Any news?

**Comment by trasherdk** [comment]
@gastonrey Take a look at https://github.com/pugjs/pug/issues/2889#issuecomment-456477196
