### ISSUE TITLE
Online demo link in README missing

### ISSUE THREAD

**Issue by TeffenEllis** [pugjs/pug#2892]
Navigating to https://pugjs.org redirects to https://pugjs.org/api/getting-started.html, rather than an online demo as the README suggests.

**Comment by mikesamuel** [comment]
For context, I think this refers to the third paragraph in [README.md](https://raw.githubusercontent.com/pugjs/pug/926f7c720112cac76cfedb003e25e9f43d3a1767/README.md):

> You can test drive Pug online [here](https://pugjs.org/).

**Comment by mikesamuel** [comment]
Perhaps that README link should point to [`api/reference.md`](https://github.com/pugjs/pug-en/blob/master/src/api/reference.md#api-reference) which says

> ::: float info Tip Pug is available in your Web browser's console! To test drive Pug's API, as documented on this page, try entering:
> 
> pug.render('p Hello world!');
> :::

**Comment by mikesamuel** [comment]
That page corresponds to https://pugjs.org/api/reference.html.

Will send a PR.

**Comment by ForbesLindesay** [comment]
The website is sadly still a long way form finished, I will get round to it eventually.

**Comment by mikesamuel** [comment]
Fwiw, https://github.com/pugjs/pug/pull/2894 tries to fix this.
