### ISSUE TITLE
how in one .jade use the variable curr from another .jade???

### ISSUE THREAD

**Issue by hello-guoguo** [pugjs/pug#2896]
1. layout.jade:
doctype html
head
  meta(charset="utf-8")
  link(rel="shortcut icon", href="/static/img/favicon.ico", type="image/x-icon")
  block info
  link(rel="stylesheet", href="/static/style/reset.css")
body
  block header
  block section
  block footer
--------------------------------------------
2. main.jade: 
extends ../../commons/layout/layout.jade
block info
  title 首页title
  meta(name="keywords", content= "首页关键字")
  meta(name="description", content= '首页描述')
prepend header
  -- var curr = 'index'
  include ../../commons/header/header.jade
block section
  div.section 首页section
block footer
  div.footer 首页footer

---------------------------------------------
3. header.jade:
ul.nav
  li
    a(href="javascript:;" class= curr=='index'?'on':'') 首页#{curr}
  li
    a(href="javascript:;" class= curr=='aaa1'?'on':'') 首页1
  li
    a(href="javascript:;" class= curr=='aaa2'?'on':'') 首页2
  li
    a(href="javascript:;" class= curr=='aaa3'?'on':'') 首页3

finally,as you can know,how in header.jade use the variable curr from main.jade???
who can help me,please!

**Comment by droooney** [comment]
First off, use the `pug` package instead of `jade`, because the latter is deprecated.

About your issue: you've done exactly what you needed to do, and using the new `pug` will do the job perfectly. You can read about template inheritance [here](https://pugjs.org/language/inheritance.html).

P.S.: to post a piece of code use `markdown`, so that the indents won't be lost and the code will be easier to read.

**Comment by hello-guoguo** [comment]
I will try it,and thank you very much!

**Comment by hello-guoguo** [comment]
@droooney:

Hello, I'm already use the pug package instead of jade, but it still not in effect.
P.S: I use pug through the tool of webpack,and I doubt the pug-loader has bug.

**Comment by droooney** [comment]
Once again, could you post the pieces of code using `markdown` ([here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) you can read how) as your code now doesn't have any indents and indentation is very important for `pug`? Also what's the result of rendering this? Does this result in an error and if yes could you post it as well?

**Comment by hello-guoguo** [comment]
@droooney 
Thanks again，I'm already solved it，and I use two loaders（html-loader/pug-html-pug）instead of pug-loader，then it‘s working order。hei~hei~
