### ISSUE TITLE
data-src problem

### ISSUE THREAD

**Issue by robbisy** [pugjs/pug#2898]
Hi I'm trying to create a cards mixins in codepen which take two variables image and text
image work with src but it doesn’t work with `data-src` and I don't understand why.
I don't know the node or pug version use in codepen
here is the [codepen link](https://codepen.io/anon/pen/aVBXXp)

**Comment by droooney** [comment]
The `data-src` attribute is set there.

**Comment by robbisy** [comment]
@droooney where ?

**Comment by droooney** [comment]
The `img` element has both `data-src` and `title` attributes set. Try inspecting the demo frame.

**Comment by michellomp** [comment]
@droooney I think what robbisy trying to ask is why image didn't appear because you're right the pug is correctly converted to html but the image didn't appear indeed
![pug](https://user-images.githubusercontent.com/13666439/32608935-34919330-c55e-11e7-9b65-50917cfa426d.png)
