### ISSUE TITLE
Cannot set value of nonce attribute. [solved]

### ISSUE THREAD

**Issue by GCDeveloper** [pugjs/pug#2899]
**Pug Version:** ^2.0.0-rc.4

**Node Version:** 8.9.0

## Input JavaScript Values

```js
pug.renderFile('input.pug', {
  nonce: "some-nonce",
});
```

## Input Pug

```pug
script(nonce=nonce).
    //some code
style(id=nonce)&attributes({'nonce': nonce}).
```

## Expected HTML

```html
<script nonce="some-nonce">
//some code
</script>
<style id="some-nonce" nonce="some-nonce"></style>
```

## Actual HTML

```html
<script nonce>
//some code
</script>
<style id="some-nonce" nonce></style>
```

## Additional Comments

Any string or number value given for attribute nonce is ignored and not set.

Despite the above, I ran tests and 
assert.equal('<script nonce="some-nonce"></script>', pug.render('script(nonce="some-nonce")'), 'Test nonce')
passed. So I am confused.

**Comment by droooney** [comment]
Running

```pug
pug.render('script(nonce=nonce)', { nonce: 'some-nonce' })
```

in the browser console on the pug documentation page resulted in

```html
<script nonce="some-nonce"></script>
```

**Comment by GCDeveloper** [comment]
Yes, correct, it was just that the nonce value was not visible with element inspect in Google Developer tools (I think for security reasons).

**Comment by droooney** [comment]
I'll just close it.

BTW: I don't think that the developer tools have anything to do with it as they do show the actual content therefore the attribute should be visible (maybe it doesn't exist by the moment you look at it in the developer tools).

**Comment by GCDeveloper** [comment]
see https://github.com/whatwg/html/issues/2369#issuecomment-343226224

**Comment by droooney** [comment]
Ah, I see. It is indeed expected :)
