### ISSUE TITLE
JavaScript load order messed up

### ISSUE THREAD

**Issue by csakis** [pugjs/pug#2901]
I posted a bug on StackOverflow 2 weeks ago. I believe it's a pretty serious issue that needs some more attention. 
https://stackoverflow.com/questions/46979947/jade-bug-loading-order-of-scripts-is-messed-up

**Comment by droooney** [comment]
I don't see how it's related to `pug` as the output html is correct.

**Comment by csakis** [comment]
What else can cause this problem if not `pug`?

**Comment by droooney** [comment]
Well, in your StackOverflow post it's clearly written by yourself that the output html is correct :) What's happening next with that html is not a pug concern and has nothing to do with it. If the output html is *not* correct, please, post a minimal reproduction of the input and the output.

**Comment by csakis** [comment]
I understand your point. It's logical. The only argument I can make is that if I use handlebars or dust.js, I do not have this problem. Only pug seems to present this weird behavior.

**Comment by droooney** [comment]
Then please a full minimal reproduction in which you encounter such behavior.

**Comment by csakis** [comment]
Then I should what?

**Comment by droooney** [comment]
Post minimum amount of code that reproduces the issue.

**Comment by csakis** [comment]
Sounds good, I'll make a small github repo, then share the link here

**Comment by droooney** [comment]
That's exactly what's needed :)
