### ISSUE TITLE
Is pug-lint still supported by pugjs?

### ISSUE THREAD

**Issue by lightbringer1991** [pugjs/pug#2903]
I don't know if this is appropriate to have a stackoverflow question, as it seems to be more management/support question.
So recently I upgraded from jade to pug (I know it's like 2 years late). And for the first time, `pug-lint` seems to be a great choice to uphold our code style. However, we hit some limitation that it doesn't support (hopefully not for long). 
I have submitted a pull-request to close similar issues we encountered that other people also have. But when I look through the issue list, it seems that the repo is not very active, issues are not being answered to, and PRs are going stale.

I'm just wondering if it is abandoned, or has not acquired a good attention from the community/organization.

**Pug Version:** your version number here
N/A

**Node Version:** your version number here
N/A

## Input JavaScript Values
N/A

## Input Pug
N/A

## Expected HTML
N/A

## Actual HTML
N/A

## Additional Comments
N/A

**Comment by ForbesLindesay** [comment]
pug-lint is not maintained by me personally, but is still officially supported. In general "Is X still maintained" issues often come across as entitled and offensive, but I'll give you the benefit of the doubt and assume good intentions:

If you feel your pull request is high quality (i.e. you've done your best to write clean code and add tests if appropriate) and it appears to be being ignored, please open a new issue on this repository asking to be added as a maintainer.  Provide a link to your pull request as evidence of your investment in the project and I will add you as a maintainer, then you can help clear the backlog of issues/pull requests.
