### ISSUE TITLE
Warning: You should not have pug tags with multiple attributes.

### ISSUE THREAD

**Issue by svenyonson** [pugjs/pug#2906]
**Pug Version:** 2.0.0-beta11

**Node Version:** 8.9.0

## Input JavaScript Values

```js
pug.renderFile('input.pug', {
  whatIsIt: 'language',
});
```

## Input Pug

*views/partials/device-update.pug*
```
include ../mixins/device
+device-details(device)
```
*views/mixins/device.pug*

```mixin device-details(details)
	div.device(id=details.device.UID, onclick="clickDevice(this);")
		div.header
			h3.dev-name=details.device.TYPE
		div.detail
			table.device-details
				tr
					td.key Manufacturer
					td.val=details.device.MFG
				tr
					td.key Model
					td.val=details.device.MODEL
				tr
					td.key SN#
					td.val=details.device.SN

```

## Expected HTML

```HTML is OK
```

## Actual HTML

```HTML is OK
```

## Additional Comments
This line:
```
div.device(id=details.device.UID, onclick="clickDevice(this);")
```
Is throwing a warning: *You should not have pug tags with multiple attributes.*
Multiple attributes  separated by commas should be permitted. Because of this warning, 
I am not able to set header values as text has already been sent in the warning.

**Comment by droooney** [comment]
Need more info on this. You didn't specify full pug files, variables, mixin initialization and etc. A minimal reproduction will do.

**Comment by svenyonson** [comment]
Hello. 

Thanks for the quick reply. I have pared down a minimal reproduction - attached is a .zip of the full project.

Console output:
$ node pug-demo.js 
/Users/svenyonson/github/micronets/pug-demo/views/mixins/device.pug, line 3:
You should not have pug tags with multiple attributes.
GET /test 304 258.280 ms - -


Browser:


The offending line is pug-parser/index.js LINE 1009

Project:


Thanks,

Steve

**Comment by droooney** [comment]
Where is the `.zip` file you were talking about? A repo would be an ideal solution for the reproduction.

**Comment by svenyonson** [comment]
It was attached to my last email, but perhaps it was blocked.

Git repo here: https://github.com/svenyonson/pug-test.git <https://github.com/svenyonson/pug-test.git>

**Comment by svenyonson** [comment]
Looks like the screenshots I sent along with the zip were also found.
You can test the request that causes the warning with this url:
`localhost:3000/test`

**Comment by droooney** [comment]
Please, provide *a minimal reproduction*: just pug code and js code with only `pug.render` or `pug.renderFile`. The express (or anything else) related things don't have anything to do with pug issues.

**Comment by svenyonson** [comment]
Ah, hadn't thought of standalone pug code. Please do a pull, I replaced the code with a minimal reproduction. You will notice that despite the warning from  pug-parser/index, the generated html code is correct, with both attributes.

**Comment by droooney** [comment]
Ah, I see. Here:

> This line:
> 
> div.device(id=details.device.UID, onclick="clickDevice(this);")
> Is throwing a warning: You should not have pug tags with multiple attributes.

you've written that your code looks like this, though it looks like this in your repro:

```pug
div(id=details.device.UID).device(onclick="clickDevice(this);")
```

which is why the warning was printed. I don't really know why this syntax is not recommended in the first place, but rewriting the line as 

```pug
div.device(id=details.device.UID, onclick="clickDevice(this);")
```

will do the job.

**Comment by svenyonson** [comment]
Thats weird. I unintentionally had two copies of device.pug, one in ./partials (correct) and one in ./mixins (incorrect). I thought I was using the correct one but apparently I was not. So yes, the warning makes sense. Thanks for taking a look.
