### ISSUE TITLE
Pug 2 version confusion

### ISSUE THREAD

**Issue by lpellegr** [pugjs/pug#2908]
I am new to pugjs and really confused about what is the latest version of Pug. The [website says the following](https://pugjs.org/api/migration-v2.html):

> Pug 2 was released in August 2016.

However, if I look for the latest version I see the most recent tag is _pug@2.0.0-rc.4_. Is the release candidate the latest version?

**Comment by raisedadead** [comment]
At @lpellegr yes, the readme and the website probably need an update. 
/cc @ForbesLindesay

**Comment by LionNatsu** [comment]
Yes, it is confusing. Pug 2.0.0 WILL be the first version, but yes, it is still a pre-release for now.

A brief history from tag list
```
(now)
 6 Sep 2017 2.0.0-rc.4
 1 Aug 2017 2.0.0-rc.3
 2 Jun 2017 2.0.0-rc.2
 2 May 2017 2.0.0-rc.1
18 Apr 2017 2.0.0-beta.12
 4 Feb 2017 2.0.0-beta.11
29 Jan 2017 2.0.0-beta10
26 Jan 2017 2.0.0-beta9
25 Jan 2017 2.0.0-beta8
24 Jan 2017 2.0.0-beta7
27 Aug 2016 2.0.0-beta6
10 Aug 2016 2.0.0-beta5   <- August 2016
18 Jul 2016 2.0.0-beta4
11 Jun 2016 2.0.0-beta3
 3 Jun 2016 2.0.0-beta2
 3 Jun 2016 2.0.0-beta1
22 May 2016 2.0.0-alpha8
10 May 2016 2.0.0-alpha7
18 Apr 2016 2.0.0-alpha6
↓(Jade)
```

Pug started from 2.x after it had been renamed from Jade.

https://github.com/pugjs/pug-en/blob/master/src/api/migration-v2.md#migrating-to-pug-2

**Comment by yivo** [comment]
Hi guys. 

I am also curious if pug is maintained. Pug hasn't been updated a lot and there are several open PRs. Could please someone handle this?

**Comment by ForbesLindesay** [comment]
Pug is being maintained, and the current release candidate should be stable enough for production applications, but I don't have time to work on it as often as I'd like so it sometimes takes a while before I get time to look at/respond to issues.
