### ISSUE TITLE
Problems rendering example JSX code

### ISSUE THREAD

**Issue by jlmakes** [pugjs/pug#2913]
**Pug Version:** `pug@2.0.0-rc.4`

**Node Version:** `8.6.0`

Initially I ran into this:

```jsx
<Original {...this.props}>
    {children}
</Original>
```

Being rendered by Pug as:

```js
<Original {...this.props}="">
    {children}
</Original>
```

Most people seemed to recommend setting a doctype, but I had already done that. Then I noticed how badly the rest of the JSX came through; take this example:

## Input Pug

```pug
pre(data-lang-js)
    code.lang-js
        :escaped
            // App.js
            import React from 'react'
            import { render } from 'react-dom'

            import List from './List'
            import WithScrollReveal from './WithScrollReveal'

            const RevealedList = WithScrollReveal(List)

            const App = () => (
                <RevealedList options={{ duration: 2000 }} interval={200}>
                    <div>foo</div>
                    <div>bar</div>
                    <div>jam</div>
                </RevealedList>
            )

            render(<App />, document.getElementById('root'))
```

<summary>

> Note: The `:escaped` custom filter just helps to escape illegal characters in example code.

<details>

```js
filters: {
    escaped (block) {
        /**
         * First replace & characters, in order
         * to not escape the & of escaped characters
         * such as &gt; becoming &amp;gt;
         *
         * This solves the issue of highlight.js
         * incorrectly rendering escape characters
         */
        block.replace(/&/g, '&amp;')

        block
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/#/g, '&#35;')
            .replace(/\\/g, '\\\\')

        return block
    },
},
```

</details>
</summary>

## Rendered Output

```jsx
import React from 'react'
import { render } from 'react-dom'

import List from './List'
import WithScrollReveal from './WithScrollReveal'

const RevealedList = WithScrollReveal(List)

const App = () => (
    <revealedlist 2000="" options="{{" duration:="" }}="" interval="{200}">
        <div>foo</div>
        <div>bar</div>
        <div>jam</div>
    </revealedlist>
)

render(<app>, document.getElementById('root'))

</app>
```

The rest of the code comes through fine—HTML, CSS and JS have been working great—but the JSX portion has been mangled.

```diff
- <RevealedList options={{ duration: 2000 }} interval={200}>
+ <revealedlist 2000="" options="{{" duration:="" }}="" interval="{200}">
     <div>foo</div>
     <div>bar</div>
     <div>jam</div>
- </RevealedList>
+ </revealedlist>

- render(<App />, document.getElementById('root'))
+ render(<app>, document.getElementById('root'))
+ 
+ </app>
```

* React components (such as `<RevealedList>`) have been lowercased.
* The props (such as `options={{ duration: 2000 }}` are interpretted token by token as their own attributes (with empty string values).
* The `<App />` passed to `render()` seems to have spawned a closing tag.

Is there a way to have Pug ignore JSX instead of treating it like HTML?

**Comment by droooney** [comment]
Your filter doesn't seem to change the text inside. `String#replace` doesn't modify the string (as strings cannot be changed). Your filter should look like:

```js
filters: {
    escaped(text) {
        return text
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/#/g, '&#35;')
            .replace(/\\/g, '\\\\');
    }
}
```

And the output HTML in your case is perfectly correct, but you rather posted what it looks like in the browser console after the browser has parsed it.

**Comment by jlmakes** [comment]
Great catch @droooney, you're right the filter wasn't doing much... I'm not sure what was going on when creating this filter seemed to help. In fact, the filter in its current form just seems to prevent "unexpected text" errors.

I've done some testing, and it seems the problem is introduced when the syntax highlighter is ran—not the result of Pug.
