### ISSUE TITLE
where is pug "include" api source code

### ISSUE THREAD

**Issue by anlexN** [pugjs/pug#2916]
**Pug Version:** latest

**Node Version:** latest

**Comment by mathiasschopmans** [comment]
https://github.com/pugjs/pug/tree/master/packages/pug-linker

**Comment by ForbesLindesay** [comment]
Pug is a pipeline, the keyword is converted into a token in pug-lexer, then parsed into an AST node by pug-parser, then the file is loaded and parsed in pug-load, pug-linker then strips the include node from the AST and resolves `yield` keywords.
