### ISSUE TITLE
[idea] modularized pug?

### ISSUE THREAD

**Issue by zhangciwu** [pugjs/pug#2917]
Recently working with modularized html project, I think maybe add some modular ability for pug is a good idea.

Here is the idea:

## Source files
list:
```
index.pug
a/a.pug
a/a.js
a/a.css
a/a.jpg

b/b.pug
b/b.js
b/b.css
b/b.jpg
```

index.pug:
```pug
head
    pop(style,dest='all.css')
body
    include a/a
    include b/b
    pop(script,dest='all.js')
    pop(image,dest='image/')
```

a/a.pug:
```
push a.css
push a.js
.content
    p blabla
    push a.jpg
    p blabla
```

js, css, b/* files are omitted

## After compile 

list:
```
index.pug
all.js
all.css
image/a.jpg
image/b.jpg
```

index.pug:
```
head
    link(href="all.css",rel="stylesheet")
body
    .content
        p blabla
        img(src="image/a.jpg")
        p blabla
    script(src="all.js")
```

## Run time

```
pug.render('index.pug',{...data})
```

## Desciption

- push is different with include, it's not inline
- push will push script or css into stack until pop, create a corresponding tag at pop position, and make files in stack into one file, and put it at the path of dest; or put files into path if dest is a dir
- if no pop, will use original file position, and insert tag at original position
- can have customized stack,like `push(stack='s1') a.js`,and  `pop(script,stack='s1')`
- the ability to deliver data at include is needed, like `include(data=pugData.something) a/a`
- this will need manipulate pathes in pug, css, js cause after compile, file path changed

this is a very preliminary idea, destination is to develop application in modulized blocks,
it will be much better than using webpack and html loader, which always turns everything into js
welcome to discuss

**Comment by ForbesLindesay** [comment]
Thanks for the detailed write up. This is an interesting idea for a project, but would be quite a big deviation from how pug is currently structured. I don't want to grow pug into a webpack alternative, I just want it to be one of the most advanced HTML templating engines.
