### ISSUE TITLE
Comments break else-if blocks

### ISSUE THREAD

**Issue by mayeaux** [pugjs/pug#2920]
Is this expected functionality? 

``
else if blah blah
`` 

works, but if you add a comment

```
// something

else if blah blah 
```

that breaks, expected functionality? wasted a good chunk of time for me (only error that is returned is 'unexpected token'

**Comment by mayeaux** [comment]
This also breaks even with commented out else-if statements

**Comment by emilyford352** [comment]
@mayeaux - Can you provide a sample of exactly what you were running? I just tested this scenario and am not getting an error.

**Comment by ForbesLindesay** [comment]
This works fine if the comment is "unbuffered", i.e. `//- something` or if it is indented, `// something` is really "print the html comment `something`"
