### ISSUE TITLE
Internal support of text converters (for example i18n)

### ISSUE THREAD

**Issue by sarkiroka** [pugjs/pug#2922]
It is a feature request :)

I saw this issue (https://github.com/pugjs/pug/issues/2036) were closed, but I think internal support for custom text transformers is a good idea. So what I mean?

In a simple case the pug is super simple language for html
```pug
html
  head
    title It's great
  body
    h1 I Love Pug
    p It's a great
```
but when we need language support, then every string need to be wrap a converter function. It is ugly, and complex and gives an opportunity to make a lot of mistake :(
I think if you provide a custom callback for text (and/or attributes, tags, etc.) where we can modify the text when we need it without make an ugly template.

For example use the above pug and this javascript:
```js
var pug = require('pug');
var fn = pug.compile(stringOfAbovePug, {
  textCallback: function (text) { // its called 3 times, with "It's great", "I Love Pug" and "It's a great" - after all of variables and dynamic content are resolved
    return t(text); // use custom transformation of text
  }
});
...
```
It is a basic usage. I don't know how your compiler work, but I imagine this situation:
```js
var pug = require('pug');
var fn = pug.compile(stringOfPug, {
  textBeforeCallback: function(text){ // its called before the pug variables and dynamic contents are resolved
    return t(text); // use custom transformation of text
  }
});
...
```
This second use case allow we use very nice way to translate the texts

And the greatest thing, the original pug is still clear and readable.

best regards
sarkiroka

**Comment by sarkiroka** [comment]
And / or any support of these in express application.
For example
```js
app.set('view engine', 'pug')
app.use(pugi18n(options)); // and the magic will happen
app.get('/', function (req, res) {
  res.render('index');
})
```

**Comment by sarkiroka** [comment]
@droooney, I see, it is nice and clean, but I read the filters will be deprecated. And the template will be clutched with the filter name multiple times. But when I use i18n, all of text want to translate, not need write the filter name again and again for all of string.

**Comment by droooney** [comment]
@sarkiroka then take a look at the repo I've provided :)

**Comment by sarkiroka** [comment]
@droooney I made some changes on your example and it will be super simple with express :)
```pug
//- index.pug
html
    head
        title It's great
    body
        h1 I #{variable} Love Pug
        p It's a great
```
The express usage
```js
// index.js
var app = require('express')();
var useI18n = require('./useI18n');

app.set('view engine', 'pug');
app.set('views', __dirname);
app.use(useI18n());// here is the magic
app.get('/', function (req, res, next) {// usage example
    res.render('index', {variable: 'always'});
});
app.listen(3000, ()=>console.log('running on port 3000'));
```
Your undocumented magic :)
```js
//useI18n.js
const i18n = require('./i18n');
const walk = require('pug-walk');

module.exports = function() {
    return function (req, res, next) {
        res.locals.plugins = [{
            postParse(ast) {
                return walk(ast, (node) => {
                    if (node.type === 'Text') {
                        node.val = i18n.t(node.val);
                    }
                });
            }
        }];
        next();
    };
};
```
And the mock
```js
// i18n.js
const i18n = {
    "It's great": "it's really great",
    "I": "i",
    "Love Pug": "love pug",
    "It's a great": "it's really great"
};

exports.t = (text) => {
    let trimmedText = text.trim();
    let retValue = i18n[trimmedText];
    if (!retValue) {
        console.warn(`there is no translation for this text "${text}"`);
        retValue = text;
    }
    if (/^ /.test(text)) {
        retValue = ' ' + retValue;
    }
    if (/ $/.test(text)) {
        retValue += ' ';
    }
    return retValue;
};
```
Thanks! You helped me a lot

**Comment by droooney** [comment]
@sarkiroka yeah, probably, plugins are not very well documented, if even documented, I'm not sure. Glad that helped :)
