### ISSUE TITLE
toJSON method should  be called on object-like values only

### ISSUE THREAD

**Issue by FarSeeing** [pugjs/pug#2925]
**Pug Version:** pug@2.0.0-rc.4

**Node Version:** 9.3.0

## Input JavaScript Values

```js
String.prototype.toJSON = function() { return 'bar' };
console.log(pug.render('x(foo=foo)', {foo: 'foo'}));
```

## Expected HTML

```html
<x foo="foo"></x>
```

## Actual HTML

```html
<x foo="bar"></x>
```

## Additional Comments

Now pug calls `toJSON` method on input values if it's a function. That breaks attributes when some library modifies `String.prototype` (I know it's a disaster when some code changes native prototypes but that happens on customer site that we cannot control).
What I suggest is to call `toJSON` on object-like input values only (when `typeof ... === 'object'`). That will make pug be synced with native `JSON.stringify` method: according to [current standard](https://tc39.github.io/ecma262/#sec-serializejsonproperty) it's is called on objects:

> 2, If Type(value) is Object, then
>     a. Let toJSON be ? Get(value, "toJSON").
>     b. If IsCallable(toJSON) is true, then
>         i. Set value to ? Call(toJSON, value, « key »).

**Comment by droooney** [comment]
Sounds good. But I think `toJSON` is called not only on `typeof ... === 'object'`, but on `'function'` as well. I think, for now you can work this around by removing `String.prototype.toJSON` before render and restoring it afterwards.

Though, this change _might_ (but very unlikely) break some existent code. @ForbesLindesay @TimothyGu what are your thoughts on this?

**Comment by FarSeeing** [comment]
Functions are not supported neither by JSON itself nor by `JSON.stringify` and I hardly imagine anyone passing function itself and not function call result to be inserted in template.

**Comment by droooney** [comment]
@FarSeeing I'm just pointing out that `toJSON` is called by `JSON.stringify` on functions as well :) however, this is not really related to the issue.
