### ISSUE TITLE
Remove the warning `You should not have pug tags with multiple attributes.`

### ISSUE THREAD

**Issue by caikan** [pugjs/pug#2926]
**Pug Version:** 2.0.0-beta7

## Input Pug

```pug
a(href="https://github.com")(title="github")
```
## Expected & Actual HTML

```html
<a href="https://github.com" title="github"></a>
```

## Output warning message

```
You should not have pug tags with multiple attributes.
```

## Additional Comments

Multiple attributes work well, and sometimes can make code more clear, why warning it?
So I think the warning should be removed.

related issues: #2906 #2163

**Comment by droooney** [comment]
```pug
a(href="https://github.com", title="github")
```

or

```pug
a(href="https://github.com" title="github")
```

or

```pug
a(
  href="https://github.com"
  title="github"
)
```

work just fine, so use any of these approaches. I personally think the multiline one is good for separating groups of attributes and looks even cleaner than multiple brace groups.
