### ISSUE TITLE
Newbie question - Accessing properties of local variable inside template

### ISSUE THREAD

**Issue by Alexn117** [pugjs/pug#2927]
Hi, I'm new to Pug. Is it always necessary to precede a local variable that you pass in through a post request with an if statement in order to access the properties of that variable inside a template? I find that if I don't do that I get a `Cannot read property 'name-of-property' of undefined`.

For example:

**app.js**
```
const bodyParser = require('body-parser');
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// render test page
app.get('/test', function (req, res) {
    res.render('test');
});

// render test page after sample form is submitted and pass "body" local variable to use "body.name" inside template
app.post('/test', function (req, res) {
    res.render('test', { body: req.body, name: req.body.name });
});
```

**test.pug**
```
doctype html
html
    body
        form(action='/test' method='post')
            
            label Enter a name 
            input(type='text' name='name')
            
            p Repeat name below after submitting form, using "body.name" with "body" local variable that was passed in:

            // this works
            if body
                h1= body.name

            // this does NOT work, kicks up error "Cannot read property 'name' of undefined"
            // h1= body.name

            // this works
            h1= name
                     
            button(type='submit') Submit
```

* I noticed that if pass an additional local variable of **name** `{ body: req.body, name: req.body.name }`, then I can call that variable directly inside the template with no need to use an if statement, and no errors will fire.

So, does one always have to use an if statement each time you want to access the properties of a local variable or the properties of an object that you pass in, if those individual properties have not been directly defined as other variables like in the example of **name** I posted above?

Thanks, and apologies for what might be a very simple question. I'm new to Node.js and Pug and haven't found a beginner-friendly answer in some of the similar posts I've read.

**Pug Version:** 2.0.0-rc.4

**Node Version:** v9.2.1

**Comment by droooney** [comment]
If you use a non-existent variable, that's ok:

```pug
h1= header
```

but if you try to access a property of `undefined` (which gets passed if you don't pass anything), you'll get this error as you would get the same error in JS:

```pug
h1= values.header
```

\- if you don't pass `values` (equals to passing `undefined`) you'll get `Cannot read property "header" of undefined`.

By the way, it's a usual approach in JS:

```js
const people = [
  { name: 'Bob', age: 13 },
  { name: 'Alice', age: 18 }
];
let foundPerson;

for (const person of people) {
  if (person.name === 'Jack') {
    foundPerson = person;
    break;
  }
}

if (foundPerson) {
  console.log(foundPerson.age);
}
```

**Comment by Alexn117** [comment]
Thanks. So basically, if you want to access the properties of a variable **you always have to check first if that variable exists** so no error fires. In this example I pass in a "name" variable object and all its properties through the post request like so: `{ name: { first: 'John', last: 'Doe'} }`.

But just calling the property I need on the Pug template as follows will cause an error, _even if I passed in that property through the post request and I'm certain it exists_:
```
h1= name.first
```
`Cannot read property 'first' of undefined`

So, I have to do this instead:
```
if name
    h1= name.first
```
Or maybe this is better:
```
if name
    if 'first' in name
        h1= name.first
```

Is this correct way of doing it?

**Comment by droooney** [comment]
If you're certain it exists and is not `null` or `undefined` you don't need the checking. But if you do need it, it would be enough to just write

```pug
if name
  h1= name.first
```

as you would do in javascript.
