### ISSUE TITLE
call onclick js function and pass param from pug

### ISSUE THREAD

**Issue by iShawnWang** [pugjs/pug#2933]
emmmmm : 

```
    each file in files
      div
        p(onclick="viewPost(file);")= file.name
```

I want to pass file to javascript function `viewPost()`, i also tried 
- `viewPost('file')`
- `viewPost(' + file + ')`
- `viewPost(#{file})`

all not works, How could i do this ?

Also, demo codes here : https://stackoverflow.com/questions/47952498/pug-jade-onclick-call-function-and-pass-param

**Comment by iShawnWang** [comment]
I solved this by : 
**take care of the ` symbol**

```

a.postTitle(onclick=`viewPost(${JSON.stringify(file)})`)= file.name

```

**Comment by droooney** [comment]
I think

```pug
each file in files
  div
    p(onclick="viewPost(" + file + ");")= file.name
```

should work great.

Also if you run your code in an ES6 environment, you can write

```pug
each file in files
  div
    p(onclick=`viewPost(${file});`)= file.name
```

**Comment by kavithakavithap** [comment]
Thanks a lot iShawnWang.... I was stucked here more than 3days... It helped me lot and thankyou very much......This thing really worked "a.postTitle(onclick=`viewPost(${JSON.stringify(file)})`)= file.name"

**Comment by cuongw** [comment]
Thank you 🙏, @iShawnWang.
