### ISSUE TITLE
Feature Request : extends variable name

### ISSUE THREAD

**Issue by mikerouxfr** [pugjs/pug#2937]
**Pug Version:** 2.0.0-rc.4

**Node Version:** 8.6.0

## Input JavaScript Values

```js
pug.renderFile('home.pug', {
  templates: '~/some/path',
});
```

## Input Pug

`./layout.pug`
```pug
extends `${templates}/layout_2018.pug`

block prepend header
  h1 this is specific to this project
```
`./home.pug`
```pug
extends layout.pug

block main
  h1 I Love Pug
  p It's a great #{whatIsIt}
```

## Expected HTML

```html
<header>
  <h1>this is specific to this project</h1>
  <img src="logo.png">
</header>
<main>
  <h1>I Love Pug</h1>
  <p>It's a great language</p>
</main>
```

## Actual HTML

```html
Error: ENOENT: no such file or directory, open '~/project_path/`${templates}/layout_2018.pug`'
```

## Additional Comments

Hello.

I've seen the following comment and related posts: https://github.com/pugjs/pug/issues/1900#issuecomment-85659177
From what I understand, the team doesn't want to implement this feature because that would require a second compilation.

In my situation here, it wouldn't be needed as the variable is defined in the backend.

Do you think it could be possible ?
Thanks for your patience and for pug !

**Comment by mikerouxfr** [comment]
Hi again, sorry for spamming but while looking for a workaround, I've found that issue (#809) that might do the work too

**Comment by mikerouxfr** [comment]
Still sorry for spamming but using the `templates` variable as the `basedir` for __absolute__ `extends` does the trick. I'm not sure that this would be the best way to do that but that will work for now.

Here is a quick example for those who would need to do something similar. (Based on what's above)
## Input JavaScript Values
```js
pug.renderFile('home.pug', {
  basedir: '~/some/path',
});
```

## Input Pug
`./layout.pug`
```pug
extends /layout_2018.pug

block prepend header
  h1 this is specific to this project
```


_____

However, I'm still curious to know what the Pug team thinks about that feature request later on.

**Comment by ForbesLindesay** [comment]
This is the correct approach. Dynamic imports/extends (the feature you originally requested) has been requested many, many times, but it's extremely difficult to build without destroying the performance of pug.  The basedir approach works great, providing that the basedir is always the same (otherwise caching may break).
