### ISSUE TITLE
how to dynamically reference locals scope on render

### ISSUE THREAD

**Issue by lunelson** [pugjs/pug#2938]
**Pug Version:** 2.0.0rc4
**Node Version:** 8.5.0

There was an earlier question [here](https://github.com/pugjs/pug/issues/1490) about how to capture a reference to the locals object, however it captures a reference to the object as defined, not the one ~~being used~~ I'm using at runtime ~~(probably because it gets copied/merge on the way to the actual render)~~ because I'm copying the locals object to avoid it being mutated by template code. So in the following:

```js
function getFilename() { return this.filename };
var locals = {};
locals.getFilename = getFilename.bind(locals);
var html = pug.renderFile('./some/file.pug', Object.assign({}, locals));
```

...assuming that `some/file.pug` contains `pre!= getFilename()`, although `filename` will exist in the local scope at the time of render with the value `/Full/Path/To/some/file.pug` the result will be empty because the `getFilename` function is bound to the original locals object.

So my question is: is there a way I can reference the *runtime* locals scope from a function?

**Comment by droooney** [comment]
Are you sure that locals contain a `filename` field? Because I've run a similar example on the pug site and it's all ok:

```js
const locals = {
  foo: 1
};

locals.bar = (function () { return this.foo; }).bind(locals);

console.log(pug.render('p= bar()', locals)); // <p>1</p>
```

**Comment by lunelson** [comment]
@droooney yes the `renderFile` method inserts `filename` key, as the full path of the file being rendered; but I just realized a mistake in my example above and corrected it. The point is, the value I want to refer to is not being set until render time, but the locals object I'm passing to the render function is also being copied at that time, to avoid the danger of templates being able to arbitrarily mutate the locals object, which would leak in to other templates; so the binding is broken. To modify your example:

```js
const locals = {};
locals.bar = (function () { return this.foo; }).bind(locals);
console.log(pug.render('p= bar()', Object.assign({}, locals, {foo: 1}))); // <p></p>
```
...and then the `p` tag is empty, because the binding is broken through copying. If I don't copy the object, I could have the following problem:

```js
const locals = {foo: 1};
locals.bar = (function () { return this.foo; }).bind(locals);
console.log(pug.render('- locals.foo = 2', locals));
console.log(locals); // {foo: 2, bar: ƒ}
```
...which means the next template I render gets `foo` with a value of `2`

**Comment by droooney** [comment]
First off, your first example from the latest post shouldn't work because you bind the `bar` function to the `locals` object which *never* has the `foo` property. Second: don't modify the locals then if you don't want it to be changed or construct a new object each time you render a template.

**Comment by lunelson** [comment]
The first example in my post above *does* work if it is written without copying the object in to a blank one via `Object.assign` (see below), as the original `locals` object is then mutated to contain `foo`; but I don't want to write it that way because I can't ensure that a user will not unwittingly change the locals. If I was the only one using this code I would know not to do it, but otherwise it's untenable.
```js
const locals = {};
locals.bar = (function () { return this.foo; }).bind(locals);
console.log(pug.render('p= bar()', Object.assign(locals, {foo: 1}))); // <p>1</p>
```

**Comment by droooney** [comment]
I guess, you could write this:

```js
const locals = {};
// do something with locals
const bar = function () { return this.foo };
const newLocals = Object.assign({}, locals);

newLocals.bar = bar.bind(newLocals);

console.log(pug.render(`
- locals.foo = 1
p= bar()
`, newLocals)); // <p>1</p>
```

**Comment by lunelson** [comment]
Yes, that would work but it requires access to the code that's calling `pug.render`, in order to bind the functions after the object is copied, but before the template is rendered.

I was hoping for a way that my locals could be more 'portable' i.e. usable by any pug-based code, but would have needed a magic keyword or function or something;

That being said, the idea of copying the object before binding the functions is on the right track—I could also export my locals as a function that returns the object with bound functions:

```js
// in 'locals.js'
module.exports = function() {
  const locals = {};
  locals.bar = (function () { return this.foo; }).bind(locals);
  return locals;
}
// in 'render.js'
const locals = require('./locals')();
console.log(pug.render('p= bar()', Object.assign(locals, {foo: 1})));
```

**Comment by droooney** [comment]
What about

```js
const locals = {
  bar() {
    return this.foo;
  }
};
console.log(pug.render(`
- locals.foo = 1
p= locals.bar()
`, locals)); // <p>1</p>
```

then?

This idea should have come up earlier :)

**Comment by lunelson** [comment]
Right, I guess the step of explicitly binding them shouldn't be necessary. I think this is the solution then, combined with exporting them as a function that returns an object, to prevent mutations. 😉

**Comment by droooney** [comment]
Ok, glad you've figured it out :)
