### ISSUE TITLE
Use with hyperscript tools

### ISSUE THREAD

**Issue by timwis** [pugjs/pug#2940]
Hi folks, I'd like to use pug in the same way I use [bel](https://github.com/shama/bel/)/[yo-yo](https://github.com/maxogden/yo-yo)/[lit](https://github.com/Polymer/lit-html):

```js
const el = pug`
  div#foo Hello
`
document.body.appendChild(el)
```
results in:
```js
const el = document.createElement('div')
el.setAttribute('id', 'foo')
el.innerText = 'Hello'
document.body.appendChild(el)
```

I think the easiest way to accomplish this is to leverage the [hyperscript](https://github.com/hyperhype/hyperscript) API, where the pug preprocessor would construct:
```el
h('div', {id:"foo"}, 'Hello!')
```
And `h` would, by default, be something like hyperscript which returns an HTML string, but could also be something like bel/hyperx that returns an `HTMLElement`, or `React.createElement` to return virtual DOM.

Does anyone know of an out-of-the-box way to accomplish this with pug, or would this functionality need to be written?

**Comment by ForbesLindesay** [comment]
You'd need to build a custom compiler.  A couple of very different examples of doing this:

 - https://github.com/pugjs/babel-plugin-transform-react-pug
 - https://github.com/pugjs/then-jade
