### ISSUE TITLE
Feature request: interpolation in class literal

### ISSUE THREAD

**Issue by benface** [pugjs/pug#2941]
**Pug Version:** 2.0.0-rc.4

**Node Version:** 9.4.0

## Input Pug

```
- var allow = '.allow';
.please#{allow + '.this'}
```

## Expected HTML

```html
<div class="please allow this"></div>
```

## Actual HTML

None, it doesn't compile:
> Unexpected token `interpolation` expected `text`, `interpolated-code`, `code`, `:`, `slash`, `newline` or `eos`

## Additional Comments

This was suggested and refused [back in 2011](https://github.com/pugjs/pug/issues/258), but the person who closed the issue doesn't seem to be in the Pug team anymore. Any chance someone in the team wants this? :)

**Comment by ForbesLindesay** [comment]
I still agree with the person who originally closed this. We support the shorthand only for static class names.  When i think about which of these would be easier to read, the later always wins in my mind.

```pug
- var allow = '.allow';
.please#{allow + '.this'}
```

is less readable than

```pug
- var allow = 'allow';
.please(class=[allow, 'this'])
