### ISSUE TITLE
Basedir with compileFile

### ISSUE THREAD

**Issue by Xstoudi** [pugjs/pug#2943]
**Pug Version:** 2.0.0-rc.4

**Node Version:** v9.4.0

## Input JavaScript Values

```js
const path = require('path')

const Pug = require('pug')

const options = {
  basedir: path.join(__dirname, 'views')
}

module.exports = {
  login: Pug.compileFile('login.pug', options)
}

```

## Additional Comments

It's seems that Pug doesn't use the basedir to get the login.pug file.

**Comment by droooney** [comment]
`options.basedir` is needed for writing things such as

```pug
include /header.pug
```

**Comment by ForbesLindesay** [comment]
Please submit a test case.  You can follow https://github.com/pugjs/pug/tree/master/packages/pug/test/duplicate-block as a self contained example of a test case. You can call it `basedir` and add any examples that currently fail.

**Comment by Xstoudi** [comment]
Just saying that I could be able to set the root folder of my views.

**Comment by ForbesLindesay** [comment]
Ah, basedir isn't supposed to work in this case. We use normal node.js resolution rules for the initial pug template. I suppose we could support basedir for paths starting `/` as that would match the behaviour of `include`/`extends` but it's not something I see as high priority.
