### ISSUE TITLE
Feature Request: Allow CSS-style bracket attributes

### ISSUE THREAD

**Issue by clshortfuse** [pugjs/pug#2944]
**Pug Version:** v2.0.0-rc4

**Node Version:** v8.9.3

## Input Pug

```pug
input#myElementId.myElementClass[value="50"][required]
```

## Expected HTML

```html
<input id="myElementId" class="myElementClass" value="50" required>
```

## Actual HTML

(None)

## Additional Comments

While I know we can use parentheses to do this, consider that the CSS rule for the above would look like:

```
input#myElementId.myElementClass[value="50"][required] {
  // rules go here
}
```

Which would be the same as the proposed bracket support.

Is it imperative? No. But it's nice to have. Also, I don't think brackets are used at all by Pug. (correct me if I'm wrong).

**Comment by ForbesLindesay** [comment]
This has been requested in the past. I just don't think it's worth the cost of:

1. Having two ways to accomplish the same thing or
2. Making a massive breaking change to the language

It's also a much noisier syntax, requiring two brackets for every single attribute.  We happen to borrow the shorthands for class name and id from css, but the goal of this language is not to replicate css.

**Comment by clshortfuse** [comment]
> This has been requested in the past.

That alone means it has some desirableness to it.
> Having two ways to accomplish the same thing

That's not a bad thing. The point is to make tasks easier. For example you also support single quotes('`') and double quotes (`"`). Having options is good.

> Making a massive breaking change to the language.

I'm not clear on this. What would it break?

**Comment by ForbesLindesay** [comment]
Having multiple ways to accomplish the same thing generally makes a language harder to learn. It would be a breaking change if we removed the existing attributes syntax. Single/double quotes is very different to a completely different attribute syntax.

**Comment by clshortfuse** [comment]
>Having multiple ways to accomplish the same thing generally makes a language harder to learn.

I strongly disagree. If anything, it's the opposite, especially when the syntax of widely known language is compatible. But I don't want to argue the point any further. You seem to have you mind made up.

Here's a real world example. For the documentation I'm writing, I'm using Pug as the default template. If Pug were be able to use CSS syntax, reader who don't know the Pug syntax would find it easier to understand. Also, depending on the template, some wouldn't even realize they're reading Pug and not CSS.

https://github.com/clshortfuse/materialdesignweb/tree/master/components/button

This would be easier to read if Pug supported CSS styles attributes as well.
