### ISSUE TITLE
Confusing jade-lang.com

### ISSUE THREAD

**Issue by nasht00** [pugjs/pug#2953]
I've never heard of jade nor pug before, but a client asked me to write their page using "Jade".
A google search brought me to http://jade-lang.com/

Since I wanted to look at the github repo I ended up in this pug repo, and slowly learned about the name change.

However, in the jade-lang website, there are absolutely no reference to this name change, links to the new website, links to the repo, etc... This makes the experience very confusing.

Just some heads up from an outsider.

**Comment by TimothyGu** [comment]
We have the name change in a prominent position on the README: https://github.com/pugjs/pug#rename-from-jade

Would you be willing to submit a PR to https://github.com/pugjs/pug-en to change this?

**Comment by nasht00** [comment]
I probably could, but I don't think it would help.

The repo you linked seems to be for the website pugjs.org. If I am already at pugjs.org then I don't need to know about the old name.

The problem is with the OLD website, http://jade-lang.com/, which does not match the linked repository so I'm not sure where to do a PR ...

**Comment by ForbesLindesay** [comment]
jade-lang.com isn't maintained by any of us. Somebody else set it up immediately after our name change. I asked them to take it down straight away, but they were not interested.  I'm sorry, there's not really anything more I can do.

**Comment by nasht00** [comment]
Oh that's sad. What do they gain from it?

They just explain the old jade API, no advertising or links....

**Comment by ForbesLindesay** [comment]
Some people were _very_ angry that I renamed jade to pug. I think he's just trying to resist that change.

**Comment by atilkan** [comment]
@ForbesLindesay 
Genetically modified, fabricated, consumed product for human entertainment. Well done. Very creative.
