### ISSUE TITLE
Pug doesn't support newlines between parentheses

### ISSUE THREAD

**Issue by problem233** [pugjs/pug#2960]
**Pug Version:** 2.0.0-rc.4

**Node Version:** 9.5.0

## Input JavaScript Values

```js
pug.renderFile('input.pug', {
  content: `<figure class="highlight haskell"></figure>`
});
```

## Input Pug

```pug
- const fixed = content.replace(
-   `<figure class="highlight`,
-   `<figure class="hljs highlight`)
!= fixed
```

## Expected HTML

```html
<figure class="hljs highlight haskell"></figure>
```

## Actual HTML

```
SyntaxError: Unexpected token (3:0)
```

## Additional Comments

However, this:

```pug
- const fixed = content.replace(`<figure class="highlight`, `<figure class="hljs highlight`)
!= fixed
```

gives expected HTML, but the line is too long and ugly. In fact, the real code is much longer.

**Comment by droooney** [comment]
You can write

```pug
-
  const fixed = content.replace(
    `<figure class="highlight`,
    `<figure class="hljs highlight`)
!= fixed
```

This is the block unbuffered code syntax ([ref](https://pugjs.org/language/code.html#unbuffered-code)).

**Comment by ForbesLindesay** [comment]
@droooney's workaround is correct.

If you set `debug: false`, your original code should work. Unfortunately there's no easy way to make it work in debug mode without also losing exact line numbers on error messages.  In the long run, I'd like to support:


```pug
- const fixed = content.replace(
   `<figure class="highlight`,
   `<figure class="hljs highlight`)
!= fixed
```

This would be a pretty big breaking change though, as it would prevent you doing things like:

```pug
- for (var i = 0; i < 10; i++) {
div= i
- }
```

so it needs to be carefully thought through.
