### ISSUE TITLE
Trailing ; at the end of style attribute breaks riotjs behavior

### ISSUE THREAD

**Issue by 0tho** [pugjs/pug#2961]
**Pug Version:** v2.0.0-rc.4

**Node Version:** 8.9.4

## Input Pug

```pug
my-tag
  p(style="{ styles }")
  script.
    this.styles = {
      color: 'red',
      height: '10rem'
    }

```

## Expected HTML

```html
<my-tag>
  <p style="{ styles }"></p>
  <script>
    this.styles = {
      color: 'red',
      height: '10rem'
    }
  </script>
</my-tag>
```

## Actual HTML

```html
<my-tag>
  <p style="{ styles };"></p>
  <script>
    this.styles = {
      color: 'red',
      height: '10rem'
    }
  </script>
</my-tag>
```

## Additional Comments

When using Pug as the template engine for riotjs the extra ";" generated on the style attribute breaks a riotjs behaviour that expands an object to css properties. 

About riot [style-object-expression](http://riotjs.com/guide/#style-object-expressions)

Related riot issue: riot/riot#2301

I was not able to find exactly where on riotjs code the ";" becomes a problem.

[Pug related code](https://github.com/pugjs/pug/blob/master/packages/pug-runtime/index.js#L113)

As far as I understand the ";" is generated at the end of the string so even if people forget to put ";" on their last css attribute the Pug compiler will fix it for them. 

Is this necessary? Is there a workaround so the ";" is not generated?

**Comment by ForbesLindesay** [comment]
This is actually for when attributes get merged:

```pug
mixin element
  p(style="background: red")&attributes(attributes)
+element(style="color: blue")
```

results in

```html
<p style="background: red;color: blue;"></p>
```

However, we should probably only add the trailing `;` when styles get merged. If there is only a single `style` attribute, and it is a `string`, we should leave it un-touched.  Happy to accept a pull request.
