### ISSUE TITLE
hope to allow UTF-8 string in #ID syntax

### ISSUE THREAD

**Issue by n-arakawa** [pugjs/pug#2964]
**Pug Version:*2.0.0-rc.4* 

**Node Version:*v8.9.4*

## Input Pug
All  UTF8STR strings in the following are actually  2 letter in japanese ('特徴' :%E7%89%B9%E5%BE%B4).

```pug
html
  body
    h1#UTF8STR
```

## Expected HTML

```html
<html><body><h1 id="UTF8STR"></h1></body></html>
```

## Error message

```
Error: /tmp/a.pug:3:7
    1| html
    2|   body
  > 3|     span#UTF8STR
-------------^
    4| 

"UTF8STR
" is not a valid ID.

```

## Additional Comments

Sometime HTML ID's are  used  for  location hash property.
In this case, utf-8 string may be used.

For example 
`https://ja.wikipedia.org/wiki/HyperText_Markup_Language#%E7%89%B9%E5%BE%B4`
```html
<span class="mw-headline" id="UTF8STR">UTF8STR</span>
````
"html2jade" generates `span(id="USTF8String")` version which is OK with pug.
However   "html2pug"  generates  `span#USTF8String.` 

hope to relax the rules  in 'pug-cli/node_modules/pug-lexer/index.js'
```javascript
    if (/^#/.test(this.input)) {
      this.error('INVALID_ID', '"' + /.[^ \t\(\#\.\:]*/.exec(this.input.substr(1))[0] + '" is not a valid ID.');
    }
```

**Comment by ForbesLindesay** [comment]
We're intentionally keeping the character set supported in this shorthand fairly narrow. This ensures that all the special characters are available to be given special meaning in the future. The non-short-hand approach of `span(id="whatever')` should work fine. I suggest opening an issue on html-to-pug to request that it only use the shorthand for the valid character set.
