### ISSUE TITLE
Concatenation conditional

### ISSUE THREAD

**Issue by ECDonelson** [pugjs/pug#2965]
I'm not sure if this is a question or a request, but I'm trying to change the "required" attribute of a label using a concatenation in a conditional statement in pug and cant seem to get it to work properly.

**Pug Version:** your version number here
2.0.0-rc.4

**Node Version:** your version number here
9.6.1

## Input JavaScript Values

```js
var storeNbr = employee.storeNbr;
var location = (derived from a list of locations);
var locationsList = ['0001 - An', '0002 - Array', '0003 - Of', '0004 - Locations'];
```

## Input Pug

```pug
if #{storeNbr} - #{location} == newLocation
    input#effectiveTransDate(type=date, required)
else 
    input#effectiveTransDate(type=date) //not required
```

## Expected HTML

(if the storeNbr + ' - ' + location === newLocation //from a list of locations - selected)

```html
    <input type="date", id="effectiveTransDate", required>
```

else

```html
    <input type="date", id"effectiveTransDate">
```

## Actual HTML

500 Internal Server Error

## Additional Comments

I have the values for storeNbr, and the location, but I'd like to be able to concatenate the two and compare them to what is selected in the "New Location" drop down (obviously its a list).
I can concatenate the storeNbr and location, but I'm unable to run the comparison on that concatenation and the selected location from the list of locations.

**Comment by ForbesLindesay** [comment]
The value in the `if` is just a JavaScript expression, so you can do something like:

```pug
if storeNbr + ' - ' + location == newLocation
```

i.e. do what you would do if you needed to concatenate some strings in JavaScript.

**Comment by ECDonelson** [comment]
That works for static values, but I need it to do that when the newLocation value changes. So:

select#newLocation(style='', value='', onchange='checkValuesAndRequire()')
    //loop thought the locations list I send in res.render

but I'm unable to call and "onchange" function.

**Comment by ForbesLindesay** [comment]
If you're using a client side data-binding engine (e.g. knockout, angular, ember) on the output of pug, you'll need to use that to handle the if, as pug won't be aware of that data.

If you use pug directly, you just need to re-render each time the data changes.

**Comment by ECDonelson** [comment]
Okay,

That makes sense, I was afraid that I was going to have to re render the page, I was really trying to avoid that.

I’ll see about adding jQuery to the pug view.

Thanks!
