### ISSUE TITLE
interpolation problem here

### ISSUE THREAD

**Issue by shavingmace** [pugjs/pug#2969]
`div(class="eight wide column" onclick='javascript:window.location="/process/showpost/'+i._doc._id+'"')`

my code produces blank so that my query gets error. how can i fix this?

**Comment by droooney** [comment]
What is the html output for this? Btw, I don't think you need `javascript:` prefix in the `onclick` attribute.

**Comment by shavingmace** [comment]
i solved my problem. i applied pug2 grammar and it worked thanks to ${my variable} instead of '+ my variable+'!

**Comment by morteryler** [comment]
Close please
