### ISSUE TITLE
Consider a linting solution

### ISSUE THREAD

**Issue by TheDancingCode** [pugjs/pug#2982]
Given the size of this repo, it would be good to lint and/or format the code in a consistent way.

When it comes to linting, ESLint is an easy solution that requires little or no configuration if you stick with its set of [recommended rules](https://eslint.org/docs/user-guide/configuring#using-eslintrecommended). These report common problems and sources of bugs.

As for formatting, I noticed that you're already using Prettier for your snapshot tests. Running Prettier on the rest of the codebase would be an easy way to achieve consistent formatting over the whole repo, without requiring new dependencies or settings.

If you're interested in this, I'd be happy to submit a PR.

**Comment by ForbesLindesay** [comment]
Yes, I would like to have prettier used on the whole codebase, I just haven't got round to it yet.
