### ISSUE TITLE
Using require without requiring...

### ISSUE THREAD

**Issue by TheColorRed** [pugjs/pug#2983]
I am not sure what is happening here but in electron, I can do `<script>require('./main')</script>`. When doing this with pug, it doesn't work (can't even see the final result, so I don't know what the html looks like):

```pug
<!DOCTYPE html>
html(lang="en")
  head
    script require('./main')
  body
    block content
```

If I convert this to html, and run that through electron, it works. Is pug trying to do something with the `require` statement? Is there a way around this if it is?

**Comment by Matthias-Hermsdorf** [comment]
try 

    head
      script
        include main
