### ISSUE TITLE
Pug Name Trademarked

### ISSUE THREAD

**Issue by tracker1** [pugjs/pug#2984]
http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4805:3m0kud.2.11

http://tsdr.uspto.gov/#caseNumber=87745066&caseType=SERIAL_NO&searchType=statusSearch

**Comment by ForbesLindesay** [comment]
Do you know if these are anything we need to do anything about?

**Comment by Come2Daddy** [comment]
international
Class 41: Education and Entertainment Services

U.S.
Class 100 : Press
Class 101 : Printing
Class 107 : Education and entertainment

I guess it's ok for this trademark as pugjs doesn't fit in theses classes.

**Comment by ForbesLindesay** [comment]
@Come2Daddy thanks, in that case I'll close this issue.
