### ISSUE TITLE
Clearer welcome page

### ISSUE THREAD

**Issue by Stephanevg** [pugjs/pug#2987]
Hi,

It would be great to ad a few setences of what pug.js actually is, what it brings, and why people would have interest in downloading and using it on your [HomePage](https://pugjs.org/api/getting-started.html ). Currently the homepage just explains how to install pug.

I am not from a Javascript background, and it was difficult for me to get, if pug.js was actually someting for me or not. I originally search for Jade.js. I learned from Jade from [MVA](https://mva.microsoft.com/en-us/training-courses/building-apps-with-node-js-jump-start-8422?l=jJXdHaKz_5804984382)

**Comment by ForbesLindesay** [comment]
Thank you for the feedback. We're aware that the website needs substantial improvements.
