### ISSUE TITLE
It is possible to unwrap nested content from element, witch layout is result of interpolation from false variable?

### ISSUE THREAD

**Issue by 7iomka** [pugjs/pug#2993]
It is possible to unwrap nested content from element, witch layout is result of interpolation from variable, that have any false value?
DEMO: https://codepen.io/7iomka/pen/NYXwEa?editors=1100

**Pug Version:** LATEST and all previously versions

## Expected HTML
Button without inner
```html
<a class="btn" href="#lol">
  demo text on another more difficult content or config
</a>
```

## Actual HTML

```html
<a class="btn" href="#lol">
  &lt;&gt;demo text on another more difficult content or config
</a>
```

## Additional Comments
In my example, I simplified problem, but in real development i need more difficult hardcode with copy-paste same setup-stuff in multiple (if)-conditions.
I want that if the result of interpolation was a false expression, it would be perceived as not an existing html-element, and transferred as embedded content from it was extracted (unwrapped)

**Comment by droooney** [comment]
You can simply write:

```pug
- var content = 'demo text on another more difficult content or config';

if inner
  #{inner}
    =content
else
  = content
```

**Comment by 7iomka** [comment]
@droooney, I asked this question, since the string of conditions is only suitable for simple components. In complex so easy to do it will not work! 
For example, if we need wrappers in several enclosed parts, and the structure variations themselves are broken down according to several conditions and put into mixin.. Additional conditions make reading and sustainability worse! :(

**Comment by ForbesLindesay** [comment]
You can use mixins for this purpose, there is no other approach that's supported.
