### ISSUE TITLE
rethrow does not give any indication of the original error

### ISSUE THREAD

**Issue by chharvey** [pugjs/pug#2995]
Continuing the discussion from https://github.com/pugjs/pug-runtime/issues/35 (archived)

> TypeError: Cannot set property message of&nbsp;&nbsp;which has only a getter

The rethrow seems to be trying to set a property for which there is no setter. This is a bit frustrating because the trace of the new `TypeError` does not contain the original error, which makes debugging a lot harder.

**Comment by morteryler** [comment]
Once helped close the topic
