### ISSUE TITLE
Non working <> in properties/attributes

### ISSUE THREAD

**Issue by BananaAcid** [pugjs/pug#2997]
Hi,

I am trying to use something like: 

    meta(name="description", lang="!{'<?=$code?>'}", content="#[<?=$description?>'])

expected:

    <meta name="description" lang="<?=$code?>" content="<?=$description?>">

but all <> are converted to html entities.

I can't find the correct interpolation syntax to get this to work. So I assume it is missing or one is not working as expected.

**Comment by ForbesLindesay** [comment]
We don't support "interpolation" in attributes. They are just JavaScript values. You can use `!=` instead of `=` to indicate you want to use unescaped values:

```pug
meta(name="description", lang!="<?=$code?>", content!="<?=$description?>")
```

**Comment by BananaAcid** [comment]
Thank you! Where can I find this in the docs?

@ForbesLindesay : additional question: is there a way to do something like

    input(id="newsletter", type="checkbox", !{'<?=$checked?>'} )

seems to be a related case.

**Comment by ForbesLindesay** [comment]
"Unescaped attributes" on https://pugjs.org/language/attributes.html
