### ISSUE TITLE
ENOENT: no such file or directory, open '/home/user/nodejs/proj/views/includes/head.pug'

### ISSUE THREAD

**Issue by morteryler** [pugjs/pug#3000]
**Pug Version:** 2.0.0-beta11

**Node Version:**9.8.0

## Input JavaScript Values

```js
app.get('/render/', (req, res) => {
	res.render('rdr', {
		basedir: '/home/user/nodejs/proj/'
	});
});
```

## Input Pug

```pug
doctype
html
	include includes/head.pug
	body
		h1 Welcome!
		include includes/menu.pug
```

## Expected HTML

That brought h1 with my css file!

## Actual HTML

```
<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>ENOENT: no such file or directory, open '/home/user/nodejs/proj/views/includes/head.pug'
    at /home/user/nodejs/proj/views/rdr.pug line 3</h1><h2></h2></body></html>
```

## Additional Comments

As you can see the option basedir does not work! What to do?

**Comment by cekvenich** [comment]
renderFile(...) instead of render(..)

**Comment by morteryler** [comment]
> renderFile(...) instead of render(..)

This is inconvenient and also gives an error:
`ENOENT: no such file or directory, open 'views/includes/head.pug' at views/rdr.pug line 3
`
`const pug = require('pug');

app.get('/render/', (req, res) => {
	res.send(pug.renderFile('views/rdr.pug', {
		basedir: '/home/user/'
	}));
});`

The option basedir does not work and the hike is a bug!

**Comment by droooney** [comment]
`options.basedir` works the way that

```pug
include /some/path
```

(path that starts with `/`) is resolved relatively to `options.basedir` rather than `/`. So you need to change

```pug
include includes/menu.pug
```

to

```pug
include /includes/menu.pug
```

**Comment by ForbesLindesay** [comment]
Yes, `basedir` only applies to paths that start with `/`, relative paths area always resolved relative to the current pug file.
