### ISSUE TITLE
render('include ...') fails

### ISSUE THREAD

**Issue by cekvenich** [pugjs/pug#3001]
**Pug Version:**  2.03
I'm writing an open source project for S3. S3 is not a real file system, so I get strings from 'objects/files'), and give it to render(). I want to be able to compile pug on S3. So this fails of course:

```
let p=`
p oh hi
include d
`
let html = pug.render(p)
console.log(html)

```

It fails because of the include. If I could use renderFile(...) on a file system I would.  So try number two:
```
const link = require('pug-linker')
const lex = require('pug-lexer')
const walk = require('pug-walk')
const parse = require('pug-parser')

let ast = parse(lex(p))
walk(ast, function before(node, replace) {
		console.log(node)
	}, {includeDependencies: true}
)

```

My plan would be to feed it a string when it needs one, I would provide it instead of the file system. I assume on 'FileReference'. But it has to work anytime I need a file, including markdown, extends, etc. 
Just like renderFile(...) but on S3.
Sadly I need some help/hints.

**Comment by morteryler** [comment]
I think you'll need pug.compileClient(source, ?options)
// Compile the Pug template for a JavaScript string that can
// used on the client side along with the execution time of the Pug.
// The options are the same as for pug.compile
// Returns: The JavaScript string representing the function
// Example:
const pug = require ('pug');
let f = pug.compileClient ('p Paragraph');
console.log (f);

**Comment by ForbesLindesay** [comment]
What you'll need to do is build your own, asynchronous version of [pug-load](https://github.com/pugjs/pug/tree/master/packages/pug-load). The output of your async version of pug-load can be fed into pug-linker, pug-filters, pug-code-gen etc.

**Comment by ForbesLindesay** [comment]
I should probably mention, if you have the files available already, you just need to pass a plugin that implements `read` as a function from a filename to a string of source code. e.g.

```js
let p=`
p oh hi
include d
`
let html = pug.render(p, {plugins: [{
  resolve: (filename, sourceFilename) => filename,
  read: filename => {
    if (filename === 'd') {
      return `p included content`;
    }
    throw new Error('Unknown file ' + filename);
  },
}]})
console.log(html)
```
