### ISSUE TITLE
Is it possible to pass an inline anchor within a string?

### ISSUE THREAD

**Issue by ekfuhrmann** [pugjs/pug#3009]
I have a mixin:

```pug
mixin hyerlinkString(text)
    p= text
```

Within that text field I want to interpolate a hyperlink but can't seem to figure out how to get it work.

I've tried the following method as well as the legacy `#[a(href="#") Hyperlink]`, but to no avail.

```pug
- var text = `This is a sample string with an inline ${a(href='#') 'Hyperlink'}.`
```

Is this possible?

**EDIT:**  I did find a way to get this working via [String Interpolation, Unescaped](https://pugjs.org/language/interpolation.html#string-interpolation-unescaped), but I wonder if there is a better method now with Pug 2.0.

```pug
- var text = `This is a sample string with an inline <a href="#">Hyperlink'</a>.`
```

**Comment by ForbesLindesay** [comment]
```pug
mixin hyerlinkString
    p
      block

+hyperlinkString This is a sample string with an inline #[a(href='#') Hyperlink]
```

Interpolation of html elements into strings is not supported by design, it tends to create a lot of security hazards.
