### ISSUE TITLE
I want to use both doctype xml and html features

### ISSUE THREAD

**Issue by onelongblock** [pugjs/pug#3014]
### pug example
```pug
input(wx:else)
```
### when doctype is xml, it output this
```html
<input wx:else="wx:else"></input>
```
### when doctype is html, it output this
```html
<input wx:else>
```
### but I want to output like this, how should I do
```html
<input wx:else></input>
```

**Comment by ForbesLindesay** [comment]
I think your best off just putting the html in directly if you need that level of control.

```pug
| <input wx:else></input>
```

**Comment by onelongblock** [comment]
thanks
