### ISSUE TITLE
How can we add custom strings in place of attributes?

### ISSUE THREAD

**Issue by ceremcem** [pugjs/pug#3017]
I need to produce the following HTML-like output regarding to Ractive's [conditional event declaration](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAIwD2SAJ6CsnbjwC2AB16UeAgAaza3ADz0CigK61StCYoQBediGpgE1ANZiAHjdJ2Hj5NZDBgCASUwrzIGBjuAPQAfKT+gcGhSOFausLGtKIEccAAxPQAZqQJIWEYWQC01Lz0Tr4AAii8osKUvAB0bQgwtCyC9rzNggCUNv6RheHRqdq0A4Oii6KkM9z++UUlSSlcs9zcLNW1jokIpASixKO7+7TxvLgIO7e3LBcmR06n55fXL3fACYFZ6zHSRdK0TIEaa7TQEDDDTBAA): 

```html
<div class="foo" {{#if hello}}on-click="somestring"{{/if}}> Hello world </div>
```

What would be the Pug version?

**Comment by droooney** [comment]
Try

```pug
div.foo&attributes({ 'on-click': hello && 'something' })
```

**Comment by ceremcem** [comment]
@droooney There is a problem with this approach: It's targeting a server-side rendering approach. I have to generate exactly the output in the question, because Ractive handles event firing decision on the client side.

**Comment by droooney** [comment]
Then just render plain HTML. pug does not handle plain html and outputs it without changes.

**Comment by ForbesLindesay** [comment]
Yep:

```pug
div
  <div class="foo" {{#if hello}}on-click="somestring"{{/if}}> Hello world </div>
```

Outputs

```html
<div><div class="foo" {{#if hello}}on-click="somestring"{{/if}}> Hello world </div></div>
```

**Comment by ceremcem** [comment]
@ForbesLindesay 

Are you kidding me?

**Comment by ForbesLindesay** [comment]
No, what you're asking for as output is not valid HTML, or valid XML. It's another templating language. Pug is intentionally **not** optimised for that use case. We do, however, let you just output arbitrary text, either by using `| some arbitrary text` or by starting the line with `<`, which causes pug to treat it as plain HTML.

**Comment by ceremcem** [comment]
### Solution:

[By evs-chris](https://gitter.im/ractivejs/ractive?at=5b08188a6fcbaf377df89b6d)

```
doctype html
a('{{#if foo}}on-click="bar"{{/if}}') hello
```
