### ISSUE TITLE
[Feature Request] optional parameters for includes

### ISSUE THREAD

**Issue by Rc85** [pugjs/pug#3023]
I was working on my project the other day and I have an include that is basically a template for a upvote/downvote form. The form has a hidden input that has a post ID for the post that users want to upvote/downvote. I couldn't use it because the ID is different for each post. Then I thought, wouldn't it be nice if we can put in optional parameters to include into the file.

I'm no expert at creating libraries like pug and others so I'm not sure if this would be too hard or if it would break the concept of templating.

**Comment by ForbesLindesay** [comment]
Check out https://pugjs.org/language/mixins.html - you can define a mixin in a separate file and then "include" it.
