### ISSUE TITLE
blocks can be override, but original content is not showing

### ISSUE THREAD

**Issue by Rc85** [pugjs/pug#3024]
Node version: 10.3
Pug version: ^2.0.3

```
// layout.pug
html
    head
        body
            block content
                div title
```
the div title is not shown at all if I don't have page.pug
```
// page.pug
extends layout

block content
    div new title
```
having page.pug, div new title shows. can anyone try to replicate this and see if it works for them?

**Comment by ForbesLindesay** [comment]
I'm not able to replicate this. Please fill out the full issue template, including version numbers, expected HTML and actual html.
