### ISSUE TITLE
Use the name of a template file within this template file

### ISSUE THREAD

**Issue by djcaesar9114** [pugjs/pug#3026]
Hello,
Not an issue but a question: I'd like to use the name of a template file (for example "test.pug") inside this template file, is there a way to do this?
Thanks :)

**Comment by ForbesLindesay** [comment]
This is partially a duplicate of #3012. The answer is: not currently. We do want to implement the "import" functionality, but adding a way of retrieving the name of the current template is not currently anywhere on our roadmap.
