### ISSUE TITLE
Substitute local javascript variable's value into Pug's interpolation

### ISSUE THREAD

**Issue by HaoyangFan** [pugjs/pug#3030]
**Pug Version:** 2.0.3

**Node Version:** 10.4.1

## Input JavaScript Values

```
const express = require('express');
const pug = require('pug')
var app = module.exports = express();

app.set('view engine', 'pug');

var foo = [{
        apple: 1,
        pine: 2,
        peach: 3
    }, {
        apple: 4,
        pine: 5,
        peach: 6
    },
    {
        apple: 7,
        pine: 8,
        peach: 9
    }
];
app.get('/', (req, res) => {
    res.render('index', {
        data: foo
    });
});

app.listen(3000, () => console.log('Listent to port 3000 now'));
```

## Input Pug

`index.pug`

```
doctype html
html(lang='en')
    head
        title Pug
    body
        table
            - var columns = ['apple', 'pine', 'peach'];
            tr
                each column in columns
                    th #{column}
            - for (var i = 0; i < 3; i++)
                tr 
                    each column in columns 
                        td #{data[i].column}
```

## Additional Comments
I am not sure how should I do the following trick: inside` index.pug` I do declare a local js array of three possible values `apple`, `pine` and `peach`, and I am use a for-each loop to iterate over this array. However, in the last line of pug, it seems like that pug doesn't substitute the `"column"` in `#{data[i].column}` with `apple`, `pine` and `peach` as the loop is iterating over.

So is there a way to tell pug to replace column in `#{data[i].column}` with the values of same local js variable that I have declared?

Thanks

**Comment by droooney** [comment]
In the last line you should write just JS code. Pug does not replace "column" with the corresponding value, the expression is just being evaluated by JS engine. So instead of `#{data[i].column}` you should write `#{data[i][column]}`.

**Comment by HaoyangFan** [comment]
@droooney  Thank you so much, it works. Now I am curious that why Pug is able to substitute `column` in `{data[i][column]}` with corresponding values `apple`, `pine` and `peach`, but not in my previous way `#{data[i].column}` which I thought is also a valid JS statement?

**Comment by droooney** [comment]
It *is* a valid JS statement, but that code tries to access the `column` property instead of `apple`, `pine` and `peach`.

**Comment by ForbesLindesay** [comment]
This question is just about JavaScript expressions. `foo.bar` is equivalent to `foo['bar']` (i.e. the property called `bar`, rather than the property with the name stored in the value of a variable called `bar`.
