### ISSUE TITLE
The slash is missing

### ISSUE THREAD

**Issue by EpicHigh** [pugjs/pug#3031]
```pug
var indexGallery = <div style="background-image: url(upload/d534efa2.jpeg)"></div>
    article
        .cf.pa2!= indexGallery
```

```html
<div class="cf pa2">
     <div style="background-image: url(upload d534efa2.jpeg)"></div>
</div>
```
When pug renders itself to HTML, the slash disappear like this but other slash render normally.

**Comment by ForbesLindesay** [comment]
Please fill out the issue template. The code you've posted doesn't look like valid pug source code; it starts with a variable declaration, which is not a valid pug statement.
