### ISSUE TITLE
Print Pug syntax block in mixin

### ISSUE THREAD

**Issue by hmalaud** [pugjs/pug#3032]
I am trying to create a mixin to generate both pug and html markups but can't get my head around it. The idea is to have:
```
mixin code
  block
  pre.pug
    **block** // <- only prints pug syntax
  pre.html
    +escape // creates escaped html
      block
```
and then

```
+code
  button.bt-01 Button 1
```
should yield in

```
<pre>
  <button classs="bt-01">Button 1</button> (<- this part is OK)
  button.bt-01 Button 1 (<- this part is NOT OK)
  &lt;button class="bt-01"&gt;Button 1&lt;/button&gt; (<- this part is OK)
</pre>
```

I'm OK with generating the escaped html but can't get the pug syntax to be printed barely as typed in when using the mixin.

**Comment by ForbesLindesay** [comment]
You could probably do it with a custom `filter` as then you'd get given the raw pug code, and you could manually call `pug.render` and escape the html as you see fit. The code inside the `:filter` would not have access to any locals though.
