### ISSUE TITLE
webstorm can't find filter

### ISSUE THREAD

**Issue by Heartz66** [pugjs/pug#3035]
I have installed the `jstransformer-uglify-js` module to uglify my inline javascript, when starting my server, everything works as excepted.

However, webstorm doesn't see it as a valid filter:
![9f22ba7db8be66a733834aed16d8ed07](https://user-images.githubusercontent.com/8833887/42821868-d6bc1618-89d9-11e8-98bd-728b89e60079.png)

**Comment by ForbesLindesay** [comment]
That's a webstorm bug. The pug core team doesn't maintain the webstorm integration, please contact their support instead.
