### ISSUE TITLE
Critical vulnerability in dependency

### ISSUE THREAD

**Issue by DanielAskTia** [pugjs/pug#3039]
**Pug Version:** 2.0.3

I was just looking into securing one of my deployments, and found a tool called `nsp`.  After installing, I ran an `nsp check` and it gave me the following:

Sandbox Bypass Leading to Arbitrary Code Execution
Name       │ constantinople
CVSS       │ 10 (Critical)
Installed  │ 3.0.2
Vulnerable │ <3.1.1
Patched    │ >=3.1.1
Path       │ www@1.0.0 > pug@2.0.3 > pug-filters@3.1.0 > constantinople@3.0.2
More Info  │ https://nodesecurity.io/advisories/568

Any chance of rolling dependency versions?  Any way I can help?  Fork and PR?

**Comment by ForbesLindesay** [comment]
This package already specifies `^3.0.1`, so simply deleting your lock file and then re-installing should pull in the patched version of constantinople

**Comment by DanielAskTia** [comment]
Worked a charm!  Close it on up!
