### ISSUE TITLE
template variable concatenation

### ISSUE THREAD

**Issue by anagarciatemp** [pugjs/pug#3044]
I am trying to concatenate some variable values: 

## Input Pug
 - var authors = ''
 each authorName in slice.repeatable.data
                    - authors += authorName.full_name.value.text + ", "

## Expected HTML

John, Marco, Lewis

## Actual HTML

unable to evaluate [authors += authorName.full_name.value.text + ", "] - Parsing de.neuland.jade4j.expression.JexlExpressionHandler.evaluateExpression@1:10 parsing error near '... rs += auth ...' in article:34

Is this possible? is there any other way of doing it?

**Comment by ForbesLindesay** [comment]
It doesn't look like your using the node implementation of pug. You should ask for help on https://github.com/neuland/jade4j instead.
