### ISSUE TITLE
Can display Unicode characters in Jade/Pug ?

### ISSUE THREAD

**Issue by yctan118** [pugjs/pug#3047]
Newbie here.  Hope my question is appropriate.  I just downloaded the Nodes and Jade 
Can someone guide me how to create a simple page that display Chinese Characters.

**Pug Version:** your version number here

**Node Version:** your version number here
8.11.4
## Input JavaScript Values

```js
pug.renderFile('input.pug', {
  whatIsIt: 'language',
});
```

## Input Pug

```pug
h1 I Love Pug
p It's a great #{whatIsIt}
```

## Expected HTML

```html
<h1>I Love Pug</h1>
<p>It's a great language</p>
```

## Actual HTML

```html
<h1>I Love Pug</h1>
<p>It's a great language</p>
```

**Comment by dylankbuckley** [comment]
@yctan118 Your expected HTML and Actual HTML are the same? Check your question contains the actual scenario including the characters that aren't rendering so people can better assist.

**Comment by ForbesLindesay** [comment]
Pug supports Chinese characters either as literal UTF-8 characters, or HTML escaped via `&...;`.
