### ISSUE TITLE
How to have an empty line in an output HTML?

### ISSUE THREAD

**Issue by evgeniy-vashchuk** [pugjs/pug#3048]
I want to see empty lines in my output HTML, but PUG removes all of it:

![e03544252a](https://user-images.githubusercontent.com/24987866/44628434-5c88aa80-a948-11e8-82c6-dd263d40c433.png)

What I want:

![c87a53db49](https://user-images.githubusercontent.com/24987866/44628466-c903a980-a948-11e8-98fe-8987726a7af0.png)

How can I change this? Pug have any options for this?

**Comment by pratikborsadiya** [comment]
You will have to insert three pipes after a tag on 3 new lines to insert an empty line in output. [Here](https://pugjs.org/language/plain-text.html#whitespace-control) is more info about how PugJS handles white-space.

![screenshot from 2018-08-27 17-01-04](https://user-images.githubusercontent.com/7806891/44657546-d38e7380-aa1a-11e8-8cb0-ec6cd98257c3.png)

**Comment by ForbesLindesay** [comment]
As @pratikborsadiya says, you can use the `|` (pipe) to force an empty line. You can alternatively use `= '\n\n'` to manually insert two line breaks. You should also note that pretty HTML output is not a priority for pug. If you want that kind of fine grained control over your HTML code, you should probably write it by hand.

**Comment by evgeniy-vashchuk** [comment]
Inserting 2 pipes or = '\n' is worked, but it looks ugly...

The main reason of beautiful output HTML for me, is that I will work with final HTML in WordPress...
