### ISSUE TITLE
removing whitespace before #[]

### ISSUE THREAD

**Issue by gPaxbit** [pugjs/pug#3050]
**Pug Version:** 2.0.3
**Node Version:** 10.6
### Input Pug
```pug
p some text #[br]some another text at new line
```
### HTML
```html
<p>some text<br/>some another text at new line</p>
```

In result before tag` br` whitespace'll removing

Code such as `&ensp;` and similar them working, but what then is the benefit when you have to make crutches, instead of just printing  whitespace

**Comment by ForbesLindesay** [comment]
I'm not able to reproduce this. I think the problem is probably that you're looking at the web inspector. The actual text outputted by pug includes the single space character.
