### ISSUE TITLE
TypeError: S.input is not a function while running npm install-test

### ISSUE THREAD

**Issue by ossdev07** [pugjs/pug#3055]
I am struck with type error while running npm install-test.

Please find below error details after running the command:
> pug-monorepo@ pretest /pug
> lerna run pretest

lerna info version 2.9.0
lerna info versioning independent
lerna ERR! pretest Errored while running script in 'pug-runtime'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run pretest
lerna ERR! undefined:1970
lerna ERR!             S.token = S.input();
lerna ERR!                         ^
lerna ERR!
lerna ERR! TypeError: S.input is not a function
lerna ERR!     at next (eval at <anonymous> (/pug/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:1970:25)
lerna ERR!     at Object.parse (eval at <anonymous> (/pug/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:1954:15)
lerna ERR!     at /pug/packages/pug-runtime/prepublish.js:32:22
lerna ERR!     at Array.forEach (<anonymous>)
lerna ERR!     at Object.<anonymous> (/pug/packages/pug-runtime/prepublish.js:18:10)
lerna ERR!     at Module._compile (internal/modules/cjs/loader.js:689:30)
lerna ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
lerna ERR!     at Module.load (internal/modules/cjs/loader.js:599:32)
lerna ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
lerna ERR!     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! pug-runtime@2.0.4 prepublish: `node prepublish`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the pug-runtime@2.0.4 prepublish script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! npm WARN Local package.json exists, but node_modules missing, did you mean to install?
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /root/.npm/_logs/2018-09-27T08_08_23_507Z-debug.log
lerna ERR! error Command failed with exit code 1.

Could you please suggest me on solving the same.
Thanks in advance.

**Comment by ForbesLindesay** [comment]
I don't know what this is about. To install pug you should run `npm install pug`.
