### ISSUE TITLE
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by pmjcreations** [pugjs/pug#3056]
**Pug Version:** your version number here
2.0.3
**Node Version:** your version number here
10.7.0

## Additional Comments

When I run npm install on my server I am getting error message 
```
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/pug failed, reason: unable to get local issuer certificate

```

**Comment by droooney** [comment]
This has nothing to do with pug, search for npm issues.
