### ISSUE TITLE
How to import file on scss filter?

### ISSUE THREAD

**Issue by BloodSucker123** [pugjs/pug#3057]
I tried using the sass parameters like includePath inside may pugjs filter but an error occured.
![screen shot 2018-10-03 at 9 47 49 am](https://user-images.githubusercontent.com/41031355/46385968-6c3aa200-c6f1-11e8-98ec-2674fb9d8ea1.png)

But the transformer or the cli could not locate the specified location.
Also Im using pug-cli on my build
Does someone has an idea on how to fix this? or did I do it wrongly?

**Comment by BloodSucker123** [comment]
I solved the issue by using the `--basedir` option of the pug-cli then instead of using the `--includePath` option of scss transformer I use `@import 'node_modules/compass-mixins/lib/compass';` inside the filter
![screen shot 2018-10-03 at 9 57 42 am](https://user-images.githubusercontent.com/41031355/46386234-cc7e1380-c6f2-11e8-81ae-05ca022027b5.png)

**Comment by ForbesLindesay** [comment]
This looks like a problem with https://github.com/jstransformers/jstransformer-scss but it would need a clear test case submitted to that repo for us to fix it.
