### ISSUE TITLE
Convert HMTL to PUG

### ISSUE THREAD

**Issue by arunkumar413** [pugjs/pug#3058]
I'm using this tool in my express webapp. I need to convert a few HTML snippets to PUG. is it possible to achieve it using this tool.

**Comment by gabrielsimoes** [comment]
No, but this tool is linked in the readme:

https://github.com/donpark/html2jade

**Comment by arunkumar413** [comment]
Can you consider this as a feature request for this tool as other tools are not well maintained and not sure about their support in the future.

**Comment by gabrielsimoes** [comment]
I am not responsible for neither of the two tools. But html2jade should work for what you want. jade is the same format as pug, just its past name.

**Comment by tBoccinfuso** [comment]
> I'm using this tool in my express webapp. I need to convert a few HTML snippets to PUG. is it possible to achieve it using this tool.

https://html-to-pug.com/

**Comment by ForbesLindesay** [comment]
Converting html to pug is out of scope of the pug project. As others have pointed out, there are tools that attempt to do this.
