### ISSUE TITLE
Pass parameters to imported function from node to pug

### ISSUE THREAD

**Issue by algorys** [pugjs/pug#3059]
**Pug Version:** 2.0.3
**Node Version:** v8.12.0
**express:** ~4.16.0
**xmlhttprequest:** ^1.8.0

I'm trying to use a function in my template given by nodejs, but it seems that some parameters of my function (especially with a variable in your "escape" syntax) are set as undefined.

## Input JavaScript Values (**inventory.js**)

```js
// Here a file who use XMLHttpRequest and give me some Post and Get function on an external server.
const HttpClient = require('../tools/http-client');

router.get('/', utils.requireLogin, function(req, res) {
    res.render('inventory/inventory', {..., HttpClient:HttpClient});
});
```

File called **http-client.js**
```js
exports.Post = function (endpoint, params, async = false)
{
    console.log('Params ', params);

    xmlHttp.open( "POST", finalUrl, async); // false for synchronous request
    xmlHttp.setRequestHeader('Content-Type', 'application/json');
    xmlHttp.send(JSON.stringify(params));

    if(xmlHttp.readyState === 4 && xmlHttp.status === 200) {
        console.log("result responce ", JSON.parse(xmlHttp.responseText));
        if(endpoint === "PostInventoryInfo") {
            nodeData = JSON.parse(xmlHttp.responseText);
        }
        return JSON.parse(xmlHttp.responseText);
    } else {
        return {
            result: xmlHttp.responseText,
            code: xmlHttp.status
        };
    }

};
```
## Input Pug

```pug
div.
    script.
        function getNodeInfos(nodePath) {
            // Syntax who runs
            result="!{HttpClient.Post('PostInventoryInfo', {inventory_path: "myPath"})}";
            // Syntax who fails
            result="!{HttpClient.Post('PostInventoryInfo', {inventory_path: nodePath})}";
            return JSON.parse('!{JSON.stringify(HttpClient.getNode())}');
        }
        let nodeInfos = getNodeInfos("somePath");
        console.log('result ', nodeInfos);
```

## Additional Comments

So if I write the text hard, the request passes, but if I use the variable `nodePath`, it arrives undefined from the other side (in the file **http-client.js**)

How can I solve this kind of problem?

**PS:** And I'm looking for documentation on syntax `#{...}`, `!{...}`, but I did not find much that explained how they worked

**Comment by jeromew** [comment]
I am not sure I understand your use case.

by writing

    div.
      script.
        function getNodeInfos(nodePath) {
          ..
        }

when your template will be rendered, you will have a getNodeInfos function defined. The nodePath variable will be defined when, in another browser script, you will call getNodeInfos

the rendering process takes place server side so when `HttpClient.Post('PostInventoryInfo', {inventory_path: "myPath"})`, the server does the call (do you have everything setup so that it works ?) but when `HttpClient.Post('PostInventoryInfo', {inventory_path: nodePath})` is called on the server, nodePath is undefined.

**Comment by algorys** [comment]
The nodePath variable will be defined when I'll click on a button. And yes when `HttpClient.Post('PostInventoryInfo', {inventory_path: nodePath})` is called, nodePath is undefined inside the `Post` function.

In fact I try to access this function to return data received by a REST server. I've also tried to use this function in the **inventory.js** file, `HttpClient` is undefined. That's why I try to use it that way.

**Comment by ForbesLindesay** [comment]
You need to use [js-stringify](https://www.npmjs.com/package/js-stringify) if you want to safely pass variables from rendering into scripts in your HTML.
