### ISSUE TITLE
include style and template at same time

### ISSUE THREAD

**Issue by theonlygusti** [pugjs/pug#3062]
**Pug Version:** 2.0.3

**Node Version:** 9.8.0

## Input JavaScript Values

```js
pug.renderFile('input.pug');
```

## Input Pug

something like this

```pug
//- input.pug
doctype html
html
  head
    link(rel="stylesheet",href="/css/input.css")
  body
    include nav.pug
```

```pug
//- nav.pug
head
  //- ^^ or "append head" or something
  link(rel="stylesheet",href="/css/nav.css")

//- now the template stuff that will get rendered
ol
  li Home
  li About
```

## Expected HTML

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="/css/input.css">
    <link rel="stylesheet" href="/css/input.css">
  </head>
  <body>
    <ol>
      <li>Home</li>
      <li>About</li>
    </ol>
  </body>
</html>
```

## Actual HTML

probably doesn't compile

## Additional Comments

I want to be able to use includes like widgets or something, have custom styling on them.

They should be able to put stuff in the head and into the body at the same time.

**Comment by tBoccinfuso** [comment]
In your example, you would be rendering out two <head> elements, which of course is not valid markup. What I would suggest doing is remove the head element in nav.pug and in that stylesheet target the nav item only that way styles are not applied on a global level.

**Comment by ForbesLindesay** [comment]
It sounds like what you really want is inheritance.
