### ISSUE TITLE
Should we expose runtime methods on "pug" exports in addition to "pug.runtime"?

### ISSUE THREAD

**Issue by niftylettuce** [pugjs/pug#3065]
I experienced the following error message in [cache-pug-templates](https://github.com/ladjs/cache-pug-templates).

```sh
TypeError: pug.rethrow is not a function
```

Due to the fact that the project uses `const pug = require('pug');` instead of `const pug = require('pug-runtime');`.  When `require('pug')` is used, the runtime functions are nested inside `pug.runtime` as opposed to being available on the `pug` object itself.

```sh
> require('pug-runtime');
{ merge: [Function: pug_merge],
  classes: [Function: pug_classes],
  style: [Function: pug_style],
  attr: [Function: pug_attr],
  attrs: [Function: pug_attrs],
  escape: [Function: pug_escape],
  rethrow: [Function: pug_rethrow] }
> require('pug');
{ name: 'Pug',
  runtime:
   { merge: [Function: pug_merge],
     classes: [Function: pug_classes],
     style: [Function: pug_style],
     attr: [Function: pug_attr],
     attrs: [Function: pug_attrs],
     escape: [Function: pug_escape],
     rethrow: [Function: pug_rethrow] },
  cache: {},
  filters: {},
  compile: [Function],
  compileClientWithDependenciesTracked: [Function],
  compileClient: [Function],
  compileFile: [Function],
  render: [Function],
  renderFile: [Function],
  compileFileClient: [Function],
  __express: [Function] }
```

It's only an issue when the user is using `eval()` pretty much, as we do with `cache-pug-templates`.

Feel free to close this if you feel it is a non-issue, but I had to do a workaround as such in the latest release of `cache-pug-templates` to resolve this:

```sh
const pug = require('pug');

Object.entries(pug.runtime).forEach((key, value) => {
  pug[key] = value;
});
```

**Comment by niftylettuce** [comment]
cc @ForbesLindesay - you may have run into this bug if you are using `cache-pug-templates`

**Comment by niftylettuce** [comment]
The alternative fix is to compile the views as if they were for the client (which inlines the runtime functions into the templates).

**Comment by niftylettuce** [comment]
For perf:

```
for (const [key, value] of Object.entries(pug.runtime)) {
  pug[key] = value;
}
```

**Comment by ForbesLindesay** [comment]
Why not do `new Function('pug', src)(pug.runtime)`, similar to what pug does natively?
