### ISSUE TITLE
how do you pass {debug:true} option for pug?

### ISSUE THREAD

**Issue by MR-T77** [pugjs/pug#3071]
How can I use this debug option while rendering a page with parameters?:

```
res.render("target", {
          title: title,
          wavs: wav,
          params: params,
        });
```
And what's the best way to debug the rendering process? (I'm having some errors but can't figure what's going on?)

**Comment by kylekatarnls** [comment]
Locals and options are the same object according to the documentation:
https://pugjs.org/api/reference.html#pugrendersource-options-callback

```js
res.render("target", {
          debug: true,
          title: title,
          wavs: wav,
          params: params,
        });
```
