### ISSUE TITLE
weird behaviour accessing object property

### ISSUE THREAD

**Issue by Rajoba** [pugjs/pug#3072]
** pug:2.0.0-beta11** your version number here
**Node Version:11** your  number here

## Input JavaScript Values
    res.render('index', {
            title: 'Express',
            templates: ['BD/TD','BD/MD/TD','SDF/MD','PD/MD','4S/MD','6S/MD'],
            root: {"BD_TD":{"XXX":{"Foo":{"qty":"1000","cst":"XXX","prj":"Foo"}},"cur":{"cst":"XXX","prj":"Foo"}}},
            idstr: function (str){
                var res = str.replace(/\s+|\-|\//g,'_');
                res     = res.replace(/^(\d)(.+)/,"\_$1$2");
                return res;
            }
        });

## Input Pug
    extends layout

    block content
      h1= title
      p #{JSON.stringify(root)}
      p #{JSON.stringify(templates)}
      each tpl in templates
          - var id = idstr(tpl);
          h5 #{JSON.stringify(root[id])}
          h4 +#{id} / #{tpl}+
          h4 #{root[id].cur.cst}

## Expected HTML
   <h5>{"XXX":{"Foo":{"qty":"1000","cst":"XXX","prj":"Foo"}},"cur":{"cst":"XXX","prj":"Foo"}}</h5>
    <h4>+BD_TD / BD/TD+</h4>
    <h4>XXX</h4>

## Actual HTML
can't call cur on undefined ...

## Additional Comments
This works! why???

    extends layout

    block content
      h1= title
      p #{JSON.stringify(root)}
      p #{JSON.stringify(templates)}
      each tpl in templates
          - var id = idstr(tpl);
          - var tmp = 'BD_TD';
          h5 #{JSON.stringify(root[id])}
          if id === tmp
              h4 +#{id} / #{tpl}+
              h4 #{root[id].cur.cst}

**Comment by Rajoba** [comment]
https://github.com/Rajoba/pugtest.git

**Comment by droooney** [comment]
You have many values in your `templates` value, but only one of them has its corresponding content in `root ` value, therefore the error.
