### ISSUE TITLE
How to set cache-control in pug template?

### ISSUE THREAD

**Issue by nebitrams** [pugjs/pug#3075]
**Pug Version:** 2.0.3

**Node Version:** 10.13.0

## Input Pug

```pug
html
  title My Page
    meta (charset='utf-8')
    meta( http-equiv='Cache-Control', content='public, max-age=86400')
```

## Expected HTML

```html
<head>
  <title>Elo Challenge</title>
  <meta charset="utf-8">
  <meta http-equiv="Cache-Control" content="public,max-age=86400">
</head>
```

## Additional Comments

The final rendered html has Cache-Control but I still cannot achieve caching at browser.  How do I set the cache-control in pug template?  I am using it with Express in Parse-Server.

**Comment by Jikstra** [comment]
Cache-Control has to be set as a http header, you can't do that from inside the html markup. You can set the http header directly in your express server. https://stackoverflow.com/questions/23751914/how-can-i-set-response-header-on-express-js-assets

**Comment by ForbesLindesay** [comment]
your expected html matches the actual html you get. As @Jikstra says, you should set the headers outside of pug.
