### ISSUE TITLE
Vue attribute modifier causes "Unexepected token"

### ISSUE THREAD

**Issue by vpratfr** [pugjs/pug#3077]
**Pug Version:** 2.0.3

## Input Pug

```pug
address-control(
:options.sync="addresses",
v-model="selectedAddress")

address-control(
':options.sync'="addresses",
v-model="selectedAddress")
```

None of the above alternative give the expected HTML but give the error `Module build failed: SyntaxError: Unexpected token`

## Expected HTML

```html
<address-control :options.sync'="addresses" v-model="selectedAddress"></address-control>
```

## Additional Comments

If I remove the `.sync` part from the attribute name, it works (but not on VueJS side of course).

**Comment by ForbesLindesay** [comment]
```pug
address-control(
:options.sync="addresses",
v-model="selectedAddress")

address-control(
':options.sync'="addresses",
v-model="selectedAddress")
```

works fine for me:

```html
<address-control :options.sync="addresses" v-model="selectedAddress"></address-control><address-control :options.sync="addresses" v-model="selectedAddress"></address-control>
```

Your error does not look like a typical pug error, and you haven't provided a stack trace.
