### ISSUE TITLE
Cannot Install pug via npm install

### ISSUE THREAD

**Issue by fredreyestwist** [pugjs/pug#3078]
**Pug Version:** not installing

**Node Version:** 11.2.0

## Additional Comments

When I try to install using "npm install pug" command, I get these errors:

npm WARN saveError ENOENT: no such file or directory, open '/Users/myusername/Development/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/myusername/Development/package.json'
npm WARN Development No description
npm WARN Development No repository field.
npm WARN Development No README data
npm WARN Development No license field.

What could be the problem here?

**Comment by droooney** [comment]
You need to create `package.json` in your project directory in order to install `npm` packages. That could be done running `npm init` (interactive mode) or `npm init -y` (automatically fills the fields).

**Comment by droooney** [comment]
If you intend to use Pug CLI you need to install [pug-cli](https://www.npmjs.com/package/pug-cli).

**Comment by marichellebisuna** [comment]
try to update your node by npm install npm@latest -g
then clear the cache by npm cache clean --force
then you can finally install the pug by npm install pug@latest
it should work after these.

i did this when i had the same problem of not being able to install the pug : )

**Comment by tejasnavalkhe1810** [comment]
![error](https://user-images.githubusercontent.com/63551486/98162198-ff64e800-1f06-11eb-8771-b5430027a723.png)
**Please, Help me**

I got this error, I am just started Backend. (Please, find the image below.)

**Comment by atishbagate** [comment]
thank you i do this steps and it works
