### ISSUE TITLE
CSS not showing

### ISSUE THREAD

**Issue by shetberd** [pugjs/pug#3079]
**Pug Version:** 2.0.3

**Node Version:** v8.12.0

## Input JavaScript Values

```js
app.get('/test', (req, res) => {
  res.render('test');
});

router.get('/login', (req,res) => {
  res.render('test');
});
```

## Input Pug

```pug
extends home

block content
  div(class="content")
    a(href="/auth/google") Google+
    p asfas

```

## Expected HTML
With css styles
```html
<html><head><title>Šnaps</title><link href="style.css" rel="stylesheet"/></head><body><div class="topnav"><nav><a href="/">Home</a><a href="/auth/login">Login</a></nav><br/></div></body><div class="content"><a href="/auth/google">Google+</a><p>asfas</p></div></html>
```

## Actual HTML
Without css styles
```html
<html><head><title>Šnaps</title><link href="style.css" rel="stylesheet"/></head><body><div class="topnav"><nav><a href="/">Home</a><a href="/auth/login">Login</a></nav><br/></div></body><div class="content"><a href="/auth/google">Google+</a><p>asfas</p></div></html>
```

## Additional Comments
Im sry if this is the wrong place to post my issue,i cant figure out whats going on...
When i go through the /test route i get the page with css,but when i go through the router /auth/login 
the css wont load or something...both routes rendering the same pug file and the html source is the same on both routes

**Comment by ForbesLindesay** [comment]
Your expected html and actual html are the same, so this has nothing to do with pug. You should make sure your `style.css` file is actually being served and fetched, which you can check in the network tab of the browser dev tools.
