### ISSUE TITLE
import javascript in block append/prepend

### ISSUE THREAD

**Issue by dasiyes** [pugjs/pug#3081]
**Pug Version:** 2.0.3

**Node Version:** 10.13

## Input JavaScript Values

```js

```

## Input Pug

```pug
// layout.pug
body
  block content
  block bodyscripts
---------------------
// my_page.pug
...
block prepand bodyscripts
    script(language='javascript', src='https://cdnjs.cloudflare.com/ajax/libs/blueimp-md5/2.10.0/js/md5.min.js')
```

## Expected HTML

```html
...
<script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-md5/2.10.0/js/md5.min.js"></script>
...
```

## Actual HTML

```html
...
<script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-md5/2.10.0/js/md5.min.js"></script>
...
```

## Additional Comments
If the import is done as described above - I am getting: "Uncaught ReferenceError: md5 is not defined"
If I use exact same code to import md5 library in the layout.pug head - everything works perfectly. However I need this lib only in one of my pages and would like to include it only in it. I have tried to replace the block instead of append/prepend, but it did not work either.

**Comment by ForbesLindesay** [comment]
Your actual and expected html are the same.
