### ISSUE TITLE
Interpolation for attribute names

### ISSUE THREAD

**Issue by DzmVasileusky** [pugjs/pug#3082]
**Pug Version:** 2.0.3

**Node Version:** 8.11.4

Since Angular 2 tags can have refs attributes, which looks like: <input #someName="ngModel">.
In this case attribute name becomes a dynamic value. So it would be great to interpolate a variable here while using form control mixins.
```
mixin formControl(name, model)
    input.form-control(
        `#${name}`="ngModel", [(ngModel)]=`${model}.${name}`,
        name=`${name}`, type="text"
    )&attributes(attributes)
```

Currently it causes an error 

> DOMException: Failed to execute 'setAttribute' on 'Element': '`#${name}`' is not a valid attribute name.

**Comment by droooney** [comment]
You can just use `attributes`:

```pug
mixin formControl(name, model)
    input.form-control(
        [(ngModel)]=`${model}.${name}`,
        name=`${name}`, type="text"
    )&attributes(attributes)&attributes({[name]: 'ngModel'})
```

**Comment by DzmVasileusky** [comment]
@droooney Thanks a lot. Missed this, tried to find in mixin section of docs.
