### ISSUE TITLE
list attribute on input tag cases Unexpected token exception when rendering page

### ISSUE THREAD

**Issue by jim-holmes-vtcsecure** [pugjs/pug#3085]
**Pug Version:** your version number here

2.0.3

**Node Version:** your version number here

10.14.0

## Input JavaScript Values

res.render('acdAdmin/adminView.pug', {socketURL: socketURL, tenantId: req.locals.tenant.id, logout_destination: req.locals.tenant.on_logout_destination, userIdentifier: identifier, userName: makeFullName(result.data.first_name, result.data.last_name)});

## Input Pug

        .form-group
          label.col-sm-4.col-sm-offset-2(for="ctcTextColor", title="Text color") Text color
          .col-sm-5
            input#ctcTextColor(type="text", title="Text color", list="textColors")

        .form-group
          label.col-sm-4.col-sm-offset-2(for="ctcBackgroundColor", title="Background color") Background color
          .col-sm-5
            input#ctcBackgroundColor(type"text", title="Background color", list="backgroundColors")
            
        .form-group
          label.col-sm-4.col-sm-offset-2(for="ctcUserBalloonTextColor", title="Your sms text color") Your sms text color
          .col-sm-5
            input#ctcUserBalloonTextColor(type="text", title="Your sms text color", list="textColors")

        .form-group
          label.col-sm-4.col-sm-offset-2(for="ctcUserBalloonBackgroundColor", title="User sms background color") Your sms background color
          .col-sm-5
            input#ctcUserBalloonBackgroundColor(type"text", title="Your sms background color", list="backgroundColors")
            
        .form-group
          label.col-sm-4.col-sm-offset-2(for="ctcOtherUserBalloonTextColor", title="Other person's text color") Other's sms text color
          .col-sm-5
            input#ctcOtherUserBalloonTextColor(type="text", title="Other person's sms text color", list="textColors")

        .form-group
          label.col-sm-4.col-sm-offset-2(for="ctcUserBalloonBackgroundColor", title="Other person's sms background color") Other's sms background color
          .col-sm-5
            input#ctcOtherBalloonBackgroundColor(type"text", title="Other person's sms background color", list="backgroundColors")
            
        datalist#textColors
          option(value="black") Black
          option(value="red") Red
          option(value="yellow") Yellow
          option(value="gold") Gold
          option(value="darkblue") Dark Blue
          option(value="darkgreen") Dark Green
          option(value="white") White

        datalist#backgroundColors
          option(value="black") Black
          option(value="darkolivegreen") Dark Green
          option(value="green") Green
          option(value="grey") Grey
          option(value="lightblue") Light Blue
          option(value="beige") Beige
          option(value="white") White

## Expected HTML

<div class="form-group"><label class="col-sm-4 col-sm-offset-2" for="ctcTextColor" title="Text color">Text color</label><div class="col-sm-5"><input id="ctcTextColor" type="text" title="Text color" list="textColors"></div></div><div class="form-group"><label class="col-sm-4 col-sm-offset-2" for="ctcBackgroundColor" title="Background color">Background color</label><div class="col-sm-5"><input id="ctcBackgroundColor" type"text title="Background color" list="backgroundColors"></div></div><div class="form-group"><label class="col-sm-4 col-sm-offset-2" for="ctcUserBalloonTextColor" title="Your sms text color">Your sms text color</label><div class="col-sm-5"><input id="ctcUserBalloonTextColor" type="text" title="Your sms text color" list="textColors"></div></div><div class="form-group"><label class="col-sm-4 col-sm-offset-2" for="ctcUserBalloonBackgroundColor" title="User sms background color">Your sms background color</label><div class="col-sm-5"><input id="ctcUserBalloonBackgroundColor" type"text title="Your sms background color" list="backgroundColors"></div></div><div class="form-group"><label class="col-sm-4 col-sm-offset-2" for="ctcOtherUserBalloonTextColor" title="Other person's text color">Other's sms text color</label><div class="col-sm-5"><input id="ctcOtherUserBalloonTextColor" type="text" title="Other person's sms text color" list="textColors"></div></div><div class="form-group"><label class="col-sm-4 col-sm-offset-2" for="ctcUserBalloonBackgroundColor" title="Other person's sms background color">Other's sms background color</label><div class="col-sm-5"><input id="ctcOtherBalloonBackgroundColor" type"text title="Other person's sms background color" list="backgroundColors"></div></div><datalist id="textColors"><option value="black">Black</option><option value="red">Red</option><option value="yellow">Yellow</option><option value="gold">Gold</option><option value="darkblue">Dark Blue</option><option value="darkgreen">Dark Green</option><option value="white">White</option></datalist><datalist id="backgroundColors"><option value="black">Black</option><option value="darkolivegreen">Dark Green</option><option value="green">Green</option><option value="grey">Grey</option><option value="lightblue">Light Blue</option><option value="beige">Beige</option><option value="white">White</option></datalist>

## Actual HTML

Fails to render

SyntaxError: Unexpected token (21:13368)
    at Parser.pp$4.raise (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp.expect (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:617:26)
    at Parser.pp$3.parseExprList (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2406:14)
    at Parser.pp$3.parseSubscripts (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1900:29)
    at Parser.pp$3.parseExprSubscripts (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1875:21)
    at Parser.pp$3.parseMaybeUnary (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOp (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1810:41)
    at Parser.pp$3.parseExprOps (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1793:15)
    at Parser.pp$3.parseMaybeConditional (/opt/product/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1774:19)

## Additional Comments

It is the list= attributes on the input tags that are the problem.  If I remove them, it creates the HTML correctly.   

This works ok (it produces HTML) on some systems but not on others (it gets the exception).   I don't know what the difference is between the systems.  I also tried this using Node 8.14.x and it still failed.

**Comment by ForbesLindesay** [comment]
I'm unable to reproduce this. For me it renders fine.
