### ISSUE TITLE
有人在webstorm里的vue文件里用过pug吗

### ISSUE THREAD

**Issue by cuteCloud** [pugjs/pug#3086]
指定vue模板template的属性lang=‘pug’后，安装有pug（ex-Jade）插架，模板内的pug语法可以高亮，但是无法折叠，但单独的xxx.pug格式的文件内pug语法的代码可以折叠。有解决办法吗？

**Comment by ForbesLindesay** [comment]
I think your best bet would be to ask for help directly from the makers of WebStorm.

我认为你最好的选择是直接向WebStorm的制造商寻求帮助。
Wǒ rènwéi nǐ zuì hǎo de xuǎnzé shì zhíjiē xiàng WebStorm de zhìzào shāng xúnqiú bāngzhù.

**Comment by ForbesLindesay** [comment]
Duplicate of #3090
