### ISSUE TITLE
TypeError: this.input.charCodeAt is not a function

### ISSUE THREAD

**Issue by zkxwpdam** [pugjs/pug#3089]
```
Exception has occurred: TypeError
TypeError: this.input.charCodeAt is not a function
    at Parser.fullCharCodeAtPos (xyz\node_modules\babylon\lib\index.js:781:27)
```

**Pug Version:** 2.0.0-beta11
**Node Version:** v10.14.1

## Input JavaScript Values

```js
// using express v4.16.0
app.set('view engine', 'pug');
```

## Input Pug 💥 

```pug
form()
  input(type="text" required)
```
when rendering **Exception has occurred: TypeError**
[Official docs says Boolean attributes should work this way](https://pugjs.org/language/attributes.html#boolean-attributes)

## Input Pug ✅ 

```pug
form()
  input(type="text" required=true)
```
**works fine without throwing Exception**

## Additional Comments

I guess this is not strictly a pug issue, but in case anyone else encounters the same error, just put some `=true` by your Boolean attributes. 👍 

PS: This seems to be a caught Exception anyways. I just found it while debug with VS Code break on all Exceptions 😎

**Comment by ForbesLindesay** [comment]
A caught exception in a dependency sounds like it's not a problem :)
