### ISSUE TITLE
i use pug to vue‘s template in webstorm，can't Folding code

### ISSUE THREAD

**Issue by cuteCloud** [pugjs/pug#3090]
As the title suggests，the picture show i can fold the all template，not the son code block
![qq 20190104090449](https://user-images.githubusercontent.com/17820879/50669392-eedc4180-0fff-11e9-805d-7d17b75f7e91.png)

**Comment by ForbesLindesay** [comment]
This is a problem with webstorm, not pug. Please ask webstorm for support.

**Comment by cuteCloud** [comment]
> This is a problem with webstorm, not pug. Please ask webstorm for support.

thanks
