### ISSUE TITLE
Static variable no longer static after passing into a mixin

### ISSUE THREAD

**Issue by SilentAntenna** [pugjs/pug#3091]
**Pug Version:** 2.03

**Node Version:** 10.14.2

The following template cannot be compiled by pug. "opt" is considered as a is non-constant variable (it is, of course). If this is intentional, I think this issue should be specified in the documents.

## Pug Template

```pug
mixin fn(opt)
  :my-filter(opt=opt)

+fn('option')
```

**Comment by droooney** [comment]
It is specified ([here](https://pugjs.org/language/filters.html) inside the warning block).

**Comment by SilentAntenna** [comment]
@droooney 

The problem is, there is no dynamic content in this template. It can be rendered at compile time, but pug didn't do it.

**Comment by droooney** [comment]
Filters don't support neither dynamic content nor dynamic options as stated in the warning block. You example contains dynamic options therefore the error.

**Comment by SilentAntenna** [comment]
I see that. thanks.
