### ISSUE TITLE
How can I call variables in loop pug?

### ISSUE THREAD

**Issue by karzol73** [pugjs/pug#3092]
What is the correct syntax to call predefined arrays in a loop in jade/pug? Thank you in advance!

```
- var test_1 = [1, 2, 3]
    - var test_2 = [4, 5, 6]
    - var test_2 = [7, 8, 9]

    - for(var i = 1; i < 3; i++) {      
        each n in 'test_' + i
          p= n
    - }
```

**Comment by ForbesLindesay** [comment]
There's no way to do this, just as there would be no way to dynamically reference a variable in JavaScript. What you can always do is something like:

```pug
- var lists = [test_1, test_2, test_3]
each list in lists
  each n in list
    p= n
```
