### ISSUE TITLE
Output single quote in data attributes

### ISSUE THREAD

**Issue by Nurjaman57** [pugjs/pug#3095]
Hi,
How can i escape single being render in data attributes
here is my pug code 
https://prnt.sc/ma3cel

it outputing like 
https://prnt.sc/ma3dh4

i need to like this so i can set option for different instance for my carousel 
https://prnt.sc/ma3ebb

Please someone help me otherwise i need t rewrite my entire template using plain html :( :( :( 

Thanks in advance 
Nur

**Comment by ForbesLindesay** [comment]
You can do it via:

```pug
.carousel(data-slick!={slidesToShow:3, slidesToScroll:3}) Google
```

When you `JSON.stringify` with escaping disabled, pug outputs single quotes.

### N.B. This will not do any escaping. If you have user input in that object, it could cause a Cross Site Scripting Vulnerability.
