### ISSUE TITLE
Feature request: Force unescaped output

### ISSUE THREAD

**Issue by rotsee** [pugjs/pug#3100]
**Pug Version:** 2.0.3

I would suggest to add an option that makes all output unescaped. The use case is debugging, where I want to add some markup around various helper methods in debug mode. The workaround is to search and replace all `#{` with `!{` before rendering, but this is not always straightforward. 

## Input JavaScript Values

```js
helperFunctions.upperCase = (t) => {
 let output = t.toLocalUpperCase
 if (helperFunctions.debug) {
   output = `<span data-method="upperCase" data-message="Something that's useful for debugging">${output}</span>`
 }
 return output
}
pug.renderFile('input.pug', helperFunctions, {unescapedOutput: true});
```

## Input Pug

```pug
p Hello #{upperCase('world')}!
```

## Expected HTML

```html
<p>Hello <span data-method="upperCase" data-message="...">World</span>!</p>
```

## Actual HTML

```html
<p>Hello &lt;span data-method="upperCase" data-message="..."glt;World&lt;/spanglt;!</p>
```

## Additional Comments

I realize this is not a common need, but I seems like something that could farily easily be added to the rendering options.

**Comment by droooney** [comment]
This functionality already exists. Take a look at [this](https://pugjs.org/language/interpolation.html#string-interpolation-unescaped).

**Comment by rotsee** [comment]
@droooney Sorry, I was probably unclear. The feature I'd find useful is a setting (when rendering the template) to make `#{...}` behave like `!{...}`, without the template author having to take any action.

**Comment by ForbesLindesay** [comment]
This is a security foot-gun for a one-off use case. Sorry, but we're not ever going to support this.
