### ISSUE TITLE
Is it the expected behavior for plain text feature?

### ISSUE THREAD

**Issue by reebr** [pugjs/pug#3111]
I'm trying to use the [plain text](https://pugjs.org/language/plain-text.html) feature to define the content of a `<img>` tag based on a variable. I have a boolean variable that defines when I'm in "development mode". When this value is set to `false` I would like to use a raw string that will be processed by my server (it is a Flask application).

So I've tried this:

```pug
if development
   img#qr-code(src='https://via.placeholder.com/300')
else
   | <img src='{{ qrcode }}' id='qr-code' title='QR code'>
```

When I compile it with `- var development = true`, everything works.
But, when I use `- var development = false`, it fails. Is pug trying to render `{{ qrcode }}`?

**Comment by ForbesLindesay** [comment]
With development set to false, pug outputs:

```html
<img src='{{ qrcode }}' id='qr-code' title='QR code'>
```
