### ISSUE TITLE
the keyword "block" can not be expanded to a tag named `<block>`

### ISSUE THREAD

**Issue by BananaAcid** [pugjs/pug#3112]
As an idea.

Since HTML5 is not strict and any tag name is permitted, as well as future html versions might introduce new tag names (yes, w3c asks coders to use tagnames with a dash in between to differentiate), i think, the mixins `block` keyword should also be usable as for example `+block` or `!block`, so `block` can be expanded to a tag as `<block>` ... (by using a config switch?).

This came up in a project, where web components were generated from pug.

**Comment by ForbesLindesay** [comment]
We use lots of keywords in pug. This isn't changing any time soon.
