### ISSUE TITLE
How to explicitly end the 'dot' block ? 

### ISSUE THREAD

**Issue by AntonGrekov** [pugjs/pug#3117]
if i write 'dot' block of plain text, how do i then end it ?

example:

    #start.block
      .h1.
        lorem ipsum plain text
        input(type=button)

I want input to be a tag not text.

**Comment by ezhlobo** [comment]
@AntonGrekov indentation is the main idea in pug, so in your case you can make it work this way:

```pug
#start.block
  .h1
    .
      lorem ipsum plain text

    input(type=button)
```
