### ISSUE TITLE
V2 - Data/Aria Attribute shorthand

### ISSUE THREAD

**Issue by bardbess** [pugjs/pug#3120]
**Pug Version:**  2.0.3

**Node Version:** v11.7.0

## Input Pug

```pug
div(data=(name='myName'  id='myId')) Welcome
.tab-contents
  .panel-1(role='tabpanel'  aria=(labelledby='tab-1'  hidden='false') Tab 1 Content
  .panel-2(role='tabpanel'  aria=(...ariavalues) Tab 2 Content
```

## Desired HTML

```html
<div data-name='myName' data-id='myId' >Welcome</div>
<div class="tab-contents">
  <div id="panel-1" role="tabpanel" aria-labelledby="tab-1" aria-hidden="false">Tab 1 Content</div>
  <div id="panel-2" role="tabpanel" aria-labelledby="tab-2" aria-hidden="false">Tab 1 Content</div>
</div>
```

## Additional Comments

This is another request for a shorthand method when setting `data` and `aria` attributes. #670 suggested opening a new issue if this is not resolved post v2. A PR (#572) was also created as a possible solution.

Perhaps the es6 spread operator could be used to spread values from an object into a data attribute?

Alternative could be a haml like syntax.

```
div(data:{attr1: data.value, attr2: data.value2})
```

Really any shorthand would be great!

**Comment by ForbesLindesay** [comment]
I do not have any intention to add any attribute shorthands to pug. I think it will make the language too difficult to understand and learn.
