### ISSUE TITLE
[expressjs] Interpolation, e.g. `This is #{title}`, outputs "This is"; string not rendered.

### ISSUE THREAD

**Issue by dennismayr** [pugjs/pug#3122]
When creating an `express` project with `pug` as template engine, a default `index.pug` is generated in the following fashion:

_index.pug_
```
extends layout

block content
  h1= title
  p Welcome to #{title}
  p This is #{title}, but it won't be rendered in Express.
```

_layout.pug_
```
doctype html
html
  head
    title= title
    link(rel='stylesheet', href='/stylesheets/style.css')
  body
    block content
```

However, when loading `/` (e.g. `127.0.0.1:8080`), the following text is rendered to the screen:

**Welcome to**

**This is , but it won't be rendered in Express.**

I checked the `pug` documentation, things seem in place, including the addition (if missing) of the following snippets:

_app.js_
```
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');
```

_server.js_
```
app.get('/', (req, res) => {
    res.render('index.pug');
});
```

Text is rendered correctly in every HTML hierarchy, **except** for interpolation `#{tags}`.

Is this a known interaction between `pug` and `express`?
Is there a syntax workaround to avoid the issue in the meantime?

**Comment by jeromew** [comment]
cf https://expressjs.com/en/guide/using-template-engines.html
no wonder why `#{title}` is empty if you do not pass a value for title.

**Comment by dennismayr** [comment]
My `./route/index.js does have
```
router.get('/', function(req, res, next) {

  res.render('index', { title: 'The Jaguar House' });

});
```

**Comment by jeromew** [comment]
in your first post you said

````
app.get('/', (req, res) => {
    res.render('index.pug');
});
````
I really don't think this is a problem with pug.

**Comment by dennismayr** [comment]
You're right. PEBCAK.

Never mind, thanks for the heads-up.
