### ISSUE TITLE
Feature Request: include, extends 'alias'

### ISSUE THREAD

**Issue by pronist** [pugjs/pug#3125]
**Pug Version:** your version number here

**Node Version:** your version number here

## Input JavaScript Values

```js
options: {
  basedir: process.cwd(),
  alias: {
    '@': 'node_modules/@my',
  }
}
```

## Input Pug

```pug
//- include __BASE_DIR__/node_modules/@my/myModule/Example
include @/myModule/Example
```

## Additional Comments

I want to use alias in 'include', or 'extends' file path :)

**Comment by pronist** [comment]
I made it.
<https://github.com/pronist/pug-alias>

Thanks :)

**Comment by ForbesLindesay** [comment]
This is awesome. You could try writing it as a `{resolve}` plugin. That way you could just pass `{plugins: [require('pug-plugin-alias')({'@': 'node_modules/@my'})]}` to the regular `pug` package.

All you'd need would be to have something like:

```js
const load = require('load');
const path = require('path');

module.exports = aliases => ({
  resolve(filename, source, loadOptions) {
    // custom code to handle custom filenames, returning an absolute path to the resolved files
    for(let i = 0; i < Object.keys(options.alias).length; i++) {
      var alias = Object.keys(options.alias)[i];
      if(filename.indexOf(alias) === 0) {
        path.resolve(filename.replace(alias, options.alias[alias]));
      }
    }
    // fallback to:
    return load.resolve(filename, source, loadOptions);
  }
});
```

Currently, we only support one `resolve` plugin, but we may relax that constraint in the future.

**Comment by pronist** [comment]
Great!
 
Why is not there 'how to write plugin' on official documentation?
I think, this is useful for people.

**Comment by ryanmeador** [comment]
@ForbesLindesay, would you be able to expand upon your last comment?  I'd really like to use this functionality, but I don't understand how to pass the plugin to Pug.  @pronist's link is now dead, and my Google-fu can't turn up anything about plugins for Pug except filters.  I'm using Pug with Express, if that matters.  Sorry to dredge up an old thread, and thank you for your help!
