### ISSUE TITLE
require("pug") causes unknown server error on AWS Lambda

### ISSUE THREAD

**Issue by JL102** [pugjs/pug#3127]
**Pug Version:** 2.0.3

**Node Version:** 8.10

## Input JavaScript Values

```js
var pug = require("pug");
```

## Input Pug

```pug
doctype html
html
	head
		title test
	body
		p test
```

## Expected HTML

```html
<!DOCTYPE html>
<html>
  <head>
    <title>hello</title>
  </head>
  <body>
    <p>hey</p>
  </body>
</html>
```

## Actual HTML

```html
{"message": "Internal server error"}
```

## Additional Comments
I originally tried using Express's built-in `res.render` function to render Pug, but no matter what I tried, the process would hang for 3 seconds then terminate. (`res.send` and `res.sendFile` work.) 

Then, I managed to narrow it down to the `require` function by attempting to render a page manually. Code:

```js
router.get('/', function(req, res){
	
	console.log("gonna ask for fs");
	
	var fs = require("fs");
	
	console.log("gonna ask for pug");
	
	var pug = require("pug");
	
	console.log("got my reqs");
	
	var pugString = fs.readFileSync(__dirname+"/views/test.pug");
	
	console.log("pugString: "+pugString);
	
	// Compile a function
	var fn = pug.compile(pugString);
	
	console.log(fn);

	// Render the function
	var html = fn({});
	
	console.log(html);
	
	res.send(html);
});
```
Output:
```
START RequestId: 18e82ba4-ec50-4aef-b635-01d6d545c47e Version: $LATEST
2019-04-02T20:19:40.075Z	18e82ba4-ec50-4aef-b635-01d6d545c47e	gonna ask for fs
2019-04-02T20:19:40.077Z	18e82ba4-ec50-4aef-b635-01d6d545c47e	gonna ask for pug
END RequestId: 18e82ba4-ec50-4aef-b635-01d6d545c47e
REPORT RequestId: 18e82ba4-ec50-4aef-b635-01d6d545c47e	Duration: 3014.88 ms	Billed Duration: 3000 ms Memory Size: 128 MB	Max Memory Used: 76 MB	
```
The process hangs during the `require("pug")` call, and does not give any error message for me to work with.  During my testing, I also tried to use Jade version 1.11.0, but I got the same issue.

Is there some setting I'm missing, maybe?? Some way to set up the package on Lambda that isn't written in the pugjs.org docs? Any other `require` function that I've seen does work. Just not pug.

**Comment by JL102** [comment]
Looks like it was a RAM issue. AWS didn't give any hints that it was this, but increasing the allocated memory of the function from 128MB to 384MB fixed the issue.

**Comment by ForbesLindesay** [comment]
I'd probably recommend pre-compiling pug templates like you would for running them client side. That way you won't need to include pug in what you deploy.
