### ISSUE TITLE
pass parameters form .pug file to .js file

### ISSUE THREAD

**Issue by Ram0987** [pugjs/pug#3128]
**Pug Version:** 2.0.3

**Node Version:** 10.15.0

Hey,
I am trying to render a plot using express's `res.render()` method. chart's date points are stored in with in a `node` variable. I have managed to pass those values to `.pug` file. Now I have to pass the same data points form `.pug` to `.js` file. 

How do i accomplish this? I will be thankful for your advice of any kind.

Thanks!!

**Comment by ForbesLindesay** [comment]
You can pass the `jsStringify` helper to your pug template:

```js
const jsStringify = require('js-stringify');

app.get('/chart', (req, res) => {
  res.render('template.pug', {jsStringify, data});
});
```

Then in pug:

```pug
script.
  const data = !{jsStringify(data)};
script(src="/render-chart.js")
```

The `!` is generally dangerous as it does not escape the value passed in, but the `jsStringify` helper escapes the value for you, so in this example it is safe to use.

**Comment by Ram0987** [comment]
Thank you very much for your response. I will work on it and let you know!! 
Thanks!! :)
