### ISSUE TITLE
adding combo items in a callback

### ISSUE THREAD

**Issue by diginfo** [pugjs/pug#3129]
Hi;

Is this possible ??

```
mixin combo(attr)
  select(class="combo")&attributes(attr)
    option(value="aa")
      aitem1
    -myfunc(function(rows){
      -for(var idx in rows){  
        -row = rows[idx];
        option(value=row.value)=row.text
      -}
    -})
```

**Comment by ForbesLindesay** [comment]
Yes, but only if `myfunc` calls the callback synchronously, otherwise you will get undefined behaviour.

[then-pug](https://github.com/pugjs/then-pug) adds support for `yield`ing promises if you need async function calls within pug.
