### ISSUE TITLE
Add commandline installation instructions to pugjs.org

### ISSUE THREAD

**Issue by Executerror** [pugjs/pug#3132]
Hey, I spent 1 hour to find out why my Webstorm File Watcher could not detect pug. I had installed Node.js, Express.js. 
What I was missing was commandline installation instruction, which was not visible in the website. 

Only in the github website I found it, and at the the I didn't even know what the question and solution was supposed to be. 

So could you please also write the Command Line installation instructions from Github shown below in your website, that would save a lot of time. Thanks. 
https://pugjs.org/api/getting-started.html

Command Line
After installing the latest version of Node.js, install with:

$ npm install pug-cli -g
and run with

$ pug --help

**Comment by YasharF** [comment]
I think you may want to open this issue in https://github.com/pugjs/pug-www repo instead of this repo.

**Comment by Executerror** [comment]
Good idea
