### ISSUE TITLE
How do i incorporate tags into JavaScript objects/massives with pug ?

### ISSUE THREAD

**Issue by AntonGrekov** [pugjs/pug#3134]
Pug is an awesome tool and i enjoy using it big time. However here is a problem i met today. All the time i meet a section of PSD layout with similar blocks, but with different data (like icons, text) i automatically make a JSON-like object in JS with data diff of that blocks and iterating through that object i make a html code via pug.

Let me describe it in code

## Input Pug

```pug
var footerMenu = {
   left: {
      title: "sometitle",
      list: [
         {
         title: "First thing to do",
         text:  "wake up and brush some teeth"
         },

         {
         title: "Second thing to do",
         text:   "start coding"
         },
      ...
```

Problems comes when text withing property footerMenu.left[0].text has to be styled with some tags. I want to mark some words or style them differently.

I need something like this

```pug
...... text: "wake up and #[span.color-red brush] some teeth"
```

## Expected HTML

```html
wake up and <span class="color-red"> brush some teeth
```

## Actual HTML

```html
wake up and #[span.color-red brush] some teeth
```

but, of course pug read that as simple string. I don't want to write each block manually, how do i save same code structure but apply random tags into my JSON-object with pug ?

**Comment by ForbesLindesay** [comment]
This is not possible with pug because it is difficult to do securely. You will need to generate the HTML you want from those text values (you could use markdown, or you could use `pug.render`) then **sanitize** the resulting HTML (if these strings are user entered), then you can output them as unescaped html.

**Comment by AntonGrekov** [comment]
Thx
