### ISSUE TITLE
How to view pug errors ?

### ISSUE THREAD

**Issue by AntonGrekov** [pugjs/pug#3135]
Some times i do see pug errors in console like this: http://prntscr.com/nfah3s

It's impossible to track them down only by line and carret numbers , even in a finally concatinated file......

My gulp config about pug looks like this:

pug     = require("gulp-pug"),  
gutil   = require("gulp-util"),

```js
gulp.task('pug', (cb) => {
    gulp.src(paths.pug.src)
     .pipe(plumber(function (error) {
        gutil.log(error.message);
        this.emit('end');
     }))
     .pipe(pug({
        pretty: true,
     }))
     .pipe(gulp.dest(paths.pug.dest))
     .pipe(browserSync.reload({ stream: true }));
     cb();
})
```

How do i setup gulp to view errors in more verbose way ? Thanks a lot

**Comment by ForbesLindesay** [comment]
This question is specific to [gulp-pug](https://github.com/gulp-community/gulp-pug), please open an issue there.
