### ISSUE TITLE
Are there drawbacks to “including” files you don't require in PUG?

### ISSUE THREAD

**Issue by harrydry2** [pugjs/pug#3137]
I want to load a different mixin depending on what data the pug file gets passed. This requires me to store mixins as a variable. e.g.

`+#{slug}()`

where slug is the variable. This works well but (because dynamic mixins aren't possible) the drawback is I have to "include" all the pug files (even one's which are never required)

```
include ./mixins/slug1

include ./mixins/slug2

include ./mixins/slug3

```
etc ...

Are there drawbacks to including loads of pug files you don't need? Or is it the case where if you just "include", but never actually call the file then it's all ok? Thanks for any help :)

**Comment by ForbesLindesay** [comment]
It depends somewhat on context. If the templates are being rendered client side, the extra code that gets included will definitely slow things down slightly, but as long as there's not thousands of mixins and they're not massive it's probably ok.

If you're rendering the templates server side it shouldn't matter. It will slow down compilation slightly, but shouldn't make any meaningful difference to render performance.
