### ISSUE TITLE
Single-line comment can help with trailing spaces

### ISSUE THREAD

**Issue by Th0rN13** [pugjs/pug#3138]
Feature reques

Lots users use linter\IDE with "no trailing spaces" rule.
I offer add the possibility of single-line comments to the end of line.
This will add some possibility to comment one line, and also solve the problem with trailing spaces simply by adding a comment

How to add space in current version

## First example

```pug
h1 I Love Pug #{' '}
p It's a great
```

## Second example

```pug
h1 I Love Pug
  |
p It's a great
```

## What i offer

I use // for example, but better discuss what we need to use, maybe //# or something

```pug
h1 I Love Pug //
p It's a great
```

**Comment by ForbesLindesay** [comment]
I think the current solution is good enough, and does not add any extra syntax to learn/understand.
