### ISSUE TITLE
pug-code-gen housekeeping

### ISSUE THREAD

**Issue by YasharF** [pugjs/pug#3140]
**Pug Version:** 2.0.3

**Node Version:** v10.15.3

NPM Warning:
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

I noticed the above npm error in a different project and have narrowed the cause down to the out of date version of npm package "with" in pug-code-gen.  To reproduce you need to start a blank nodejs project, then install pug and then install a package that requires a current version of acorn-jsx, like `eslint` through its dependency tree.  Since currently pug -> "pug-code-gen": "^2.0.1" -> "with": "^5.0.0" -> "acorn": "^3.1.0" , npm ends up installing the very outdated acorn 3.1, and the above error happens when a package like the current version of eslint needs to be installed which through its dependency tree needs acorn-jsx ^5.0.0 and hence acorn@^6.0.0 as a peer dependency.

"eslint": "5.16.0" -> "espree": "^5.0.1" -> "acorn-jsx": "^5.0.0"

Other housekeeping items:
https://www.npmjs.com/package/pug-code-gen doesn't seem to link to the git repo since the repo is now moved to https://github.com/pugjs/pug/tree/master/packages/pug-code-gen and https://david-dm.org/pugjs/pug-code-gen is broken because of the repo move.

void-elements in pug-code-gen's dependencies also seems to have a new major version.

**Comment by YasharF** [comment]
https://github.com/pugjs/pug/pull/3146 fixes the david-dm dependency status badges.

**Comment by ForbesLindesay** [comment]
> "eslint": "5.16.0" -> "espree": "^5.0.1" -> "acorn-jsx": "^5.0.0"

That just means that espree or eslint should explicitly depend on acorn@^6.0.0. It has nothing to do with pug's version. The two can co-exist quite happily. In the mean time, you should be able to fix by explicitly installing acorn@^6.0.0 yourself.

I would be happy to accept a PR to update void-elements, you'll need to check if the list of void elements has changed, as that would be a breaking change.

I would also accept a separate PR to update the repo links (e.g. https://github.com/pugjs/pug/blob/master/packages/pug-code-gen/package.json#L23) if you feel like going through and checking all of them.
