### ISSUE TITLE
Variables syntaxis ${var}

### ISSUE THREAD

**Issue by soulcreate** [pugjs/pug#3143]
**Pug Version:** 2.0.3

**Node Version:** v11.13.0

> span(class="icon-${item.icon}")

May you give any example?
I have `node -v v11.13.0` and nothing render. What is environments I should have to get work it?
for example [online pug2html converter](https://pughtml.com/)
convert this:
```
- var v = '123'
span(class="icon-${v}"+v)
```
to this:
```
<span class="icon-${v}123"></span>
```
What is a problem?

**Comment by ForbesLindesay** [comment]
You need to use backticks ``` ` ``` not double quotes `"` if you want to use itnerpolation like that. This is a JavaScript thing, not a pug thing.
