### ISSUE TITLE
SVGs created in .pug file do not scale

### ISSUE THREAD

**Issue by colorwheeloflife** [pugjs/pug#3144]
Pug Version: 2.0.3
Node Version: 8.15.1

Expected:  SVGs created in pug partials to scale appropriately

Behaviour:  SVG element can grow and shrink, but its child `g` and `path` elements stay completely static. 

When importing .svg files directly, they scale as you would expect.  But as soon as we put them in a .pug file, the children of `svg` are static and do not scale. 

<img width="96" alt="Screen Shot 2019-05-22 at 3 53 55 PM" src="https://user-images.githubusercontent.com/10913613/58214245-e08a7b80-7ca9-11e9-8a9a-f2ce456cbc67.png">
<img width="207" alt="Screen Shot 2019-05-22 at 3 54 03 PM" src="https://user-images.githubusercontent.com/10913613/58214246-e08a7b80-7ca9-11e9-8a08-c7815435ef2b.png">
<img width="247" alt="Screen Shot 2019-05-22 at 3 54 11 PM" src="https://user-images.githubusercontent.com/10913613/58214247-e08a7b80-7ca9-11e9-8ddc-b496e2b91431.png">

Thank you for your time

**Comment by colorwheeloflife** [comment]
Here is another example using Material Icons 'check' icon:

<img width="211" alt="Screen Shot 2019-05-22 at 4 00 37 PM" src="https://user-images.githubusercontent.com/10913613/58214506-d157fd80-7caa-11e9-8da5-099a07f27022.png">

https://material.io/tools/icons/?search=check&icon=check&style=baseline

**Comment by ForbesLindesay** [comment]
Please submit a new issue, filling out the actual issue template.
