### ISSUE TITLE
Cannot pass variables when including script

### ISSUE THREAD

**Issue by ttfreeman** [pugjs/pug#3145]
Hello,
The issue is well explained in this stackoverflow post: [https://stackoverflow.com/questions/46600484/pug-pass-variable-to-include-js-file](https://stackoverflow.com/questions/46600484/pug-pass-variable-to-include-js-file ). There seems to be no where to pass variables when including an external script file:

```
  script
    include dynamicLoad.js 
```
I need to pass nextPageToken to the script that will be used for fetching data:

```
if (nextPageToken) {
      fetch(`?pageToken=${encodeURIComponent(nextPageToken)}`)
        .then(r => r.json())
        .then(data => console.log(data))
        .catch(e => console.log("Booo"));
```
Thanks!

**Comment by ForbesLindesay** [comment]
```js
const stringify = require('js-stringify');
pug.render('template.pug', {stringify, nextPageToken});
```

```pug
  script
    | var nextPageToken = !{stringify(nextPageToken)};
    include dynamicLoad.js
```

**Comment by ttfreeman** [comment]
Doesn't work. Doesn't even recognize that there is a script block. I gave up. Going to uninstall pug and switch to something else. 

```
doctype html
html(lang="en")
  head
    link(rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css")
  body
    nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
        a(href="/")
          .navbar-brand XXXX

        ul.nav.navbar-nav
          li.nav-item
            a(href="/posts" class="nav-link") Posts

    .container
      block content
    
    button.btn.btn-danger#someButton Click Me
  
    script(type='text/javascript').  
      var myVar = ‘Hello Var’;
      console.log(myVar);
    script(src='some.js')
```

and here is some.js:

```
document.getElementById("someButton").addEventListener('click', someClick)

function someClick() {
    console.log('I am clicked');
```

**Comment by ForbesLindesay** [comment]
My example definitely works, providing there is a `nextPageToken` variable in scope in the js code that renders pug. If you want to figure out what's going wrong I suggest starting with the simplest example you can, and getting that working, before building up to your full application.

If you want to uninstall pug that's also fine. I don't get paid anything for you using pug.
