### ISSUE TITLE
Feature: Convert images into base64 if they are static

### ISSUE THREAD

**Issue by mayank** [pugjs/pug#3147]
**Pug Version:** v2.0.3

**Node Version:** v10.15.3

## Input JavaScript Values

```js
pug.renderFile('input.pug', []);
```

## Input Pug

```pug
h1 I Love Pug
img(src="/Users/test/love.jpg")
```

## Expected HTML

```html
<h1>I Love Pug</h1>
<img src="data:image/jpeg;base64, LzlqLzRBQ...<!-- base64 data -->" />
```

## Actual HTML

```html
<h1>I Love Pug</h1>
<img src="/Users/test/love.jpg" />
```

## Additional Comments
I need to convert images into base64 when I am compiling the image in case they are from static sources. I am caching the templates on server to save the compile time.

**Comment by jeromew** [comment]
It should be doable via a pug filter - cf https://pugjs.org/language/filters.html

you will need to develop your own filter.

**Comment by mayank** [comment]
@jeromew thanks!
