### ISSUE TITLE
No newline at end of output

### ISSUE THREAD

**Issue by jocap** [pugjs/pug#3150]
**Pug Version:** 2.0.3

**Node Version:** v8.12.0

Thank you for maintaining Pug.

Currently, Pug produces (for most purposes) invalid output for Unix systems, because it doesn't end with a final newline. Should be an easy fix.

**Comment by ForbesLindesay** [comment]
You can add a newline explicitly via `= '\n'` It is not invalid for a file to not end with a new line on any system I'm aware of.

**Comment by jocap** [comment]
Ah, thank you. I shouldn’t have used the word invalid, but final newlines are required for the majority of the default text-processing Unix programs.
