### ISSUE TITLE
Why is pug not throwing an error ?

### ISSUE THREAD

**Issue by AntonGrekov** [pugjs/pug#3153]
**Pug Version:** your version number here
"gulp-jade": "^1.1.0"

**Node Version:** your version number here
10.14.1
## Input JavaScript Values

```js
gulp.src(PATH_CONFIG.pug.src)
      .pipe(plumber(function (error) {
         gutil.log(error.message);
         this.emit('end');
      }))
      .pipe(pug({
         pretty: true,
      }))
      .pipe(gulp.dest(PATH_CONFIG.pug.dest))
      .pipe(browserSync.reload({ stream: true }));
      cb(); 
});
```

## Input Pug

/extends/default.pug
```pug
block config
	//- include ../helpers/config

doctype html

html(lang="ru")
	include ../modules/head

		block head
			
		title #{siteTitle}
	body
		.wrap
			include ../helpers/includes/preloader
			include ../modules/header

			block content

			include ../modules/footer

		include ../modules/svg-inline

		block bottom-scripts
```

in modules/header, i have a mixin container added
```pug
+cointainer()
    block
```
## Expected HTML
Expected to work same way in 2 projects(throw error) - "Cannot read property of undefined" when i don't include container.

In one project i include container mixin file after header, in index.pug(that is extend version of default.pug, and include container-mixin file is going in block content section, which as you can see is after modules/header including) , but it somehow caches it. 
I checked code million times. In another project exact same structure(i copied my workaround template) pug simply doesn't work same way ! It throws expected error when container not yet included. I just want to understand why the heck in same structure project it works!!!

To clarify. I have 2 projects same same structure. File extends/default.pug is above. In include/header i am using +container() mixin. I include that container mixin in index.pug(that extends default.pug). In one project i get expected error - "Cannot read property undefined", in another its somehow works. I cant understand what is the difference and why its working when:
extends/default.pug -> has block header included (include modules/header) that uses container BEFORE incuding container-mixin....(its included in index.pug that extends default.pug)

**Comment by ForbesLindesay** [comment]
This looks specific to gulp: https://github.com/gulp-community/gulp-pug

I would suggest updating both projects to gulp-pug 4.0.1 first and see if that fixes things, as I doubt the gulp community would offer support on such an old version.
