### ISSUE TITLE
[Feature?] pugjs and tailwindcss

### ISSUE THREAD

**Issue by acidjazz** [pugjs/pug#3155]
Has there been any discussion or request to get better support for usinng tailwindcss with pugjs? Allowing other characters that are allowed in CSS (that tailwind uses) in pugjs, if not I'd like to propose we allow

* `colins`, this will allow [responsive](https://tailwindcss.com/docs/responsive-design/) and [psuedo](https://tailwindcss.com/docs/pseudo-class-variants/) variants
* `slashes`, this will allow access to many kinds of [fluid sizing](https://tailwindcss.com/docs/width/#fluid-width)

I know that these can be added with `(class="")`, but I think it'd make much better syntactic sugar to allow these characters to be used in the normal way.

**Comment by acidjazz** [comment]
just guessing but would it maybe be [here](https://github.com/pugjs/pug/blob/master/packages/pug-lexer/index.js#L437) ?

**Comment by ForbesLindesay** [comment]
We intentionally do not support this, as we want to save those special characters for potential future use.  As you pointed out, the `(class="")` syntax is supported as a fallback for class names with special characers.

**Comment by alivefromupstairs** [comment]
@ForbesLindesay Could you reconsider? Just allowing the use of those characters in the meantime through some non master branch.

**Comment by ForbesLindesay** [comment]
You should feel free to maintain your own fork or lexer plugin.
