### ISSUE TITLE
How to write indented comments ?

### ISSUE THREAD

**Issue by AntonGrekov** [pugjs/pug#3157]
I cannot write a comment inside my pug code when i am around some indent level

Example:
````
    .container
        .container__inner
            //- or // Comment <- stars a block multi line comment
            .new_block
````

starting comment with zero indent also not working since : 
    Only named blocks and mixins can appear at the top level of an extending template

**What i want ?**  
Is just to be able to comment code for pug only before some blocks are starting(any level on indentation). How i do that ?

**Comment by ForbesLindesay** [comment]
I don't understand the question. Please fill out the issue template with a single example of the pug code you have written and what you expect the output to be.

https://pugjs.org/language/comments.html documents both block comments and inline comments.
