### ISSUE TITLE
Variable does not get formatted properly in a .pug-file in pStorm

### ISSUE THREAD

**Issue by gkorchun** [pugjs/pug#3159]
# Variable does not get formatted properly in a .pug-file in pStorm

What we want:
![0EYLg_mPZpaCfex8K0fN2Q](https://user-images.githubusercontent.com/38717221/60888860-59489580-a260-11e9-8753-df9a57bda8bd.png)

What pStorm does:
![eSIohQJhRQH0N_IewIcn2w](https://user-images.githubusercontent.com/38717221/60888887-649bc100-a260-11e9-8fc2-7e2225dd5623.png)

how can we solve this problem?

**Comment by ForbesLindesay** [comment]
Please ask the developers of pStorm. This has nothing to do with the core pug development.
