### ISSUE TITLE
Accessing local variables in every template

### ISSUE THREAD

**Issue by ozgurg** [pugjs/pug#3162]
**Pug Version:** ^2.0.4

**Node Version:** 10.16.0

## Input JavaScript Values

```js
app.get("/", function(request, response, next){
	response.locals.helloWorld = "Hello World!";
	next();
});
```

## Input Pug

```pug
#{helloWorld}

or

#{locals.helloWorld}
```

## Expected HTML

```html
Hello World!
```

## Actual HTML

```html
Hello World!
```

## Additional Comments

Is that possible? I searched, but I didn't find if it's possible

**Comment by ForbesLindesay** [comment]
Yes, it's possible. You do it pretty much exactly as you've put it in the question. This is more about express than pug though.
