### ISSUE TITLE
Pass function to be used in callback in Javascript frontend (is it possible?)

### ISSUE THREAD

**Issue by mayeaux** [pugjs/pug#3163]
I'm trying to pass a function (timeAgo module) to be used in my frontend Javascript during a callback.

However no combination of methods I try can get the module to work during a callback. If I use it while I compile the frontend it works fine of course, but I can't load the module as a function in a script tag such that I can use it again.

So: 

`p.balance-text #{timeAgo.format(new Date(story.publishedAt))}`

Works fine, but how can I do something like: 

```
script. 
  // this allows me to use it to format dates received via an AJAX request
  var  timeAgo = #{timeAgo}
  
```

I've also tried things like using JSON.stringify to pass it to the frontend but nothing seems to work. Is it possible with pug? Thanks

**Comment by ForbesLindesay** [comment]
Short answer is no. You'll probably be able to get someone to help you work out a solution over on https://stackoverflow.com/ though. This isn't really the forum for this kind of support question.

**Comment by mayeaux** [comment]
Thanks, if any other curious soul finds themself at this question the I answer I received with detail was here: https://stackoverflow.com/questions/57047376/pass-function-to-pug-template-to-be-used-via-callback-in-javascript-frontend/57047773#57047773
