### ISSUE TITLE
Get value of a variable inside an 'if' conditional

### ISSUE THREAD

**Issue by asjd** [pugjs/pug#3168]
Hi! 

Need help to get (global) variable inside a conditional

**Pug Version:** 2.0.4

**Node Version:** 11.14
## Input Pug

```pug
- var vegetables = ['onion','garlic','potato','tomato','bean']
- var i
each val, index in vegetables
  if (val == 'potato')
    i= index    
   .div= val
    - break
div= i
```

I need to get the index of an array. 
In this example above, I want to show the value of index of potato (2)
Nothing apprear when div= vegetables[i]  and 'potato' appear when indicating .div= vegetables[2]

Thanks

**Comment by ForbesLindesay** [comment]
just use `- i= index` instead of `i= index`

**Comment by asjd** [comment]
lol ! just this hyphen !!

thanks a lot
