### ISSUE TITLE
Inline conditionals

### ISSUE THREAD

**Issue by Petrivah** [pugjs/pug#3169]
**Pug Version:**
Last (2.0.4)

**Node Version:**
8.10.0

## Expected working pug, that would be cool
```pug
- let inline = true;
if inline p Cool
//- or
if inline: p Cool
//- or
if inline then p Cool
```

**Comment by its-arun** [comment]
We can make use of [interpolation](https://pugjs.org/language/interpolation.html) for that.

```
- let inline = true
p #{inline ? 'Cool' : 'Not cool'}
```

**Comment by Petrivah** [comment]
> We can make use of [interpolation](https://pugjs.org/language/interpolation.html) for that.
> 
> ```
> - let inline = true
> p #{inline ? 'Cool' : 'Not cool'}
> ```
> 
> [Codepen](https://codepen.io/anon/pen/bXarPK)

But i think there should be more beautiful solution :\

**Comment by ForbesLindesay** [comment]
Thanks for the suggestion. This would involve some pretty complex parsing of the JS expression used for the condition, so I'm not going to implement it at this time.
