### ISSUE TITLE
Ternary operator does not respect short circuit

### ISSUE THREAD

**Issue by gmlazu** [pugjs/pug#3174]
**Pug Version:** 2.0.4

**Node Version:** 10.16.2

## Input JavaScript Values

```js
Object.assign(vars, { errors: [e.errors] });
res.render("pages/event", vars);
```

## Input Pug

```pug
.input-group(class=errors && errors.name?'has-error':'')
```

## Expected HTML
If errors.name is truthy:
```html
<div class="input-group has-error">
```
If not:
```html
<div class="input-group">
```

## Actual HTML
Pug error:
```
Cannot read property 'name' of undefined
```

## Additional Comments

The issue stems from the fact that the expression `errors && errors.name` does not appear to respect the short circuit operator, and also evaluates `errors.name`.

Is it an issue on my end, or a bug with pug?

**Comment by ForbesLindesay** [comment]
I tested the input pug code you provided and it works fine. Although your example js gives an array of errors, but the pug code appears to expect a single error called errors.
