### ISSUE TITLE
Remove extra space in XML doctype

### ISSUE THREAD

**Issue by caspermaven** [pugjs/pug#3182]
Pug adds an additional space when declaring `doctype xml`, before the closing `?>`, as shown below:

Pug output:

    <?xml version="1.0" encoding="utf-8" ?>

Expected:

    <?xml version="1.0" encoding="utf-8"?>

Under [XML 1.0](https://www.w3.org/TR/xml/#sec-prolog-dtd), the extra space is not necessary. A bit of a nitpick, but I know how Pug likes to be concise. 💯

**Comment by ForbesLindesay** [comment]
I don't feel strongly about this, but if we remove it we're guaranteed to get at least one complaint from someone who wants it back for aesthetic reasons. If you want to submit a PR, I'll probably merge it though.
