### ISSUE TITLE
use of "globals" in option not clear

### ISSUE THREAD

**Issue by jacobbogers** [pugjs/pug#3198]
there is this in the current [doc](https://pugjs.org/api/reference.html)
![image](https://user-images.githubusercontent.com/896018/69014610-41122100-098c-11ea-9f15-4764232c884d.png)

but no examples whatso ever, i was thinking it was globals from the `window` object , 

I attempted this amongst others

```javascript
const fn = pug.compileFile('./template.pug',{  self:true, debug: false, compileDebug:true, globals:['location']});
```
sample template
```pug
doctype html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN"
-
  var list = ["Uno", "Dos", "Tres",
          "Cuatro", "Cinco", "Seis"]
each item in list
  li= item
img(src="/this-image.jpg") 
p written with love from #{self.author} #{self.copyright} #{location.href}
```
but that didnt work

1.Can you explain how to use globals and what it does?
2.Can you update the documentation with an example?

Thank you

**Comment by jacobbogers** [comment]
I found resolution for this code

Below is a demo that works (node, not browser)

the global is the node `global`  if you run code in the windows client, make sure the  `window` object is used as global

```Javascript
const pug = require('pug');
const p5 = require('parse5');
const stringify = require('json-stringify-safe');

global.hello='world';

const fn = pug.compileFile('./template.pug',{ doctype:'xml', self:true, debug: false, compileDebug:true, globals:['global']});
//console.log(fn);

console.log(typeof fn);

if (typeof fn === 'function'){
   // console.log(fn.toString());
    console.log(fn({ author: 'my name', copyright: '© 2019 Jacob Bogers'}));
    const ast = p5.parse(fn({x:'y'}));
    console.log(p5.serialize(ast));
}
```

**Comment by fusir** [comment]
That is still incredibly unclear.
