### ISSUE TITLE
Feature Request: Vue Unscoped v-slot and Shorthand

### ISSUE THREAD

**Issue by qt911025** [pugjs/pug#3199]
**Pug Version:** 2.0.4

**Node Version:** 12.11.1

# Case 1: Unscoped v-slot

## Input Pug

```pug
Foo
  template(v-slot:foo)
    p Hello
```

## Expected HTML

```html
<foo>
  <template v-slot:foo>
    <p>Hello</p>
  </template>
</foo>
```

## Actual HTML

```html
<foo>
  <template v-slot:foo="v-slot:foo">
    <p>Hello</p>
  </template>
</foo>
```

# Case 2: Shorthand "#" for v-slot

## Input Pug

```pug
Foo
  template(#foo)
    p Hello
```

## Expected HTML

```html
<foo>
  <template #foo>
    <p>Hello</p>
  </template>
</foo>
```

## Actual HTML

```html
<foo>
  <template #foo="#foo">
    <p>Hello</p>
  </template>
</foo>
```

## Additional Comments

These parse result will cause an error while vue-template-compiler compiling template files, like:

```
SyntaxError: Unexpected token (1:98)
    1 : var __render__ = function () {with(this){return _c('Foo',{scopedSlots:_u([{key:"foo",fn:function(v-slot:foo){return [_c('p',[_v("Hello")])]}}])})}}
```

and

```
SyntaxError: Unexpected character '#' (1:97)
    1 : var __render__ = function () {with(this){return _c('Foo',{scopedSlots:_u([{key:"foo",fn:function(#foo){return [_c('p',[_v("Hello")])]}}])})}}
```

**Comment by ssipos90** [comment]
I think you have something badly configured, because that works on our project. What package(s) are you using?

**Comment by qt911025** [comment]
@ssipos90 
pug-cli, which is directly used by parcel.

**Comment by ForbesLindesay** [comment]
To get the HTML shorthand for boolean properties like these, you need to use `--doctype html` when building via pug-cli. Alternatively you can start the template itself with `doctype html` but that will also add the doctype to the output.
