### ISSUE TITLE
If I get an error in Pug, rather than display in the console the route will just 404

### ISSUE THREAD

**Issue by mayeaux** [pugjs/pug#3208]
Has anyone heard of this before? Sorry for skipping the template it's super late and I've been banging my head against the wall with this. If nobody has heard of anything I will rewrite this with all the versions and stuff. Basically if there is an error in pug, rather than display it in the console the route will just 404. Thanks

**Comment by cekvenich** [comment]
This has little to do w/ Pug.

**Comment by mayeaux** [comment]
Yeah this is for sure due to my own middlewares I can close it, thanks
