### ISSUE TITLE
Adding comment blows up Javascript

### ISSUE THREAD

**Issue by mayeaux** [pugjs/pug#3229]
**Pug Version:** 2.0.4

**Node Version:** 8.17.0

## Input Pug

```pug
script
        // this includes the validation functionality
        include ./swal.js
```
^ adding this line of comments breaks the script

Is this expected functionality? Was kind of hard to trace it back to this comment line being the cause of the JavaScript crashing

**Comment by cekvenich** [comment]
That is user error.

**Comment by ForbesLindesay** [comment]
This comment is rendered as an HTML comment by pug. You can either use an un-buffered comment, that will not appear in the output:

```pug
script
        //- this includes the validation functionality
        include ./swal.js
```

or mark the comment as a literal string so it is put into JS as is:

```pug
script
        | // this includes the validation functionality
        include ./swal.js
```
