### ISSUE TITLE
Capture output of mixin to variable.

### ISSUE THREAD

**Issue by kevupton** [pugjs/pug#3235]
Hey guys, 
So I love pug, however I am facing the issue whereby I am trying to save the output of a pug render to a variable, which I can later use in my pug template.
For example

```pug
mixin test()
    .do-something-here
        = SomeGlobalValue.function()

- const val = +test();

html
head
body
    != val
```

The reason why I want to render it at a later time, is because my use case is that I want to render a bunch of body content, and then based on this rendering, render some other content in the head. 
The problem is that the head will always be output no matter what, before I can run the pug logic for the body. 

Some similar issues:
https://github.com/pugjs/pug/issues/374
https://github.com/pugjs/pug/issues/2137

If you know of any other way I can approach this problem of creating the body content, and then the head content, without moving the head tag below the body tag, that would be awesome.

**Comment by kevupton** [comment]
Maybe something similar to this could work?
https://www.php.net/manual/en/function.ob-start.php

**Comment by kevupton** [comment]
Ok, I managed to figure out a hack for doing this... After reading many lines of how pug actually works. 
What pug does is output the mixin directly to the variable `pug_html`. So while it is a bit hard to capture the mixin directly, one way we can achieve this is by taking the difference, before and after of this pug_html, and taking that difference as the output of the variable. 

For example. 
```pug
- const beforeHtml = pug_html;

+someMixin(content)

- const someMixinOutput= pug_html.replace(beforeHtml, '');
- pug_html = beforeHtml;
```

**Comment by SidOfc** [comment]
As an added bonus, `block` works the same way when used inside a `mixin`. Since `block` is a function inside a `mixin`, executing it will add the contents to `pug_html` as well. I came up with this function:

```pug
-
  function captureblock(blk) {
    const beforehtml = pug_html;
    blk();
    const output = pug_html.replace(beforehtml, '');
    pug_html = beforehtml;

    return output;
  }
```

Which can be used like this:

```pug
mixin page_images
  - const blockContent = captureBlock(block);
  - const images = (blockContent.match(/<img/gi) || []).length
  .page__image-row(class=`page__image-row--${images}`)
    != blockContent
```

I'm using it to dynamically reduce margins when adding multiple images in `+page_images` :)
Thanks @kevupton for the hack :+1:

**Comment by ForbesLindesay** [comment]
There is no builtin way of doing this. The above hack does work though (at least for now).

**Comment by paulzi** [comment]
One more hack:
```pug
mixin someMixin
    .component component

mixin initMixins
    +someMixin

.using
    - const mixinInVar = pug_mixins.someMixin()
    .wrapper !{mixinInVar}
```

**Comment by paulzi** [comment]
One more hack:
```pug
mixin someMixin
    .component component

mixin initMixins
    +someMixin
    
-
    function pugMixin(mixin, ...params) {
        const len = pug_html.length;
        pug_mixins[mixin](...params);
        const result = pug_html.slice(len);
        pug_html = pug_html.slice(0, len);
        return result;
    }

.using
    - const mixinInVar = pugMixin('someMixin')
    .wrapper !{mixinInVar}
```

**Comment by aminta** [comment]
> ```
> const beforeHtml = pug_html; // save the current HTML state in a variable
> ```

Hi Kevin! I'm using your plugin with `"@anduh/pug-cli": "^1.0.0-alpha8"` but it doesn't output nothing, because 

`  if (!pug_mixins[mixinName]) {
    return;
  }`

is called; so I'm supposing that the mixins are not added to `pug_mixins` at that point of code... Any hint?
