### ISSUE TITLE
Release pug-filters 3.1.2 to update constantinople & remove core-js notices

### ISSUE THREAD

**Issue by EricRabil** [pugjs/pug#3248]
**Pug Version:** 2.0.4

**Node Version:** 14.1.0

Heyo, saw a couple of issues regarding this but they don't seem to be getting much traction. Currently, `pug-filters@3.1.1` depends on `constantinople@3.1.2` which depends on `@types/babel-types@7.0.0` which depends on `babel-runtime@7.9.6` which ultimately depends on `core-js@2.6.11`

`core-js@2` is deprecated, and `constantinople@4.0.1` removes the dependency on `@types/babel-types` altogether, removing pug's dependency on core-js altogether.

Because of this sub-dependency on `core-js@2`, this is what I see whenever I run `npm install`:
![image](https://user-images.githubusercontent.com/8052613/80855119-37176e00-8c0c-11ea-9f53-97bb6857ee0a.png)

The `package.json` for `pug-filters` is already updated to use `constantinople@4.0.1`, it just hasn't been pushed to npm. It would mean a lot to myself and many other developers if this could be pushed to npm ❤️

**Comment by ForbesLindesay** [comment]
The next release will probably happen this Friday. You can subscribe to my mailing list if you'd like to be notified when it happens: https://pugjs.org/support/community.html
