### ISSUE TITLE
Update to core-js@3?

### ISSUE THREAD

**Issue by rowild** [pugjs/pug#3252]
When I do a `npm ls core-js@2`, i get this tree:

```
└─┬ pug@2.0.4
  └─┬ pug-code-gen@2.0.2
    └─┬ constantinople@3.1.2
      └─┬ babel-types@6.26.0
        └─┬ babel-runtime@6.26.0
          └── core-js@2.6.11 
```

npm warns me that core-js is deprecated. Is there any chance to update it to version 3 by using later babel-related packages?

**Comment by zackschuster** [comment]
`constantinople` was updated in #3184 & no longer uses that package. as soon as the next release happens this will be resolved :)

**Comment by rowild** [comment]
@zackschuster Thank you for letting me know! Awesome!
