### ISSUE TITLE
Deno 1.0 Support

### ISSUE THREAD

**Issue by WaseemRakab** [pugjs/pug#3255]
Do you have any plans for supporting Deno?
[https://deno.land/v1](url)

**Comment by ForbesLindesay** [comment]
No, I've given my reasoning in https://github.com/denoland/deno_website2/pull/440

At present, it appears to be a toxic community, and they haven't figured out their story for npm interop. When these are resolved, as I'm sure they will be if deno continues to mature, I may change my position on this.

**Comment by Pointotech** [comment]
I like Deno, but it's weird and frustrating that they're making it hard for maintainers of existing NPM packages. And just because they want to ban the "dash" character, which has never caused any problems for anyone in a URL???

**Comment by Pointotech** [comment]
"By definition - isn't an alphanumeric character. _ is." -- A Deno contributor, justifying why they banned the dash character.

Wow.

You heard it here, folks. There are 27 letters in the alphabet, and one of them is `_`. Or maybe there are 11 digits in the decimal number system, and one of them is `_`.

**Comment by oscarotero** [comment]
Hi, I've created a port of Pug for Deno, because I needed for a project: https://github.com/lumeland/pug
If you are interested, I can transfer the ownership to this organization.
