### ISSUE TITLE
Pug 3.0.0

### ISSUE THREAD

**Issue by ForbesLindesay** [pugjs/pug#3258]
I'm intending to publish pug 3.0.0 within the next 24 hours. In the mean time, it would be great if as many people as possible could try out the "canary" build. You can get it by running `npm install pug@canary`.

I've automated the release process via [Rolling Versions](https://rollingversions.com/) so it will now always be possible to install the version currently on the master branch via `pug@canary`, and new production-ready releases should be much more frequent.

The provisional release notes for pug@3.0.0 are as follows:

## Breaking Changes

* The minify option on filters now requires you to install the relevant jstransformer (#3084)

  Currently we support:

  * jstransformer-uglify-js for JavaScript
  * jstransformer-clean-css for CSS

* read plugins must now return Buffer if you want to support filters that use renderBuffer (#3213)

  If you don't wish to support this advanced use case, you can continue returning string. If you did not provide a read plugin, you do not need to do anything.

* Drop support for node 6 and 8 (#3243)

## Features

* Add support for replacing code gen via a plugin with generateCode (#3230)

* Support each ... of ... loops (#3179)

  ```pug
  each value of iterable
    li= value
  ```

  This requires an environment that supports the for (const val of iterable) syntax in JS. You can iterate over Maps, Sets etc. as well as arrays. There is also some destructuring of map keys:

  ```pug
  - const map = new Map([['a', 'x'], ['b', 'y']]);
  each [key, value] of map
    li
      strong= key
      = value
  ```

* Support filters that apply to Buffers (#3213)

  e.g.

  ```js
  // options.js
  exports.filters = {
    png: {
      // instead of a function, specify an object with a "renderBuffer" property
      // whose value is a function that takes a Buffer instead of a string
      renderBuffer: function(buffer, options) {
        var data = Buffer.from(buffer).toString('base64');
        return '<img src="data:image/png;base64, ' + data + '"/>';
      }
    }
  };
  ```

  You can then use the filter like:

  ```pug
  // foo.pug
  include:png my-small-image.png
  ```

**Comment by ForbesLindesay** [comment]
Here's the official release: https://github.com/pugjs/pug/releases/tag/pug%403.0.0

**Comment by zackschuster** [comment]
@ForbesLindesay my `node_modules` deploys went from 6.8mb to 4.0mb entirely due to the changes for v3. thank you so much!!
