### ISSUE TITLE
Breaking v3.x change

### ISSUE THREAD

**Issue by niftylettuce** [pugjs/pug#3260]
It seems in v3.x that variables declared are no longer working and throwing errors...

```sh
✖  error     SyntaxError: Identifier 'isHelp' has already been declared
```

**Comment by niftylettuce** [comment]
This is the line, it's at the top in `layout.pug`:

```pug
- const isHelp = ctx.pathWithoutLocale === '/help'
```

As soon as I upgraded to v3.x (with no other changes), the error appeared.

What's up here @ForbesLindesay?

**Comment by niftylettuce** [comment]
@ForbesLindesay to reproduce, clone this repo, and then `yarn add pug@latest` -- then you'll notice this line is the culprit <https://github.com/forwardemail/forwardemail.net/blob/4c4327ca1abe3153bd75ea376b41cab7f8cbbde2/app/views/layout.pug#L82> when you `node web` and then go to `http://localhost:3000`.

**Comment by tapz** [comment]
I'm seeing this too. Should be mentioned in the breaking changes if this feature has been dropped.

**Comment by ForbesLindesay** [comment]
This is odd. I'm not sure what's causing this. I'll have a go at debugging and see what I can do.

**Comment by ForbesLindesay** [comment]
This is a regression in `with`. I should hopefully have a fix out later today.

**Comment by ForbesLindesay** [comment]
Thank you for reporting this. If you update the "with" dependency to [7.0.1](https://github.com/pugjs/with/releases/tag/7.0.1) it should now be fixed. You can do this in your lock file, as `pug` does not use exact versions.

**Comment by niftylettuce** [comment]
No problem @ForbesLindesay I'll try the new version

**Comment by tapz** [comment]
Any plans to release the fix to NPM?

**Comment by ForbesLindesay** [comment]
@tapz it is released to npm. If you still have problems it means you have a cached dependency in your lock file. Update your lock file.
