### ISSUE TITLE
Documentation: No changes or migration list for v3

### ISSUE THREAD

**Issue by BarryCarlyon** [pugjs/pug#3261]
The documentation has

https://pugjs.org/api/migration-v2.html

But no to v3 migration guide

I was also looking for a changelog and cannot find one

**Comment by ForbesLindesay** [comment]
Please see the release notes at https://github.com/pugjs/pug/releases/tag/pug%403.0.0

**Comment by ForbesLindesay** [comment]
Thanks for pointing this out. I've added an equivalent guide to: https://pugjs.org/api/migration-v3.html
