### ISSUE TITLE
each fails with variable named "officers"

### ISSUE THREAD

**Issue by jabberwock31415** [pugjs/pug#3263]
**Pug Version:** your version number here
3.0.0

**Node Version:** your version number here
10.21.0

## Input JavaScript Values

```js
router.get('/foo', (req, res, next) => {
    res.render('foo', {});
});
```

## Input Pug

```pug
- let officers = [{name:'alan'}, {name:'betty'}, {name:'charlie'}];
each dude in officers
  p #{dude.name}
```

## Expected HTML

```html
<p>alan</p>
<p>betty</p>
<p>charlie</p>
```

## Actual HTML

none--pug errors out

## Additional Comments

I get an error thrown from pug:

Error: /home/NPL/www/express-web/views/directory.pug:3:22
    1| - let officers = [{name:'alan'}, {name:'betty'}, {name:'charlie'}];
    2|
  > 3| each dude in officers
----------------------------^
    4|   p #{dude.name}
    5|

The value variable for each must either be a valid identifier (e.g. `item`) or a pair of identifiers in square brackets (e.g. `[key, value]`).

If I change the name of the variable from "officers" to something else ("ooficers" for example) the script works

**Comment by jabberwock31415** [comment]
I get the same error with the new syntax:

```
Error: /mnt/storage/npl/www/express-web/views/foo.pug:3:22
    1| - let officers = [{name:'alan'}, {name:'betty'}, {name:'charlie'}];
    2| 
  > 3| each dude of officers
----------------------------^
    4|   p #{dude.name}
    5| 

The value variable for each must either be a valid identifier (e.g. `item`) or a pair of identifiers in square brackets (e.g. `[key, value]`).
```

**Comment by error418** [comment]
Proposed a Pull-Request. Rename your variable to start with something other than `of`, in case you need a quick workaround

**Comment by efiand** [comment]
Variable named `offers` gives the same error. Maybe, `of` sequence is a reason of this bug.

**Comment by error418** [comment]
The variable must not start with any of the keywords (like `of`)

**Comment by Delagen** [comment]
Half year past, breaking issue does not solved

**Comment by trasherdk** [comment]
@Delagen Seems just fine to me. Did you try?

```javascript

- let officers = [{name:'alan'}, {name:'betty'}, {name:'charlie'}];

each officer in officers
  officer #{officer.name}

```

![image](https://user-images.githubusercontent.com/5003891/105269199-0e823a80-5bc6-11eb-8064-29470bc01666.png)

**Comment by Delagen** [comment]
Try to use via locals as express template engine

**Comment by trasherdk** [comment]
This run in the browser, no express involved, still good.

JSON:
```json
{
  "user": {
    "name": "TrasherDK",
    "options": {"A": "Alpha","B": "Bravo","C": "Charlie","D": "Delta"}
  },
  "officegirls": [
    {"name":"Alice"},
    {"name":"Beatrice"},
    {"name":"Cindy"}
  ],
```
PUG:
```pug
- let officers = [{name:'alan'}, {name:'betty'}, {name:'charlie'}];
each officer in officers
  officer #{officer.name}

each officegirl in officegirls
  officer #{officegirl.name}

#select Select something &nbsp;
  select
    each option in user.options
      option(option.id) #{option}
```
Output:
![image](https://user-images.githubusercontent.com/5003891/105318378-05a95d00-5bf6-11eb-882c-d81a7648ccdf.png)


![image](https://user-images.githubusercontent.com/5003891/105318762-80727800-5bf6-11eb-936b-40d6a814abb8.png)

**Comment by error418** [comment]
I think this would also fail if your variable would start with the characters "in". #3274 fixes this behaviour for the `of`-syntax.

**Comment by justanightcorelover** [comment]
I have a same problem
code:
```pug
extends dashboardLayout

block content
    h4.grey-text.center-align Offerwalls
    .row.justify-content-center.justify-content-md-start(style="margin-top: 3rem;")
        each offerwall in offerwalls
            .col.card.shadow.border-0.m-1(style='min-width: 15rem;max-width: 18rem;')
                img.card-img-top(src=`${offerwall.bannerImgUrl || '/img/noimage.png'}` style='height:15rem;object-fit: cover;')
                .card-body
                    h6.card-title.font-weight-bold #{offerwall.title}
                    br
                    p.text-grey #{offerwall.description}
                    .text-center 
                        a.btn.btn-primary(href=`/dashboard/offerwall/${offerwall.id}`) Show #{offerwall.title}
```
error: 
```
    4|     h4.grey-text.center-align Offerwalls
    5|     .row.justify-content-center.justify-content-md-start(style="margin-top: 3rem;")
  > 6|         each n in offerwalls
-----------------------------------^
    7|             .col.card.shadow.border-0.m-1(style='min-width: 15rem;max-width: 18rem;')
    8|                 img.card-img-top(src=`${offerwall.bannerImgUrl || '/img/noimage.png'}` style='height:15rem;object-fit: cover;')
    9|                 .card-body

The value variable for each must either be a valid identifier (e.g. `item`) or a pair of identifiers in square brackets (e.g. `[key, value]`).
```

**Comment by bglamadrid** [comment]
Hi, I faced this problem when I had a variable named `offers` that I tried to iterate over.
I see PR #3318 would address the issue but it's stalled since May 2021, if there's anything I can do to help, I'm up for it!

**Comment by efiand** [comment]
I also spent a few hours then. But is it still relevant?
