### ISSUE TITLE
"img" error

### ISSUE THREAD

**Issue by ErsinCabuk** [pugjs/pug#3265]
**Pug Version:** 2.0.4

**Node Version:** 12

## Input JavaScript Values

```js
pug.renderFile('input.pug', {
  image: 'image link',
});
```

## Input Pug

```pug
img(src="#{image}")
```

## Expected HTML

```html
<img src="image link">
```

## Actual HTML

```html
<img src="#{image}">
```

## Additional Comments
While waiting for the image link to be there, only the result of "# {image}" appeared. What is the solution to this?

**Comment by ForbesLindesay** [comment]
The value of attributes is just JavaScript. You can use:

```pug
img(src=image)
```

See https://pugjs.org/language/attributes.html#attribute-interpolation
