### ISSUE TITLE
Windows display scaling and PDF

### ISSUE THREAD

**Issue by duzenko** [pugjs/pug#3270]
**Pug Version:** 3.0.0

**Node Version:** 12.14

I have a problem with composing PUG files in that the PDF output varies greatly in font size
Attached are two PDF's of the same input data. The only difference is one was taken with Windows screen scaling of 100% and another with scaling of 200%

[coverSheetSummary.pdf](https://github.com/pugjs/pug/files/4813817/coverSheetSummary.pdf)
[coverSheetSummary200.pdf](https://github.com/pugjs/pug/files/4813818/coverSheetSummary200.pdf)

**Comment by ForbesLindesay** [comment]
This has nothing to do with pug. Pug outputs HTML, not PDFs
