### ISSUE TITLE
Render error for Chrome but Postman correct

### ISSUE THREAD

**Issue by gb53smith** [pugjs/pug#3273]
**Pug Version:** your version number here
3.00
**Node Version:** your version number here
v14.4.0

In this code I continue a table with the results of a database search
```
extends wineSearch

block content
   for val in wineSelection
      tr
         td
            form(action='/wine/update', method='POST')
               input(type='hidden', name='loc', value=val.wine_Location)
               button.loc_button=val.wine_Location   
         td= val.wine_Quantity
         td= val.wine_Type
         td= val.wine_Colour
         td= val.wine_Grape
         td= val.wine_Winery
         td= val.wine_Country
         td= val.wine_Vintage
```
In chrome the first row, the form is excluded.  Remaining rows are correct. Testing using Postman yields the correct result

Chrome: (error)
```
						<td>
							<input type="hidden" name="loc" value="E1" /><button
								class="loc_button"
							>
								E1
							</button>
						</td>
```
Postman:  (correct)
```
<td>
						<form action="/wine/update" method="POST">
							<input type="hidden" name="loc" value="E1" /><button
								class="loc_button"
							>
								E1
							</button>
						</form>
					</td>
```
I am sure that the input to PUG is the same.  ie wineSelection
Does the express server detect the client and render differently? 
Is there a way to force the render as if a Postman client?

**Comment by ForbesLindesay** [comment]
A form element cannot be placed inside a table (https://stackoverflow.com/a/5967613/272958). This is a limitation of the HTML spec, and has nothing to do with pug. Pug outputs the HTML you asked it to, which you see in Postman. You would see the same thing in Chrome if you went to "View Source" but when you look in the inspect elements tab you see the DOM that results after chrome applies the rules of the HTML spec, which force it to remove your form

**Comment by gb53smith** [comment]
Thanks Forbes,
I now understand that PUB can generate bad HTML if you are not careful.
Turns out that you can put a form inside a table data element.  My bigger problem was trying to nest a form within a form.
To test the PUG output I uploaded the Postman response to https://validator.w3.org/nu/ for HTML checking.  This is how it corrected my error.
