### ISSUE TITLE
Blank new line is added before output with pretty print

### ISSUE THREAD

**Issue by mvorisek** [pugjs/pug#3291]
## Input Pug

```pug
<{_element}div{/}>
| {$x}
</{_element}div{/}>
= "\n"
```

## Expected HTML

```html
<{_element}div{/}>{$x}</{_element}div{/}>
```

## Actual HTML

```html
 
<{_element}div{/}>{$x}</{_element}div{/}>
```
(notice the blank new line at the beginning)

**Comment by ForbesLindesay** [comment]
Pretty print output is only intended to support generating human readable HTML for documentation purposes. We do not accept any fixes to whitespace behaviour of pretty printing mode and we recommend never using pretty printing to generate HTML to actually be rendered.

If you want to debug the HTML that is rendered, you can usually use the "Inspect Element" feature to look at the DOM (the actual tree of elements the browser uses) in most modern browsers.

Sorry for the inconvenience.
