### ISSUE TITLE
Optional chaining (?.)

### ISSUE THREAD

**Issue by dn-l** [pugjs/pug#3292]
**Pug Version:** your version number here
3.0.0

**Node Version:** your version number here
v14.11.0

## Input Pug

```pug
h1= a?.b?.c
```

## Expected HTML

```html
<h1>I Love Pug</h1>
```

## Result

Syntax Error: Unexpected token

## Additional Comments

Will pug support [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)?

**Comment by desertdisk** [comment]
Any update here?

**Comment by RevealedFrom** [comment]
The optional chaining operator does not work in some contexts.

```
- console.log(`OK: ${user?.id ? "red" : "green"}`);
p(style=    `color:${user?.id ? "red" : "green"}`) Profile
```
For the above in the same pug file, the first line works fine, but the second produces a `Syntax Error: Unexpected token`.

The following, however, works fine:

    p(style=`color:${user? user.id ? "red" : "green" : "green"`}) Profile

**Comment by matthewjumpsoffbuildings** [comment]
Any updates on this?

**Comment by sahlex** [comment]
Same issue for me. Please give an update on this topic!

**Comment by robincsamuel** [comment]
+1

**Comment by jwleon** [comment]
+1

**Comment by pedroleung** [comment]
+1

**Comment by Slayess** [comment]
Hello,
Not sure that it's the better way, but the files ../node_modules/pug-lexer/index.js (line 75) can be modified like :
`  isExpression: function(exp) {
    return isExpression(exp, {
      throw: true,
      ecmaVersion: 2020
    });
  },`

**Comment by matthewjumpsoffbuildings** [comment]
@Slayess does this allow optional chaining? If so it should be easy enough to make a pull request right?

**Comment by Slayess** [comment]
@matthewjumpsoffbuildings : 2 reasons why I don't do it :
1) I don't have enough knowledge and I'm not sur that it's the cleanest way
2) It strange that it's necessary to set the ecmaVersion, I'm working with the latest version of all packages  ... without special settings it should be "work" by default with the latest ecmaVersion.... I didn't see any default settings...

**Comment by rounakEmpower** [comment]
@matthewjumpsoffbuildings is there any other way like dynamic include in the pug template https://stackoverflow.com/questions/45824697/workaround-to-dynamic-includes-in-pug-jade

**Comment by yssrku** [comment]
This is simply because `is-expression` locks to older version of acorn, which defaults to earlier ecmaVersion.

A workaround is to set overrides in package.json (or resolutions is using yarn) like this:
```json
{
  "overrides": {
    "acorn": "8.8.1"
  }
}
```

This is output warning though, as later version now requires ecmaVersion to be set explicitly.

**Comment by H3RSKO** [comment]
2023 and optional chaining doesn't work by default? 😞

**Comment by Bessonov** [comment]
2023 and you still haven't contributed? :disappointed:

**Comment by LeM0-Dev** [comment]
It appears that PUGJS is no longer actively maintained/atleast no new features are being added for quite some time.

One way to solv this is to perform the check before rendering the view. In other words, make sure your variables are good before attempting to render, alternatively when passing the data to the render function. 

Example for original comment:
`
res.render("index", {
  a: a?.b?.c
});
`
so then 
`h1= a`
will produce the desired outcome

**Comment by chrisspiegl** [comment]
@dn-l how is this closed as completed if there hasn't been a new version in years?
I'd suggest keeping this open for now. If you no longer use Pug or don't want notifications for this issue anymore, you can change the notification settings, maybe that's what you wanted to do?
