### ISSUE TITLE
multiple line of classes support

### ISSUE THREAD

**Issue by anurat** [pugjs/pug#3307]
I'm planning to use tailwind css with pug js. 
Tailwind css provides utility classes for about everything so when you style an element,
its associated classes could get really long. Some elements may end up having a dozen of classes
and the code becomes very long.

I am wondering whether there is a way to wrap those classes to a new line in pug js

I don't mind about the syntax as long as we can add new line of classes on an element.

```pug
h1.container.mx-auto.box-border.flex-1.clear-both.justify-center.items-center.pt-6.pb-8.font-sans.text-lg.italic.font-medium.text-indigo-300.underline I Love Pug

h1.container.mx-auto.box-border.flex-1.clear-both.justify-center.items-center ->
    .pt-6.pb-8.font-sans.text-lg.italic.font-medium.text-indigo-300.underline I Love Pug

p You get the idea.
```

**Comment by cpof-tea** [comment]
First of all, I would suggest you to use editor word-wrap settings and column width.
For the pug, you can use object or array notation for class attribute
```pug
h1(class=[
  'container', 'mx-auto', 'box-border', 'flex-1', 'clear-both', 'justify-center', 'items-center',
  'pt-6', 'pb-8', 'font-sans', 'text-lg', 'italic', 'font-medium', 'text-indigo-300', 'underline',
]) I Love Pug
```
or just (but I wouldn't do that)
```pug
h1(class=[
  'container mx-auto box-border flex-1 clear-both justify-center items-center',
  'pt-6 pb-8 font-sans text-lg italic font-medium text-indigo-300 underline',
]) I Love Pug
```
Also, I would suggest you to replace all dot-classes in elements to attributes instead. Tailwind has a lot of colon classes `lg:text-center` and pug outputs an error when it meets a colon in dot-classes, so you will have to move these classes to attributes, and then you will get confused by mix of class notations
```pug
.container.mx-auto.box-border.flex-1.clear-both(class="lg:pt-6 sm:pt-3")
```
Would be better
```pug
div(class="container mx-auto box-border flex-1 clear-both lg:pt-6 sm:pt-3")
```

**Comment by anurat** [comment]
@cpof-tea Thank you so much, that works too.
