### ISSUE TITLE
Colon breaks syntax highlighting

### ISSUE THREAD

**Issue by jaycc008** [pugjs/pug#3309]
## Problem

![Screenshot 2021-01-27 at 15 19 33](https://user-images.githubusercontent.com/2969879/106004015-1143ca80-60b3-11eb-89d7-9012400c4872.png)

Colon breaks syntax highlighting, I have read about several workarounds, but I am wondering if there is an actual way to make the colons work instead of using `v-bind`, comma's between attributes or putting parentheses around the attribute

**Comment by cpof-tea** [comment]
I think syntax highlighting is not a case of pug issue. It's more of syntax highlighting implementation itself. I would suggest you to try another syntax highlight plugin (or you could try to write your)

**Comment by ForbesLindesay** [comment]
I don't maintain the syntax highlighters for any editors. You will need to contact the plugin author/author of your editior.
