### ISSUE TITLE
The release notes should make it more apparent when a release fixes security vulnerabilites

### ISSUE THREAD

**Issue by ParkerM** [pugjs/pug#3316]
I recently got a dependabot notice about a version bump from 3.0.0 to 3.0.1. The changelog seemed innocent at a glance so I brushed it off, but after reading it again I noticed it was a security fix. I probably expected a security fix to be explicitly highlighted as such, and assumed the "Bug Fixes" section would account for a use case I probably wouldn't run into. It'd be nice if the release notes made more distinction between security fixes and general bug fixes.

Screenshot for reference:  
![image](https://user-images.githubusercontent.com/5124113/109755606-ea921b80-7bab-11eb-9b7b-e5f0671e9ba5.png)

**Comment by ForbesLindesay** [comment]
I publicised this as widely as I could.
