### ISSUE TITLE
Does it make sense to implement something like class name reference (& in jade/less/sass)?

### ISSUE THREAD

**Issue by sgtpep** [pugjs/pug#332]
Hi,

For my own convention (due to some technical reasons) I prepend prefixes (preserving hierarchy) to all my class name. Example:

```
.some-block
  .some-block-header
    .some-block-header-title
    .some-block-header-tab-bar
      .some-block-header-tab-bar-item
```

Styling them using jade/less/sass is DRY and nifty:

```
.some-block
  &-header
    &-title
      ...
    &-tab-bar
      &-item
        ...
```

But Jade template above doesn't so DRY and has some repetition. It could be cool to have something like ampersand operator in Jade. Thanks.

**Comment by Grawl** [comment]
Agree. Still want it.
