### ISSUE TITLE
html code 1 line

### ISSUE THREAD

**Issue by raf-lii** [pugjs/pug#3320]
**Pug Version:** 3.0.2

**Node Version:** 12.9

## Input Pug

```pug
doctype html
html
    head
        title=title
        link(rel='stylesheet', href='/css/style.css')
        link(rel='stylesheet', href='/css/bootstrap.min.css')
    body
        block content
```
## Block content

```block content
block content
    h1(class='title-content') title
    p welcome to #{title}
```

## Expected HTML

```html
         <head>
              <title>MY TITLE</title>
              <link rel="stylesheet" href="/css/style.css">
              <link rel="stylesheet" href="/css/bootstrap.min.css">
         </head>
         <body>
                <h1 class="title-content")MY TITLE</h1>
                <p>Welcome to MY TITLE</p>
         </body>
     html
```

## Actual HTML

```html
<!DOCTYPE html><html><head><title>Express hi</title><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/bootstrap.min.css"></head><body><h1 class="title-content">title</h1><p>welcome to Express hi</p></body></html>
```

## Additional Comments

please someone tell me whats wrong in my code why my code is everything in 1 line?

**Comment by jeromew** [comment]
pug does not try to output a nicely formatted HTML and what you get on one line would correctly be interpreted by a browser.
If you need a nicely formatted html, you will need to postprocess the output of pug.
I am closing this issue as this question has already been discussed previously and that it was decided at this stage to not support nicely formatted html.

**Comment by trasherdk** [comment]
Take a look at [pug options](https://pugjs.org/api/reference.html#options)

`pretty: boolean | string` and `compileDebug: boolean`
