### ISSUE TITLE
https://lov.linkeddata.es/dataset/lov/ is down - stack trace

### ISSUE THREAD

**Issue by gibsonf1** [pugjs/pug#3323]
TypeError: Property 'visitundefined' of object #<Object> is not a function Please report this entire error and stack trace to https://github.com/jadejs/jade/issues at Object.Compiler.visitNode (/usr/local/lov/lovnode/node_modules/jade/lib/compiler.js:225:37) at Object.Compiler.visit (/usr/local/lov/lovnode/node_modules/jade/lib/compiler.js:212:10) at Object.Compiler.visitBlock (/usr/local/lov/lovnode/node_modules/jade/lib/compiler.js:295:12) at Object.Compiler.visitNode (/usr/local/lov/lovnode/node_modules/jade/lib/compiler.js:225:37) at Object.Compiler.visit (/usr/local/lov/lovnode/node_modules/jade/lib/compiler.js:212:10) at Object.Compiler.compile (/usr/local/lov/lovnode/node_modules/jade/lib/compiler.js:66:10) at parse (/usr/local/lov/lovnode/node_modules/jade/lib/index.js:112:19) at Object.exports.compile (/usr/local/lov/lovnode/node_modules/jade/lib/index.js:177:16) at Object.exports.render (/usr/local/lov/lovnode/node_modules/jade/lib/index.js:315:15) at Object.exports.renderFile (/usr/local/lov/lovnode/node_modules/jade/lib/index.js:352:18)

**Comment by ForbesLindesay** [comment]
You are using an old version of pug. Please update to the latest version.
