### ISSUE TITLE
how performant is pug.js?

### ISSUE THREAD

**Issue by creativemacmac** [pugjs/pug#3324]
Hey there guys :) Not really an issue more like curiosity :) I am on a course using pug.js and I got curious about how it performs speed-wise, but I cannot find any info. Are there sites out there that use pug.js in production?

thanks in advance

Linda

**Comment by benjaminbhollon** [comment]
@creativemacmac My site, https://seewitheyesclosed.com/, uses it in production, and I haven't noticed any performance problems (my TTFB is usually 300ms according to GTMetrix). I use it with ExpressJS, and when `NODE_ENV` is set to `production`, compiled templates are cached, which hugely reduces the time to load. You're welcome to run any tests you'd like on that site; if you need my help with something, contact me through the form there and we'll talk. 😉

**Comment by creativemacmac** [comment]
@benjaminbhollon thank you sooooooooooooooooooooooooo much for responding to this:)  your site loads swiftly and looks really good too, now I can continue with my little pug project :)

**Comment by benjaminbhollon** [comment]
@creativemacmac No problem! Don't forget to close this issue if you're done with it (I'm not actually a project contributor so I can't do that)
