### ISSUE TITLE
The logo of pug is wrong,Could you fix it?

### ISSUE THREAD

**Issue by Hackcr** [pugjs/pug#3325]
Pug have two black points on his face.Like this:
![image](https://user-images.githubusercontent.com/5523475/113832040-ccc36200-97ba-11eb-8f82-1d6bd998c2bc.png)
![image](https://user-images.githubusercontent.com/5523475/113832420-317ebc80-97bb-11eb-8a7b-224fdc93b922.png)

Could you add two black points on logo image?

**Comment by trasherdk** [comment]
ROFL!

**Comment by w3sheldon** [comment]
I think you late for April fools
