### ISSUE TITLE
pug@3.0.2 has a vulnerability dependency : pug-code-gen@3.0.2

### ISSUE THREAD

**Issue by UjwalaK** [pugjs/pug#3327]
**Pug Version:** 3.0.2
**pug-code-gen Version:** 3.0.2

## Additional Comments

Dependency checker scanner associated with our project has reported vulnerability with pug-code-gen version 3.0.2

Issue:

```js
Classname: CWE-74: Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')

{
  "message": "cvssV3: MEDIUM, score: 5.3 (/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N)"
}
```

**Comment by ForbesLindesay** [comment]
This does not have any detail for me to review in order to know if this is genuine. I suspect it is not: https://overreacted.io/npm-audit-broken-by-design/
