### ISSUE TITLE
HTML5 Boolean attributes

### ISSUE THREAD

**Issue by edemaine** [pugjs/pug#3330]
**Pug Version:** 2.0.3

**Node Version:** 15.5.1

## Input Pug

```pug
input(disabled)
```

## Expected HTML

```html
<input disabled>
```

## Actual HTML

```html
<input disabled="disabled">
```

## Additional Comments

[HTML5 defines empty attributes as defaulting to the empty string](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2). Pug follows HTML4 behavior for Booleans, defaulting to the key value, but it should now default to `""`.

## Workaround

```pug
input(disabled="")
```

**Comment by battlehater** [comment]
doctype: "html" in pug options can help you.

There is my gulp cofig:

const html = () =>
  gulp
    .src(PATH.html.src /*{ since: gulp.lastRun("html") }*/)
    .pipe(plumberNotifier())
    .pipe(pug({ doctype: "html", data: { env } })) // <--- HERE
    .pipe(gulpIf(env !== "dev", prettier()))
    .pipe(gulp.dest(PATH.html.build))
    .pipe(server.stream());

export default html; 

And build result: 
<input
  class="form-check-input"
  id="odDeliveryPickup"
  type="radio"
  name="delivery"
  value="pickup"
  checked
/>

**Comment by edemaine** [comment]
Ah, you're right &mdash; adding `doctype html` to the top of the file also fixes this issue &mdash; great!  I think this is just a documentation issue then.  I'll try to put together a PR.
