### ISSUE TITLE
Pug doesn't render anchor tags properly

### ISSUE THREAD

**Issue by richardnguyen99** [pugjs/pug#3332]
**Pug Version:** `3.0.2`

**Node Version:** `v16.1.0`

## Input JavaScript Values

```js
// Nothing
```

## Input Pug

```pug
a(href="/").card.card__article
  img(src="/assets/images/bubble-sort.jpg", alt="Bubble sort").card-img-top

  div.card__text
    div.card__tags
      a.badge.bg-primary sorting
    h5.card-title Bubble sort
     p Swapping everything
```

## Expected HTML

```html
<a href="/" class="card card__article">
  <img src="/assets/images/bubble-sort.jpg" alt="Bubble Sort">
  <div class="card__text">
    <div class="card__tags">
      <a class="badge bg-primary">sort</a>
    </div>
    <h5 class="card-title">Bubble sort</h5>
    <p>Swapping everything</p>
  </div>
</a>
```

## Actual HTML

```html
<a href="/" class="card card__article">
  <img src="/assets/images/bubble-sort.jpg" alt="Bubble Sort">
</a>
<div class="card__text">
    <div class="card__tags">
      <a class="badge bg-primary">sort</a>
    </div>
    <h5 class="card-title">Bubble sort</h5>
    <p>Swapping everything</p>
</div>
```

## Additional Comments

Inside `card__text`, if it has only two elements or three element with one excessive no-style element, it works just fine. But if it is as showed above, it doesn't render properly. At first, I thought it was a styling error, but when I fixed it by hands on my browser, the component is exactly what I wanted.

**Comment by richardnguyen99** [comment]
After grinding on the issue, I realize that whenever I put an anchor tag inside another anchor tag, this issue will happen. So for some reasons, pug doesn't allow me to do nested anchor tags.

**Comment by trasherdk** [comment]
Du you have a link to somewhere describing nested anchors as a solution to something?
```html
<a href="/"><a foo="bar">Something</a></a>
```

**Comment by richardnguyen99** [comment]
Based off the code above, I have a card as an anchor element to navigate to some according posts. But I also want to have a list of tags that when you click on one, they will navigate you to a list of posts that share the same tag.

**Comment by trasherdk** [comment]
Googling `html nested anchor tags` the top reference is: [Why are nested anchor tags illegal?](https://stackoverflow.com/questions/18666915/why-are-nested-anchor-tags-illegal)

**Comment by richardnguyen99** [comment]
From reading your link, I guess this is a feature on modern browsers to prevent nested anchor tags. I will close this issue since it doesn't relate to pug. Thank you btw!
