### ISSUE TITLE
is pug no longer maintained?

### ISSUE THREAD

**Issue by chase-moskal** [pugjs/pug#3339]
pug-cli has fallen behind, and is emitting red npm security warnings

it's indirectly making my packages look unsavoury as they inherit those security warnings

i just want to know whether there are any plans in the works, so i can plan my next steps on this issue, thanks

**Comment by minustime** [comment]
I'm also interested to know this.

**Comment by MxReaper** [comment]
Me too.

**Comment by rejais** [comment]
count me in.
I follow pugs since it's Jade.

**Comment by ForbesLindesay** [comment]
Pug is still maintained, but it is currently working, so I am releasing less frequent updates.

**Comment by chase-moskal** [comment]
@ForbesLindesay

> but it is currently working

not so fast --

many of us use pug via the cli because it's the only way to setup a watch routine for our projects

and it's fallen into a state of outdated disrepair

https://github.com/pugjs/pug-cli/issues/86

**Comment by lil5** [comment]
https://github.com/pugjs/pug#dependency-status

The README shows that the base package `pug` also has outdated dependencies

**Comment by Anduh** [comment]
> many of us use pug via the cli because it's the only way to setup a watch routine for our projects
> and it's fallen into a state of outdated disrepair

Yeah, it's to the point that I forked & published a version of pug-cli with updated dependencies [@anduh/pug-cli](https://www.npmjs.com/package/@anduh/pug-cli), which feels really pointless bc it's a quick fix. 

pugjs/pug-cli/pull/88 is an open PR waiting for this.

**Comment by geoidesic** [comment]
There are open issues dating back to 2015 and 250 open issues – that's not a good look. Do you need help? I'm sure you'd find volunteers @ForbesLindesay.

**Comment by matthewjumpsoffbuildings** [comment]
@ForbesLindesay 
> Pug is still maintained, but it is currently working, so I am releasing less frequent updates.

well the official `pug-cli` package, which is linked to on the main `pug` readme, just doesnt install. not what i would call 'currently working'

can you take a look at https://github.com/pugjs/pug-cli/pull/88 ?

**Comment by ekfuhrmann** [comment]
> Pug is still maintained, but it is currently working, so I am releasing less frequent updates.

Continued support would be nice. Outside of updating the outdated packages as highlighted in this thread, there are also simple QoL improvements sitting in the Issues Tracker such as #3347 or #3214 that all greatly aid in the usage of Pug in development.

If it's a matter of resourcing, there are willing people who could help maintain these requests and keep Pug relevant.

**Comment by Anduh** [comment]
> If it's a matter of resourcing, there are willing people who could help maintain these requests and keep Pug relevant.

Yes, ideally more people could be added as maintainers of the actual package.

I've been meant to test & eventually include those in my fork([@anduh/pug-cli](https://www.npmjs.com/package/@anduh/pug-cli)), but apart from updating the deps mid-2021, this have fallen to the wayside. Obviously Open to add maintainers to my fork. @ekfuhrmann 

Might revisit & update it in the near future, when I'll be look into some VS Code-integration.
