### ISSUE TITLE
Variable Declaration Syntax

### ISSUE THREAD

**Issue by alexjavascript** [pugjs/pug#3340]
```
- var site_links = [{title: "Home", link: "home.html"}, {title: "Works", link: "works.html"}, {title: "Booking", link: "booking.html"}, {title: "Contacts", link: "contacts.html"}, {title: "Alex", link: ""}];
```

Difficult to read, but code line breaks invoke parsing errors, so I can't use something like this: 

```
- var site_links = [
  {
    title: "Home", 
    link: "home.html"
  }, {
    title: "Works", 
    link: "works.html"
  }
]
```

Is there possibility to implement that?

**Comment by ForbesLindesay** [comment]
You can use a code block to break onto multiple lines: https://pugjs.org/language/code.html#unbuffered-code

![image](https://user-images.githubusercontent.com/1260646/125300634-1f646b00-e322-11eb-8f9b-b383cbe6e93e.png)
