### ISSUE TITLE
Interpolate HTML unscape

### ISSUE THREAD

**Issue by PedroFumero** [pugjs/pug#3359]
**Pug Version:** 3.0.2

**Node Version:** 16.13.2

## Input Pug

```pug
!{recipe.ingredientsList}
```

## Expected HTML

```html
<ul>
  <li>One</li>
  <li>Two</li>
  <li>Three</li>
</ul>
```

## Actual error

```html
unexpected text "!{rec"
```

## Additional Comments

Using the String Interpolation, Unescaped section of docs: https://pugjs.org/language/interpolation.html#string-interpolation-unescaped, I'm not able to introduce my unordered list using: !{variable} syntax.

Any advice for introducing unescaped HTML on pug?

**Comment by PedroFumero** [comment]
The solutions proposed by @zoldbogar at https://github.com/pugjs/pug/issues/3133 works just fine. Issue solved.

**Comment by zoldbogar** [comment]
it's been a while since I used pug templating, but now re-reading the (above mentioned) article, I guess (did not try it) that the string interpolation would work if you put a pipe sign before it: `| !{recipe.ingredientsList}`... @PedroFumero, can you confirm or inform this for me, please?

**Comment by PedroFumero** [comment]
I confirm @zoldbogar after adding the pipe character it worked just fine! Thanks a lot!
