### ISSUE TITLE
Can I use pug to precompile a simple static site?

### ISSUE THREAD

**Issue by temocj** [pugjs/pug#3369]
Greetings,

I haven't done webdev since the 2000's and I'm overwhelmed with all the new tools people are using. I just want to revamp an old website with old school HTML & CSS and the main thing that I'm looking for is the ability to embed templates (aka inherit/extend templates).

I also like pug's syntax a lot compared to some other templating languages I've seen.

Can I use pug to compile some templates on my PC before uploading the HTML & CSS to an Apache server where it will be statically served? Kinda like SCSS/Less precompile?

I do also have the ability run PHP on my server, so alternatively I could use Phug, but I don't have Apache/PHP on my PC so I couldn't test it easily. I used to do MAMP webdev on my PC but I'd like to avoid having to deal with all that again!

Kind regards,
Temoc

**Comment by nomuna** [comment]
May be these methods could help you. Try them out in a little node/express project and see if it fits your needs.

```
pug.compile
pug.compileFile
pug.renderFile
```

**Comment by temocj** [comment]
Thanks for your reply! I was hoping to avoid installing 1000 npm dependencies, but it seems unavoidable.
