### ISSUE TITLE
Pug adds double quotes when rendering string objects as tag attribute values 

### ISSUE THREAD

**Issue by Git-I985** [pugjs/pug#3382]
**Pug Version:** 3.0.2

**Node Version:** 14.18.3

## Input JavaScript Values

```js
pug.renderFile('input.pug', {
  description: new String('str'),
});
```

## Input Pug

```pug
 meta(name='description', content=description)
```

## Expected HTML

```html
<meta name="description" content="str">
```

## Actual HTML

```html
<meta name="description" content=""str"">
```

## Additional Comments
Pug adds double quotes when rendering string **objects** as tag attribute values (new Number or object literals rendered correctly)

**Comment by webdiscus** [comment]
@Git-I985 

Pug renders correct.

yes of cause `new String('str')` is the object `{ "str" }`.
You self should take care of the correct value type:

```js
pug.renderFile('input.pug', {
  description: new String('str').toStrting(),
});
```
then it will be rendered as expected: `<meta name="description" content="str">`

P.S. it is not a Bug, it is the feature ;-)
