### ISSUE TITLE
How can I add an attribute without a value?

### ISSUE THREAD

**Issue by respectTheCode** [pugjs/pug#370]
How can I create this output?

```
<script src="/javascripts/angular-0.9.19.js" ng:autobind></script>
```

I have tried

```
script(src="/javascripts/angular-0.9.19.js",ng:autobind)
```

and

```
script(src="/javascripts/angular-0.9.19.js","ng:autobind")
```

both produce the output

```
<script src="/javascripts/angular-0.9.19.js" ng:autobind="ng:autobind"></script>
```

With angular this creates an error and prevents angular from running.

**Comment by geoidesic** [comment]
Can we re-open this? I'm having the same problem. Some directives require the attribute without any value being set at all. Jade is unusable with AngularJS in many instances because of this requirement.

**Comment by TimothyGu** [comment]
Hm…

With html doctype:

```jade
doctype html
script(src="/javascripts/angular-0.9.19.js" ng:autobind)
```

```html
<!DOCTYPE html>
<script src="/javascripts/angular-0.9.19.js" ng:autobind></script>
```

Without (or with x(ht)ml) doctype:

```jade
doctype strict
script(src="/javascripts/angular-0.9.19.js" ng:autobind)
```

```xml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<script src="/javascripts/angular-0.9.19.js" ng:autobind="ng:autobind"></script>
```

----

The reason for this is that XML does not support valueless attribute, while HTML5 does. I think. So FWIW I don't support reopening this bug. Use a proper doctype.

Even if we decide to change it will be a major bump.

**Comment by jhulbert-eb** [comment]
Revisiting this in the interest of Angular 2 component templates. It seems that when no doctype is declared in a file (such as component templates) the default behavior of pug is to automatically add an attribute value in accordance with XHTML doctype. This makes it impossible to use Angular local variables to target a view child - which is a common means of querying elements.

`div(#myElement class="my-element")` --> `<div #myElement="#myElement" class="my-element"></div>`

**Comment by PowerOfM** [comment]
Could a compiler options be added to treat the files as `doctype html`?

**Comment by PowerOfM** [comment]
Oh, you can just specify the compiler option "doctype" to be "html", and then it renders everything correctly.

**Comment by mattychen** [comment]
@PowerOfM adding `doctype html` to the top of your template worked out well. Thanks!

**Comment by VadymGidulian** [comment]
In addition to @jhulbert-eb and @PowerOfM comments:
[API Reference](https://pugjs.org/api/reference.html)
[Doctype (Language reference)](https://pugjs.org/language/doctype.html#doctype-option)
