### ISSUE TITLE
can't parse #{variable} in script tag

### ISSUE THREAD

**Issue by rogical** [pugjs/pug#396]
Hello,

How can I do this ?  I need to parse #{variable} in script tag.

**Comment by PareshSolankiMI** [comment]
console.log(!{JSON.stringify(variable)})

**Comment by ForbesLindesay** [comment]
N.B. if you want to do this securely, you need to use [js-stringify](https://www.npmjs.com/package/js-stringify)

```pug
script.
  console.log(!{stringify(variable)})
```

```js
pug.renderFile('template.pug', {stringify: require('js-stringify')});
```
