### ISSUE TITLE
:markdown filter processing the text of a String variable

### ISSUE THREAD

**Issue by bobmonteverde** [pugjs/pug#404]
So I have a variable that's a sting containing markdown text (the body of an article for a simple node powered blog).

so, first I tried:

:markdown
&nbsp;&nbsp;#{ article.body }

which outputs: &lt;h1&gt;{ article.body }&lt;/h1&gt;

I also tried:

:markdown
&nbsp;&nbsp;&#92;#{ article.body}

which outputs the contents of article.body, BUT does not process the contents with the markdown filter.

So, is there a way to accomplish what I am trying?

**Comment by deni35** [comment]
Much time has passed. Is still there no way to pass text variable to filter?
What's problem to do something the next?
```:markdown-it(content=article.body)```
Or
```:markdown-it= article.body```

I think in most cases it is necessary to pass text in variable.

**Comment by TimothyGu** [comment]
https://github.com/pugjs/jade/blob/master/docs/views/reference/filters.jade:
> Filters are rendered at compile time, which makes them fast but also means that they cannot support dynamic content or options.

They are designed to not support dynamic content.

**Comment by deni35** [comment]
This is strange. I don't see any difference. Filter the text from current jade file or take the text from the locals.

**Comment by ForbesLindesay** [comment]
There are two stages to generating html from jade.  The first step (compiling) happens once on application startup, and doesn't have access to local variables, only to the raw source code.  The second stage (rendering) happens for every single page request.  It's responsible for combining the compiled code with the locals.  It's critical that this stage is really fast.

**Comment by rriemann-eu** [comment]
I use pugjs to generate html files much like in statically generated websites. For this, it would be very useful to generate html from markdown using variables.

**Comment by buckle2000** [comment]
```
:markdown-it= article.body
```
I feel like this should work somehow.

It doesn't even throw an error.
