### ISSUE TITLE
if you're having inheritance problems...

### ISSUE THREAD

**Issue by sebphfx** [pugjs/pug#407]
Eureka!
I was having problems with inheritance using block and extends and I didn't know what the problem was. Newbie alert!! On Linux, I just changed my file permissions in the app folder and everything works now.

**Comment by thesksamim** [comment]
> I also get that when I don't point to the layout from the extended one.
> 
> E.g.
> 
> > layout.jade
> > pages/page.jade
> 
> If page.jade extends layout and extends it using "extends layout" instead of "extends ../layout" I get that error.
