### ISSUE TITLE
input type=checkbox bug?

### ISSUE THREAD

**Issue by ghost** [pugjs/pug#445]
input(id='agreement', type='checkbox') I agree to the terms of use

only renders the checkbox

input(id='agreement', type='checkbox')I I agree to the terms of use

renders checkbox and text in italic

input(id='agreement', type='checkbox')g I agree to the terms of use

renders checkbox and text as expected

**Comment by chornbe** [comment]
@Forbes, not, it's not an html issue; you can put the expected html right in-line and it renders the label where it should.

.form-group
	label(for="passwordRepeat") repeat password
	input#passwordRepeat.form-control(type="password", placeholder="Repeat Password", name="passwordRepeat", required)
.form-group
<label id="lblChkInstBillCode"><input type="checkbox" name="chkInstBillCode" id="chkInstBillCode"/>&nbsp;my label goes here</label>
.form-group
	input#textInstBillCode.form-control(type="text", placeholder="institutional billing code", name="instbillingcode", disabled="disabled")

**Comment by ForbesLindesay** [comment]
Fix your indentation. If you want your input inside your label, indent it inside the label.
