### ISSUE TITLE
Populating attributes from objects (extracting keys/values)

### ISSUE THREAD

**Issue by Prestaul** [pugjs/pug#664]
I'm wondering if there is any way to populate the attributes on an element from the keys/values on an object.  What I really want to do is something like this:

```
input.foo(name=name, value=value, attributes)
```

Pass in data like this:

```
{
    name: 'username',
    value: 'bob',
    attributes: {
        maxlength: 16
    }
}
```

and get this output:

```
<input name="username" value="bob" maxlength="16" />
```

Is there any way to accomplish this without needing to specify each attribute individually?

**Comment by handeman67** [comment]
very old post but i am using this. probably came with updates.
<code>
input(
name= 'username',
value='bob',
maxlength= '16')
</code>
