### ISSUE TITLE
What is the best way to assign a class to <body> from within a template

### ISSUE THREAD

**Issue by chrisbuttery** [pugjs/pug#684]
Hi All, 

I'm wondering if there's a particular way I can assign a class to the `<body>` from within an article.jade template.

I'm using Wintersmith https://github.com/jnordberg/wintersmith and have a layout.jade template, and an article.jade template.

The article.jade template looks like so

```
extends layout

block content
  div.content
    article.page-entry
      header.entry-header
        h1.entry-title= page.title
      div.entry-content!= page.html
```

...which then extends the layout.jade template 

```
<!doctype html> 
    head
    block head
    body
      block header
      block content
      block footer
```

Is there anyway from inside my article.jade template, that I can pass through 'just' a class to the `<body>` element ?

Thanks in advance.
Chris

**Comment by reardestani** [comment]
In my side, I had to define bodyClass as follows to make it work.
```
body(class=bodyClass)
```
