### ISSUE TITLE
Impossible to extends from template in parent folder

### ISSUE THREAD

**Issue by josser** [pugjs/pug#710]
Example: 

<pre>
layout.jade
index.jade
users/
   show.jade
posts
   show.jade
</pre>

posts/show.jade: 

// Tried several variants: 
extends layout 
extends /layout
extends ../layout
// No luck :( 

Thanks!

**Comment by davaahoo** [comment]
It's working new pug 
`extends ../layout.pug`

**Comment by VictorioBerra** [comment]
Why not just search upwards and grab the nearest layout?

**Comment by ForbesLindesay** [comment]
It's best to be explicit, so we support either absolute paths (from a basedir) or relative paths (from current dir)
