### ISSUE TITLE
Pretty Options

### ISSUE THREAD

**Issue by rafaelfaria** [pugjs/pug#718]
I know it has been discussed here about this option but it got me a bit confused because I've read from an issue (2 years ago) that pretty got removed but I can't find an alternative to get my markup to be readble now.

I'm using the following

// Configuration
app.configure(function(){
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.set('view options', { pretty: true });
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(express.static(__dirname + '/public'));
});

Pretty: true doesnt work (If has been removed will make sense), but I quick google on it and Ive also read a few people using it. 

Question is, Does pretty still works? and if does why wouldnt be working on mine? If doesnt, what would be the alternative?

Btw I'm using express 3beta7 and jade 0.26.3

Thanks
Raf

**Comment by snowdream** [comment]
http://stackoverflow.com/a/11812841

**Comment by ryanouyang** [comment]
Sometimes it's necessary to keep the line breaks for layout purpose ( spaces between elements), and tidy the HTML is not my final purpose!
