### ISSUE TITLE
Support for `continue` statement.

### ISSUE THREAD

**Issue by chakrit** [pugjs/pug#759]
Somehow this parses as valid jade:

```
each kind in array
  if !kind in result
    continue

  //- render kind
```

But from my tests the if would falls-through anyway despise the `continue` guard. So apparently `continue` is either broken or not supported.

Will add more info/patch when I have more time.

**Comment by popey456963** [comment]
@ForbesLindesay Could I inquire as to why this was closed?

**Comment by ForbesLindesay** [comment]
It's already supported:

```pug
each kind in array
  if !kind in result
    - continue

  //- render kind
```

We use the `-` prefix for js statements so that we don't have to re-implement the entire JavaScript spec in pug.

**Comment by popey456963** [comment]
Ah, I didn't realise you could interact with pug each / if statements using JS.

That's a really great design decision, thanks so much for sharing!
