### ISSUE TITLE
Support for Stylus plugins for inline Stylus

### ISSUE THREAD

**Issue by wasokeli** [pugjs/pug#760]
I posted a question on StackOverflow, but I figure I should repost it here: 
### [Is it possible to use Stylus plugins with inline Stylus code embedded in a Jade file?](http://stackoverflow.com/questions/12272936/is-it-possible-to-use-stylus-plugins-with-inline-stylus-code-embedded-in-a-jade)

There's a detailed description of the problem and a workaround therein. Anyway, is there any chance of this being made easier?

**Comment by wesleycoder** [comment]
What about the web components and polymer stuff?
Most modules have html, css, and js on one file, we could benefit from getting jade with stylus and coffee inline

**Comment by arxpoetica** [comment]
What a pity. Visiting this thread later, and developer biases about >best practices< is rues over what is expected browser behavior. I favor Jade/Stylus, but Slim/Sass gets it right on this one—let the developer choose.

For the record, I have a working use case that 100% calls for inline styles.

What a sad pity.

**Comment by ForbesLindesay** [comment]
Email templates call for a build step to inline styles (but that should be run against the html so has nothing to do with jade).

Things have moved on a long way since this issue.  If you want to improve a given filter you just need to submit a pull request to the relevant jstransformer.
