### ISSUE TITLE
Multiple appends cause all appends to be duplicated

### ISSUE THREAD

**Issue by ianstormtaylor** [pugjs/pug#781]
Here's the situation:

```
main.jade
  |
  \ page.jade
      | |
      | \ header.jade
      |
      \ docs.jade
         |
         \ faq.jade
```

main.jade

```
!!!
html
  block scripts
    script(src="scripts.js")

  body
    block header
    block body
```

page.jade

```
extends main

block header
  include header.jade

block body
  div.page
    block content
```

header.jade

```
header
  h1 Stuff

append scripts
  script(src="header.js")
```

docs.jade

```
extends page

append scripts
  script(src="docs.js")
```

faq.jade

```
extends docs

block content
  h2 Buncha content
```

The problem is the two different `append scripts` calls cause both of the appends to be duplicated, so `header.js` and `docs.js` execute twice. This only happens when `header.jade` is  included... if i put header's `append` in `page.jade` instead, everything it only appended once.

**Comment by ArVan** [comment]
Hi there. I know this is an old issue for jade, but now the same duplication happens to me when using pug. I'm on `pug 2.0.0-beta9`. Any way to solve this?

**Comment by ForbesLindesay** [comment]
Please open a new issue that describes the exact problem you're having now.  i.e. Provide a sample that is as small as possible of what files you are rendering, what the output is, and what output you expected.
