### ISSUE TITLE
Add wrap functionality for blocks

### ISSUE THREAD

**Issue by kinergy** [pugjs/pug#797]
It would be great if I could 'wrap' an existing block in addition to doing a prepend or append. For instance, assume this layout.jade:

```
!!! 5
html(lang='en')
head
    title Some title

body
  block content
    p Lorem ipsum...
```

I'd like to be able to write:

```
extends layout

wrap content
  div.classWrap
```

to get the following result:

```
body
  div.classWrap
    p Lorem ipsum...
```

Currently, the best solution I have found is instead to hack together the following:

```
!!! 5
html(lang='en')
head
    title Some title

body
  block content
    div(class=myClass)
      p Lorem ipsum...
```

and then:

```
extends layout

prepend content
  var myClass = classWrap
```

**Comment by tkafka** [comment]
This is a functionality I was hacking around for past 2 years - existing for 8 years already!

This is important, as it enables a whole new class of 'wrapper mixins', so useful in the era of utility css frameworks - where a wrapper easily looks like `div.wrap.max-width-2.mx-auto.mb4`, and this allows me to reuse it!
