### ISSUE TITLE
boolean attributes annoyance

### ISSUE THREAD

**Issue by cjroebuck** [pugjs/pug#816]
Hey,

`echo "input.hello(type='checkbox', checked)" | jade`

returns

`<input type="checkbox" checked="checked" class="hello"/>`

According to docs, and what I want, it should just return:

`<input type="checkbox" checked class="hello"/>`

**Comment by yukulele** [comment]
```html
<div itemscope> This is valid HTML but invalid XML. </div>
<div itemscope=itemscope> This is also valid HTML but invalid XML. </div>
<div itemscope=""> This is valid HTML and also valid XML. </div>
<div itemscope="itemscope"> This is also valid HTML and XML, but perhaps a bit verbose. </div>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#Boolean_Attributes

**Comment by ForbesLindesay** [comment]
All of these can be created, depending on your doctype. If you have a specific bit of HTML/XML you are unable to produce, please open a fresh issue and make sure you follow the issue template.
