### ISSUE TITLE
Jade + Json + local compilator (CodeKit/LiveReload/etc)

### ISSUE THREAD

**Issue by Grawl** [pugjs/pug#833]
How can I use Json as database for Jade file?
There is my situation…
index.jade:

``` jade
include data
title = 'Даниил «Grawl» Пронин'
doctype
html
    head
        meta(charset='utf-8')
        title #{title}
    body
        each slide in slides
            figure
                img(src='library/#{slide.file}.png')
                figcaption
                    a(
                        href='#{slide.link}'
                        title='#{slide.name}') #{slide.name}
```

data.jade:

``` jade
slides = [{"name":"ABC-Logistic","file": "Abc-logistic","link": "abc-logistic.co.jp"},{"name":"Art-TEK","file": "ArtTEK","link": "arttek-dv.ru"},{"name":"Ногтевой салон Maki","file": "maki-nails","link": "maki-nails.ru"},{"name":"ПримКомпСервис","file": "PrimCompService","link": "primcompservice.ru"},{"name":"Восточные Лета","file": "vostochnieleta","link": "vostochnieleta.ru"}]
```

I don't like this one-line syntax. It's bad to me. If I add some readability to data, like this:

``` jade
slides = [
    {
        "name": "ABC-Logistic",
        "file":  "Abc-logistic",
        "link":  "abc-logistic.co.jp"
    },
    …
]
```

this code above won't compile (I tried CodeKit and LiveReload). Hmm, this code liiks like Json from codekit-config.json! But how can I use it? If I replace `slides = []` with `include index.json`, compiler just ignore it and returns error `slides is not defined`.
I don't want to use express.js server or jader, I want to compile simple one-page website with data in Json. It's real?

**Comment by Nikolasgrizli** [comment]
hi, this is my example:
`-
	var slides = [
		{
			"name": "test",
			"wul" : "tester",
			"inner": [
				"3", "2", "1"
			]
		},
		{
			"name": "test2",
			"wul" : "tester",
			"inner": [
				"1", "2", "3"
			]
		}
	]
ul.row
	each slide in slides
		li.col
			p
				| #{slide.name}
			small
				| #{slide.wul}
			p
				| #{slide.inner}
`
but I dont understand how this work with json file
