### ISSUE TITLE
Overhaul `filters`

### ISSUE THREAD

**Issue by ForbesLindesay** [pugjs/pug#853]
I think there are a number of things that could be done to improve `filters` enormously.  I'm mostly using Jade for static site generation, so filters are one of the most important features for me as they allow me to do things like write the actual posts in markdown.
## Use `transformers`

[transformers](https://github.com/ForbesLindesay/transformers) is like consolidate.js except that it supports synchronous rendering where possible (it almost always is) and it has a few things that are not really tempting languages (markdown, coffee-script, cdata and uglify-js).

Over time, separating filters out into a separate library like this would allow the collection of possible filters to explode as a result of being able to share their implementation with many other libraries.

Each transformer also has an `.outputFormat` (`xml`, `css` or `js`) which can be used to work out what kind of `script`/`style` tags to wrap the result in.
## Filtered includes

I would like to support filtering an included file:

``` jade
:markdown include path/to/markdown.md
```
## Filtering Filters

This needs to be clever enough not to keep wrapping the result in an additional `<script>` or `<style>` tag each time (it should only do that for the last filter):

``` jade
:uglify:coffee
  my coffee script
```
## Runtime filters

I would like to have filters sometimes be compile time and sometimes be run-time.  They'd be compile time where possible, and only fall back to run-time when necessary.

This would allow the following significant use cases:

The following escapes `foo` then transforms it using `filter` before buffering it (all at runtime):

``` jade
:filter= foo
```

The following transforms `foo` using `filter` before buffering it (all at runtime):

``` jade
:filter!= foo
```

The following passes `{user: user}` to the filter `EJS` and runs it at **run** time.

``` jade
:ejs(user=user)
  <%- user.id %>
```

The following passes `{compress: true}` to the filter `less` and runs it at **compile** time

``` jade
:less(compress=true)
  .less-styles {
    background:blue;
  }
```

At compile time

``` jade
:uglify(mangle=false):coffee(bare=true)
  some coffee script
```

**Comment by ileathan** [comment]
I tried http://jade-lang.com/reference/filters/ and it failed but works with mixins? is this normal? should it work like seen on the website? other filters work for me but not the ':coffee' i see on the website. Anyway I got it all working, would just be nice to see more up to date info on the site. 

Very good work on this all btw :+1:

**Comment by ForbesLindesay** [comment]
You may be using an old version of jade.
