### ISSUE TITLE
URLEncode href and src

### ISSUE THREAD

**Issue by EvanCarroll** [pugjs/pug#915]
If you have a something that has a url, like 

```
a(href="http://www.google.com/search?q=foo bar") 
```

I'd expect that to URL Encode the HREF attribute to 

```
a(href="http://www.google.com/search?q=foo%20bar")
```

I'm not suggesting that Jade automagically encode the reserved characters, just the unreserved URI characters. In perl's TT this is the difference between the [uri](http://template-toolkit.org/docs/manual/Filters.html#section_uri) and [url](http://template-toolkit.org/docs/manual/Filters.html#section_url) filters. TT did not have the knowledge of the attribute, so it couldn't do this transparently. Jade can though.

The same thing applies for `src`. Both `src`, and `href` should be transparently URL-encoded.

> The url filter is a less aggressive version of the uri filter. It encodes any characters outside of the permitted URI character set (as defined by RFC 2396) into %nn hex escapes. However, unlike the uri filter, the url filter does not encode the reserved characters &, @, /, ;, :, =, +, ? and $.

**Comment by ospfranco** [comment]
How do you manually encode it then? I have the following code:
    - each results in result
            a(href="localhost:3000/download/" + #{results} ) Download

Yet I get parser errors

**Comment by TimothyGu** [comment]
@ospfranco try:

```jade
          each result in results
            a(href="localhost:3000/download/" + #{result} ) Download
```

**Comment by ForbesLindesay** [comment]
I would guess what you're after is something like:

```jade
          each result in results
            a(href="localhost:3000/download/" + encodeUriComponent(result)) Download
```

**Comment by ospfranco** [comment]
each result in results
            a(href="localhost:3000/download/" + encodeUriComponent(result)) Download

This worked, many thanks!
