### ISSUE TITLE
New line

### ISSUE THREAD

**Issue by drgullin** [pugjs/pug#921]
``` jade
.user-points
  a(href = '#') John
  span.count 15 points
```

This code compiles to:

``` html
<div class="user-points">
  <a href="#">John</a><span class="count">15 points</span>
</div>
```

How do I make it compile to (add a new line after the link):

``` html
<div class="user-points">
  <a href="#">John</a>
  <span class="count">15 points</span>
</div>
```

**Comment by ivanhalen** [comment]
+1, interested in this too for readability reasons

**Comment by dreamyguy** [comment]
+1 because... why not? After all, Jade compiles to readable, indented HTML.

**Comment by ForbesLindesay** [comment]
Jade pretty mode is only intended for use in generating documentation for jade.  It is an internal feature that you should not be using in production websites.  There are many cases where extra whitespace will break people's templates, so it is better to add none by default.
