### ISSUE TITLE
jade browser compatible issues

### ISSUE THREAD

**Issue by xiaods** [pugjs/pug#930]
when i use grunt to concat jade.js to min.js, came across a issue,  

'public/javascripts/vendor/jquery-1.7.2.js',  
 26   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/jquery-ui.js',  
 27   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/dropdown.js',  
 28   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/async.js',  
 29   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/underscore.js',  
 30   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/backbone.js',  
 31   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/backbone.iobind.js',  
 32   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/backbone.iosync.js',  
 33   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/moment.js',  
 34   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/bootstrap-modal.js',  
 35   ¦ ¦ ¦ ¦ 'public/javascripts/vendor/jade.js',   

chrome console error output:
Uncaught TypeError: Property 'visits' of object #<Object> is not a function

**Comment by sachinavinaw** [comment]
Hi.

I am facing a problem.
I am using pug. I have used number of page events using jquery.
When i run the application, mostly it fails to load js in one go. When I refresh the tab, it loads the js.
I tried both ways:
-Adding js in head
-Adding js in footer
Problem is still persisting. can anyone help?
