### ISSUE TITLE
generate SourceMaps

### ISSUE THREAD

**Issue by sokra** [pugjs/pug#941]
On a quick look it doesn't seem to be too compilated to add this.

**Comment by jamiehutber** [comment]
My suggestion is just to add html comments in each jade file of its location

**Comment by lukewatts** [comment]
@jamiehutber Like line_comments in Sass. That would be enough for me I think rather than all out sourcemaps. Although being able to edit the Jade (.jade) files in Firefox or Chrome like sourcemaps allow in Sass/Compass would mean you could essentially do everything in the browser once a Task runner is compiling.

**Comment by Grawl** [comment]
@jamiehutber how about to add this comments with something like [`gulp-header`](https://www.npmjs.com/package/gulp-header/)?

**Comment by johnsoncodehk** [comment]
> No, we're not talking about the context switch between jade and HTML, we're talking about reading the JavaScript output of Jade's compile function. That's not HTML, it's JavaScript, and it's ugly stuff with a tone of extra closures and variables and buffer.push and so on. That's where it would be a big win, not somehow mapping the generated html back to the jade that created it, that would be pointless.

I need to perform diagnostics for html and then map the results to pug, so SourceMaps of html-pug are meaningful.
Are there any plans for this?

**Comment by Grawl** [comment]
https://github.com/hhru/html-set-source-attribute

**Comment by johnsoncodehk** [comment]
@Grawl Sorry I didn't make it clear!
What I need is SourceMaps that convert pug to html, so I cannot insert anything into html.
