### ISSUE TITLE
Double-quotes HTML-encoded in attribute values

### ISSUE THREAD

**Issue by es128** [pugjs/pug#969]
`li(ng-repeat='item in collection | orderBy:"order"')`
yields
`<li ng-repeat="item in collection | orderBy:&quot;order&quot;">`
and does not get processed properly by angular.

Backslash-escaping the double-quotes in jade seems to have no effect.

Currently solving this by inverting the single and double-quotes `li(ng-repeat="item in collection | orderBy:'order'")`, but would like to keep single-quoted attribute definitions to be consistent with the rest of the project.

Seems like it would be better if jade inverted double-quotes wrapped within single-quotes,  or just maintained the quote style of the original definition (when variable interpolation is not involved)

**Comment by khaledfathy** [comment]
Dear all 
i have problem  when i fetch data with angularjs it return but in double quotes i want to remove double quotes because  the data is script and i want generate script at run time


 <div id="divTest" ng-controller='BCChartsCtrl'>
        <div ng-repeat='item in products'>
            <div id='{{item.ChartId}}'>Chart Id: {{item.ChartId}}
                @*<script id="javaScriptValue" type="text/javascript" src="{{item.ChartScript}}"></script>*@
                <p>
                    {{ item.ChartScript | limitTo:item.ChartScript.length}}
                </p>
          </div>
        </div>
    </div>

what can I do?

**Comment by khaledfathy** [comment]
<div id="divTest" ng-controller='BCChartsCtrl'>
        <div ng-repeat='item in products'>
            <div id='{{item.ChartId}}'>Chart Id: {{item.ChartId}}
                <p>
                    {{ item.ChartScript | limitTo:item.ChartScript.length}}
                </p>
          </div>
        </div>
    </div>

i need remove double quotes from html attr
